// packages/react/src/components/radio-group/radio-group.tsx
import React, { createContext, useContext, useId, useState } from 'react';
import { getRadioState, radioGroupStyleKeys } from '@tile-ui/core';
import type { RadioGroupBaseProps, RadioGroupItemBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/radio-group.module.scss';

interface RadioGroupContextValue {
	value: string;
	name: string;
	disabled: boolean;
	select: (value: string) => void;
}

const RadioGroupContext = createContext<RadioGroupContextValue | null>(null);

function useRadioGroupContext(): RadioGroupContextValue {
	const context = useContext(RadioGroupContext);
	if (!context) {
		throw new Error('RadioGroup sub-components must be used within <RadioGroup>.');
	}
	return context;
}

export interface RadioGroupProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'value' | 'defaultValue'>, RadioGroupBaseProps {}

const RadioGroup = React.forwardRef<HTMLDivElement, RadioGroupProps>(
	({ className = '', value, defaultValue = '', onValueChange, orientation = 'vertical', name = '', disabled = false, children, ...props }, ref) => {
		const [internalValue, setInternalValue] = useState(defaultValue);
		const currentValue = value !== undefined ? value : internalValue;

		function select(next: string) {
			if (disabled) {
				return;
			}
			if (value === undefined) {
				setInternalValue(next);
			}
			onValueChange?.(next);
		}

		return (
			<RadioGroupContext.Provider value={{ value: currentValue, name, disabled, select }}>
				<div
					ref={ref}
					role="radiogroup"
					aria-orientation={orientation}
					data-orientation={orientation}
					className={`${styles[radioGroupStyleKeys.root]} ${className}`}
					{...props}>
					{children}
				</div>
			</RadioGroupContext.Provider>
		);
	},
);
RadioGroup.displayName = 'RadioGroup';

export interface RadioGroupItemProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'checked'>, RadioGroupItemBaseProps {
	value: string;
}

const RadioGroupItem = React.forwardRef<HTMLInputElement, RadioGroupItemProps>(({ className = '', value, disabled = false, onChange, children, ...props }, ref) => {
	const context = useRadioGroupContext();
	const checked = context.value === value;
	const state = getRadioState(checked);
	const inputId = useId();

	function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
		context.select(value);
		onChange?.(event);
	}

	return (
		<label htmlFor={inputId} className={`${styles[radioGroupStyleKeys.label]} ${className}`}>
			<input
				{...props}
				ref={ref}
				id={inputId}
				type="radio"
				name={context.name}
				value={value}
				checked={checked}
				disabled={disabled || context.disabled}
				onChange={handleChange}
				className={styles[radioGroupStyleKeys.input]}
			/>
			<span aria-hidden data-state={state} className={styles[radioGroupStyleKeys.item]}>
				<span className={styles[radioGroupStyleKeys.indicator]}>
					<span className={styles[radioGroupStyleKeys.dot]} />
					{children}
				</span>
			</span>
		</label>
	);
});
RadioGroupItem.displayName = 'RadioGroupItem';

export { RadioGroup, RadioGroupItem };
export default RadioGroup;

// packages/vue/src/components/radio-group/radio-group.tsx
import { computed, defineComponent, h, inject, provide, ref, useId, type ComputedRef, type InjectionKey, type PropType } from 'vue';
import { getRadioState, radioGroupStyleKeys } from '@tile-ui/core';
import type { RadioGroupOrientation } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/radio-group.module.scss';

interface RadioGroupContextValue {
	value: string;
	name: string;
	disabled: boolean;
	select: (value: string) => void;
}

type RadioGroupContext = ComputedRef<RadioGroupContextValue>;

const RadioGroupContextKey: InjectionKey<RadioGroupContext> = Symbol('tile-radio-group');

export const RadioGroup = defineComponent({
	name: 'RadioGroup',
	props: {
		modelValue: { type: String, default: undefined },
		defaultValue: { type: String, default: '' },
		orientation: {
			type: String as PropType<RadioGroupOrientation>,
			default: 'vertical',
		},
		name: { type: String, default: '' },
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit, slots }) {
		const internalValue = ref(props.defaultValue);
		const currentValue = computed(() => (props.modelValue !== undefined ? props.modelValue : internalValue.value));

		const context = computed<RadioGroupContextValue>(() => ({
			value: currentValue.value,
			name: props.name,
			disabled: props.disabled,
			select: (next: string) => {
				if (props.disabled) {
					return;
				}
				if (props.modelValue === undefined) {
					internalValue.value = next;
				}
				emit('update:modelValue', next);
				emit('change', next);
			},
		}));

		provide(RadioGroupContextKey, context);

		return () =>
			h(
				'div',
				{
					class: styles[radioGroupStyleKeys.root],
					role: 'radiogroup',
					'aria-orientation': props.orientation,
					'data-orientation': props.orientation,
				},
				slots.default?.(),
			);
	},
});

export const RadioGroupItem = defineComponent({
	name: 'RadioGroupItem',
	props: {
		value: { type: String, required: true },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots }) {
		const context = inject(RadioGroupContextKey);
		if (!context) {
			throw new Error('RadioGroupItem must be used within <RadioGroup>.');
		}

		const checked = computed(() => context.value.value === props.value);
		const state = computed(() => getRadioState(checked.value));
		const inputId = `tile-radio-${useId()}`;

		return () =>
			h('label', { class: styles[radioGroupStyleKeys.label], for: inputId }, [
				h('input', {
					id: inputId,
					type: 'radio',
					name: context.value.name,
					value: props.value,
					checked: checked.value,
					disabled: props.disabled || context.value.disabled,
					class: styles[radioGroupStyleKeys.input],
					onChange: () => {
						if (!checked.value) {
							context.value.select(props.value);
						}
					},
				}),
				h('span', { 'data-state': state.value, class: styles[radioGroupStyleKeys.item] }, [
					h('span', { class: styles[radioGroupStyleKeys.indicator] }, [h('span', { class: styles[radioGroupStyleKeys.dot] })]),
				]),
				...(slots.default?.() ?? []),
			]);
	},
});

export default RadioGroup;
