// packages/react/src/components/checkbox/checkbox.tsx
import React, { useState } from 'react';
import { checkboxStyleKeys, getCheckboxState, getNextCheckboxState } from '@tile-ui/core';
import type { CheckboxCheckedState } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/checkbox.module.scss';

export interface CheckboxProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onChange' | 'defaultChecked'> {
	checked?: CheckboxCheckedState;
	defaultChecked?: CheckboxCheckedState;
	onCheckedChange?: (checked: CheckboxCheckedState) => void;
}

const Checkbox = React.forwardRef<HTMLButtonElement, CheckboxProps>(({ className = '', checked, defaultChecked = false, disabled, onCheckedChange, ...props }, ref) => {
	const [internalChecked, setInternalChecked] = useState<CheckboxCheckedState>(defaultChecked);
	const isChecked = checked !== undefined ? checked : internalChecked;
	const state = getCheckboxState(isChecked);

	function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
		const next = getNextCheckboxState(isChecked);

		if (checked === undefined) {
			setInternalChecked(next);
		}

		onCheckedChange?.(next);
		props.onClick?.(event);
	}

	const ariaChecked = state === 'checked' ? 'true' : state === 'mixed' ? 'mixed' : 'false';

	return (
		<button
			ref={ref}
			type="button"
			role="checkbox"
			aria-checked={ariaChecked}
			data-state={state}
			disabled={disabled}
			className={`${styles[checkboxStyleKeys.root]} ${className}`}
			{...props}
			onClick={handleClick}>
			<span className={styles[checkboxStyleKeys.indicator]}>
				{state === 'checked' && (
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
						<path d="M20 6 9 17l-5-5" />
					</svg>
				)}
				{state === 'mixed' && (
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round">
						<path d="M5 12h14" />
					</svg>
				)}
			</span>
		</button>
	);
});

Checkbox.displayName = 'Checkbox';

export { Checkbox };
export default Checkbox;

// packages/vue/src/components/checkbox/checkbox.tsx
import { defineComponent, computed, h, ref, type PropType } from 'vue';
import { checkboxStyleKeys, getCheckboxState, getNextCheckboxState } from '@tile-ui/core';
import type { CheckboxCheckedState } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/checkbox.module.scss';

export const Checkbox = defineComponent({
	name: 'Checkbox',
	props: {
		modelValue: {
			type: [Boolean, String] as PropType<boolean | 'indeterminate'>,
			default: undefined,
		},
		defaultChecked: {
			type: [Boolean, String] as PropType<boolean | 'indeterminate'>,
			default: false,
		},
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit }) {
		const internalChecked = ref<CheckboxCheckedState>(props.defaultChecked);
		const isChecked = computed<CheckboxCheckedState>(() =>
			props.modelValue !== undefined ? (props.modelValue === 'indeterminate' ? 'indeterminate' : !!props.modelValue) : internalChecked.value,
		);
		const state = computed(() => getCheckboxState(isChecked.value));
		const ariaChecked = computed(() => (state.value === 'checked' ? 'true' : state.value === 'mixed' ? 'mixed' : 'false'));

		function handleClick() {
			const next = getNextCheckboxState(isChecked.value);
			if (props.modelValue === undefined) {
				internalChecked.value = next;
			}
			emit('update:modelValue', next);
			emit('change', next);
		}

		return () =>
			h(
				'button',
				{
					type: 'button',
					role: 'checkbox',
					'aria-checked': ariaChecked.value,
					'data-state': state.value,
					disabled: props.disabled,
					class: styles[checkboxStyleKeys.root],
					onClick: handleClick,
				},
				[
					h('span', { class: styles[checkboxStyleKeys.indicator] }, [
						state.value === 'checked'
							? h(
									'svg',
									{
										xmlns: 'http://www.w3.org/2000/svg',
										viewBox: '0 0 24 24',
										fill: 'none',
										stroke: 'currentColor',
										'stroke-width': '3',
										'stroke-linecap': 'round',
										'stroke-linejoin': 'round',
									},
									[h('path', { d: 'M20 6 9 17l-5-5' })],
								)
							: null,
						state.value === 'mixed'
							? h(
									'svg',
									{
										xmlns: 'http://www.w3.org/2000/svg',
										viewBox: '0 0 24 24',
										fill: 'none',
										stroke: 'currentColor',
										'stroke-width': '3',
										'stroke-linecap': 'round',
									},
									[h('path', { d: 'M5 12h14' })],
								)
							: null,
					]),
				],
			);
	},
});

export default Checkbox;
