// packages/react/src/components/empty/empty.tsx
import React from 'react';
import { emptyStyleKeys, getEmptyMediaVariantKey } from '@tile-ui/core';
import type { EmptyMediaBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/empty.module.scss';

export interface EmptyProps extends React.HTMLAttributes<HTMLDivElement> {}

const Empty = React.forwardRef<HTMLDivElement, EmptyProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="empty" className={`${styles[emptyStyleKeys.root]} ${className}`} {...props}>
			{children}
		</div>
	);
});
Empty.displayName = 'Empty';

export interface EmptyHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const EmptyHeader = React.forwardRef<HTMLDivElement, EmptyHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="empty-header" className={`${styles[emptyStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
EmptyHeader.displayName = 'EmptyHeader';

export interface EmptyMediaProps extends React.HTMLAttributes<HTMLDivElement>, EmptyMediaBaseProps {}

const EmptyMedia = React.forwardRef<HTMLDivElement, EmptyMediaProps>(({ className = '', variant = 'default', children, ...props }, ref) => {
	const variantKey = getEmptyMediaVariantKey(variant);
	const classes = [styles[emptyStyleKeys.media], styles[variantKey], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} data-slot="empty-icon" data-variant={variant} className={classes} {...props}>
			{children}
		</div>
	);
});
EmptyMedia.displayName = 'EmptyMedia';

export interface EmptyTitleProps extends React.HTMLAttributes<HTMLDivElement> {}

const EmptyTitle = React.forwardRef<HTMLDivElement, EmptyTitleProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="empty-title" className={`${styles[emptyStyleKeys.title]} ${className}`} {...props}>
			{children}
		</div>
	);
});
EmptyTitle.displayName = 'EmptyTitle';

export interface EmptyDescriptionProps extends React.HTMLAttributes<HTMLDivElement> {}

const EmptyDescription = React.forwardRef<HTMLDivElement, EmptyDescriptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="empty-description" className={`${styles[emptyStyleKeys.description]} ${className}`} {...props}>
			{children}
		</div>
	);
});
EmptyDescription.displayName = 'EmptyDescription';

export interface EmptyContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const EmptyContent = React.forwardRef<HTMLDivElement, EmptyContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="empty-content" className={`${styles[emptyStyleKeys.content]} ${className}`} {...props}>
			{children}
		</div>
	);
});
EmptyContent.displayName = 'EmptyContent';

export { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription, EmptyContent };
export default Empty;

// packages/vue/src/components/empty/empty.tsx
import { computed, defineComponent, h, type PropType } from 'vue';
import { emptyStyleKeys, getEmptyMediaVariantKey } from '@tile-ui/core';
import type { EmptyMediaVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/empty.module.scss';

export const Empty = defineComponent({
	name: 'Empty',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'empty', class: [styles[emptyStyleKeys.root], attrs.class] }, slots.default?.());
	},
});

export const EmptyHeader = defineComponent({
	name: 'EmptyHeader',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'empty-header', class: [styles[emptyStyleKeys.header], attrs.class] }, slots.default?.());
	},
});

export const EmptyMedia = defineComponent({
	name: 'EmptyMedia',
	props: {
		variant: {
			type: String as PropType<EmptyMediaVariant>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const variantKey = computed(() => getEmptyMediaVariantKey(props.variant));
		const classes = computed(() => [styles[emptyStyleKeys.media], styles[variantKey.value], attrs.class]);

		return () => h('div', { ...attrs, 'data-slot': 'empty-icon', 'data-variant': props.variant, class: classes.value }, slots.default?.());
	},
});

export const EmptyTitle = defineComponent({
	name: 'EmptyTitle',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'empty-title', class: [styles[emptyStyleKeys.title], attrs.class] }, slots.default?.());
	},
});

export const EmptyDescription = defineComponent({
	name: 'EmptyDescription',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'empty-description', class: [styles[emptyStyleKeys.description], attrs.class] }, slots.default?.());
	},
});

export const EmptyContent = defineComponent({
	name: 'EmptyContent',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'empty-content', class: [styles[emptyStyleKeys.content], attrs.class] }, slots.default?.());
	},
});

export default Empty;
