// packages/vue/src/components/switch/switch.tsx
import { defineComponent, computed, h, ref, type PropType } from 'vue';
import { getSwitchState, switchStyleKeys } from '@tile-ui/core';
import type { SwitchSize } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/switch.module.scss';

export const Switch = defineComponent({
	name: 'Switch',
	props: {
		modelValue: { type: Boolean, default: undefined },
		defaultChecked: { type: Boolean, default: false },
		size: {
			type: String as PropType<SwitchSize>,
			default: 'default',
		},
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit }) {
		const internalChecked = ref(props.defaultChecked);
		const isChecked = computed(() => (props.modelValue !== undefined ? props.modelValue : internalChecked.value));
		const state = computed(() => getSwitchState(isChecked.value));

		function handleClick() {
			const next = !isChecked.value;
			if (props.modelValue === undefined) {
				internalChecked.value = next;
			}
			emit('update:modelValue', next);
			emit('change', next);
		}

		return () =>
			h(
				'button',
				{
					type: 'button',
					role: 'switch',
					'aria-checked': isChecked.value ? 'true' : 'false',
					'data-state': state.value,
					'data-size': props.size,
					disabled: props.disabled,
					class: styles[switchStyleKeys.root],
					onClick: handleClick,
				},
				[h('span', { class: styles[switchStyleKeys.thumb] })],
			);
	},
});

export default Switch;

// packages/react/src/components/switch/switch.tsx
import React, { useState } from 'react';
import { getSwitchState, switchStyleKeys } from '@tile-ui/core';
import type { SwitchBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/switch.module.scss';

export interface SwitchProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'>, SwitchBaseProps {
	checked?: boolean;
	defaultChecked?: boolean;
	onCheckedChange?: (checked: boolean) => void;
}

const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
	({ className = '', size = 'default', checked, defaultChecked = false, disabled, onCheckedChange, ...props }, ref) => {
		const [internalChecked, setInternalChecked] = useState(defaultChecked);
		const isChecked = checked !== undefined ? checked : internalChecked;
		const state = getSwitchState(isChecked);

		function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
			const next = !isChecked;

			if (checked === undefined) {
				setInternalChecked(next);
			}

			onCheckedChange?.(next);
			props.onClick?.(event);
		}

		return (
			<button
				ref={ref}
				type="button"
				role="switch"
				aria-checked={isChecked}
				data-state={state}
				data-size={size}
				disabled={disabled}
				className={`${styles[switchStyleKeys.root]} ${className}`}
				onClick={handleClick}
				{...props}>
				<span className={styles[switchStyleKeys.thumb]} />
			</button>
		);
	},
);

Switch.displayName = 'Switch';

export { Switch };
export default Switch;
