// packages/vue/src/components/select/select.tsx
import {
	computed,
	defineComponent,
	h,
	inject,
	nextTick,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	useId,
	watch,
	Teleport,
	type ComputedRef,
	type InjectionKey,
	type PropType,
	type Ref,
} from 'vue';
import { getSelectCheckState, getSelectPosition, getSelectState, selectStyleKeys } from '@tile-ui/core';
import type { SelectAlign, SelectPosition } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/select.module.scss';

interface SelectContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	value: string | undefined;
	setValue: (value: string) => void;
	triggerRef: Ref<HTMLButtonElement | null>;
	contentId: string;
	itemTexts: Record<string, string>;
	registerItemText: (value: string, text: string) => void;
}

type SelectContext = ComputedRef<SelectContextValue>;

const SelectContextKey: InjectionKey<SelectContext> = Symbol('tile-select');

interface SelectContentContextValue {
	itemsRef: Ref<HTMLElement[]>;
	close: () => void;
}

type SelectContentContext = ComputedRef<SelectContentContextValue>;

const SelectContentContextKey: InjectionKey<SelectContentContext> = Symbol('tile-select-content');

function useSelectContext(): SelectContext {
	const context = inject(SelectContextKey);
	if (!context) {
		throw new Error('Select 子组件必须位于 <Select> 内部。');
	}
	return context;
}

function useSelectContentContext(): SelectContentContext {
	const context = inject(SelectContentContextKey);
	if (!context) {
		throw new Error('SelectItem 必须位于 <SelectContent> 内部。');
	}
	return context;
}

function selectCheckIcon() {
	return h(
		'svg',
		{
			class: styles[selectStyleKeys.checkIcon],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'M20 6 9 17l-5-5' })],
	);
}

function selectChevronIcon() {
	return h(
		'svg',
		{
			class: styles[selectStyleKeys.chevron],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'm6 9 6 6 6-6' })],
	);
}

function selectScrollUpIcon() {
	return h(
		'svg',
		{
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'm18 15-6-6-6 6' })],
	);
}

function selectScrollDownIcon() {
	return h(
		'svg',
		{
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'm6 9 6 6 6-6' })],
	);
}

export const Select = defineComponent({
	name: 'Select',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
		value: { type: String, default: undefined },
		defaultValue: { type: String, default: undefined },
	},
	emits: ['update:open', 'update:value'],
	setup(props, { emit, slots, attrs }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const internalValue = ref(props.defaultValue);
		const resolvedValue = computed(() => (props.value !== undefined ? props.value : internalValue.value));
		const triggerRef = ref<HTMLButtonElement | null>(null);
		const contentId = `tile-select-${useId()}`;
		const itemTexts = ref<Record<string, string>>({});

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		function setValue(next: string) {
			if (props.value === undefined) {
				internalValue.value = next;
			}
			emit('update:value', next);
		}

		function registerItemText(value: string, text: string) {
			if (itemTexts.value[value] === text) {
				return;
			}
			itemTexts.value = { ...itemTexts.value, [value]: text };
		}

		const context = computed<SelectContextValue>(() => ({
			open: isOpen.value,
			setOpen,
			value: resolvedValue.value,
			setValue,
			triggerRef,
			contentId,
			itemTexts: itemTexts.value,
			registerItemText,
		}));

		provide(SelectContextKey, context);

		return () => h('div', { ...attrs, class: [styles[selectStyleKeys.root], attrs.class] }, slots.default?.());
	},
});

export const SelectTrigger = defineComponent({
	name: 'SelectTrigger',
	inheritAttrs: false,
	props: {
		size: { type: String as PropType<'sm' | 'default'>, default: 'default' },
	},
	setup(props, { slots, attrs }) {
		const context = useSelectContext();

		function handleClick() {
			context.value.setOpen(!context.value.open);
		}

		function handleKeyDown(event: KeyboardEvent) {
			if (event.defaultPrevented) {
				return;
			}
			if (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown' || event.key === 'ArrowUp') {
				event.preventDefault();
				context.value.setOpen(true);
			}
		}

		return () =>
			h(
				'button',
				{
					...attrs,
					ref: context.value.triggerRef,
					type: 'button',
					role: 'combobox',
					'aria-haspopup': 'listbox',
					'aria-expanded': context.value.open,
					'aria-controls': context.value.contentId,
					'data-state': getSelectState(context.value.open),
					'data-size': props.size,
					class: [styles[selectStyleKeys.trigger], attrs.class],
					onClick: handleClick,
					onKeydown: handleKeyDown,
				},
				[...(slots.default?.() ?? []), selectChevronIcon()],
			);
	},
});

export const SelectValue = defineComponent({
	name: 'SelectValue',
	inheritAttrs: false,
	props: {
		placeholder: { type: String, default: undefined },
	},
	setup(props, { slots, attrs }) {
		const context = useSelectContext();

		return () => {
			const text = context.value.value !== undefined ? context.value.itemTexts[context.value.value] : undefined;
			const showPlaceholder = !text;
			return h('span', { ...attrs, 'data-placeholder': showPlaceholder, class: [styles[selectStyleKeys.value], attrs.class] }, [
				text ?? props.placeholder ?? slots.default?.(),
			]);
		};
	},
});

export const SelectContent = defineComponent({
	name: 'SelectContent',
	inheritAttrs: false,
	props: {
		position: { type: String as PropType<SelectPosition>, default: 'item-aligned' },
		align: { type: String as PropType<SelectAlign>, default: 'center' },
		sideOffset: { type: Number, default: 4 },
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots, attrs }) {
		const context = useSelectContext();
		const portalContainer = usePortalContainer(() => props.container);
		const contentRef = ref<HTMLElement | null>(null);
		const itemsRef = ref<HTMLElement[]>([]);
		const coords = ref<{ top: number; left: number } | null>(null);

		const contentContext = computed<SelectContentContextValue>(() => ({
			itemsRef,
			close: () => context.value.setOpen(false),
		}));

		provide(SelectContentContextKey, contentContext);

		let disposeDocListeners: (() => void) | null = null;

		function updatePosition() {
			const trigger = context.value.triggerRef.value;
			const content = contentRef.value;
			if (!trigger || !content) {
				return;
			}
			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			coords.value = getSelectPosition({ triggerRect, contentSize, align: props.align, sideOffset: props.sideOffset, viewport });
		}

		function highlightSelected() {
			const items = itemsRef.value;
			items.forEach((item) => item.removeAttribute('data-highlighted'));
			const selected = items.find((item) => item.getAttribute('aria-selected') === 'true');
			const target = selected ?? items[0];
			if (target) {
				target.setAttribute('data-highlighted', 'true');
				target.focus();
			}
		}

		function handleOpen() {
			nextTick(() => {
				updatePosition();
				highlightSelected();
			});
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				const content = contentRef.value;
				const trigger = context.value.triggerRef.value;
				if (!target) {
					return;
				}
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				context.value.setOpen(false);
			}

			document.addEventListener('pointerdown', handlePointerDown);
			disposeDocListeners = () => document.removeEventListener('pointerdown', handlePointerDown);
		}

		function handleClose() {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
			disposeDocListeners?.();
			disposeDocListeners = null;
		}

		onMounted(() => {
			if (context.value.open) {
				handleOpen();
			}
		});

		watch(
			() => context.value.open,
			(open) => {
				if (open) {
					handleOpen();
				} else {
					handleClose();
				}
			},
		);

		watch(
			() => [props.align, props.sideOffset],
			() => {
				if (context.value.open) {
					updatePosition();
				}
			},
		);

		onBeforeUnmount(handleClose);

		function handleKeyDown(event: KeyboardEvent) {
			const items = itemsRef.value.filter((item) => item.getAttribute('data-disabled') !== 'true');

			if (event.key === 'Escape') {
				event.preventDefault();
				context.value.setOpen(false);
				context.value.triggerRef.value?.focus();
				return;
			}

			if (items.length === 0) {
				return;
			}

			const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');

			const highlight = (next: number) => {
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[next].setAttribute('data-highlighted', 'true');
				items[next].focus();
			};

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
					break;
				case 'ArrowUp':
					event.preventDefault();
					highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
					break;
				case 'Home':
					event.preventDefault();
					highlight(0);
					break;
				case 'End':
					event.preventDefault();
					highlight(items.length - 1);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
					break;
			}
		}

		return () => {
			const userClass = attrs.class;
			const userStyle = attrs.style;
			const restAttrs = { ...attrs };
			delete restAttrs.class;
			delete restAttrs.style;

			return h(Teleport, { to: portalContainer.value }, [
				h(
					'div',
					{
						...restAttrs,
						ref: contentRef,
						id: context.value.contentId,
						role: 'listbox',
						tabindex: -1,
						'data-state': getSelectState(context.value.open),
						'data-position': props.position,
						class: [styles[selectStyleKeys.content], userClass],
						style: coords.value ? [userStyle, { top: `${coords.value.top}px`, left: `${coords.value.left}px` }] : userStyle,
						onKeydown: handleKeyDown,
					},
					slots.default?.(),
				),
			]);
		};
	},
});

export const SelectGroup = defineComponent({
	name: 'SelectGroup',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, role: 'group', class: [styles[selectStyleKeys.group], attrs.class] }, slots.default?.());
	},
});

export const SelectLabel = defineComponent({
	name: 'SelectLabel',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, class: [styles[selectStyleKeys.label], attrs.class] }, slots.default?.());
	},
});

export const SelectItem = defineComponent({
	name: 'SelectItem',
	inheritAttrs: false,
	props: {
		value: { type: String, required: true },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useSelectContentContext();
		const root = useSelectContext();
		const itemRef = ref<HTMLElement | null>(null);
		const isSelected = computed(() => root.value.value === props.value);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
				root.value.registerItemText(props.value, itemRef.value.textContent ?? '');
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick() {
			if (props.disabled) {
				return;
			}
			root.value.setValue(props.value);
			context.value.close();
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'option',
					tabindex: -1,
					'aria-selected': isSelected.value,
					'data-checked': getSelectCheckState(isSelected.value),
					'data-disabled': props.disabled,
					class: [styles[selectStyleKeys.item], attrs.class],
					onClick: handleClick,
				},
				[h('span', { class: styles[selectStyleKeys.indicator] }, [isSelected.value ? selectCheckIcon() : null]), ...(slots.default?.() ?? [])],
			);
	},
});

export const SelectSeparator = defineComponent({
	name: 'SelectSeparator',
	setup(_props, { attrs }) {
		return () => h('div', { ...attrs, role: 'separator', class: [styles[selectStyleKeys.separator], attrs.class] });
	},
});

export const SelectScrollUpButton = defineComponent({
	name: 'SelectScrollUpButton',
	setup(_props, { attrs }) {
		return () => h('div', { ...attrs, class: [styles[selectStyleKeys.scrollButton], attrs.class] }, [selectScrollUpIcon()]);
	},
});

export const SelectScrollDownButton = defineComponent({
	name: 'SelectScrollDownButton',
	setup(_props, { attrs }) {
		return () => h('div', { ...attrs, class: [styles[selectStyleKeys.scrollButton], attrs.class] }, [selectScrollDownIcon()]);
	},
});

export default Select;

// packages/react/src/components/select/select.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { getSelectCheckState, getSelectPosition, getSelectState, selectStyleKeys } from '@tile-ui/core';
import type { SelectBaseProps, SelectContentBaseProps, SelectItemBaseProps, SelectPositionResult, SelectTriggerBaseProps } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/select.module.scss';

interface SelectContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	value: string | undefined;
	setValue: (value: string) => void;
	triggerRef: React.RefObject<HTMLButtonElement | null>;
	contentId: string;
	itemTexts: Record<string, string>;
	registerItemText: (value: string, text: string) => void;
}

const SelectContext = createContext<SelectContextValue | null>(null);

function useSelectContext(): SelectContextValue {
	const context = useContext(SelectContext);
	if (!context) {
		throw new Error('Select 子组件必须位于 <Select> 内部。');
	}
	return context;
}

interface SelectContentContextValue {
	itemsRef: React.RefObject<HTMLElement[]>;
	close: () => void;
}

const SelectContentContext = createContext<SelectContentContextValue | null>(null);

function useSelectContentContext(): SelectContentContextValue {
	const context = useContext(SelectContentContext);
	if (!context) {
		throw new Error('SelectItem 必须位于 <SelectContent> 内部。');
	}
	return context;
}

function SelectCheckIcon() {
	return (
		<svg
			className={styles[selectStyleKeys.checkIcon]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="M20 6 9 17l-5-5" />
		</svg>
	);
}

function SelectChevronIcon() {
	return (
		<svg
			className={styles[selectStyleKeys.chevron]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="m6 9 6 6 6-6" />
		</svg>
	);
}

export interface SelectProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'defaultValue'>, SelectBaseProps {}

const Select = React.forwardRef<HTMLDivElement, SelectProps>(
	({ className = '', open, defaultOpen = false, onOpenChange, value, defaultValue, onValueChange, children, ...props }, ref) => {
		const [internalOpen, setInternalOpen] = useState(defaultOpen);
		const isOpen = open !== undefined ? open : internalOpen;

		const [internalValue, setInternalValue] = useState(defaultValue);
		const resolvedValue = value !== undefined ? value : internalValue;

		const triggerRef = useRef<HTMLButtonElement | null>(null);
		const contentId = useId();
		const [itemTexts, setItemTexts] = useState<Record<string, string>>({});

		const setOpen = useCallback(
			(next: boolean) => {
				if (open === undefined) {
					setInternalOpen(next);
				}
				onOpenChange?.(next);
			},
			[open, onOpenChange],
		);

		const setValue = useCallback(
			(next: string) => {
				if (value === undefined) {
					setInternalValue(next);
				}
				onValueChange?.(next);
			},
			[value, onValueChange],
		);

		const registerItemText = useCallback((itemValue: string, text: string) => {
			setItemTexts((prev) => (prev[itemValue] === text ? prev : { ...prev, [itemValue]: text }));
		}, []);

		return (
			<SelectContext.Provider value={{ open: isOpen, setOpen, value: resolvedValue, setValue, triggerRef, contentId, itemTexts, registerItemText }}>
				<div ref={ref} className={`${styles[selectStyleKeys.root]} ${className}`} {...props}>
					{children}
				</div>
			</SelectContext.Provider>
		);
	},
);
Select.displayName = 'Select';

export interface SelectTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, SelectTriggerBaseProps {}

const SelectTrigger = React.forwardRef<HTMLButtonElement, SelectTriggerProps>(({ className = '', size = 'default', children, onClick, onKeyDown, ...props }, ref) => {
	const context = useSelectContext();

	function setRef(element: HTMLButtonElement | null) {
		context.triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
		onClick?.(event);
		if (event.defaultPrevented) {
			return;
		}
		context.setOpen(!context.open);
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) {
		onKeyDown?.(event);
		if (event.defaultPrevented) {
			return;
		}
		if (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown' || event.key === 'ArrowUp') {
			event.preventDefault();
			context.setOpen(true);
		}
	}

	const state = getSelectState(context.open);
	const classes = [styles[selectStyleKeys.trigger], className].filter(Boolean).join(' ');

	return (
		<button
			ref={setRef}
			type="button"
			role="combobox"
			aria-haspopup="listbox"
			aria-expanded={context.open}
			aria-controls={context.contentId}
			data-state={state}
			data-size={size}
			className={classes}
			onClick={handleClick}
			onKeyDown={handleKeyDown}
			{...props}>
			{children}
			<SelectChevronIcon />
		</button>
	);
});
SelectTrigger.displayName = 'SelectTrigger';

export interface SelectValueProps extends React.HTMLAttributes<HTMLSpanElement> {
	/** 未选中时展示的占位文本 */
	placeholder?: string;
}

const SelectValue = React.forwardRef<HTMLSpanElement, SelectValueProps>(({ className = '', placeholder, children, ...props }, ref) => {
	const { value, itemTexts } = useSelectContext();
	const text = value !== undefined ? itemTexts[value] : undefined;
	const showPlaceholder = !text;
	const classes = [styles[selectStyleKeys.value], className].filter(Boolean).join(' ');

	return (
		<span ref={ref} data-placeholder={showPlaceholder} className={classes} {...props}>
			{text ?? placeholder ?? children}
		</span>
	);
});
SelectValue.displayName = 'SelectValue';

export interface SelectContentProps extends React.HTMLAttributes<HTMLDivElement>, SelectContentBaseProps {
	container?: PortalContainer;
}

const SelectContent = React.forwardRef<HTMLDivElement, SelectContentProps>(
	({ className = '', position = 'item-aligned', align = 'center', sideOffset = 4, container, children, onKeyDown, ...props }, ref) => {
		const { open, setOpen, triggerRef, contentId } = useSelectContext();
		const portalContainer = usePortalContainer(container);
		const [coords, setCoords] = useState<SelectPositionResult | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);
		const itemsRef = useRef<HTMLElement[]>([]);

		function setRef(element: HTMLDivElement | null) {
			contentRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		useLayoutEffect(() => {
			if (!open) {
				return;
			}

			function updatePosition() {
				const trigger = triggerRef.current;
				const content = contentRef.current;
				if (!trigger || !content) {
					return;
				}

				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				setCoords(getSelectPosition({ triggerRect, contentSize, align, sideOffset, viewport }));
			}

			function highlightSelected() {
				const items = itemsRef.current;
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				const selected = items.find((item) => item.getAttribute('aria-selected') === 'true');
				const target = selected ?? items[0];
				if (target) {
					target.setAttribute('data-highlighted', 'true');
					target.focus();
				}
			}

			updatePosition();
			highlightSelected();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			return () => {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
			};
		}, [open, align, sideOffset, triggerRef]);

		useEffect(() => {
			if (!open) {
				return;
			}

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				if (!target) {
					return;
				}
				const content = contentRef.current;
				const trigger = triggerRef.current;
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				setOpen(false);
			}

			document.addEventListener('pointerdown', handlePointerDown);
			return () => document.removeEventListener('pointerdown', handlePointerDown);
		}, [open, triggerRef, setOpen]);

		function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
			onKeyDown?.(event);
			if (event.defaultPrevented) {
				return;
			}

			const items = itemsRef.current.filter((item) => item.getAttribute('data-disabled') !== 'true');
			if (items.length === 0) {
				if (event.key === 'Escape') {
					event.preventDefault();
					setOpen(false);
					triggerRef.current?.focus();
				}
				return;
			}

			const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');

			const highlight = (next: number) => {
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[next].setAttribute('data-highlighted', 'true');
				items[next].focus();
			};

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
					break;
				case 'ArrowUp':
					event.preventDefault();
					highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
					break;
				case 'Home':
					event.preventDefault();
					highlight(0);
					break;
				case 'End':
					event.preventDefault();
					highlight(items.length - 1);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
					break;
				case 'Escape':
					event.preventDefault();
					setOpen(false);
					triggerRef.current?.focus();
					break;
			}
		}

		const state = getSelectState(open);
		const classes = [styles[selectStyleKeys.content], className].filter(Boolean).join(' ');

		const content = (
			<SelectContentContext.Provider value={{ itemsRef, close: () => setOpen(false) }}>
				<div
					ref={setRef}
					id={contentId}
					role="listbox"
					tabIndex={-1}
					data-state={state}
					data-position={position}
					className={classes}
					style={coords ? { top: `${coords.top}px`, left: `${coords.left}px` } : undefined}
					onKeyDown={handleKeyDown}
					{...props}>
					{children}
				</div>
			</SelectContentContext.Provider>
		);

		if (!portalContainer) {
			return null;
		}

		return createPortal(content, portalContainer);
	},
);
SelectContent.displayName = 'SelectContent';

export interface SelectGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const SelectGroup = React.forwardRef<HTMLDivElement, SelectGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} role="group" className={`${styles[selectStyleKeys.group]} ${className}`} {...props}>
			{children}
		</div>
	);
});
SelectGroup.displayName = 'SelectGroup';

export interface SelectLabelProps extends React.HTMLAttributes<HTMLDivElement> {}

const SelectLabel = React.forwardRef<HTMLDivElement, SelectLabelProps>(({ className = '', children, ...props }, ref) => {
	const classes = [styles[selectStyleKeys.label], className].filter(Boolean).join(' ');
	return (
		<div ref={ref} className={classes} {...props}>
			{children}
		</div>
	);
});
SelectLabel.displayName = 'SelectLabel';

export interface SelectItemProps extends React.HTMLAttributes<HTMLDivElement>, SelectItemBaseProps {}

const SelectItem = React.forwardRef<HTMLDivElement, SelectItemProps>(({ className = '', value, disabled = false, children, onClick, ...props }, ref) => {
	const { itemsRef, close } = useSelectContentContext();
	const { value: selectedValue, setValue, registerItemText } = useSelectContext();
	const itemRef = useRef<HTMLDivElement | null>(null);
	const isSelected = selectedValue === value;

	useEffect(() => {
		const element = itemRef.current;
		if (!element) {
			return;
		}
		itemsRef.current.push(element);
		return () => {
			itemsRef.current = itemsRef.current.filter((item) => item !== element);
		};
	}, [itemsRef]);

	useLayoutEffect(() => {
		const element = itemRef.current;
		if (element) {
			registerItemText(value, element.textContent ?? '');
		}
	}, [value, registerItemText, children]);

	function setRef(element: HTMLDivElement | null) {
		itemRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleClick(event: React.MouseEvent<HTMLDivElement>) {
		onClick?.(event);
		if (event.defaultPrevented) {
			return;
		}
		if (disabled) {
			return;
		}
		setValue(value);
		close();
	}

	const classes = [styles[selectStyleKeys.item], className].filter(Boolean).join(' ');
	return (
		<div
			ref={setRef}
			role="option"
			tabIndex={-1}
			aria-selected={isSelected}
			data-checked={getSelectCheckState(isSelected)}
			data-disabled={disabled}
			className={classes}
			onClick={handleClick}
			{...props}>
			<span className={styles[selectStyleKeys.indicator]}>{isSelected && <SelectCheckIcon />}</span>
			{children}
		</div>
	);
});
SelectItem.displayName = 'SelectItem';

export interface SelectSeparatorProps extends React.HTMLAttributes<HTMLDivElement> {}

const SelectSeparator = React.forwardRef<HTMLDivElement, SelectSeparatorProps>(({ className = '', ...props }, ref) => {
	const classes = [styles[selectStyleKeys.separator], className].filter(Boolean).join(' ');
	return <div ref={ref} role="separator" className={classes} {...props} />;
});
SelectSeparator.displayName = 'SelectSeparator';

export interface SelectScrollUpButtonProps extends React.HTMLAttributes<HTMLDivElement> {}

const SelectScrollUpButton = React.forwardRef<HTMLDivElement, SelectScrollUpButtonProps>(({ className = '', ...props }, ref) => {
	const classes = [styles[selectStyleKeys.scrollButton], className].filter(Boolean).join(' ');
	return (
		<div ref={ref} className={classes} {...props}>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="16"
				height="16"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				strokeWidth="2"
				strokeLinecap="round"
				strokeLinejoin="round"
				aria-hidden="true">
				<path d="m18 15-6-6-6 6" />
			</svg>
		</div>
	);
});
SelectScrollUpButton.displayName = 'SelectScrollUpButton';

export interface SelectScrollDownButtonProps extends React.HTMLAttributes<HTMLDivElement> {}

const SelectScrollDownButton = React.forwardRef<HTMLDivElement, SelectScrollDownButtonProps>(({ className = '', ...props }, ref) => {
	const classes = [styles[selectStyleKeys.scrollButton], className].filter(Boolean).join(' ');
	return (
		<div ref={ref} className={classes} {...props}>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="16"
				height="16"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				strokeWidth="2"
				strokeLinecap="round"
				strokeLinejoin="round"
				aria-hidden="true">
				<path d="m6 9 6 6 6-6" />
			</svg>
		</div>
	);
});
SelectScrollDownButton.displayName = 'SelectScrollDownButton';

export { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectLabel, SelectItem, SelectSeparator, SelectScrollUpButton, SelectScrollDownButton };
export default Select;
