// packages/vue/src/components/direction/direction.tsx
import { computed, defineComponent, h, inject, provide, type InjectionKey, type PropType, type Ref } from 'vue';
import { normalizeDirection } from '@tile-ui/core';
import type { DirectionValue } from '@tile-ui/core';

const DirectionContextKey: InjectionKey<Ref<DirectionValue>> = Symbol('tile-direction');

export const DirectionProvider = defineComponent({
	name: 'DirectionProvider',
	props: {
		dir: { type: String as PropType<DirectionValue>, default: undefined },
		direction: { type: String as PropType<DirectionValue>, default: undefined },
	},
	setup(props, { slots }) {
		const dir = computed(() => normalizeDirection(props.direction ?? props.dir));
		provide(DirectionContextKey, dir);
		return () => h('div', { dir: dir.value }, slots.default?.());
	},
});

/**
 * 读取当前阅读方向 (需在 DirectionProvider 内使用)
 */
export function useDirection(): Ref<DirectionValue> {
	return inject(
		DirectionContextKey,
		computed(() => 'ltr' as DirectionValue),
	);
}

export default DirectionProvider;

// packages/react/src/components/direction/direction.tsx
import React, { createContext, useContext } from 'react';
import { normalizeDirection } from '@tile-ui/core';
import type { DirectionBaseProps, DirectionValue } from '@tile-ui/core';

interface DirectionContextValue {
	dir: DirectionValue;
}

const DirectionContext = createContext<DirectionContextValue>({ dir: 'ltr' });

export interface DirectionProviderProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'dir'>, DirectionBaseProps {
	/** 阅读方向 (dir 的别名，用于兼容上游 API) */
	direction?: DirectionValue;
}

const DirectionProvider = React.forwardRef<HTMLDivElement, DirectionProviderProps>(({ dir, direction, children, ...props }, ref) => {
	const value: DirectionValue = normalizeDirection(direction ?? dir);

	return (
		<DirectionContext.Provider value={{ dir: value }}>
			<div ref={ref} dir={value} {...props}>
				{children}
			</div>
		</DirectionContext.Provider>
	);
});
DirectionProvider.displayName = 'DirectionProvider';

/**
 * 读取当前阅读方向
 */
function useDirection(): DirectionValue {
	return useContext(DirectionContext).dir;
}

export { DirectionProvider, useDirection };
export default DirectionProvider;
