// apps/solid/components/demos/alert-dialog.tsx
import { createSignal } from 'solid-js';
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from '@tile-ui/solid';

export default function AlertDialogDemo() {
	const [result, setResult] = createSignal('No decision yet');
	return (
		<div class="component-preview__stack" data-demo-alert-dialog>
			<AlertDialog onOpenChange={(open) => !open && setResult((value) => (value === 'No decision yet' ? 'Dismissed outside or with Escape' : value))}>
				<AlertDialogTrigger class="component-preview__action">Delete workspace</AlertDialogTrigger>
				<AlertDialogContent onPointerDownOutside={(event) => event.preventDefault()}>
					<AlertDialogHeader>
						<AlertDialogTitle>Delete the Solid workspace?</AlertDialogTitle>
						<AlertDialogDescription>Pointer interaction outside is blocked; Tab stays inside until you choose an action.</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel onClick={() => setResult('Cancelled')}>Cancel</AlertDialogCancel>
						<AlertDialogAction onClick={() => setResult('Deleted')}>Delete</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>
			<p data-demo-state>{result()}</p>
		</div>
	);
}

// apps/react/components/demos/alert-dialog.tsx
import {
	AlertDialog,
	AlertDialogTrigger,
	AlertDialogContent,
	AlertDialogTitle,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogCancel,
	AlertDialogAction,
} from '@tile-ui/react';

export default function AlertDialogDemo() {
	return (
		<AlertDialog>
			<AlertDialogTrigger className="component-preview__action">Delete</AlertDialogTrigger>
			<AlertDialogContent>
				<AlertDialogTitle>Are you sure?</AlertDialogTitle>
				<AlertDialogDescription>This action cannot be undone.</AlertDialogDescription>
				<AlertDialogFooter>
					<AlertDialogCancel>Cancel</AlertDialogCancel>
					<AlertDialogAction>Delete</AlertDialogAction>
				</AlertDialogFooter>
			</AlertDialogContent>
		</AlertDialog>
	);
}
