// apps/solid/components/demos/direction.tsx
import { createSignal } from 'solid-js';
import { Button, DirectionProvider, useDirection } from '@tile-ui/solid';

function DirectionValue() {
	const direction = useDirection();
	return <p class="component-preview__text">Hook value: {direction()}</p>;
}

export default function DirectionDemo() {
	const [direction, setDirection] = createSignal<'ltr' | 'rtl'>('ltr');
	return (
		<DirectionProvider dir={direction()} class="component-preview__stack" data-direction-demo>
			<Button size="sm" variant="outline" onClick={() => setDirection((value) => (value === 'ltr' ? 'rtl' : 'ltr'))}>
				Switch to {direction() === 'ltr' ? 'RTL' : 'LTR'}
			</Button>
			<DirectionValue />
			<p class="component-preview__text">Start aligned text follows the provider direction.</p>
		</DirectionProvider>
	);
}

// apps/react/components/demos/direction.tsx
import { useState } from 'react';
import { DirectionProvider, Button } from '@tile-ui/react';

export default function DirectionDemo() {
	const [rtl, setRtl] = useState(false);

	return (
		<div className="component-preview__stack">
			<DirectionProvider dir={rtl ? 'rtl' : 'ltr'}>
				<div style={{ display: 'flex', gap: 8 }}>
					<span className="component-preview__text">One</span>
					<span className="component-preview__text">Two</span>
					<span className="component-preview__text">Three</span>
				</div>
			</DirectionProvider>
			<div className="button-group">
				<Button variant="outline" onClick={() => setRtl((v) => !v)}>
					{rtl ? 'RTL' : 'LTR'}
				</Button>
			</div>
		</div>
	);
}
