// apps/vue/components/demos/input.tsx
import { defineComponent, ref } from 'vue';
import { Input } from '@tile-ui/vue';

export default defineComponent({
	name: 'InputDemo',
	setup() {
		const value = ref('');
		return () => (
			<div class="component-preview__stack">
				<Input
					label="Project name"
					helperText="Used in your dashboard and generated URLs."
					modelValue={value.value}
					onUpdate:modelValue={(nextValue: string) => {
						value.value = nextValue;
					}}
					placeholder="Tile UI Docs"
				/>
				<Input label="Read-only example" helperText="Use this for immutable values or generated fields." defaultValue="tile-ui" readOnly />
				<Input label="Validation example" error="A project name is required before publishing." defaultValue="" />
			</div>
		);
	},
});

// apps/react/components/demos/input.tsx
import { useState } from 'react';
import { Input } from '@tile-ui/react';

export default function InputDemo() {
	const [value, setValue] = useState('');

	return (
		<div className="component-preview__stack">
			<Input
				label="Project name"
				helperText="Used in your dashboard and generated URLs."
				value={value}
				onChange={(event) => setValue(event.target.value)}
				placeholder="Tile UI Docs"
			/>
			<Input label="Read-only example" helperText="Use this for immutable values or generated fields." defaultValue="tile-ui" readOnly />
			<Input label="Validation example" error="A project name is required before publishing." defaultValue="" />
		</div>
	);
}
