// apps/solid/components/demos/native-select.tsx
import { createSignal } from 'solid-js';
import { Button, NativeSelect, NativeSelectOptGroup, NativeSelectOption } from '@tile-ui/solid';

export default function NativeSelectDemo() {
	const [value, setValue] = createSignal('solid');
	return (
		<form class="component-preview__stack" onReset={() => queueMicrotask(() => setValue('solid'))}>
			<NativeSelect name="framework" defaultValue="solid" aria-label="Framework" onValueChange={setValue}>
				<NativeSelectOptGroup label="Framework">
					<NativeSelectOption value="solid">Solid</NativeSelectOption>
					<NativeSelectOption value="react">React</NativeSelectOption>
					<NativeSelectOption value="vue">Vue</NativeSelectOption>
				</NativeSelectOptGroup>
			</NativeSelect>
			<Button type="reset" size="sm" variant="outline">
				Reset selection
			</Button>
			<p class="component-preview__text">Selected: {value()}</p>
		</form>
	);
}

// apps/react/components/demos/native-select.tsx
import { NativeSelect, NativeSelectOption } from '@tile-ui/react';

export default function NativeSelectDemo() {
	return (
		<NativeSelect defaultValue="a" aria-label="Fruit" style={{ maxWidth: 260 }}>
			<NativeSelectOption value="a">Apple</NativeSelectOption>
			<NativeSelectOption value="b">Banana</NativeSelectOption>
			<NativeSelectOption value="c">Cherry</NativeSelectOption>
		</NativeSelect>
	);
}
