// apps/vue/components/demos/slider.tsx
import { defineComponent, ref } from 'vue';
import { Slider, SliderTrack, SliderRange, SliderThumb } from '@tile-ui/vue';

export default defineComponent({
	name: 'SliderDemo',
	setup() {
		const value = ref(40);
		return () => (
			<div class="component-preview__stack">
				<Slider
					modelValue={value.value}
					onUpdate:modelValue={(next: number) => {
						value.value = next;
					}}
					max={100}
					step={1}>
					<SliderTrack>
						<SliderRange />
						<SliderThumb aria-label="Volume" />
					</SliderTrack>
				</Slider>
				<p class="component-preview__text">
					Value:
					<strong>{value.value}</strong>
				</p>
			</div>
		);
	},
});

// apps/react/components/demos/slider.tsx
import { useState } from 'react';
import { Slider, SliderTrack, SliderRange, SliderThumb } from '@tile-ui/react';

export default function SliderDemo() {
	const [value, setValue] = useState(40);

	return (
		<div className="component-preview__stack">
			<Slider value={value} onValueChange={setValue} max={100} step={1}>
				<SliderTrack>
					<SliderRange />
					<SliderThumb aria-label="Volume" />
				</SliderTrack>
			</Slider>
			<p className="component-preview__text">
				Value: <strong>{value}</strong>
			</p>
		</div>
	);
}
