// apps/vue/components/demos/use-local-storage.tsx
import { defineComponent } from 'vue';
import { useLocalStorage } from '@tile-ui/vue';

export default defineComponent({
	name: 'UseLocalStorageDemo',
	setup() {
		const theme = useLocalStorage<'light' | 'dark'>('theme', 'light');
		return () => (
			<div class="component-preview__stack">
				<div class="button-group">
					<button
						type="button"
						class="component-preview__action"
						onClick={() => {
							theme.value = 'light';
						}}>
						Light
					</button>
					<button
						type="button"
						class="component-preview__action"
						onClick={() => {
							theme.value = 'dark';
						}}>
						Dark
					</button>
				</div>
				<p class="component-preview__text">
					Current theme preference: <strong>{theme.value}</strong>
				</p>
			</div>
		);
	},
});

// apps/react/components/demos/use-local-storage.tsx
import { Button } from '@tile-ui/react';
import { useLocalStorage } from '@tile-ui/react/hooks';

export default function UseLocalStorageDemo() {
	const [theme, setTheme] = useLocalStorage<'light' | 'dark'>('theme', 'light');

	return (
		<div className="component-preview__stack">
			<div className="button-group">
				<Button variant={theme === 'light' ? 'default' : 'outline'} onClick={() => setTheme('light')}>
					Light
				</Button>
				<Button variant={theme === 'dark' ? 'default' : 'outline'} onClick={() => setTheme('dark')}>
					Dark
				</Button>
			</div>
			<p className="component-preview__text">
				Current theme preference: <strong>{theme}</strong>
			</p>
		</div>
	);
}
