// packages/react/src/components/scroll-area/scroll-area.tsx
import React, { createContext, useContext, useEffect, useRef, useState } from 'react';
import { getScrollBarSizeKey, scrollAreaStyleKeys } from '@tile-ui/core';
import type { ScrollAreaBaseProps, ScrollBarBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/scroll-area.module.scss';

interface ScrollAreaContextValue {
	viewportRef: React.RefObject<HTMLDivElement | null>;
}

const ScrollAreaContext = createContext<ScrollAreaContextValue | null>(null);

function useScrollAreaContext(): ScrollAreaContextValue {
	const context = useContext(ScrollAreaContext);
	if (!context) {
		throw new Error('ScrollArea sub-components must be used within <ScrollArea>.');
	}
	return context;
}

export interface ScrollAreaProps extends React.HTMLAttributes<HTMLDivElement>, ScrollAreaBaseProps {}

const ScrollArea = React.forwardRef<HTMLDivElement, ScrollAreaProps>(({ className = '', children, ...props }, ref) => {
	const viewportRef = useRef<HTMLDivElement | null>(null);

	return (
		<ScrollAreaContext.Provider value={{ viewportRef }}>
			<div ref={ref} className={`${styles[scrollAreaStyleKeys.root]} ${className}`} {...props}>
				<div ref={viewportRef} tabIndex={0} className={styles[scrollAreaStyleKeys.viewport]}>
					{children}
				</div>
			</div>
		</ScrollAreaContext.Provider>
	);
});
ScrollArea.displayName = 'ScrollArea';

interface ScrollBarMetrics {
	size: number;
	offset: number;
	visible: boolean;
}

export interface ScrollBarProps extends React.HTMLAttributes<HTMLDivElement>, ScrollBarBaseProps {}

const ScrollBar = React.forwardRef<HTMLDivElement, ScrollBarProps>(({ className = '', orientation = 'vertical', ...props }, ref) => {
	const context = useScrollAreaContext();
	const trackRef = useRef<HTMLDivElement | null>(null);
	const dragRef = useRef<number | null>(null);
	const [metrics, setMetrics] = useState<ScrollBarMetrics>({ size: 0, offset: 0, visible: false });
	const isVertical = orientation === 'vertical';

	useEffect(() => {
		const viewport = context.viewportRef.current;
		const track = trackRef.current;
		if (!viewport || !track) {
			return;
		}

		function update() {
			const track = trackRef.current;
			const viewport = context.viewportRef.current;
			if (!track || !viewport) {
				return;
			}
			const trackSize = isVertical ? track.clientHeight : track.clientWidth;
			const scrollable = isVertical ? viewport.scrollHeight - viewport.clientHeight : viewport.scrollWidth - viewport.clientWidth;
			const visibleSize = isVertical ? viewport.clientHeight : viewport.clientWidth;
			const total = visibleSize + scrollable;
			const size = total > 0 ? Math.max((visibleSize / total) * trackSize, 24) : 0;
			const maxOffset = trackSize - size;
			const scrollPos = isVertical ? viewport.scrollTop : viewport.scrollLeft;
			const offset = scrollable > 0 && maxOffset > 0 ? (scrollPos / scrollable) * maxOffset : 0;
			setMetrics({ size, offset, visible: scrollable > 0 });
		}

		update();
		viewport.addEventListener('scroll', update, { passive: true });
		window.addEventListener('resize', update);
		const observer = new ResizeObserver(update);
		observer.observe(viewport);
		observer.observe(track);

		return () => {
			viewport.removeEventListener('scroll', update);
			window.removeEventListener('resize', update);
			observer.disconnect();
		};
	}, [context.viewportRef, isVertical]);

	function scrollToOffset(offset: number) {
		const track = trackRef.current;
		const viewport = context.viewportRef.current;
		if (!track || !viewport) {
			return;
		}
		const trackSize = isVertical ? track.clientHeight : track.clientWidth;
		const maxOffset = trackSize - metrics.size;
		const scrollable = isVertical ? viewport.scrollHeight - viewport.clientHeight : viewport.scrollWidth - viewport.clientWidth;
		if (maxOffset <= 0 || scrollable <= 0) {
			return;
		}
		const ratio = offset / maxOffset;
		if (isVertical) {
			viewport.scrollTop = ratio * scrollable;
		} else {
			viewport.scrollLeft = ratio * scrollable;
		}
	}

	function handlePointerDown(event: React.PointerEvent<HTMLDivElement>) {
		const track = trackRef.current;
		if (!track) {
			return;
		}
		track.setPointerCapture(event.pointerId);
		const rect = track.getBoundingClientRect();
		const pos = isVertical ? event.clientY : event.clientX;
		const trackStart = isVertical ? rect.top : rect.left;
		const trackSize = isVertical ? rect.height : rect.width;
		const maxOffset = trackSize - metrics.size;
		const offset = Math.min(Math.max(0, pos - trackStart - metrics.size / 2), maxOffset);
		dragRef.current = offset;
		scrollToOffset(offset);
	}

	function handlePointerMove(event: React.PointerEvent<HTMLDivElement>) {
		const dragOffset = dragRef.current;
		const track = trackRef.current;
		if (dragOffset === null || !track || !track.hasPointerCapture(event.pointerId)) {
			return;
		}
		const rect = track.getBoundingClientRect();
		const pos = isVertical ? event.clientY : event.clientX;
		const trackStart = isVertical ? rect.top : rect.left;
		const trackSize = isVertical ? rect.height : rect.width;
		const maxOffset = trackSize - metrics.size;
		const offset = Math.min(Math.max(0, pos - trackStart - metrics.size / 2), maxOffset);
		dragRef.current = offset;
		scrollToOffset(offset);
	}

	function handlePointerUp() {
		dragRef.current = null;
	}

	function setTrackRef(element: HTMLDivElement | null) {
		trackRef.current = element;

		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	return (
		<div
			{...props}
			ref={setTrackRef}
			data-orientation={orientation}
			className={`${styles[scrollAreaStyleKeys.scrollbar]} ${styles[getScrollBarSizeKey(orientation)]} ${className}`}
			style={{ opacity: metrics.visible ? 1 : 0 }}
			onPointerDown={handlePointerDown}
			onPointerMove={handlePointerMove}
			onPointerUp={handlePointerUp}>
			<div
				className={styles[scrollAreaStyleKeys.thumb]}
				style={
					isVertical
						? { height: `${metrics.size}px`, transform: `translateY(${metrics.offset}px)` }
						: { width: `${metrics.size}px`, transform: `translateX(${metrics.offset}px)` }
				}
			/>
		</div>
	);
});
ScrollBar.displayName = 'ScrollBar';

export { ScrollArea, ScrollBar };
export default ScrollArea;

// packages/vue/src/components/scroll-area/scroll-area.tsx
import { computed, defineComponent, h, inject, onBeforeUnmount, onMounted, provide, ref, type InjectionKey, type PropType, type Ref } from 'vue';
import { getScrollBarSizeKey, scrollAreaStyleKeys } from '@tile-ui/core';
import type { ScrollBarOrientation } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/scroll-area.module.scss';

const ScrollAreaContextKey: InjectionKey<Ref<HTMLElement | null>> = Symbol('tile-scroll-area');

export const ScrollArea = defineComponent({
	name: 'ScrollArea',
	setup(_props, { slots, attrs }) {
		const viewportRef = ref<HTMLElement | null>(null);
		provide(ScrollAreaContextKey, viewportRef);

		return () =>
			h('div', { ...attrs, class: [styles[scrollAreaStyleKeys.root], attrs.class] }, [
				h('div', { ref: viewportRef, tabindex: '0', class: styles[scrollAreaStyleKeys.viewport] }, slots.default?.()),
			]);
	},
});

export const ScrollBar = defineComponent({
	name: 'ScrollBar',
	props: {
		orientation: {
			type: String as PropType<ScrollBarOrientation>,
			default: 'vertical',
		},
	},
	setup(props, { attrs }) {
		const viewportValue = inject(ScrollAreaContextKey);
		if (!viewportValue) {
			throw new Error('ScrollBar must be used within <ScrollArea>.');
		}
		const viewport: Ref<HTMLElement | null> = viewportValue;

		const trackRef = ref<HTMLElement | null>(null);
		const metrics = ref({ size: 0, offset: 0, visible: false });
		let dragOffset: number | null = null;
		let observer: ResizeObserver | null = null;
		let onScroll: (() => void) | null = null;
		let onResize: (() => void) | null = null;

		const isVertical = computed(() => props.orientation === 'vertical');

		function update() {
			const track = trackRef.value;
			const vp = viewport.value;
			if (!track || !vp) {
				return;
			}
			const trackSize = isVertical.value ? track.clientHeight : track.clientWidth;
			const scrollable = isVertical.value ? vp.scrollHeight - vp.clientHeight : vp.scrollWidth - vp.clientWidth;
			const visibleSize = isVertical.value ? vp.clientHeight : vp.clientWidth;
			const total = visibleSize + scrollable;
			const size = total > 0 ? Math.max((visibleSize / total) * trackSize, 24) : 0;
			const maxOffset = trackSize - size;
			const scrollPos = isVertical.value ? vp.scrollTop : vp.scrollLeft;
			const offset = scrollable > 0 && maxOffset > 0 ? (scrollPos / scrollable) * maxOffset : 0;
			metrics.value = { size, offset, visible: scrollable > 0 };
		}

		function scrollToOffset(offset: number) {
			const track = trackRef.value;
			const vp = viewport.value;
			if (!track || !vp) {
				return;
			}
			const trackSize = isVertical.value ? track.clientHeight : track.clientWidth;
			const maxOffset = trackSize - metrics.value.size;
			const scrollable = isVertical.value ? vp.scrollHeight - vp.clientHeight : vp.scrollWidth - vp.clientWidth;
			if (maxOffset <= 0 || scrollable <= 0) {
				return;
			}
			const ratio = offset / maxOffset;
			if (isVertical.value) {
				vp.scrollTop = ratio * scrollable;
			} else {
				vp.scrollLeft = ratio * scrollable;
			}
		}

		onMounted(() => {
			const vp = viewport.value;
			const track = trackRef.value;
			if (!vp || !track) {
				return;
			}

			update();
			onScroll = () => update();
			onResize = () => update();
			vp.addEventListener('scroll', onScroll, { passive: true });
			window.addEventListener('resize', onResize);
			observer = new ResizeObserver(update);
			observer.observe(vp);
			observer.observe(track);
		});

		onBeforeUnmount(() => {
			const vp = viewport.value;
			if (vp && onScroll) {
				vp.removeEventListener('scroll', onScroll);
			}
			if (onResize) {
				window.removeEventListener('resize', onResize);
			}
			observer?.disconnect();
		});

		function handlePointerdown(event: PointerEvent) {
			const track = trackRef.value;
			if (!track) {
				return;
			}
			track.setPointerCapture(event.pointerId);
			const rect = track.getBoundingClientRect();
			const pos = isVertical.value ? event.clientY : event.clientX;
			const trackStart = isVertical.value ? rect.top : rect.left;
			const trackSize = isVertical.value ? rect.height : rect.width;
			const maxOffset = trackSize - metrics.value.size;
			const offset = Math.min(Math.max(0, pos - trackStart - metrics.value.size / 2), maxOffset);
			dragOffset = offset;
			scrollToOffset(offset);
		}

		function handlePointermove(event: PointerEvent) {
			if (dragOffset === null) {
				return;
			}
			const track = trackRef.value;
			if (!track || !track.hasPointerCapture(event.pointerId)) {
				return;
			}
			const rect = track.getBoundingClientRect();
			const pos = isVertical.value ? event.clientY : event.clientX;
			const trackStart = isVertical.value ? rect.top : rect.left;
			const trackSize = isVertical.value ? rect.height : rect.width;
			const maxOffset = trackSize - metrics.value.size;
			const offset = Math.min(Math.max(0, pos - trackStart - metrics.value.size / 2), maxOffset);
			dragOffset = offset;
			scrollToOffset(offset);
		}

		function handlePointerup() {
			dragOffset = null;
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: trackRef,
					class: [styles[scrollAreaStyleKeys.scrollbar], styles[getScrollBarSizeKey(props.orientation)], attrs.class],
					'data-orientation': props.orientation,
					style: { opacity: metrics.value.visible ? 1 : 0 },
					onPointerdown: handlePointerdown,
					onPointermove: handlePointermove,
					onPointerup: handlePointerup,
				},
				[
					h('div', {
						class: styles[scrollAreaStyleKeys.thumb],
						style: isVertical.value
							? { height: `${metrics.value.size}px`, transform: `translateY(${metrics.value.offset}px)` }
							: { width: `${metrics.value.size}px`, transform: `translateX(${metrics.value.offset}px)` },
					}),
				],
			);
	},
});

export default ScrollArea;
