// packages/react/src/components/badge/badge.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { getBadgeStyleKeys } from '@tile-ui/core';
import type { BadgeBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/badge.module.scss';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement>, BadgeBaseProps {}

const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(({ className = '', variant = 'default', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'span';
	const styleKeys = getBadgeStyleKeys(variant);

	const classes = [styles[styleKeys.base], styles[styleKeys.variant], className].filter(Boolean).join(' ');

	return (
		<Comp ref={ref} className={classes} {...props}>
			{children}
		</Comp>
	);
});

Badge.displayName = 'Badge';

export { Badge };
export default Badge;

// packages/vue/src/components/badge/badge.tsx
import { defineComponent, computed, h, type PropType } from 'vue';
import { getBadgeStyleKeys } from '@tile-ui/core';
import type { BadgeVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/badge.module.scss';

export const Badge = defineComponent({
	name: 'Badge',
	props: {
		variant: {
			type: String as PropType<BadgeVariant>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const styleKeys = computed(() => getBadgeStyleKeys(props.variant));
		const classes = computed(() => [styles[styleKeys.value.base], styles[styleKeys.value.variant], attrs.class]);

		return () => h('span', { ...attrs, class: classes.value }, slots.default?.());
	},
});

export default Badge;
