// packages/react/src/components/hover-card/hover-card.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import { getHoverCardPosition, getHoverCardState, hoverCardStyleKeys } from '@tile-ui/core';
import type { HoverCardBaseProps, HoverCardContentBaseProps, HoverCardPosition, HoverCardTriggerBaseProps } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/hover-card.module.scss';

interface HoverCardContextValue {
	open: boolean;
	triggerRef: React.RefObject<HTMLElement | null>;
	contentId: string;
	openDelay: number;
	closeDelay: number;
	setOpen: (open: boolean) => void;
}

const HoverCardContext = createContext<HoverCardContextValue | null>(null);

function useHoverCardContext(): HoverCardContextValue {
	const context = useContext(HoverCardContext);
	if (!context) {
		throw new Error('HoverCard sub-components must be used within <HoverCard>.');
	}
	return context;
}

export interface HoverCardProps extends React.HTMLAttributes<HTMLDivElement>, HoverCardBaseProps {}

const HoverCard = React.forwardRef<HTMLDivElement, HoverCardProps>(
	({ className = '', open, defaultOpen = false, openDelay = 200, closeDelay = 300, onOpenChange, children, ...props }, ref) => {
		const [internalOpen, setInternalOpen] = useState(defaultOpen);
		const isOpen = open !== undefined ? open : internalOpen;
		const triggerRef = useRef<HTMLElement | null>(null);
		const contentId = useId();

		const setOpen = useCallback(
			(next: boolean) => {
				if (open === undefined) {
					setInternalOpen(next);
				}
				onOpenChange?.(next);
			},
			[open, onOpenChange],
		);

		return (
			<HoverCardContext.Provider value={{ open: isOpen, triggerRef, contentId, openDelay, closeDelay, setOpen }}>
				<div ref={ref} className={`${styles[hoverCardStyleKeys.root]} ${className}`} {...props}>
					{children}
				</div>
			</HoverCardContext.Provider>
		);
	},
);
HoverCard.displayName = 'HoverCard';

export interface HoverCardTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, HoverCardTriggerBaseProps {}

const HoverCardTrigger = React.forwardRef<HTMLButtonElement, HoverCardTriggerProps>(({ className = '', asChild = false, children, onKeyDown, ...props }, ref) => {
	const context = useHoverCardContext();
	const openTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
	const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

	function clearOpenTimer() {
		if (openTimer.current) {
			clearTimeout(openTimer.current);
			openTimer.current = null;
		}
	}

	function clearCloseTimer() {
		if (closeTimer.current) {
			clearTimeout(closeTimer.current);
			closeTimer.current = null;
		}
	}

	function scheduleOpen() {
		clearOpenTimer();
		openTimer.current = setTimeout(() => context.setOpen(true), context.openDelay);
	}

	function scheduleClose() {
		clearCloseTimer();
		closeTimer.current = setTimeout(() => context.setOpen(false), context.closeDelay);
	}

	function handlePointerEnter() {
		clearCloseTimer();
		scheduleOpen();
	}

	function handlePointerLeave() {
		clearOpenTimer();
		scheduleClose();
	}

	function handleFocus() {
		clearCloseTimer();
		scheduleOpen();
	}

	function handleBlur() {
		clearOpenTimer();
		scheduleClose();
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) {
		if (event.key === 'Escape') {
			clearOpenTimer();
			clearCloseTimer();
			context.setOpen(false);
		}
		onKeyDown?.(event);
	}

	useEffect(() => {
		return () => {
			clearOpenTimer();
			clearCloseTimer();
		};
	}, []);

	function setRef(element: HTMLElement | null) {
		context.triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element as HTMLButtonElement | null);
		} else if (ref) {
			ref.current = element as HTMLButtonElement | null;
		}
	}

	const Comp = asChild ? Slot : 'button';
	const state = getHoverCardState(context.open);

	return (
		<Comp
			ref={setRef}
			data-state={state}
			className={asChild ? undefined : `${styles[hoverCardStyleKeys.trigger]} ${className}`}
			onPointerEnter={handlePointerEnter}
			onPointerLeave={handlePointerLeave}
			onFocus={handleFocus}
			onBlur={handleBlur}
			onKeyDown={handleKeyDown}
			{...props}>
			{children}
		</Comp>
	);
});
HoverCardTrigger.displayName = 'HoverCardTrigger';

export interface HoverCardContentProps extends React.HTMLAttributes<HTMLDivElement>, HoverCardContentBaseProps {
	container?: PortalContainer;
}

const HoverCardContent = React.forwardRef<HTMLDivElement, HoverCardContentProps>(
	({ className = '', side = 'bottom', align = 'center', sideOffset = 4, container, children, ...props }, ref) => {
		const { open, triggerRef, contentId, closeDelay, setOpen } = useHoverCardContext();
		const portalContainer = usePortalContainer(container);
		const [position, setPosition] = useState<HoverCardPosition | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);
		const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

		function setRef(element: HTMLDivElement | null) {
			contentRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		function clearCloseTimer() {
			if (closeTimer.current) {
				clearTimeout(closeTimer.current);
				closeTimer.current = null;
			}
		}

		function scheduleClose() {
			clearCloseTimer();
			closeTimer.current = setTimeout(() => setOpen(false), closeDelay);
		}

		function handlePointerEnter() {
			clearCloseTimer();
		}

		function handlePointerLeave() {
			scheduleClose();
		}

		useEffect(() => {
			return () => {
				clearCloseTimer();
			};
		}, []);

		useLayoutEffect(() => {
			if (!open) {
				return;
			}

			function updatePosition() {
				const trigger = triggerRef.current;
				const content = contentRef.current;
				if (!trigger || !content) {
					return;
				}

				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				setPosition(getHoverCardPosition({ triggerRect, contentSize, side, align, sideOffset, viewport }));
			}

			updatePosition();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			return () => {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
			};
		}, [open, side, align, sideOffset, triggerRef]);

		useEffect(() => {
			if (!open) {
				return;
			}

			function handleKeyDown(event: KeyboardEvent) {
				if (event.key === 'Escape') {
					clearCloseTimer();
					setOpen(false);
				}
			}

			document.addEventListener('keydown', handleKeyDown);

			return () => {
				document.removeEventListener('keydown', handleKeyDown);
			};
		}, [open, setOpen]);

		const state = getHoverCardState(open);
		const classes = [styles[hoverCardStyleKeys.content], className].filter(Boolean).join(' ');

		const content = (
			<div
				ref={setRef}
				id={contentId}
				role="dialog"
				aria-modal="false"
				tabIndex={-1}
				data-state={state}
				data-side={side}
				data-align={align}
				className={classes}
				style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
				onPointerEnter={handlePointerEnter}
				onPointerLeave={handlePointerLeave}
				{...props}>
				{children}
			</div>
		);

		if (!open || !portalContainer) {
			return null;
		}

		return createPortal(content, portalContainer);
	},
);
HoverCardContent.displayName = 'HoverCardContent';

export { HoverCard, HoverCardTrigger, HoverCardContent };
export default HoverCard;

// packages/vue/src/components/hover-card/hover-card.tsx
import {
	cloneVNode,
	computed,
	defineComponent,
	h,
	inject,
	mergeProps,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	useId,
	watch,
	type InjectionKey,
	type PropType,
	type Ref,
	Teleport,
} from 'vue';
import { getHoverCardPosition, getHoverCardState, hoverCardStyleKeys } from '@tile-ui/core';
import type { HoverCardAlign, HoverCardSide } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/hover-card.module.scss';

interface HoverCardContextValue {
	open: Ref<boolean>;
	triggerRef: Ref<HTMLElement | null>;
	contentId: string;
	openDelay: number;
	closeDelay: number;
	setOpen: (open: boolean) => void;
}

const HoverCardContextKey: InjectionKey<HoverCardContextValue> = Symbol('tile-hover-card');

export const HoverCard = defineComponent({
	name: 'HoverCard',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
		openDelay: { type: Number, default: 200 },
		closeDelay: { type: Number, default: 300 },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const triggerRef = ref<HTMLElement | null>(null);
		const contentId = `tile-hover-card-${useId()}`;

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		provide(HoverCardContextKey, { open: isOpen, triggerRef, contentId, openDelay: props.openDelay, closeDelay: props.closeDelay, setOpen });

		return () => h('div', { class: styles[hoverCardStyleKeys.root] }, slots.default?.());
	},
});

export const HoverCardTrigger = defineComponent({
	name: 'HoverCardTrigger',
	inheritAttrs: false,
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(HoverCardContextKey);
		if (!contextValue) {
			throw new Error('HoverCardTrigger must be used within <HoverCard>.');
		}
		const context: HoverCardContextValue = contextValue;

		let openTimer: ReturnType<typeof setTimeout> | null = null;
		let closeTimer: ReturnType<typeof setTimeout> | null = null;

		function clearOpenTimer() {
			if (openTimer) {
				clearTimeout(openTimer);
				openTimer = null;
			}
		}

		function clearCloseTimer() {
			if (closeTimer) {
				clearTimeout(closeTimer);
				closeTimer = null;
			}
		}

		function scheduleOpen() {
			clearOpenTimer();
			openTimer = setTimeout(() => context.setOpen(true), context.openDelay);
		}

		function scheduleClose() {
			clearCloseTimer();
			closeTimer = setTimeout(() => context.setOpen(false), context.closeDelay);
		}

		function handlePointerenter() {
			clearCloseTimer();
			scheduleOpen();
		}

		function handlePointerleave() {
			clearOpenTimer();
			scheduleClose();
		}

		function handleFocus() {
			clearCloseTimer();
			scheduleOpen();
		}

		function handleBlur() {
			clearOpenTimer();
			scheduleClose();
		}

		function handleKeydown(event: KeyboardEvent) {
			if (event.key === 'Escape') {
				clearOpenTimer();
				clearCloseTimer();
				context.setOpen(false);
			}
		}

		onBeforeUnmount(() => {
			clearOpenTimer();
			clearCloseTimer();
		});

		function setRef(el: unknown) {
			context.triggerRef.value = (el as HTMLElement | null) ?? null;
		}

		const triggerProps = computed(() => ({
			ref: setRef,
			'data-state': getHoverCardState(context.open.value),
			onPointerenter: handlePointerenter,
			onPointerleave: handlePointerleave,
			onFocus: handleFocus,
			onBlur: handleBlur,
			onKeydown: handleKeydown,
		}));

		return () => {
			const child = slots.default?.()[0];

			if (props.asChild && child) {
				return cloneVNode(child, mergeProps(child.props ?? {}, triggerProps.value));
			}

			return h('button', { ...attrs, ...triggerProps.value, type: 'button', class: [styles[hoverCardStyleKeys.trigger], attrs.class] }, slots.default?.());
		};
	},
});

export const HoverCardContent = defineComponent({
	name: 'HoverCardContent',
	inheritAttrs: false,
	props: {
		side: { type: String as PropType<HoverCardSide>, default: 'bottom' },
		align: { type: String as PropType<HoverCardAlign>, default: 'center' },
		sideOffset: { type: Number, default: 4 },
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots, attrs }) {
		const portalContainer = usePortalContainer(() => props.container);
		const contextValue = inject(HoverCardContextKey);
		if (!contextValue) {
			throw new Error('HoverCardContent must be used within <HoverCard>.');
		}
		const context: HoverCardContextValue = contextValue;

		const contentRef = ref<HTMLElement | null>(null);
		const position = ref<{ top: number; left: number } | null>(null);

		let closeTimer: ReturnType<typeof setTimeout> | null = null;
		let disposeDocListeners: (() => void) | null = null;

		function clearCloseTimer() {
			if (closeTimer) {
				clearTimeout(closeTimer);
				closeTimer = null;
			}
		}

		function scheduleClose() {
			clearCloseTimer();
			closeTimer = setTimeout(() => context.setOpen(false), context.closeDelay);
		}

		function handlePointerenter() {
			clearCloseTimer();
		}

		function handlePointerleave() {
			scheduleClose();
		}

		function updatePosition() {
			const trigger = context.triggerRef.value;
			const content = contentRef.value;
			if (!trigger || !content) {
				return;
			}

			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			position.value = getHoverCardPosition({ triggerRect, contentSize, side: props.side, align: props.align, sideOffset: props.sideOffset, viewport });
		}

		function addListeners() {
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);
		}

		function removeListeners() {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
		}

		function addDocListeners(): () => void {
			function handleKeyDown(event: KeyboardEvent) {
				if (event.key === 'Escape') {
					clearCloseTimer();
					context.setOpen(false);
				}
			}

			document.addEventListener('keydown', handleKeyDown);

			return () => {
				document.removeEventListener('keydown', handleKeyDown);
			};
		}

		onMounted(() => {
			if (context.open.value) {
				addListeners();
				updatePosition();
				disposeDocListeners = addDocListeners();
			}
		});

		watch(
			() => context.open.value,
			(open) => {
				if (open) {
					addListeners();
					updatePosition();
					disposeDocListeners = addDocListeners();
				} else {
					removeListeners();
					disposeDocListeners?.();
					disposeDocListeners = null;
				}
			},
		);

		watch(
			() => [props.side, props.align, props.sideOffset],
			() => {
				if (context.open.value) {
					updatePosition();
				}
			},
		);

		onBeforeUnmount(() => {
			clearCloseTimer();
			removeListeners();
			disposeDocListeners?.();
		});

		return () => {
			const open = context.open.value;
			const userClass = attrs.class;
			const userStyle = attrs.style;
			const restAttrs = { ...attrs };
			delete restAttrs.class;
			delete restAttrs.style;

			return h(Teleport, { to: portalContainer.value }, [
				h(
					'div',
					{
						...restAttrs,
						ref: contentRef,
						id: context.contentId,
						role: 'dialog',
						'aria-modal': 'false',
						tabindex: -1,
						'data-state': getHoverCardState(open),
						'data-side': props.side,
						'data-align': props.align,
						class: [styles[hoverCardStyleKeys.content], userClass],
						style: position.value ? [userStyle, { top: `${position.value.top}px`, left: `${position.value.left}px` }] : userStyle,
						onPointerenter: handlePointerenter,
						onPointerleave: handlePointerleave,
					},
					slots.default?.(),
				),
			]);
		};
	},
});

export default HoverCard;
