// packages/solid/src/components/message/message.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { getMessageStyleKeys, messageStyleKeys } from '@tile-ui/core';
import type { MessageBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/message.module.scss';

interface MessagePrimitiveProps extends JSX.HTMLAttributes<HTMLDivElement> {}

function messagePrimitive(key: 'group' | 'avatar' | 'content' | 'header' | 'footer', slot: string) {
	return (props: ParentProps<MessagePrimitiveProps>) => {
		const [local, rest] = splitProps(props, ['class', 'children']);
		return (
			<div {...rest} data-slot={slot} class={[styles[messageStyleKeys[key]], local.class].filter(Boolean).join(' ')}>
				{local.children}
			</div>
		);
	};
}

export interface MessageGroupProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const MessageGroup = messagePrimitive('group', 'message-group');

export interface MessageProps extends JSX.HTMLAttributes<HTMLDivElement>, MessageBaseProps {}

export function Message(props: ParentProps<MessageProps>) {
	const [local, rest] = splitProps(props, ['align', 'class', 'children']);
	const align = () => local.align ?? 'start';
	const styleKeys = () => getMessageStyleKeys(align());
	const classes = () => [styles[styleKeys().base], styles[styleKeys().align], local.class].filter(Boolean).join(' ');

	return (
		<div {...rest} data-slot="message" data-align={align()} class={classes()}>
			{local.children}
		</div>
	);
}

export interface MessageAvatarProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const MessageAvatar = messagePrimitive('avatar', 'message-avatar');

export interface MessageContentProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const MessageContent = messagePrimitive('content', 'message-content');

export interface MessageHeaderProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const MessageHeader = messagePrimitive('header', 'message-header');

export interface MessageFooterProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const MessageFooter = messagePrimitive('footer', 'message-footer');

export default Message;

// packages/react/src/components/message/message.tsx
import React from 'react';
import { getMessageStyleKeys, messageStyleKeys } from '@tile-ui/core';
import type { MessageBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/message.module.scss';

export interface MessageGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageGroup = React.forwardRef<HTMLDivElement, MessageGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-group" className={[styles[messageStyleKeys.group], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageGroup.displayName = 'MessageGroup';

export interface MessageProps extends React.HTMLAttributes<HTMLDivElement>, MessageBaseProps {}

const Message = React.forwardRef<HTMLDivElement, MessageProps>(({ className = '', align = 'start', children, ...props }, ref) => {
	const styleKeys = getMessageStyleKeys(align);

	return (
		<div ref={ref} data-slot="message" data-align={align} className={[styles[styleKeys.base], styles[styleKeys.align], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
Message.displayName = 'Message';

export interface MessageAvatarProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageAvatar = React.forwardRef<HTMLDivElement, MessageAvatarProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-avatar" className={[styles[messageStyleKeys.avatar], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageAvatar.displayName = 'MessageAvatar';

export interface MessageContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageContent = React.forwardRef<HTMLDivElement, MessageContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-content" className={[styles[messageStyleKeys.content], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageContent.displayName = 'MessageContent';

export interface MessageHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageHeader = React.forwardRef<HTMLDivElement, MessageHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-header" className={[styles[messageStyleKeys.header], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageHeader.displayName = 'MessageHeader';

export interface MessageFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageFooter = React.forwardRef<HTMLDivElement, MessageFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-footer" className={[styles[messageStyleKeys.footer], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageFooter.displayName = 'MessageFooter';

export { MessageGroup, Message, MessageAvatar, MessageContent, MessageHeader, MessageFooter };
export default Message;
