// packages/vue/src/components/chart/chart.tsx
import {
	computed,
	defineComponent,
	h,
	inject,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	reactive,
	useId,
	type ComputedRef,
	type InjectionKey,
	type PropType,
	type VNode,
} from 'vue';
import {
	CHART_INITIAL_DIMENSION,
	buildChartThemeCss,
	chartStyleKeys,
	computeChartLayout,
	findChartNearestIndex,
	getChartAreaPathD,
	getChartBaselineY,
	getChartBarRects,
	getChartLegendItems,
	getChartPathD,
	getChartTooltipEntries,
	getChartTooltipPosition,
} from '@tile-ui/core';
import type { ChartConfig, ChartDatum, ChartLayout, ChartLegendItem, ChartSeriesItem, ChartTooltipEntry, ChartType } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/chart.module.scss';

interface ChartContextValue {
	config: ChartConfig;
	layout: ChartLayout;
	data: ChartDatum[];
	activeIndex: number | null;
}

type ChartContext = ComputedRef<ChartContextValue>;

const ChartContextKey: InjectionKey<ChartContext> = Symbol('tile-chart');

/**
 * 读取图表上下文 (必须在 ChartContainer 内使用)
 */
function useChart(): ChartContext {
	const context = inject(ChartContextKey);
	if (!context) {
		throw new Error('图表子组件必须在 <ChartContainer /> 内使用');
	}
	return context;
}

export const ChartStyle = defineComponent({
	name: 'ChartStyle',
	props: {
		id: { type: String, required: true },
		config: { type: Object as PropType<ChartConfig>, required: true },
	},
	setup(props) {
		const css = computed(() => buildChartThemeCss(props.id, props.config));

		return () => {
			if (!css.value) {
				return null;
			}
			return h('style', { innerHTML: css.value });
		};
	},
});

export const ChartContainer = defineComponent({
	name: 'ChartContainer',
	inheritAttrs: false,
	props: {
		config: { type: Object as PropType<ChartConfig>, required: true },
		title: { type: String, default: undefined },
		tabIndex: { type: Number, default: undefined },
		data: { type: Array as PropType<ChartDatum[]>, default: () => [] },
		xKey: { type: String, default: 'x' },
		series: { type: Array as PropType<ChartSeriesItem[]>, default: undefined },
		type: { type: String as PropType<ChartType>, default: 'line' },
		initialDimension: { type: Object as PropType<{ width: number; height: number }>, default: undefined },
		showLegend: { type: Boolean, default: true },
		showTooltip: { type: Boolean, default: true },
		showGrid: { type: Boolean, default: true },
		showAxis: { type: Boolean, default: true },
	},
	setup(props, { slots, attrs }) {
		const containerRef = ref<HTMLElement | null>(null);
		const size = reactive({ width: props.initialDimension?.width ?? CHART_INITIAL_DIMENSION.width, height: props.initialDimension?.height ?? CHART_INITIAL_DIMENSION.height });
		const activeIndex = ref<number | null>(null);
		const keyboardActive = ref(false);
		const mousePosition = reactive({ x: 0, y: 0 });
		const chartId = `chart-${useId()}`;

		let observer: ResizeObserver | null = null;

		onMounted(() => {
			const element = containerRef.value;
			if (!element) {
				return;
			}
			observer = new ResizeObserver((entries) => {
				for (const entry of entries) {
					const { width } = entry.contentRect;
					if (width > 0) {
						// 高度固定：容器高度由 SVG 内容撑开，若跟随容器高度会形成正反馈循环导致无限放大
						size.width = width;
					}
				}
			});
			observer.observe(element);
		});

		onBeforeUnmount(() => {
			observer?.disconnect();
			observer = null;
		});

		const layout = computed(() =>
			computeChartLayout({
				config: props.config,
				data: props.data,
				series: props.series ?? [],
				xKey: props.xKey,
				type: props.type,
				width: size.width,
				height: size.height,
				cssVariableScope: chartId,
			}),
		);

		const context = computed<ChartContextValue>(() => ({
			config: props.config,
			layout: layout.value,
			data: props.data,
			activeIndex: activeIndex.value,
		}));

		provide(ChartContextKey, context);

		const entries = computed(() => getChartTooltipEntries(layout.value, props.config, props.data, activeIndex.value));
		const legendItems = computed(() => getChartLegendItems(layout.value));
		const tooltipX = computed(() => (activeIndex.value !== null ? (layout.value.xTickX[activeIndex.value] ?? 0) : 0));
		const tooltipLabel = computed(() => (activeIndex.value !== null ? layout.value.xLabels[activeIndex.value] : null));

		function handleMouseMove(event: MouseEvent) {
			const svg = event.currentTarget as SVGSVGElement;
			const rect = svg.getBoundingClientRect();
			const x = ((event.clientX - rect.left) / rect.width) * layout.value.width;
			const y = ((event.clientY - rect.top) / rect.height) * layout.value.height;
			keyboardActive.value = false;
			mousePosition.x = x;
			mousePosition.y = y;
			activeIndex.value = findChartNearestIndex(layout.value, x);
		}

		function handleMouseLeave() {
			activeIndex.value = null;
		}

		function callEventHandler(handler: unknown, event: Event) {
			for (const current of Array.isArray(handler) ? handler : [handler]) {
				if (typeof current === 'function') current(event);
			}
		}

		function handleKeyDown(event: KeyboardEvent) {
			callEventHandler(attrs.onKeydown, event);
			const tabIndex = props.tabIndex ?? attrs.tabindex;
			if (event.defaultPrevented || tabIndex === undefined || Number(tabIndex) < 0 || event.target !== event.currentTarget) return;
			if (event.key === 'Escape') {
				keyboardActive.value = false;
				activeIndex.value = null;
				return;
			}
			if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') return;
			const count = layout.value.xLabels.length;
			if (count === 0) return;
			event.preventDefault();
			keyboardActive.value = true;
			if (activeIndex.value === null) activeIndex.value = event.key === 'ArrowLeft' ? count - 1 : 0;
			else activeIndex.value = Math.min(count - 1, Math.max(0, activeIndex.value + (event.key === 'ArrowLeft' ? -1 : 1)));
		}

		return () => {
			const l = layout.value;
			const userClass = attrs.class;
			const restAttrs = { ...attrs };
			for (const key of ['class', 'title', 'aria-label', 'aria-labelledby', 'aria-describedby', 'tabindex', 'tabIndex', 'onKeydown']) delete restAttrs[key];
			const title = props.title;
			const ariaLabel = typeof attrs['aria-label'] === 'string' ? attrs['aria-label'] : undefined;
			const ariaLabelledBy = typeof attrs['aria-labelledby'] === 'string' ? attrs['aria-labelledby'] : undefined;
			const ariaDescribedBy = typeof attrs['aria-describedby'] === 'string' ? attrs['aria-describedby'] : undefined;
			const tabIndex = props.tabIndex ?? attrs.tabindex;
			const svgLabel = ariaLabel ?? (ariaLabelledBy ? undefined : (title ?? 'Chart'));
			const statusText =
				keyboardActive.value && activeIndex.value !== null
					? [tooltipLabel.value, ...entries.value.map((entry) => `${entry.name} ${entry.value.toLocaleString()}`)].join(', ')
					: '';

			const children: any[] = [h(ChartStyle, { id: chartId, config: props.config })];

			const svgChildren: any[] = title ? [h('title', title)] : [];

			if (props.showGrid) {
				for (const y of l.yTickY) {
					svgChildren.push(h('line', { key: `y-${y}`, class: styles[chartStyleKeys.gridLine], x1: l.padding.left, x2: l.width - l.padding.right, y1: y, y2: y }));
				}
				for (const x of l.xTickX) {
					svgChildren.push(h('line', { key: `x-${x}`, class: styles[chartStyleKeys.gridLine], x1: x, x2: x, y1: l.padding.top, y2: l.height - l.padding.bottom }));
				}
			}

			if (props.showAxis) {
				l.xLabels.forEach((label, index) => {
					svgChildren.push(
						h(
							'text',
							{
								key: `label-${index}`,
								x: l.xTickX[index],
								y: l.height - l.padding.bottom / 2,
								'text-anchor': 'middle',
								'dominant-baseline': 'middle',
								'font-size': '10',
							},
							String(label),
						),
					);
				});
			}

			l.series.forEach((item, seriesIndex) => {
				if (item.type === 'bar') {
					const barSeriesCount = l.series.filter((s) => s.type === 'bar').length;
					const rects = getChartBarRects(l, seriesIndex, barSeriesCount);
					const bars = rects.map((rect) =>
						h('rect', { key: rect.index, 'data-index': rect.index, x: rect.x, y: rect.y, width: rect.width, height: rect.height, fill: item.color, rx: '2' }),
					);
					svgChildren.push(h('g', { key: item.key, 'data-series': item.key, 'data-type': item.type }, bars));
					return;
				}

				const path = item.type === 'area' ? getChartAreaPathD(item.points, getChartBaselineY(l)) : getChartPathD(item.points);
				const group: any[] = [];
				if (item.type === 'area') {
					group.push(h('path', { 'data-area': '', d: path, fill: item.color, 'fill-opacity': '0.2' }));
				}
				group.push(
					h('path', { d: getChartPathD(item.points), fill: 'none', stroke: item.color, 'stroke-width': '2', 'stroke-linejoin': 'round', 'stroke-linecap': 'round' }),
				);
				for (const point of item.points) {
					group.push(h('circle', { key: point.index, 'data-index': point.index, cx: point.x, cy: point.y, r: '2.5', fill: item.color }));
				}
				svgChildren.push(h('g', { key: item.key, 'data-series': item.key, 'data-type': item.type }, group));
			});

			if (props.showTooltip && activeIndex.value !== null) {
				svgChildren.push(
					h('line', {
						x1: tooltipX.value,
						x2: tooltipX.value,
						y1: l.padding.top,
						y2: l.height - l.padding.bottom,
						stroke: 'currentColor',
						'stroke-dasharray': '3 3',
						opacity: '0.4',
					}),
				);
			}

			children.push(
				h(
					'svg',
					{
						class: styles[chartStyleKeys.surface],
						width: l.width,
						height: l.height,
						viewBox: `0 0 ${l.width} ${l.height}`,
						role: 'img',
						'aria-label': svgLabel,
						'aria-labelledby': ariaLabelledBy,
						'aria-describedby': ariaDescribedBy,
						onMousemove: handleMouseMove,
						onMouseleave: handleMouseLeave,
					},
					svgChildren,
				),
			);

			if (props.showTooltip && activeIndex.value !== null) {
				children.push(
					h(ChartTooltipContent, {
						active: true,
						payload: entries.value,
						label: tooltipLabel.value,
						class: styles[chartStyleKeys.tooltip],
						style: {
							position: 'absolute',
							...Object.fromEntries(Object.entries(getChartTooltipPosition(layout.value, mousePosition.x, mousePosition.y)).map(([k, v]) => [k, `${v}px`])),
						},
					}),
				);
			}

			if (props.showLegend) {
				children.push(h(ChartLegendContent, { payload: legendItems.value }));
			}

			children.push(
				h(
					'div',
					{
						'data-slot': 'chart-status',
						role: 'status',
						'aria-live': 'polite',
						'aria-atomic': 'true',
						style: {
							position: 'absolute',
							width: '1px',
							height: '1px',
							padding: '0',
							margin: '-1px',
							overflow: 'hidden',
							clipPath: 'inset(50%)',
							whiteSpace: 'nowrap',
							border: '0',
						},
					},
					statusText,
				),
			);

			if (slots.default) {
				children.push(slots.default(context.value));
			}

			return h(
				'div',
				{
					...restAttrs,
					ref: containerRef,
					'data-slot': 'chart',
					'data-chart': chartId,
					'data-active-index': activeIndex.value ?? undefined,
					class: [styles[chartStyleKeys.root], userClass],
					title,
					'aria-label': ariaLabel,
					'aria-labelledby': ariaLabelledBy,
					'aria-describedby': ariaDescribedBy,
					tabindex: tabIndex,
					onKeydown: handleKeyDown,
				},
				children,
			);
		};
	},
});

export const ChartTooltipContent = defineComponent({
	name: 'ChartTooltipContent',
	props: {
		active: { type: Boolean, default: false },
		payload: { type: Array as PropType<ChartTooltipEntry[]>, default: () => [] },
		indicator: { type: String as PropType<'line' | 'dot' | 'dashed'>, default: 'dot' },
		hideLabel: { type: Boolean, default: false },
		hideIndicator: { type: Boolean, default: false },
		label: { type: [String, Number, Object] as PropType<string | number | null>, default: null },
		color: { type: String, default: undefined },
		formatter: { type: Function as PropType<(value: number, name: string, item: ChartTooltipEntry, index: number) => VNode | string | number | null>, default: undefined },
		labelFormatter: { type: Function as PropType<(value: unknown, payload: ChartTooltipEntry[]) => VNode | string | number | null>, default: undefined },
	},
	setup(props, { attrs }) {
		const context = useChart();

		return () => {
			const items = props.payload ?? [];
			const config = context.value.config;

			if (!props.active || items.length === 0) {
				return null;
			}

			const userClass = attrs.class;
			const restAttrs = { ...attrs };
			delete restAttrs.class;

			const formattedLabel = props.labelFormatter ? props.labelFormatter(props.label, items) : String(props.label ?? '');
			const labelNode = !props.hideLabel && props.label != null ? h('div', { class: styles[chartStyleKeys.tooltipLabel] }, [formattedLabel]) : null;

			const itemNodes = items.map((item, index) => {
				const itemConfig = config[item.dataKey];
				const indicatorColor = props.color ?? item.color;

				const indicatorNode = props.hideIndicator
					? null
					: h('span', {
							class: styles[chartStyleKeys.tooltipIndicator],
							'data-indicator': props.indicator,
							style: { backgroundColor: indicatorColor, borderColor: indicatorColor },
						});

				const valueNode =
					props.formatter && item.value !== undefined
						? [props.formatter(item.value as number, item.name, item, index)]
						: [h('div', { class: styles[chartStyleKeys.tooltipItemValue] }, typeof item.value === 'number' ? item.value.toLocaleString() : String(item.value))];

				return h('div', { key: index, class: styles[chartStyleKeys.tooltipItem], 'data-indicator': props.indicator }, [
					indicatorNode,
					h('div', { class: styles[chartStyleKeys.tooltipItemName] }, itemConfig?.label ?? item.name),
					valueNode,
				]);
			});

			return h('div', { ...restAttrs, class: [userClass] }, [labelNode, h('div', { class: styles[chartStyleKeys.tooltipGrid] }, itemNodes)]);
		};
	},
});

export const ChartLegendContent = defineComponent({
	name: 'ChartLegendContent',
	props: {
		payload: { type: Array as PropType<ChartLegendItem[]>, default: () => [] },
		hideIcon: { type: Boolean, default: false },
		verticalAlign: { type: String as PropType<'top' | 'bottom'>, default: 'bottom' },
	},
	setup(props, { attrs }) {
		return () => {
			const items = props.payload ?? [];
			if (items.length === 0) {
				return null;
			}

			const userClass = attrs.class;
			const restAttrs = { ...attrs };
			delete restAttrs.class;

			const itemNodes = items.map((item, index) =>
				h('div', { key: index, class: styles[chartStyleKeys.legendItem] }, [
					props.hideIcon ? null : h('span', { class: styles[chartStyleKeys.legendSwatch], style: { backgroundColor: item.color } }),
					item.name,
				]),
			);

			return h('div', { ...restAttrs, 'data-align': props.verticalAlign, class: [styles[chartStyleKeys.legend], userClass] }, itemNodes);
		};
	},
});

export const ChartTooltip = defineComponent({
	name: 'ChartTooltip',
	setup(_props, { slots, attrs }) {
		const context = useChart();

		return () => {
			const { layout, config, data, activeIndex } = context.value;
			const entries = getChartTooltipEntries(layout, config, data, activeIndex);
			const label = activeIndex !== null ? layout.xLabels[activeIndex] : null;

			if (slots.default) {
				return slots.default({ active: activeIndex !== null, payload: entries, label });
			}

			return h(ChartTooltipContent, { ...attrs, active: activeIndex !== null, payload: entries, label });
		};
	},
});

export const ChartLegend = defineComponent({
	name: 'ChartLegend',
	setup(_props, { attrs }) {
		const context = useChart();

		return () => h(ChartLegendContent, { ...attrs, payload: getChartLegendItems(context.value.layout) });
	},
});

export default ChartContainer;

// packages/react/src/components/chart/chart.tsx
import React, { createContext, useContext, useEffect, useId, useMemo, useRef, useState } from 'react';
import {
	CHART_INITIAL_DIMENSION,
	buildChartThemeCss,
	chartStyleKeys,
	computeChartLayout,
	findChartNearestIndex,
	getChartAreaPathD,
	getChartBaselineY,
	getChartBarRects,
	getChartLegendItems,
	getChartPathD,
	getChartTooltipEntries,
	getChartTooltipPosition,
} from '@tile-ui/core';
import type { ChartConfig, ChartDatum, ChartLayout, ChartLegendItem, ChartSeriesItem, ChartTooltipEntry, ChartType } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/chart.module.scss';

interface ChartContextValue {
	config: ChartConfig;
	layout: ChartLayout;
	data: ChartDatum[];
	activeIndex: number | null;
}

const ChartContext = createContext<ChartContextValue | null>(null);

/**
 * 读取 ChartContainer 提供的图表上下文
 */
function useChart(): ChartContextValue {
	const context = useContext(ChartContext);
	if (!context) {
		throw new Error('useChart 必须在 <ChartContainer /> 内使用');
	}
	return context;
}

/**
 * 生成主题相关的 CSS 变量 (--color-<key>)
 */
export interface ChartStyleProps {
	id: string;
	config: ChartConfig;
}

const ChartStyle = React.forwardRef<HTMLStyleElement, ChartStyleProps>(({ id, config }, ref) => {
	const css = useMemo(() => buildChartThemeCss(id, config), [id, config]);

	if (!css) {
		return null;
	}

	return <style ref={ref} dangerouslySetInnerHTML={{ __html: css }} />;
});
ChartStyle.displayName = 'ChartStyle';

export interface ChartContainerProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children'> {
	/** 图表可访问名称，同时保留在容器并转发至 SVG。 */
	'aria-label'?: string;
	/** 引用外部可访问名称，同时转发至 SVG。 */
	'aria-labelledby'?: string;
	/** 引用外部可访问描述，同时转发至 SVG。 */
	'aria-describedby'?: string;
	/** SVG 标题，同时保留为容器 title 属性。 */
	title?: string;
	config: ChartConfig;
	data?: ChartDatum[];
	xKey?: string;
	series?: ChartSeriesItem[];
	type?: ChartType;
	initialDimension?: { width: number; height: number };
	showLegend?: boolean;
	showTooltip?: boolean;
	showGrid?: boolean;
	showAxis?: boolean;
	children?: (state: ChartContextValue) => React.ReactNode;
}

const ChartContainer = React.forwardRef<HTMLDivElement, ChartContainerProps>(
	(
		{
			className = '',
			title,
			'aria-label': ariaLabel,
			'aria-labelledby': ariaLabelledBy,
			'aria-describedby': ariaDescribedBy,
			tabIndex,
			onKeyDown,
			config,
			data = [],
			xKey = 'x',
			series,
			type = 'line',
			initialDimension,
			showLegend = true,
			showTooltip = true,
			showGrid = true,
			showAxis = true,
			children,
			...props
		},
		ref,
	) => {
		const uniqueId = useId();
		const chartId = `chart-${uniqueId.replace(/:/g, '')}`;
		const containerRef = useRef<HTMLDivElement | null>(null);
		const [size, setSize] = useState(initialDimension ?? CHART_INITIAL_DIMENSION);
		const [activeIndex, setActiveIndex] = useState<number | null>(null);
		const [keyboardActive, setKeyboardActive] = useState(false);
		const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });

		useEffect(() => {
			const element = containerRef.current;
			if (!element) {
				return;
			}

			const observer = new ResizeObserver((entries) => {
				for (const entry of entries) {
					const { width } = entry.contentRect;
					if (width > 0) {
						// 高度固定：容器高度由 SVG 内容撑开，若跟随容器高度会形成正反馈循环导致无限放大
						setSize((prev) => ({ ...prev, width }));
					}
				}
			});
			observer.observe(element);

			return () => observer.disconnect();
		}, []);

		const layout = useMemo(
			() => computeChartLayout({ config, data, series: series ?? [], xKey, type, width: size.width, height: size.height, cssVariableScope: chartId }),
			[config, data, series, xKey, type, size, chartId],
		);

		const contextValue = useMemo<ChartContextValue>(() => ({ config, layout, data, activeIndex }), [config, layout, data, activeIndex]);

		function setRef(element: HTMLDivElement | null) {
			containerRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		function handleMouseMove(event: React.MouseEvent<SVGSVGElement>) {
			const svg = event.currentTarget;
			const rect = svg.getBoundingClientRect();
			const x = ((event.clientX - rect.left) / rect.width) * layout.width;
			const y = ((event.clientY - rect.top) / rect.height) * layout.height;
			setKeyboardActive(false);
			setMousePosition({ x, y });
			setActiveIndex(findChartNearestIndex(layout, x));
		}

		function handleMouseLeave() {
			setActiveIndex(null);
		}

		function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
			onKeyDown?.(event);
			if (event.defaultPrevented || tabIndex === undefined || tabIndex < 0 || event.target !== event.currentTarget) return;
			if (event.key === 'Escape') {
				setKeyboardActive(false);
				setActiveIndex(null);
				return;
			}
			if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') return;
			const count = layout.xLabels.length;
			if (count === 0) return;
			event.preventDefault();
			setKeyboardActive(true);
			setActiveIndex((current) => {
				if (current === null) return event.key === 'ArrowLeft' ? count - 1 : 0;
				return Math.min(count - 1, Math.max(0, current + (event.key === 'ArrowLeft' ? -1 : 1)));
			});
		}

		const entries = useMemo(() => getChartTooltipEntries(layout, config, data, activeIndex), [layout, config, data, activeIndex]);
		const legendItems = useMemo(() => getChartLegendItems(layout), [layout]);
		const tooltipX = activeIndex !== null ? (layout.xTickX[activeIndex] ?? 0) : 0;
		const tooltipLabel = activeIndex !== null ? layout.xLabels[activeIndex] : null;
		const svgLabel = ariaLabel ?? (ariaLabelledBy ? undefined : (title ?? 'Chart'));
		const statusText = keyboardActive && activeIndex !== null ? [tooltipLabel, ...entries.map((entry) => `${entry.name} ${entry.value.toLocaleString()}`)].join(', ') : '';

		return (
			<ChartContext.Provider value={contextValue}>
				<div
					ref={setRef}
					data-slot="chart"
					data-chart={chartId}
					data-active-index={activeIndex ?? undefined}
					className={`${styles[chartStyleKeys.root]} ${className}`}
					title={title}
					aria-label={ariaLabel}
					aria-labelledby={ariaLabelledBy}
					aria-describedby={ariaDescribedBy}
					tabIndex={tabIndex}
					onKeyDown={handleKeyDown}
					{...props}>
					<ChartStyle id={chartId} config={config} />
					<svg
						className={styles[chartStyleKeys.surface]}
						width={layout.width}
						height={layout.height}
						viewBox={`0 0 ${layout.width} ${layout.height}`}
						role="img"
						aria-label={svgLabel}
						aria-labelledby={ariaLabelledBy}
						aria-describedby={ariaDescribedBy}
						onMouseMove={handleMouseMove}
						onMouseLeave={handleMouseLeave}>
						{title && <title>{title}</title>}
						{showGrid &&
							layout.yTickY.map((y, index) => (
								<line
									key={`y-${index}`}
									className={styles[chartStyleKeys.gridLine]}
									x1={layout.padding.left}
									x2={layout.width - layout.padding.right}
									y1={y}
									y2={y}
								/>
							))}
						{showGrid &&
							layout.xTickX.map((x, index) => (
								<line
									key={`x-${index}`}
									className={styles[chartStyleKeys.gridLine]}
									x1={x}
									x2={x}
									y1={layout.padding.top}
									y2={layout.height - layout.padding.bottom}
								/>
							))}
						{showAxis &&
							layout.xLabels.map((label, index) => (
								<text
									key={`label-${index}`}
									x={layout.xTickX[index]}
									y={layout.height - layout.padding.bottom / 2}
									textAnchor="middle"
									dominantBaseline="middle"
									fontSize="10">
									{String(label)}
								</text>
							))}
						{layout.series.map((item, seriesIndex) => {
							if (item.type === 'bar') {
								const rects = getChartBarRects(layout, seriesIndex, layout.series.filter((s) => s.type === 'bar').length);
								return (
									<g key={item.key} data-series={item.key} data-type={item.type}>
										{rects.map((rect) => (
											<rect key={rect.index} data-index={rect.index} x={rect.x} y={rect.y} width={rect.width} height={rect.height} fill={item.color} rx={2} />
										))}
									</g>
								);
							}

							const path = item.type === 'area' ? getChartAreaPathD(item.points, getChartBaselineY(layout)) : getChartPathD(item.points);

							return (
								<g key={item.key} data-series={item.key} data-type={item.type}>
									{item.type === 'area' && <path data-area d={path} fill={item.color} fillOpacity={0.2} />}
									<path d={getChartPathD(item.points)} fill="none" stroke={item.color} strokeWidth={2} strokeLinejoin="round" strokeLinecap="round" />
									{item.points.map((point) => (
										<circle key={point.index} data-index={point.index} cx={point.x} cy={point.y} r={2.5} fill={item.color} />
									))}
								</g>
							);
						})}
						{showTooltip && activeIndex !== null && (
							<line
								x1={tooltipX}
								x2={tooltipX}
								y1={layout.padding.top}
								y2={layout.height - layout.padding.bottom}
								stroke="currentColor"
								strokeDasharray="3 3"
								opacity={0.4}
							/>
						)}
					</svg>
					{showTooltip && activeIndex !== null && (
						<ChartTooltipContent
							active
							payload={entries}
							label={tooltipLabel}
							className={styles[chartStyleKeys.tooltip]}
							style={{
								position: 'absolute',
								...getChartTooltipPosition(layout, mousePosition.x, mousePosition.y),
							}}
						/>
					)}
					{showLegend && <ChartLegendContent payload={legendItems} />}
					<div
						data-slot="chart-status"
						role="status"
						aria-live="polite"
						aria-atomic="true"
						style={{ position: 'absolute', width: 1, height: 1, padding: 0, margin: -1, overflow: 'hidden', clipPath: 'inset(50%)', whiteSpace: 'nowrap', border: 0 }}>
						{statusText}
					</div>
					{children?.(contextValue)}
				</div>
			</ChartContext.Provider>
		);
	},
);
ChartContainer.displayName = 'ChartContainer';

export interface ChartTooltipContentProps extends React.HTMLAttributes<HTMLDivElement> {
	active?: boolean;
	payload?: ChartTooltipEntry[];
	label?: React.ReactNode;
	indicator?: 'line' | 'dot' | 'dashed';
	hideLabel?: boolean;
	hideIndicator?: boolean;
	labelFormatter?: (value: React.ReactNode, payload: ChartTooltipEntry[]) => React.ReactNode;
	formatter?: (value: number, name: string, item: ChartTooltipEntry, index: number) => React.ReactNode;
	color?: string;
	nameKey?: string;
	labelKey?: string;
	labelClassName?: string;
}

const ChartTooltipContent = React.forwardRef<HTMLDivElement, ChartTooltipContentProps>(
	(
		{ active, payload, className = '', indicator = 'dot', hideLabel = false, hideIndicator = false, label, labelFormatter, labelClassName = '', formatter, color, ...props },
		ref,
	) => {
		const { config } = useChart();
		const items = payload ?? [];

		if (!active || items.length === 0) {
			return null;
		}

		const labelNode = !hideLabel && label != null && (
			<div className={`${styles[chartStyleKeys.tooltipLabel]} ${labelClassName}`}>{labelFormatter ? labelFormatter(label, items) : String(label)}</div>
		);

		return (
			<div ref={ref} className={className} {...props}>
				{labelNode}
				<div className={styles[chartStyleKeys.tooltipGrid]}>
					{items.map((item, index) => {
						const itemConfig = config[item.dataKey];
						const indicatorColor = color ?? item.color;

						return (
							<div key={index} className={styles[chartStyleKeys.tooltipItem]} data-indicator={indicator}>
								{!hideIndicator && (
									<span
										className={styles[chartStyleKeys.tooltipIndicator]}
										data-indicator={indicator}
										style={{ backgroundColor: indicatorColor, borderColor: indicatorColor }}
									/>
								)}
								<div className={styles[chartStyleKeys.tooltipItemName]}>{itemConfig?.label ?? item.name}</div>
								{formatter && item.value !== undefined ? (
									formatter(item.value, item.name, item, index)
								) : (
									<div className={styles[chartStyleKeys.tooltipItemValue]}>
										{typeof item.value === 'number' ? item.value.toLocaleString() : String(item.value)}
									</div>
								)}
							</div>
						);
					})}
				</div>
			</div>
		);
	},
);
ChartTooltipContent.displayName = 'ChartTooltipContent';

export interface ChartLegendContentProps extends React.HTMLAttributes<HTMLDivElement> {
	payload?: ChartLegendItem[];
	hideIcon?: boolean;
	verticalAlign?: 'top' | 'bottom';
}

const ChartLegendContent = React.forwardRef<HTMLDivElement, ChartLegendContentProps>(({ className = '', payload, hideIcon = false, verticalAlign = 'bottom', ...props }, ref) => {
	const items = payload ?? [];

	if (items.length === 0) {
		return null;
	}

	return (
		<div ref={ref} data-align={verticalAlign} className={`${styles[chartStyleKeys.legend]} ${className}`} {...props}>
			{items.map((item, index) => (
				<div key={index} className={styles[chartStyleKeys.legendItem]}>
					{!hideIcon && <span className={styles[chartStyleKeys.legendSwatch]} style={{ backgroundColor: item.color }} />}
					{item.name}
				</div>
			))}
		</div>
	);
});
ChartLegendContent.displayName = 'ChartLegendContent';

export interface ChartTooltipProps {
	className?: string;
	children?: (state: { active: boolean; payload: ChartTooltipEntry[]; label: React.ReactNode }) => React.ReactNode;
}

const ChartTooltip = ({ className = '', children }: ChartTooltipProps) => {
	const { layout, config, data, activeIndex } = useChart();
	const entries = getChartTooltipEntries(layout, config, data, activeIndex);
	const label = activeIndex !== null ? layout.xLabels[activeIndex] : null;

	if (children) {
		return <>{children({ active: activeIndex !== null, payload: entries, label })}</>;
	}

	return <ChartTooltipContent className={className} active={activeIndex !== null} payload={entries} label={label} />;
};
ChartTooltip.displayName = 'ChartTooltip';

export interface ChartLegendProps extends Omit<ChartLegendContentProps, 'payload'> {}

const ChartLegend = (props: ChartLegendProps) => {
	const { layout } = useChart();
	return <ChartLegendContent {...props} payload={getChartLegendItems(layout)} />;
};
ChartLegend.displayName = 'ChartLegend';

export { ChartContainer, ChartTooltip, ChartTooltipContent, ChartLegend, ChartLegendContent, ChartStyle };
export default ChartContainer;
