// packages/react/src/components/tooltip/tooltip.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import { getTooltipPosition, getTooltipState, tooltipStyleKeys, TOOLTIP_CLOSE_DELAY_MS } from '@tile-ui/core';
import type { TooltipBaseProps, TooltipContentBaseProps, TooltipPosition, TooltipProviderBaseProps, TooltipTriggerBaseProps } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/tooltip.module.scss';

interface TooltipContextValue {
	open: boolean;
	triggerRef: React.RefObject<HTMLElement | null>;
	contentId: string;
	setOpen: (open: boolean) => void;
}

const TooltipContext = createContext<TooltipContextValue | null>(null);

function useTooltipContext(): TooltipContextValue {
	const context = useContext(TooltipContext);
	if (!context) {
		throw new Error('Tooltip sub-components must be used within <Tooltip>.');
	}
	return context;
}

interface TooltipProviderContextValue {
	delayDuration: number;
}

const TooltipProviderContext = createContext<TooltipProviderContextValue>({ delayDuration: 0 });

export interface TooltipProviderProps extends TooltipProviderBaseProps {
	children?: React.ReactNode;
}

function TooltipProvider({ delayDuration = 0, children }: TooltipProviderProps) {
	return <TooltipProviderContext.Provider value={{ delayDuration }}>{children}</TooltipProviderContext.Provider>;
}

TooltipProvider.displayName = 'TooltipProvider';

export interface TooltipProps extends React.HTMLAttributes<HTMLDivElement>, TooltipBaseProps {}

const Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(({ className = '', open, defaultOpen = false, onOpenChange, children, ...props }, ref) => {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const isOpen = open !== undefined ? open : internalOpen;
	const triggerRef = useRef<HTMLElement | null>(null);
	const contentId = useId();

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}
			onOpenChange?.(next);
		},
		[open, onOpenChange],
	);

	return (
		<TooltipContext.Provider value={{ open: isOpen, triggerRef, contentId, setOpen }}>
			<div ref={ref} className={`${styles[tooltipStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</TooltipContext.Provider>
	);
});
Tooltip.displayName = 'Tooltip';

export interface TooltipTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, TooltipTriggerBaseProps {}

const TooltipTrigger = React.forwardRef<HTMLButtonElement, TooltipTriggerProps>(({ className = '', asChild = false, children, onKeyDown, ...props }, ref) => {
	const context = useTooltipContext();
	const provider = useContext(TooltipProviderContext);
	const openTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
	const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

	function clearOpenTimer() {
		if (openTimer.current) {
			clearTimeout(openTimer.current);
			openTimer.current = null;
		}
	}

	function clearCloseTimer() {
		if (closeTimer.current) {
			clearTimeout(closeTimer.current);
			closeTimer.current = null;
		}
	}

	function scheduleOpen() {
		clearOpenTimer();
		openTimer.current = setTimeout(() => context.setOpen(true), provider.delayDuration);
	}

	function scheduleClose() {
		clearCloseTimer();
		closeTimer.current = setTimeout(() => context.setOpen(false), TOOLTIP_CLOSE_DELAY_MS);
	}

	function handleMouseEnter() {
		clearCloseTimer();
		scheduleOpen();
	}

	function handleMouseLeave() {
		clearOpenTimer();
		scheduleClose();
	}

	function handleFocus() {
		clearCloseTimer();
		scheduleOpen();
	}

	function handleBlur() {
		clearOpenTimer();
		clearCloseTimer();
		context.setOpen(false);
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) {
		if (event.key === 'Escape') {
			clearOpenTimer();
			clearCloseTimer();
			context.setOpen(false);
		}
		onKeyDown?.(event);
	}

	useEffect(() => {
		return () => {
			clearOpenTimer();
			clearCloseTimer();
		};
	}, []);

	function setRef(element: HTMLElement | null) {
		context.triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element as HTMLButtonElement | null);
		} else if (ref) {
			ref.current = element as HTMLButtonElement | null;
		}
	}

	const Comp = asChild ? Slot : 'button';
	const state = getTooltipState(context.open);

	return (
		<Comp
			ref={setRef}
			aria-describedby={context.open ? context.contentId : undefined}
			data-state={state}
			className={asChild ? undefined : `${styles[tooltipStyleKeys.trigger]} ${className}`}
			onMouseEnter={handleMouseEnter}
			onMouseLeave={handleMouseLeave}
			onFocus={handleFocus}
			onBlur={handleBlur}
			onKeyDown={handleKeyDown}
			{...props}>
			{children}
		</Comp>
	);
});
TooltipTrigger.displayName = 'TooltipTrigger';

export interface TooltipContentProps extends React.HTMLAttributes<HTMLDivElement>, TooltipContentBaseProps {
	container?: PortalContainer;
}

const TooltipContent = React.forwardRef<HTMLDivElement, TooltipContentProps>(({ className = '', side = 'top', sideOffset = 0, container, children, ...props }, ref) => {
	const { open, triggerRef, contentId, setOpen } = useTooltipContext();
	const portalContainer = usePortalContainer(container);
	const [position, setPosition] = useState<TooltipPosition | null>(null);
	const contentRef = useRef<HTMLDivElement | null>(null);
	const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

	function clearCloseTimer() {
		if (closeTimer.current) {
			clearTimeout(closeTimer.current);
			closeTimer.current = null;
		}
	}

	function handlePointerEnter() {
		clearCloseTimer();
		setOpen(true);
	}

	function handlePointerLeave() {
		clearCloseTimer();
		closeTimer.current = setTimeout(() => setOpen(false), TOOLTIP_CLOSE_DELAY_MS);
	}

	useEffect(() => {
		return () => {
			clearCloseTimer();
		};
	}, []);

	useLayoutEffect(() => {
		if (!open) {
			return;
		}

		function updatePosition() {
			const trigger = triggerRef.current;
			const content = contentRef.current;
			if (!trigger || !content) {
				return;
			}

			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			setPosition(getTooltipPosition({ triggerRect, contentSize, side, sideOffset, viewport }));
		}

		updatePosition();
		window.addEventListener('resize', updatePosition);
		document.addEventListener('scroll', updatePosition, true);

		return () => {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
		};
	}, [open, side, sideOffset, triggerRef]);

	function setRef(element: HTMLDivElement | null) {
		contentRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	const state = getTooltipState(open);
	const classes = [styles[tooltipStyleKeys.content], className].filter(Boolean).join(' ');

	const content = (
		<div
			ref={setRef}
			id={contentId}
			role="tooltip"
			data-state={state}
			data-side={side}
			className={classes}
			style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
			onPointerEnter={handlePointerEnter}
			onPointerLeave={handlePointerLeave}
			{...props}>
			{children}
			<span className={styles[tooltipStyleKeys.arrow]} aria-hidden="true" />
		</div>
	);

	if (!open || !portalContainer) {
		return null;
	}

	return createPortal(content, portalContainer);
});
TooltipContent.displayName = 'TooltipContent';

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider };
export default Tooltip;

// packages/vue/src/components/tooltip/tooltip.tsx
import {
	cloneVNode,
	computed,
	defineComponent,
	h,
	inject,
	mergeProps,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	useId,
	watch,
	type InjectionKey,
	type PropType,
	type Ref,
	Teleport,
} from 'vue';
import { getTooltipPosition, getTooltipState, tooltipStyleKeys, TOOLTIP_CLOSE_DELAY_MS } from '@tile-ui/core';
import type { TooltipSide } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/tooltip.module.scss';

interface TooltipContextValue {
	open: Ref<boolean>;
	triggerRef: Ref<HTMLElement | null>;
	contentId: string;
	setOpen: (open: boolean) => void;
}

const TooltipContextKey: InjectionKey<TooltipContextValue> = Symbol('tile-tooltip');

const TooltipProviderContextKey: InjectionKey<Ref<number>> = Symbol('tile-tooltip-provider');

export const TooltipProvider = defineComponent({
	name: 'TooltipProvider',
	props: {
		delayDuration: { type: Number, default: 0 },
	},
	setup(props, { slots }) {
		const delayDuration = ref(props.delayDuration);
		provide(TooltipProviderContextKey, delayDuration);

		return () => slots.default?.();
	},
});

export const Tooltip = defineComponent({
	name: 'Tooltip',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const triggerRef = ref<HTMLElement | null>(null);
		const contentId = `tile-tooltip-${useId()}`;

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		provide(TooltipContextKey, { open: isOpen, triggerRef, contentId, setOpen });

		return () => h('div', { class: styles[tooltipStyleKeys.root] }, slots.default?.());
	},
});

export const TooltipTrigger = defineComponent({
	name: 'TooltipTrigger',
	inheritAttrs: false,
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(TooltipContextKey);
		const provider = inject(TooltipProviderContextKey);
		if (!contextValue) {
			throw new Error('TooltipTrigger must be used within <Tooltip>.');
		}
		const context: TooltipContextValue = contextValue;
		const delayDuration = provider?.value ?? 0;

		let openTimer: ReturnType<typeof setTimeout> | null = null;
		let closeTimer: ReturnType<typeof setTimeout> | null = null;

		function clearOpenTimer() {
			if (openTimer) {
				clearTimeout(openTimer);
				openTimer = null;
			}
		}

		function clearCloseTimer() {
			if (closeTimer) {
				clearTimeout(closeTimer);
				closeTimer = null;
			}
		}

		function scheduleOpen() {
			clearOpenTimer();
			openTimer = setTimeout(() => context.setOpen(true), delayDuration);
		}

		function scheduleClose() {
			clearCloseTimer();
			closeTimer = setTimeout(() => context.setOpen(false), TOOLTIP_CLOSE_DELAY_MS);
		}

		function handleMouseenter() {
			clearCloseTimer();
			scheduleOpen();
		}

		function handleMouseleave() {
			clearOpenTimer();
			scheduleClose();
		}

		function handleFocus() {
			clearCloseTimer();
			scheduleOpen();
		}

		function handleBlur() {
			clearOpenTimer();
			clearCloseTimer();
			context.setOpen(false);
		}

		function handleKeydown(event: KeyboardEvent) {
			if (event.key === 'Escape') {
				clearOpenTimer();
				clearCloseTimer();
				context.setOpen(false);
			}
		}

		onBeforeUnmount(() => {
			clearOpenTimer();
			clearCloseTimer();
		});

		function setRef(el: unknown) {
			context.triggerRef.value = (el as HTMLElement | null) ?? null;
		}

		const triggerProps = computed(() => ({
			ref: setRef,
			'data-state': getTooltipState(context.open.value),
			'aria-describedby': context.open.value ? context.contentId : undefined,
			onMouseenter: handleMouseenter,
			onMouseleave: handleMouseleave,
			onFocus: handleFocus,
			onBlur: handleBlur,
			onKeydown: handleKeydown,
		}));

		return () => {
			const child = slots.default?.()[0];

			if (props.asChild && child) {
				return cloneVNode(child, mergeProps(child.props ?? {}, triggerProps.value));
			}

			return h(
				'button',
				{
					...attrs,
					...triggerProps.value,
					type: 'button',
					class: [styles[tooltipStyleKeys.trigger], attrs.class],
				},
				slots.default?.(),
			);
		};
	},
});

export const TooltipContent = defineComponent({
	name: 'TooltipContent',
	inheritAttrs: false,
	props: {
		side: { type: String as PropType<TooltipSide>, default: 'top' },
		sideOffset: { type: Number, default: 0 },
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots, attrs }) {
		const portalContainer = usePortalContainer(() => props.container);
		const contextValue = inject(TooltipContextKey);
		if (!contextValue) {
			throw new Error('TooltipContent must be used within <Tooltip>.');
		}
		const context: TooltipContextValue = contextValue;

		const contentRef = ref<HTMLElement | null>(null);
		const position = ref<{ top: number; left: number } | null>(null);

		let closeTimer: ReturnType<typeof setTimeout> | null = null;

		function clearCloseTimer() {
			if (closeTimer) {
				clearTimeout(closeTimer);
				closeTimer = null;
			}
		}

		function handlePointerenter() {
			clearCloseTimer();
			context.setOpen(true);
		}

		function handlePointerleave() {
			clearCloseTimer();
			closeTimer = setTimeout(() => context.setOpen(false), TOOLTIP_CLOSE_DELAY_MS);
		}

		function updatePosition() {
			const trigger = context.triggerRef.value;
			const content = contentRef.value;
			if (!trigger || !content) {
				return;
			}

			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			position.value = getTooltipPosition({ triggerRect, contentSize, side: props.side, sideOffset: props.sideOffset, viewport });
		}

		function addListeners() {
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);
		}

		function removeListeners() {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
		}

		onMounted(() => {
			if (context.open.value) {
				addListeners();
				updatePosition();
			}
		});

		watch(
			() => context.open.value,
			(open) => {
				if (open) {
					addListeners();
					updatePosition();
				} else {
					removeListeners();
				}
			},
		);

		watch(
			() => [props.side, props.sideOffset],
			() => {
				if (context.open.value) {
					updatePosition();
				}
			},
		);

		onBeforeUnmount(() => {
			clearCloseTimer();
			removeListeners();
		});

		return () => {
			const open = context.open.value;
			const userClass = attrs.class;
			const userStyle = attrs.style;
			const restAttrs = { ...attrs };
			delete restAttrs.class;
			delete restAttrs.style;

			const children = [...(slots.default?.() ?? []), h('span', { class: styles[tooltipStyleKeys.arrow], 'aria-hidden': 'true' })];

			return h(Teleport, { to: portalContainer.value }, [
				h(
					'div',
					{
						...restAttrs,
						ref: contentRef,
						id: context.contentId,
						role: 'tooltip',
						'data-state': getTooltipState(open),
						'data-side': props.side,
						class: [styles[tooltipStyleKeys.content], userClass],
						style: position.value ? [userStyle, { top: `${position.value.top}px`, left: `${position.value.left}px` }] : userStyle,
						onPointerenter: handlePointerenter,
						onPointerleave: handlePointerleave,
					},
					children,
				),
			]);
		};
	},
});

export default Tooltip;
