// packages/vue/src/components/skeleton/skeleton.tsx
import { defineComponent, h } from 'vue';
import { skeletonStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/skeleton.module.scss';

export const Skeleton = defineComponent({
	name: 'Skeleton',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, class: [styles[skeletonStyleKeys.base], attrs.class] }, slots.default?.());
	},
});

export default Skeleton;

// packages/react/src/components/skeleton/skeleton.tsx
import React from 'react';
import { skeletonStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/skeleton.module.scss';

export interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {}

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(({ className = '', ...props }, ref) => {
	return <div ref={ref} className={`${styles[skeletonStyleKeys.base]} ${className}`} {...props} />;
});

Skeleton.displayName = 'Skeleton';

export { Skeleton };
export default Skeleton;
