// packages/solid/src/components/card/card.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import { cardStyleKeys } from '@tile-ui/core';
import type { CardBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/card.module.scss';

export interface CardProps extends JSX.HTMLAttributes<HTMLDivElement>, CardBaseProps {}

/**
 * SolidJS Card：复用 core 的样式 key，样式来自共享 SCSS。
 */
export function Card(props: ParentProps<CardProps>) {
	const [local, rest] = splitProps(props, ['as', 'class', 'children']);

	return (
		<Dynamic component={local.as ?? 'div'} {...rest} class={`${styles[cardStyleKeys.card]} ${local.class ?? ''}`}>
			{local.children}
		</Dynamic>
	);
}

export interface CardHeaderProps extends JSX.HTMLAttributes<HTMLDivElement> {}

export function CardHeader(props: ParentProps<CardHeaderProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} class={`${styles[cardStyleKeys.header]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export interface CardTitleProps extends JSX.HTMLAttributes<HTMLHeadingElement> {}

export function CardTitle(props: ParentProps<CardTitleProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<h3 {...rest} class={`${styles[cardStyleKeys.title]} ${local.class ?? ''}`}>
			{local.children}
		</h3>
	);
}

export interface CardDescriptionProps extends JSX.HTMLAttributes<HTMLParagraphElement> {}

export function CardDescription(props: ParentProps<CardDescriptionProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<p {...rest} class={`${styles[cardStyleKeys.description]} ${local.class ?? ''}`}>
			{local.children}
		</p>
	);
}

export interface CardActionProps extends JSX.HTMLAttributes<HTMLDivElement> {}

export function CardAction(props: ParentProps<CardActionProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} class={`${styles[cardStyleKeys.action]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export interface CardContentProps extends JSX.HTMLAttributes<HTMLDivElement> {}

export function CardContent(props: ParentProps<CardContentProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} class={`${styles[cardStyleKeys.content]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export interface CardFooterProps extends JSX.HTMLAttributes<HTMLDivElement> {}

export function CardFooter(props: ParentProps<CardFooterProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} class={`${styles[cardStyleKeys.footer]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export default Card;

// packages/react/src/components/card/card.tsx
import React from 'react';
import { cardStyleKeys } from '@tile-ui/core';
import type {
	CardBaseProps,
	CardHeaderBaseProps,
	CardTitleBaseProps,
	CardDescriptionBaseProps,
	CardActionBaseProps,
	CardContentBaseProps,
	CardFooterBaseProps,
} from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/card.module.scss';

export interface CardProps extends React.HTMLAttributes<HTMLDivElement>, CardBaseProps {}

const Card = React.forwardRef<HTMLDivElement, CardProps>(({ className = '', as: Component = 'div', children, ...props }, ref) => {
	return (
		<Component ref={ref} className={`${styles[cardStyleKeys.card]} ${className}`} {...props}>
			{children}
		</Component>
	);
});
Card.displayName = 'Card';

interface CardHeaderProps extends React.HTMLAttributes<HTMLDivElement>, CardHeaderBaseProps {}

const CardHeader = React.forwardRef<HTMLDivElement, CardHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[cardStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
CardHeader.displayName = 'CardHeader';

interface CardTitleProps extends React.HTMLAttributes<HTMLHeadingElement>, CardTitleBaseProps {}

const CardTitle = React.forwardRef<HTMLHeadingElement, CardTitleProps>(({ className = '', children, ...props }, ref) => {
	return (
		<h3 ref={ref} className={`${styles[cardStyleKeys.title]} ${className}`} {...props}>
			{children}
		</h3>
	);
});
CardTitle.displayName = 'CardTitle';

interface CardDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement>, CardDescriptionBaseProps {}

const CardDescription = React.forwardRef<HTMLParagraphElement, CardDescriptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<p ref={ref} className={`${styles[cardStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
CardDescription.displayName = 'CardDescription';

interface CardActionProps extends React.HTMLAttributes<HTMLDivElement>, CardActionBaseProps {}

const CardAction = React.forwardRef<HTMLDivElement, CardActionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[cardStyleKeys.action]} ${className}`} {...props}>
			{children}
		</div>
	);
});
CardAction.displayName = 'CardAction';

interface CardContentProps extends React.HTMLAttributes<HTMLDivElement>, CardContentBaseProps {}

const CardContent = React.forwardRef<HTMLDivElement, CardContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[cardStyleKeys.content]} ${className}`} {...props}>
			{children}
		</div>
	);
});
CardContent.displayName = 'CardContent';

interface CardFooterProps extends React.HTMLAttributes<HTMLDivElement>, CardFooterBaseProps {}

const CardFooter = React.forwardRef<HTMLDivElement, CardFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[cardStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</div>
	);
});
CardFooter.displayName = 'CardFooter';

export { Card, CardHeader, CardTitle, CardDescription, CardAction, CardContent, CardFooter };
export type { CardHeaderProps, CardTitleProps, CardDescriptionProps, CardActionProps, CardContentProps, CardFooterProps };
export default Card;
