// packages/vue/src/components/table/table.tsx
import { defineComponent, h } from 'vue';
import { tableStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/table.module.scss';

export const Table = defineComponent({
	name: 'Table',
	inheritAttrs: false,
	setup(_props, { slots, attrs }) {
		return () => {
			const tableAttrs = { ...attrs };
			const userClass = tableAttrs.class;
			delete tableAttrs.class;

			return h('div', { class: styles[tableStyleKeys.container] }, h('table', { ...tableAttrs, class: [styles[tableStyleKeys.table], userClass] }, slots.default?.()));
		};
	},
});

export const TableHeader = defineComponent({
	name: 'TableHeader',
	setup(_props, { slots, attrs }) {
		return () => h('thead', { ...attrs, class: [styles[tableStyleKeys.header], attrs.class] }, slots.default?.());
	},
});

export const TableBody = defineComponent({
	name: 'TableBody',
	setup(_props, { slots, attrs }) {
		return () => h('tbody', { ...attrs, class: [styles[tableStyleKeys.body], attrs.class] }, slots.default?.());
	},
});

export const TableFooter = defineComponent({
	name: 'TableFooter',
	setup(_props, { slots, attrs }) {
		return () => h('tfoot', { ...attrs, class: [styles[tableStyleKeys.footer], attrs.class] }, slots.default?.());
	},
});

export const TableRow = defineComponent({
	name: 'TableRow',
	setup(_props, { slots, attrs }) {
		return () => h('tr', { ...attrs, class: [styles[tableStyleKeys.row], attrs.class] }, slots.default?.());
	},
});

export const TableHead = defineComponent({
	name: 'TableHead',
	setup(_props, { slots, attrs }) {
		return () => h('th', { ...attrs, class: [styles[tableStyleKeys.head], attrs.class] }, slots.default?.());
	},
});

export const TableCell = defineComponent({
	name: 'TableCell',
	setup(_props, { slots, attrs }) {
		return () => h('td', { ...attrs, class: [styles[tableStyleKeys.cell], attrs.class] }, slots.default?.());
	},
});

export const TableCaption = defineComponent({
	name: 'TableCaption',
	setup(_props, { slots, attrs }) {
		return () => h('caption', { ...attrs, class: [styles[tableStyleKeys.caption], attrs.class] }, slots.default?.());
	},
});

export default Table;

// packages/react/src/components/table/table.tsx
import React from 'react';
import { tableStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/table.module.scss';

export interface TableProps extends React.HTMLAttributes<HTMLTableElement> {}

const Table = React.forwardRef<HTMLTableElement, TableProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div className={styles[tableStyleKeys.container]}>
			<table ref={ref} className={`${styles[tableStyleKeys.table]} ${className}`} {...props}>
				{children}
			</table>
		</div>
	);
});
Table.displayName = 'Table';

export interface TableHeaderProps extends React.HTMLAttributes<HTMLTableSectionElement> {}

const TableHeader = React.forwardRef<HTMLTableSectionElement, TableHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<thead ref={ref} className={`${styles[tableStyleKeys.header]} ${className}`} {...props}>
			{children}
		</thead>
	);
});
TableHeader.displayName = 'TableHeader';

export interface TableBodyProps extends React.HTMLAttributes<HTMLTableSectionElement> {}

const TableBody = React.forwardRef<HTMLTableSectionElement, TableBodyProps>(({ className = '', children, ...props }, ref) => {
	return (
		<tbody ref={ref} className={`${styles[tableStyleKeys.body]} ${className}`} {...props}>
			{children}
		</tbody>
	);
});
TableBody.displayName = 'TableBody';

export interface TableFooterProps extends React.HTMLAttributes<HTMLTableSectionElement> {}

const TableFooter = React.forwardRef<HTMLTableSectionElement, TableFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<tfoot ref={ref} className={`${styles[tableStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</tfoot>
	);
});
TableFooter.displayName = 'TableFooter';

export interface TableRowProps extends React.HTMLAttributes<HTMLTableRowElement> {}

const TableRow = React.forwardRef<HTMLTableRowElement, TableRowProps>(({ className = '', children, ...props }, ref) => {
	return (
		<tr ref={ref} className={`${styles[tableStyleKeys.row]} ${className}`} {...props}>
			{children}
		</tr>
	);
});
TableRow.displayName = 'TableRow';

export interface TableHeadProps extends React.ThHTMLAttributes<HTMLTableCellElement> {}

const TableHead = React.forwardRef<HTMLTableCellElement, TableHeadProps>(({ className = '', children, ...props }, ref) => {
	return (
		<th ref={ref} className={`${styles[tableStyleKeys.head]} ${className}`} {...props}>
			{children}
		</th>
	);
});
TableHead.displayName = 'TableHead';

export interface TableCellProps extends React.TdHTMLAttributes<HTMLTableCellElement> {}

const TableCell = React.forwardRef<HTMLTableCellElement, TableCellProps>(({ className = '', children, ...props }, ref) => {
	return (
		<td ref={ref} className={`${styles[tableStyleKeys.cell]} ${className}`} {...props}>
			{children}
		</td>
	);
});
TableCell.displayName = 'TableCell';

export interface TableCaptionProps extends React.HTMLAttributes<HTMLTableCaptionElement> {}

const TableCaption = React.forwardRef<HTMLTableCaptionElement, TableCaptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<caption ref={ref} className={`${styles[tableStyleKeys.caption]} ${className}`} {...props}>
			{children}
		</caption>
	);
});
TableCaption.displayName = 'TableCaption';

export { Table, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableCaption };
export default Table;
