// packages/react/src/components/portal/portal.tsx
import React, { createContext, useContext, useEffect, useState } from 'react';

export type PortalContainer = Element | null;

const PortalContainerContext = createContext<PortalContainer>(null);

export interface PortalProviderProps {
	container?: PortalContainer;
	children?: React.ReactNode;
}

function PortalProvider({ container = null, children }: PortalProviderProps) {
	const parentContainer = useContext(PortalContainerContext);

	return <PortalContainerContext.Provider value={container ?? parentContainer}>{children}</PortalContainerContext.Provider>;
}

PortalProvider.displayName = 'PortalProvider';

function usePortalContainer(container?: PortalContainer): PortalContainer {
	const contextContainer = useContext(PortalContainerContext);
	const [defaultContainer, setDefaultContainer] = useState<PortalContainer>(null);

	useEffect(() => {
		setDefaultContainer(document.body);
	}, []);

	return container ?? contextContainer ?? defaultContainer;
}

export { PortalProvider, usePortalContainer };

// packages/vue/src/components/portal/portal.tsx
import { computed, defineComponent, inject, provide, type ComputedRef, type InjectionKey, type PropType } from 'vue';

export type PortalContainer = Element | null;

const PortalContainerKey: InjectionKey<ComputedRef<PortalContainer>> = Symbol('tile-portal-container');

export const PortalProvider = defineComponent({
	name: 'PortalProvider',
	props: {
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots }) {
		const parentContainer = inject(
			PortalContainerKey,
			computed(() => null),
		);

		provide(
			PortalContainerKey,
			computed(() => props.container ?? parentContainer.value),
		);

		return () => slots.default?.();
	},
});

export function usePortalContainer(container?: () => PortalContainer | undefined): ComputedRef<Element | string> {
	const contextContainer = inject(
		PortalContainerKey,
		computed(() => null),
	);

	return computed(() => container?.() ?? contextContainer.value ?? 'body');
}
