// packages/react/src/components/table/table.tsx
import React from 'react';
import { tableStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/table.module.scss';

export interface TableProps extends React.HTMLAttributes<HTMLTableElement> {}

const Table = React.forwardRef<HTMLTableElement, TableProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div className={styles[tableStyleKeys.container]}>
			<table ref={ref} className={`${styles[tableStyleKeys.table]} ${className}`} {...props}>
				{children}
			</table>
		</div>
	);
});
Table.displayName = 'Table';

export interface TableHeaderProps extends React.HTMLAttributes<HTMLTableSectionElement> {}

const TableHeader = React.forwardRef<HTMLTableSectionElement, TableHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<thead ref={ref} className={`${styles[tableStyleKeys.header]} ${className}`} {...props}>
			{children}
		</thead>
	);
});
TableHeader.displayName = 'TableHeader';

export interface TableBodyProps extends React.HTMLAttributes<HTMLTableSectionElement> {}

const TableBody = React.forwardRef<HTMLTableSectionElement, TableBodyProps>(({ className = '', children, ...props }, ref) => {
	return (
		<tbody ref={ref} className={`${styles[tableStyleKeys.body]} ${className}`} {...props}>
			{children}
		</tbody>
	);
});
TableBody.displayName = 'TableBody';

export interface TableFooterProps extends React.HTMLAttributes<HTMLTableSectionElement> {}

const TableFooter = React.forwardRef<HTMLTableSectionElement, TableFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<tfoot ref={ref} className={`${styles[tableStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</tfoot>
	);
});
TableFooter.displayName = 'TableFooter';

export interface TableRowProps extends React.HTMLAttributes<HTMLTableRowElement> {}

const TableRow = React.forwardRef<HTMLTableRowElement, TableRowProps>(({ className = '', children, ...props }, ref) => {
	return (
		<tr ref={ref} className={`${styles[tableStyleKeys.row]} ${className}`} {...props}>
			{children}
		</tr>
	);
});
TableRow.displayName = 'TableRow';

export interface TableHeadProps extends React.ThHTMLAttributes<HTMLTableCellElement> {}

const TableHead = React.forwardRef<HTMLTableCellElement, TableHeadProps>(({ className = '', children, ...props }, ref) => {
	return (
		<th ref={ref} className={`${styles[tableStyleKeys.head]} ${className}`} {...props}>
			{children}
		</th>
	);
});
TableHead.displayName = 'TableHead';

export interface TableCellProps extends React.TdHTMLAttributes<HTMLTableCellElement> {}

const TableCell = React.forwardRef<HTMLTableCellElement, TableCellProps>(({ className = '', children, ...props }, ref) => {
	return (
		<td ref={ref} className={`${styles[tableStyleKeys.cell]} ${className}`} {...props}>
			{children}
		</td>
	);
});
TableCell.displayName = 'TableCell';

export interface TableCaptionProps extends React.HTMLAttributes<HTMLTableCaptionElement> {}

const TableCaption = React.forwardRef<HTMLTableCaptionElement, TableCaptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<caption ref={ref} className={`${styles[tableStyleKeys.caption]} ${className}`} {...props}>
			{children}
		</caption>
	);
});
TableCaption.displayName = 'TableCaption';

export { Table, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableCaption };
export default Table;

// packages/solid/src/components/table/table.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { tableStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/table.module.scss';
export interface TableProps extends JSX.HTMLAttributes<HTMLTableElement> {
	containerClass?: string;
	containerProps?: JSX.HTMLAttributes<HTMLDivElement>;
}
export function Table(props: ParentProps<TableProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'containerClass', 'containerProps']);
	const [containerLocal, containerRest] = splitProps(local.containerProps ?? {}, ['class']);
	return (
		<div {...containerRest} class={`${styles[tableStyleKeys.container]} ${containerLocal.class ?? ''} ${local.containerClass ?? ''}`}>
			<table {...rest} class={`${styles[tableStyleKeys.table]} ${local.class ?? ''}`}>
				{local.children}
			</table>
		</div>
	);
}
export interface TableHeaderProps extends JSX.HTMLAttributes<HTMLTableSectionElement> {}
export function TableHeader(props: ParentProps<TableHeaderProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<thead {...rest} class={`${styles[tableStyleKeys.header]} ${local.class ?? ''}`}>
			{local.children}
		</thead>
	);
}
export interface TableBodyProps extends JSX.HTMLAttributes<HTMLTableSectionElement> {}
export function TableBody(props: ParentProps<TableBodyProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<tbody {...rest} class={`${styles[tableStyleKeys.body]} ${local.class ?? ''}`}>
			{local.children}
		</tbody>
	);
}
export interface TableFooterProps extends JSX.HTMLAttributes<HTMLTableSectionElement> {}
export function TableFooter(props: ParentProps<TableFooterProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<tfoot {...rest} class={`${styles[tableStyleKeys.footer]} ${local.class ?? ''}`}>
			{local.children}
		</tfoot>
	);
}
export interface TableRowProps extends JSX.HTMLAttributes<HTMLTableRowElement> {}
export function TableRow(props: ParentProps<TableRowProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<tr {...rest} class={`${styles[tableStyleKeys.row]} ${local.class ?? ''}`}>
			{local.children}
		</tr>
	);
}
export interface TableHeadProps extends JSX.ThHTMLAttributes<HTMLTableCellElement> {}
export function TableHead(props: ParentProps<TableHeadProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<th {...rest} class={`${styles[tableStyleKeys.head]} ${local.class ?? ''}`}>
			{local.children}
		</th>
	);
}
export interface TableCellProps extends JSX.TdHTMLAttributes<HTMLTableCellElement> {}
export function TableCell(props: ParentProps<TableCellProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<td {...rest} class={`${styles[tableStyleKeys.cell]} ${local.class ?? ''}`}>
			{local.children}
		</td>
	);
}
export interface TableCaptionProps extends JSX.HTMLAttributes<HTMLTableCaptionElement> {}
export function TableCaption(props: ParentProps<TableCaptionProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<caption {...rest} class={`${styles[tableStyleKeys.caption]} ${local.class ?? ''}`}>
			{local.children}
		</caption>
	);
}
export default Table;
