// packages/solid/src/components/breadcrumb/breadcrumb.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { breadcrumbStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/breadcrumb.module.scss';

export interface BreadcrumbProps extends JSX.HTMLAttributes<HTMLElement> {}
export function Breadcrumb(props: ParentProps<BreadcrumbProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<nav {...rest} aria-label={rest['aria-label'] ?? 'breadcrumb'} class={`${styles[breadcrumbStyleKeys.root]} ${local.class ?? ''}`}>
			{local.children}
		</nav>
	);
}
export interface BreadcrumbListProps extends JSX.OlHTMLAttributes<HTMLOListElement> {}
export function BreadcrumbList(props: ParentProps<BreadcrumbListProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<ol {...rest} class={`${styles[breadcrumbStyleKeys.list]} ${local.class ?? ''}`}>
			{local.children}
		</ol>
	);
}
export interface BreadcrumbItemProps extends JSX.LiHTMLAttributes<HTMLLIElement> {}
export function BreadcrumbItem(props: ParentProps<BreadcrumbItemProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<li {...rest} class={`${styles[breadcrumbStyleKeys.item]} ${local.class ?? ''}`}>
			{local.children}
		</li>
	);
}
export interface BreadcrumbLinkProps extends JSX.AnchorHTMLAttributes<HTMLAnchorElement> {}
export function BreadcrumbLink(props: ParentProps<BreadcrumbLinkProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<a {...rest} class={`${styles[breadcrumbStyleKeys.link]} ${local.class ?? ''}`}>
			{local.children}
		</a>
	);
}
export interface BreadcrumbPageProps extends JSX.HTMLAttributes<HTMLSpanElement> {}
export function BreadcrumbPage(props: ParentProps<BreadcrumbPageProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<span {...rest} role="link" aria-disabled="true" aria-current="page" class={`${styles[breadcrumbStyleKeys.page]} ${local.class ?? ''}`}>
			{local.children}
		</span>
	);
}
export interface BreadcrumbSeparatorProps extends JSX.LiHTMLAttributes<HTMLLIElement> {}
export function BreadcrumbSeparator(props: ParentProps<BreadcrumbSeparatorProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<li {...rest} role="presentation" aria-hidden="true" class={`${styles[breadcrumbStyleKeys.separator]} ${local.class ?? ''}`}>
			{local.children ?? (
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
					<path d="m9 18 6-6-6-6" />
				</svg>
			)}
		</li>
	);
}
export interface BreadcrumbEllipsisProps extends JSX.HTMLAttributes<HTMLSpanElement> {}
export function BreadcrumbEllipsis(props: BreadcrumbEllipsisProps) {
	const [local, rest] = splitProps(props, ['class']);
	return (
		<span {...rest} role="presentation" aria-hidden="true" class={`${styles[breadcrumbStyleKeys.ellipsis]} ${local.class ?? ''}`}>
			<svg class={styles[breadcrumbStyleKeys.ellipsisIcon]} viewBox="0 0 24 24" fill="currentColor">
				<circle cx="5" cy="12" r="1" />
				<circle cx="12" cy="12" r="1" />
				<circle cx="19" cy="12" r="1" />
			</svg>
			<span class={styles[breadcrumbStyleKeys.srOnly]}>More</span>
		</span>
	);
}
export default Breadcrumb;

// packages/react/src/components/breadcrumb/breadcrumb.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { breadcrumbStyleKeys } from '@tile-ui/core';
import type { BreadcrumbLinkBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/breadcrumb.module.scss';

function ChevronRightIcon(props: React.SVGProps<SVGSVGElement>) {
	return (
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
			<path d="m9 18 6-6-6-6" />
		</svg>
	);
}

function MoreHorizontalIcon(props: React.SVGProps<SVGSVGElement>) {
	return (
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" {...props}>
			<circle cx="12" cy="12" r="1" />
			<circle cx="19" cy="12" r="1" />
			<circle cx="5" cy="12" r="1" />
		</svg>
	);
}

export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {}

const Breadcrumb = React.forwardRef<HTMLElement, BreadcrumbProps>(({ className = '', children, ...props }, ref) => {
	return (
		<nav ref={ref} aria-label="breadcrumb" className={`${styles[breadcrumbStyleKeys.root]} ${className}`} {...props}>
			{children}
		</nav>
	);
});
Breadcrumb.displayName = 'Breadcrumb';

export interface BreadcrumbListProps extends React.HTMLAttributes<HTMLOListElement> {}

const BreadcrumbList = React.forwardRef<HTMLOListElement, BreadcrumbListProps>(({ className = '', children, ...props }, ref) => {
	return (
		<ol ref={ref} className={`${styles[breadcrumbStyleKeys.list]} ${className}`} {...props}>
			{children}
		</ol>
	);
});
BreadcrumbList.displayName = 'BreadcrumbList';

export interface BreadcrumbItemProps extends React.HTMLAttributes<HTMLLIElement> {}

const BreadcrumbItem = React.forwardRef<HTMLLIElement, BreadcrumbItemProps>(({ className = '', children, ...props }, ref) => {
	return (
		<li ref={ref} className={`${styles[breadcrumbStyleKeys.item]} ${className}`} {...props}>
			{children}
		</li>
	);
});
BreadcrumbItem.displayName = 'BreadcrumbItem';

export interface BreadcrumbLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement>, BreadcrumbLinkBaseProps {}

const BreadcrumbLink = React.forwardRef<HTMLAnchorElement, BreadcrumbLinkProps>(({ className = '', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'a';

	return (
		<Comp ref={ref} className={`${styles[breadcrumbStyleKeys.link]} ${className}`} {...props}>
			{children}
		</Comp>
	);
});
BreadcrumbLink.displayName = 'BreadcrumbLink';

export interface BreadcrumbPageProps extends React.HTMLAttributes<HTMLSpanElement> {}

const BreadcrumbPage = React.forwardRef<HTMLSpanElement, BreadcrumbPageProps>(({ className = '', children, ...props }, ref) => {
	return (
		<span ref={ref} role="link" aria-disabled="true" aria-current="page" className={`${styles[breadcrumbStyleKeys.page]} ${className}`} {...props}>
			{children}
		</span>
	);
});
BreadcrumbPage.displayName = 'BreadcrumbPage';

export interface BreadcrumbSeparatorProps extends React.HTMLAttributes<HTMLLIElement> {}

const BreadcrumbSeparator = React.forwardRef<HTMLLIElement, BreadcrumbSeparatorProps>(({ className = '', children, ...props }, ref) => {
	return (
		<li ref={ref} role="presentation" aria-hidden="true" className={`${styles[breadcrumbStyleKeys.separator]} ${className}`} {...props}>
			{children ?? <ChevronRightIcon />}
		</li>
	);
});
BreadcrumbSeparator.displayName = 'BreadcrumbSeparator';

export interface BreadcrumbEllipsisProps extends React.HTMLAttributes<HTMLSpanElement> {}

const BreadcrumbEllipsis = React.forwardRef<HTMLSpanElement, BreadcrumbEllipsisProps>(({ className = '', ...props }, ref) => {
	return (
		<span ref={ref} role="presentation" aria-hidden="true" className={`${styles[breadcrumbStyleKeys.ellipsis]} ${className}`} {...props}>
			<MoreHorizontalIcon className={styles[breadcrumbStyleKeys.ellipsisIcon]} />
			<span className={styles[breadcrumbStyleKeys.srOnly]}>More</span>
		</span>
	);
});
BreadcrumbEllipsis.displayName = 'BreadcrumbEllipsis';

export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis };
export default Breadcrumb;
