// packages/solid/src/components/input-group/input-group.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { getInputGroupAddonStyleKeys, getInputGroupStyleKeys, inputGroupStyleKeys } from '@tile-ui/core';
import type {
	ButtonSize,
	ButtonVariant,
	InputGroupAddonBaseProps,
	InputGroupBaseProps,
	InputGroupButtonBaseProps,
	InputGroupInputBaseProps,
	InputGroupTextareaBaseProps,
	InputGroupTextBaseProps,
} from '@tile-ui/core';
import { composeEventHandlers } from '../../utils/events';
import styles from '@tile-ui/styles/scss/components/input-group.module.scss';
import { Button, type ButtonProps } from '../button/button';

const INTERACTIVE_SELECTOR = 'button,a[href],input,select,textarea,summary,[contenteditable="true"],[role="button"],[role="link"],[tabindex]:not([tabindex="-1"])';

export interface InputGroupProps extends JSX.HTMLAttributes<HTMLDivElement>, InputGroupBaseProps {}

export function InputGroup(props: ParentProps<InputGroupProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'variant']);
	const variant = () => local.variant ?? 'default';
	const styleKeys = () => getInputGroupStyleKeys(variant());
	return (
		<div {...rest} role="group" data-slot="input-group" data-variant={variant()} class={`${styles[styleKeys().base]} ${styles[styleKeys().variant]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export interface InputGroupAddonProps extends JSX.HTMLAttributes<HTMLDivElement>, InputGroupAddonBaseProps {}

export function InputGroupAddon(props: ParentProps<InputGroupAddonProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'variant', 'align', 'onClick']);
	const variant = () => local.variant ?? 'default';
	const styleKeys = () => getInputGroupAddonStyleKeys(variant());
	const focusControl = (event: MouseEvent & { currentTarget: HTMLDivElement; target: Element }) => {
		if (event.target.closest(INTERACTIVE_SELECTOR)) return;
		event.currentTarget.parentElement?.querySelector<HTMLElement>('[data-slot="input-group-control"]')?.focus();
	};

	return (
		<div
			{...rest}
			role="group"
			data-slot="input-group-addon"
			data-variant={variant()}
			data-align={local.align ?? 'inline-start'}
			class={`${styles[styleKeys().base]} ${styles[styleKeys().variant]} ${local.class ?? ''}`}
			onClick={composeEventHandlers(local.onClick, focusControl)}>
			{local.children}
		</div>
	);
}

export interface InputGroupButtonProps extends Omit<ButtonProps, 'size' | 'variant'>, InputGroupButtonBaseProps {
	variant?: ButtonVariant;
	size?: ButtonSize;
}

export function InputGroupButton(props: ParentProps<InputGroupButtonProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'variant', 'size', 'type']);
	return (
		<Button
			{...rest}
			type={local.type ?? 'button'}
			variant={local.variant ?? 'ghost'}
			size={local.size ?? 'sm'}
			class={`${styles[inputGroupStyleKeys.button]} ${local.class ?? ''}`}>
			{local.children}
		</Button>
	);
}

export interface InputGroupTextProps extends JSX.HTMLAttributes<HTMLSpanElement>, InputGroupTextBaseProps {}

export function InputGroupText(props: ParentProps<InputGroupTextProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<span {...rest} data-slot="input-group-text" class={`${styles[inputGroupStyleKeys.text]} ${local.class ?? ''}`}>
			{local.children}
		</span>
	);
}

export interface InputGroupInputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'size'>, InputGroupInputBaseProps {}

export function InputGroupInput(props: InputGroupInputProps) {
	const [local, rest] = splitProps(props, ['class']);
	return <input {...rest} data-slot="input-group-control" class={`${styles[inputGroupStyleKeys.input]} ${local.class ?? ''}`} />;
}

export interface InputGroupTextareaProps extends JSX.TextareaHTMLAttributes<HTMLTextAreaElement>, InputGroupTextareaBaseProps {}

export function InputGroupTextarea(props: ParentProps<InputGroupTextareaProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<textarea {...rest} data-slot="input-group-control" class={`${styles[inputGroupStyleKeys.textarea]} ${local.class ?? ''}`}>
			{local.children}
		</textarea>
	);
}

export default InputGroup;

// packages/react/src/components/input-group/input-group.tsx
import React from 'react';
import { getInputGroupAddonStyleKeys, getInputGroupStyleKeys, inputGroupStyleKeys } from '@tile-ui/core';
import type {
	InputGroupAddonBaseProps,
	InputGroupBaseProps,
	InputGroupButtonBaseProps,
	InputGroupInputBaseProps,
	InputGroupTextareaBaseProps,
	InputGroupTextBaseProps,
	ButtonVariant,
	ButtonSize,
} from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/input-group.module.scss';
import { Button } from '../button';

export interface InputGroupProps extends React.HTMLAttributes<HTMLDivElement>, InputGroupBaseProps {}

const InputGroup = React.forwardRef<HTMLDivElement, InputGroupProps>(({ className = '', variant = 'default', children, ...props }, ref) => {
	const styleKeys = getInputGroupStyleKeys(variant);
	const classes = [styles[styleKeys.base], styles[styleKeys.variant], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} role="group" data-slot="input-group" data-variant={variant} className={classes} {...props}>
			{children}
		</div>
	);
});
InputGroup.displayName = 'InputGroup';

export interface InputGroupAddonProps extends React.HTMLAttributes<HTMLDivElement>, InputGroupAddonBaseProps {}

const InputGroupAddon = React.forwardRef<HTMLDivElement, InputGroupAddonProps>(({ className = '', variant = 'default', align = 'inline-start', onClick, ...props }, ref) => {
	const styleKeys = getInputGroupAddonStyleKeys(variant);
	const classes = [styles[styleKeys.base], styles[styleKeys.variant], className].filter(Boolean).join(' ');

	function handleClick(event: React.MouseEvent<HTMLDivElement>) {
		if ((event.target as HTMLElement).closest('button')) {
			return;
		}
		event.currentTarget.parentElement?.querySelector('input')?.focus();
		onClick?.(event);
	}

	return <div ref={ref} role="group" data-slot="input-group-addon" data-variant={variant} data-align={align} className={classes} onClick={handleClick} {...props} />;
});
InputGroupAddon.displayName = 'InputGroupAddon';

export interface InputGroupButtonProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type' | 'size'>, InputGroupButtonBaseProps {
	type?: 'button' | 'submit' | 'reset';
	variant?: ButtonVariant;
	size?: ButtonSize;
}

const InputGroupButton = React.forwardRef<HTMLButtonElement, InputGroupButtonProps>(
	({ className = '', type = 'button', variant = 'ghost', size = 'sm', children, ...props }, ref) => {
		return (
			<Button ref={ref} type={type} variant={variant} size={size} className={`${styles[inputGroupStyleKeys.button]} ${className}`} {...props}>
				{children}
			</Button>
		);
	},
);
InputGroupButton.displayName = 'InputGroupButton';

export interface InputGroupTextProps extends React.HTMLAttributes<HTMLSpanElement>, InputGroupTextBaseProps {}

const InputGroupText = React.forwardRef<HTMLSpanElement, InputGroupTextProps>(({ className = '', children, ...props }, ref) => {
	return (
		<span ref={ref} data-slot="input-group-text" className={`${styles[inputGroupStyleKeys.text]} ${className}`} {...props}>
			{children}
		</span>
	);
});
InputGroupText.displayName = 'InputGroupText';

export interface InputGroupInputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>, InputGroupInputBaseProps {}

const InputGroupInput = React.forwardRef<HTMLInputElement, InputGroupInputProps>(({ className = '', ...props }, ref) => {
	return <input ref={ref} data-slot="input-group-control" className={`${styles[inputGroupStyleKeys.input]} ${className}`} {...props} />;
});
InputGroupInput.displayName = 'InputGroupInput';

export interface InputGroupTextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement>, InputGroupTextareaBaseProps {}

const InputGroupTextarea = React.forwardRef<HTMLTextAreaElement, InputGroupTextareaProps>(({ className = '', ...props }, ref) => {
	return <textarea ref={ref} data-slot="input-group-control" className={`${styles[inputGroupStyleKeys.textarea]} ${className}`} {...props} />;
});
InputGroupTextarea.displayName = 'InputGroupTextarea';

export { InputGroup, InputGroupAddon, InputGroupButton, InputGroupText, InputGroupInput, InputGroupTextarea };
export default InputGroup;
