// packages/vue/src/components/label/label.tsx
import { defineComponent, computed, h } from 'vue';
import { getLabelClassKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/label.module.scss';

export const Label = defineComponent({
	name: 'Label',
	props: {
		required: { type: Boolean, default: false },
		htmlFor: String,
	},
	setup(props, { slots }) {
		const classKeys = computed(() => getLabelClassKeys(props.required));
		const classes = computed(() => [styles[classKeys.value.base], classKeys.value.required ? styles[classKeys.value.required] : '']);

		return () => h('label', { class: classes.value, for: props.htmlFor }, slots.default?.());
	},
});

export default Label;

// packages/solid/src/components/label/label.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { getLabelClassKeys } from '@tile-ui/core';
import type { LabelBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/label.module.scss';
export interface LabelProps extends JSX.LabelHTMLAttributes<HTMLLabelElement>, LabelBaseProps {}
export function Label(props: ParentProps<LabelProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'required']);
	const keys = () => getLabelClassKeys(local.required);
	return (
		<label {...rest} class={`${styles[keys().base]} ${keys().required ? styles[keys().required!] : ''} ${local.class ?? ''}`}>
			{local.children}
		</label>
	);
}
export default Label;
