// packages/vue/src/components/toggle-group/toggle-group.tsx
import { computed, defineComponent, h, inject, provide, ref, type ComputedRef, type InjectionKey, type PropType } from 'vue';
import { getToggleGroupItemState, getToggleStyleKeys, toggleGroupStyleKeys, toggleValueInList } from '@tile-ui/core';
import type { ToggleGroupType, ToggleVariant, ToggleSize } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/toggle-group.module.scss';

type ToggleGroupValue = string | string[];

interface ToggleGroupContextValue {
	type: 'single' | 'multiple';
	value: ToggleGroupValue;
	onItemClick: (itemValue: string) => void;
}

type ToggleGroupContext = ComputedRef<ToggleGroupContextValue>;

const ToggleGroupContextKey: InjectionKey<ToggleGroupContext> = Symbol('tile-toggle-group');

export const ToggleGroup = defineComponent({
	name: 'ToggleGroup',
	props: {
		modelValue: {
			type: [String, Array] as PropType<string | string[]>,
			default: undefined,
		},
		defaultValue: {
			type: [String, Array] as PropType<string | string[]>,
			default: undefined,
		},
		type: {
			type: String as PropType<ToggleGroupType>,
			default: 'single',
		},
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit, slots, attrs }) {
		const internalValue = ref<string | string[]>(props.defaultValue ?? (props.type === 'single' ? '' : []));
		const currentValue = computed(() => (props.modelValue !== undefined ? props.modelValue : internalValue.value));

		function handleItemClick(itemValue: string) {
			let next: string | string[];

			if (props.type === 'single') {
				next = currentValue.value === itemValue ? '' : itemValue;
			} else {
				const list = Array.isArray(currentValue.value) ? currentValue.value : [];
				next = toggleValueInList(itemValue, list);
			}

			if (props.modelValue === undefined) {
				internalValue.value = next;
			}

			emit('update:modelValue', next);
			emit('change', next);
		}

		const context = computed<ToggleGroupContextValue>(() => ({
			type: props.type,
			value: currentValue.value,
			onItemClick: handleItemClick,
		}));

		provide(ToggleGroupContextKey, context);

		return () =>
			h('div', { ...attrs, role: 'group', 'data-slot': 'toggle-group', 'data-type': props.type, class: [styles[toggleGroupStyleKeys.root], attrs.class] }, slots.default?.());
	},
});

export const ToggleGroupItem = defineComponent({
	name: 'ToggleGroupItem',
	props: {
		value: { type: String, required: true },
		variant: {
			type: String as PropType<ToggleVariant>,
			default: 'default',
		},
		size: {
			type: String as PropType<ToggleSize>,
			default: 'default',
		},
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = inject(ToggleGroupContextKey);
		if (!context) {
			throw new Error('ToggleGroupItem must be used within <ToggleGroup>.');
		}
		const contextRef = context;

		const selected = computed(() =>
			contextRef.value.type === 'single'
				? contextRef.value.value === props.value
				: Array.isArray(contextRef.value.value)
					? contextRef.value.value.includes(props.value)
					: false,
		);
		const state = computed(() => getToggleGroupItemState(selected.value));
		const styleKeys = computed(() => getToggleStyleKeys(props.variant, props.size));
		const classes = computed(() => [styles[toggleGroupStyleKeys.item], styles[styleKeys.value.variant], styles[styleKeys.value.size]]);

		function handleClick() {
			contextRef.value.onItemClick(props.value);
		}

		return () =>
			h(
				'button',
				{
					...attrs,
					type: 'button',
					value: props.value,
					'aria-pressed': selected.value ? 'true' : 'false',
					'data-state': state.value,
					'data-active': selected.value,
					disabled: props.disabled,
					class: [...classes.value, attrs.class],
					onClick: handleClick,
				},
				slots.default?.(),
			);
	},
});

export default ToggleGroup;

// packages/react/src/components/toggle-group/toggle-group.tsx
import React, { createContext, useContext, useState } from 'react';
import { getToggleGroupItemState, getToggleStyleKeys, toggleGroupStyleKeys, toggleValueInList } from '@tile-ui/core';
import type { ToggleGroupBaseProps, ToggleGroupItemBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/toggle-group.module.scss';

type ToggleGroupValue = string | string[];

interface ToggleGroupContextValue {
	type: 'single' | 'multiple';
	value: ToggleGroupValue;
	onItemClick: (itemValue: string) => void;
}

const ToggleGroupContext = createContext<ToggleGroupContextValue | null>(null);

function useToggleGroupContext(): ToggleGroupContextValue {
	const context = useContext(ToggleGroupContext);
	if (!context) {
		throw new Error('ToggleGroupItem must be used within <ToggleGroup>.');
	}
	return context;
}

export interface ToggleGroupProps extends React.HTMLAttributes<HTMLDivElement>, ToggleGroupBaseProps {
	value?: string | string[];
	defaultValue?: string | string[];
	onValueChange?: (value: string | string[]) => void;
}

const ToggleGroup = React.forwardRef<HTMLDivElement, ToggleGroupProps>(({ className = '', type = 'single', value, defaultValue, onValueChange, children, ...props }, ref) => {
	const [internalValue, setInternalValue] = useState<ToggleGroupValue>(defaultValue ?? (type === 'single' ? '' : []));
	const currentValue = value !== undefined ? value : internalValue;

	function handleItemClick(itemValue: string) {
		let next: ToggleGroupValue;

		if (type === 'single') {
			next = currentValue === itemValue ? '' : itemValue;
		} else {
			const list = Array.isArray(currentValue) ? currentValue : [];
			next = toggleValueInList(itemValue, list);
		}

		if (value === undefined) {
			setInternalValue(next);
		}

		onValueChange?.(next);
	}

	const context: ToggleGroupContextValue = { type, value: currentValue, onItemClick: handleItemClick };

	return (
		<ToggleGroupContext.Provider value={context}>
			<div ref={ref} role="group" data-slot="toggle-group" data-type={type} className={`${styles[toggleGroupStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</ToggleGroupContext.Provider>
	);
});
ToggleGroup.displayName = 'ToggleGroup';

export interface ToggleGroupItemProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'value'>, ToggleGroupItemBaseProps {}

const ToggleGroupItem = React.forwardRef<HTMLButtonElement, ToggleGroupItemProps>(
	({ className = '', value, variant = 'default', size = 'default', disabled, children, ...props }, ref) => {
		const context = useToggleGroupContext();
		const selected = context.type === 'single' ? context.value === value : Array.isArray(context.value) ? context.value.includes(value) : false;
		const state = getToggleGroupItemState(selected);
		const styleKeys = getToggleStyleKeys(variant, size);
		const classes = [styles[toggleGroupStyleKeys.item], styles[styleKeys.variant], styles[styleKeys.size], className].filter(Boolean).join(' ');

		return (
			<button
				ref={ref}
				type="button"
				value={value}
				role="button"
				aria-pressed={selected}
				data-state={state}
				data-active={selected}
				disabled={disabled}
				className={classes}
				onClick={() => context.onItemClick(value)}
				{...props}>
				{children}
			</button>
		);
	},
);
ToggleGroupItem.displayName = 'ToggleGroupItem';

export { ToggleGroup, ToggleGroupItem };
export default ToggleGroup;
