// apps/solid/src/app.tsx
import { Link, Meta, MetaProvider } from '@solidjs/meta';
import { Router } from '@solidjs/router';
import { FileRoutes } from '@solidjs/start/router';
import { Suspense, type ParentProps } from 'solid-js';

import '@tile-ui/styles/scss/globals.scss';
import './styles/docs.scss';

function SolidMark() {
	return (
		<svg class="solid-mark" viewBox="0 0 32 32" aria-hidden="true">
			<path d="M5 8.5 14.5 4 27 9.5l-9.5 4.4L5 8.5Z" fill="currentColor" opacity=".72" />
			<path d="m5 13 12.5 5.4L27 14v6l-9.5 4.5L5 19v-6Z" fill="currentColor" />
		</svg>
	);
}

function GitHubIcon() {
	return (
		<svg class="solid-source__icon" viewBox="0 0 24 24" aria-hidden="true">
			<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7A5.4 5.4 0 0 0 19.4 4 5 5 0 0 0 19.3.5S18.2.1 15 1.8a13.4 13.4 0 0 0-7 0C4.8.1 3.7.5 3.7.5A5 5 0 0 0 3.6 4a5.4 5.4 0 0 0-1.4 3.7c0 5.4 3.5 6.6 6.8 7A4.8 4.8 0 0 0 8 18v4" />
			<path d="M8 19c-3 .9-3-1.5-4-2" />
		</svg>
	);
}

function AppShell(props: ParentProps) {
	return (
		<div class="solid-docs-shell" data-tile-app="solidstart">
			<header class="solid-header">
				<div class="solid-header__inner">
					<a href="/" class="solid-brand">
						<SolidMark />
						<span>Tile UI</span>
						<strong>Solid</strong>
					</a>
					<div class="solid-header__actions">
						<nav aria-label="Primary navigation">
							<a href="/docs">Docs</a>
							<a href="/docs/components">Components</a>
							<a href="/docs/primitives">Primitives</a>
							<a href="/docs/registry">Registry</a>
							<a href="/docs/examples">Examples</a>
						</nav>
						<div class="solid-header__divider" aria-hidden="true" />
						<a class="solid-source" href="https://github.com/zmide/tile-ui" rel="noreferrer" target="_blank">
							<GitHubIcon />
							<span>Source code</span>
						</a>
					</div>
				</div>
			</header>
			<main id="main-content">
				<Suspense>{props.children}</Suspense>
			</main>
		</div>
	);
}

export default function App() {
	return (
		<Router
			root={(props) => (
				<MetaProvider>
					<Link rel="icon" type="image/svg+xml" href="/favicon.svg" />
					<Meta name="generator" content="SolidStart" />
					<Meta name="tile-ui-app" content="solidstart" />
					<AppShell>{props.children}</AppShell>
				</MetaProvider>
			)}>
			<FileRoutes />
		</Router>
	);
}

// apps/vue/app.tsx
import { defineComponent } from 'vue';

function GitHubIcon() {
	return (
		<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
			<path
				fill="currentColor"
				d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.866-.013-1.699-2.782.605-3.369-1.344-3.369-1.344-.455-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.071 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.091-.647.349-1.088.635-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.748-1.026 2.748-1.026.546 1.378.202 2.397.1 2.65.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.31.678.921.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .269.18.58.688.481A10.02 10.02 0 0 0 22 12.017C22 6.484 17.523 2 12 2Z"
			/>
		</svg>
	);
}

export default defineComponent({
	name: 'VueApp',
	setup() {
		return () => (
			<div class="docs-app-shell">
				<header class="docs-app-header">
					<div class="docs-app-header__inner">
						<NuxtLink to="/" class="docs-app-brand">
							Tile UI Vue
						</NuxtLink>
						<div class="docs-app-header__actions">
							<nav class="docs-app-nav">
								<NuxtLink to="/docs">Docs</NuxtLink>
								<NuxtLink to="/docs/components">Components</NuxtLink>
								<NuxtLink to="/docs/composables">Composables</NuxtLink>
								<NuxtLink to="/docs/registry">Registry</NuxtLink>
								<NuxtLink to="/docs/examples">Examples</NuxtLink>
							</nav>
							<div class="docs-app-header__divider" aria-hidden="true" />
							<a href="https://github.com/ice909/tile-ui" target="_blank" rel="noreferrer" class="docs-app-github" aria-label="Tile UI GitHub repository">
								<GitHubIcon />
								<span>Source code</span>
							</a>
						</div>
					</div>
				</header>
				<NuxtPage />
			</div>
		);
	},
});
