// packages/react/src/components/item/item.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { getItemMediaVariantKey, getItemSizeKey, getItemVariantKey, itemStyleKeys } from '@tile-ui/core';
import type { ItemBaseProps, ItemMediaBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/item.module.scss';

export interface ItemGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemGroup = React.forwardRef<HTMLDivElement, ItemGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} role="list" data-slot="item-group" className={`${styles[itemStyleKeys.group]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemGroup.displayName = 'ItemGroup';

export interface ItemSeparatorProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemSeparator = React.forwardRef<HTMLDivElement, ItemSeparatorProps>(({ className = '', ...props }, ref) => {
	return <div ref={ref} role="separator" aria-orientation="horizontal" data-slot="item-separator" className={`${styles[itemStyleKeys.separator]} ${className}`} {...props} />;
});
ItemSeparator.displayName = 'ItemSeparator';

export interface ItemProps extends React.HTMLAttributes<HTMLDivElement>, ItemBaseProps {}

const Item = React.forwardRef<HTMLDivElement, ItemProps>(({ className = '', variant = 'default', size = 'default', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'div';
	const variantKey = getItemVariantKey(variant);
	const sizeKey = getItemSizeKey(size);
	const classes = [styles[itemStyleKeys.item], styles[variantKey], styles[sizeKey], className].filter(Boolean).join(' ');

	return (
		<Comp ref={ref} data-slot="item" data-variant={variant} data-size={size} className={classes} {...props}>
			{children}
		</Comp>
	);
});
Item.displayName = 'Item';

export interface ItemMediaProps extends React.HTMLAttributes<HTMLDivElement>, ItemMediaBaseProps {}

const ItemMedia = React.forwardRef<HTMLDivElement, ItemMediaProps>(({ className = '', variant = 'default', children, ...props }, ref) => {
	const variantKey = getItemMediaVariantKey(variant);
	const classes = [styles[itemStyleKeys.media], styles[variantKey], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} data-slot="item-media" data-variant={variant} className={classes} {...props}>
			{children}
		</div>
	);
});
ItemMedia.displayName = 'ItemMedia';

export interface ItemContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemContent = React.forwardRef<HTMLDivElement, ItemContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-content" className={`${styles[itemStyleKeys.content]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemContent.displayName = 'ItemContent';

export interface ItemTitleProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemTitle = React.forwardRef<HTMLDivElement, ItemTitleProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-title" className={`${styles[itemStyleKeys.title]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemTitle.displayName = 'ItemTitle';

export interface ItemDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

const ItemDescription = React.forwardRef<HTMLParagraphElement, ItemDescriptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<p ref={ref} data-slot="item-description" className={`${styles[itemStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
ItemDescription.displayName = 'ItemDescription';

export interface ItemActionsProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemActions = React.forwardRef<HTMLDivElement, ItemActionsProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-actions" className={`${styles[itemStyleKeys.actions]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemActions.displayName = 'ItemActions';

export interface ItemHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemHeader = React.forwardRef<HTMLDivElement, ItemHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-header" className={`${styles[itemStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemHeader.displayName = 'ItemHeader';

export interface ItemFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemFooter = React.forwardRef<HTMLDivElement, ItemFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-footer" className={`${styles[itemStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemFooter.displayName = 'ItemFooter';

export { Item, ItemMedia, ItemContent, ItemActions, ItemGroup, ItemSeparator, ItemTitle, ItemDescription, ItemHeader, ItemFooter };
export default Item;

// packages/solid/src/components/item/item.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { getItemMediaVariantKey, getItemSizeKey, getItemVariantKey, itemStyleKeys } from '@tile-ui/core';
import type { ItemBaseProps, ItemMediaBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/item.module.scss';

export interface ItemGroupProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export function ItemGroup(props: ParentProps<ItemGroupProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} role={rest.role ?? 'list'} data-slot="item-group" class={`${styles[itemStyleKeys.group]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}
export interface ItemSeparatorProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export function ItemSeparator(props: ItemSeparatorProps) {
	const [local, rest] = splitProps(props, ['class']);
	return <div {...rest} role="separator" aria-orientation="horizontal" data-slot="item-separator" class={`${styles[itemStyleKeys.separator]} ${local.class ?? ''}`} />;
}
export interface ItemProps extends JSX.HTMLAttributes<HTMLDivElement>, Omit<ItemBaseProps, 'asChild'> {}
export function Item(props: ParentProps<ItemProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'variant', 'size']);
	const variant = () => local.variant ?? 'default';
	const size = () => local.size ?? 'default';
	return (
		<div
			{...rest}
			data-slot="item"
			data-variant={variant()}
			data-size={size()}
			class={`${styles[itemStyleKeys.item]} ${styles[getItemVariantKey(variant())]} ${styles[getItemSizeKey(size())]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}
export interface ItemMediaProps extends JSX.HTMLAttributes<HTMLDivElement>, ItemMediaBaseProps {}
export function ItemMedia(props: ParentProps<ItemMediaProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'variant']);
	const variant = () => local.variant ?? 'default';
	return (
		<div {...rest} data-slot="item-media" data-variant={variant()} class={`${styles[itemStyleKeys.media]} ${styles[getItemMediaVariantKey(variant())]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}
function divPrimitive(key: keyof typeof itemStyleKeys, slot: string) {
	return (props: ParentProps<JSX.HTMLAttributes<HTMLDivElement>>) => {
		const [local, rest] = splitProps(props, ['class', 'children']);
		return (
			<div {...rest} data-slot={slot} class={`${styles[itemStyleKeys[key]]} ${local.class ?? ''}`}>
				{local.children}
			</div>
		);
	};
}
export interface ItemContentProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const ItemContent = divPrimitive('content', 'item-content');
export interface ItemTitleProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const ItemTitle = divPrimitive('title', 'item-title');
export interface ItemActionsProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const ItemActions = divPrimitive('actions', 'item-actions');
export interface ItemHeaderProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const ItemHeader = divPrimitive('header', 'item-header');
export interface ItemFooterProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export const ItemFooter = divPrimitive('footer', 'item-footer');
export interface ItemDescriptionProps extends JSX.HTMLAttributes<HTMLParagraphElement> {}
export function ItemDescription(props: ParentProps<ItemDescriptionProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<p {...rest} data-slot="item-description" class={`${styles[itemStyleKeys.description]} ${local.class ?? ''}`}>
			{local.children}
		</p>
	);
}
export default Item;
