// packages/react/src/components/context-menu/context-menu.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import { contextMenuStyleKeys, getContextMenuCheckState, getContextMenuPosition, getContextMenuState } from '@tile-ui/core';
import type {
	ContextMenuBaseProps,
	ContextMenuCheckboxItemBaseProps,
	ContextMenuItemBaseProps,
	ContextMenuLabelBaseProps,
	ContextMenuPosition,
	ContextMenuRadioGroupBaseProps,
	ContextMenuRadioItemBaseProps,
	ContextMenuSubBaseProps,
	ContextMenuSubTriggerBaseProps,
	ContextMenuTriggerBaseProps,
} from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/context-menu.module.scss';

interface ContextMenuContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	triggerRef: React.RefObject<HTMLElement | null>;
	contentId: string;
	position: ContextMenuPosition | null;
	setPosition: (position: ContextMenuPosition) => void;
	closeAll: () => void;
}

const ContextMenuContext = createContext<ContextMenuContextValue | null>(null);

function useContextMenuContext(): ContextMenuContextValue {
	const context = useContext(ContextMenuContext);
	if (!context) {
		throw new Error('ContextMenu 子组件必须位于 <ContextMenu> 内部。');
	}
	return context;
}

interface ContextMenuContentContextValue {
	itemsRef: React.RefObject<HTMLElement[]>;
	close: () => void;
}

const ContextMenuContentContext = createContext<ContextMenuContentContextValue | null>(null);

function useContextMenuContentContext(): ContextMenuContentContextValue {
	const context = useContext(ContextMenuContentContext);
	if (!context) {
		throw new Error('ContextMenu 菜单项必须位于 <ContextMenuContent> 或 <ContextMenuSubContent> 内部。');
	}
	return context;
}

interface ContextMenuSubContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	triggerRef: React.RefObject<HTMLElement | null>;
}

const ContextMenuSubContext = createContext<ContextMenuSubContextValue | null>(null);

function useContextMenuSubContext(): ContextMenuSubContextValue {
	const context = useContext(ContextMenuSubContext);
	if (!context) {
		throw new Error('ContextMenu 子菜单组件必须位于 <ContextMenuSub> 内部。');
	}
	return context;
}

interface ContextMenuRadioGroupContextValue {
	value: string | undefined;
	setValue: (value: string) => void;
}

const ContextMenuRadioGroupContext = createContext<ContextMenuRadioGroupContextValue | null>(null);

function useContextMenuRadioGroupContext(): ContextMenuRadioGroupContextValue {
	const context = useContext(ContextMenuRadioGroupContext);
	if (!context) {
		throw new Error('ContextMenuRadioItem 必须位于 <ContextMenuRadioGroup> 内部。');
	}
	return context;
}

function ContextMenuCheckIcon() {
	return (
		<svg
			className={styles[contextMenuStyleKeys.checkIcon]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="M20 6 9 17l-5-5" />
		</svg>
	);
}

function ContextMenuRadioIcon() {
	return (
		<svg
			className={styles[contextMenuStyleKeys.radioIcon]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="currentColor"
			aria-hidden="true">
			<circle cx="12" cy="12" r="6" />
		</svg>
	);
}

function ContextMenuChevronIcon() {
	return (
		<svg
			className={styles[contextMenuStyleKeys.chevron]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="m9 18 6-6-6-6" />
		</svg>
	);
}

export interface ContextMenuProps extends React.HTMLAttributes<HTMLDivElement>, ContextMenuBaseProps {}

const ContextMenu = React.forwardRef<HTMLDivElement, ContextMenuProps>(({ className = '', open, defaultOpen = false, onOpenChange, children, ...props }, ref) => {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const isOpen = open !== undefined ? open : internalOpen;
	const triggerRef = useRef<HTMLElement | null>(null);
	const contentId = useId();
	const [position, setPosition] = useState<ContextMenuPosition | null>(null);

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}
			onOpenChange?.(next);
		},
		[open, onOpenChange],
	);

	const closeAll = useCallback(() => {
		setOpen(false);
	}, [setOpen]);

	return (
		<ContextMenuContext.Provider value={{ open: isOpen, setOpen, triggerRef, contentId, position, setPosition, closeAll }}>
			<div ref={ref} className={`${styles[contextMenuStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</ContextMenuContext.Provider>
	);
});
ContextMenu.displayName = 'ContextMenu';

export interface ContextMenuPortalProps {
	children?: React.ReactNode;
}

const ContextMenuPortal = ({ children }: ContextMenuPortalProps) => {
	return <>{children}</>;
};
ContextMenuPortal.displayName = 'ContextMenuPortal';

export interface ContextMenuTriggerProps extends React.HTMLAttributes<HTMLElement>, ContextMenuTriggerBaseProps {}

const ContextMenuTrigger = React.forwardRef<HTMLElement, ContextMenuTriggerProps>(({ className = '', asChild = false, children, onContextMenu, ...props }, ref) => {
	const context = useContextMenuContext();

	function setRef(element: HTMLElement | null) {
		context.triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleContextMenu(event: React.MouseEvent<HTMLElement>) {
		onContextMenu?.(event);
		if (event.defaultPrevented) {
			return;
		}
		event.preventDefault();
		context.setPosition({ top: event.clientY, left: event.clientX });
		context.setOpen(true);
	}

	const Comp = asChild ? Slot : 'div';
	const state = getContextMenuState(context.open);

	return (
		<Comp ref={setRef} data-state={state} className={asChild ? undefined : `${styles[contextMenuStyleKeys.trigger]} ${className}`} onContextMenu={handleContextMenu} {...props}>
			{children}
		</Comp>
	);
});
ContextMenuTrigger.displayName = 'ContextMenuTrigger';

export interface ContextMenuContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const ContextMenuContent = React.forwardRef<HTMLDivElement, ContextMenuContentProps>(({ className = '', children, ...props }, ref) => {
	const { open, position, setPosition, closeAll } = useContextMenuContext();
	const contentRef = useRef<HTMLDivElement | null>(null);
	const itemsRef = useRef<HTMLElement[]>([]);

	function setRef(element: HTMLDivElement | null) {
		contentRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	useLayoutEffect(() => {
		if (!open) {
			return;
		}

		function updatePosition() {
			const content = contentRef.current;
			if (!content) {
				return;
			}
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			const base = position ?? { top: 0, left: 0 };
			setPosition(getContextMenuPosition({ x: base.left, y: base.top, contentSize, viewport }));
		}

		function highlightFirst() {
			const items = itemsRef.current;
			if (items.length === 0) {
				return;
			}
			items.forEach((item) => item.removeAttribute('data-highlighted'));
			items[0].setAttribute('data-highlighted', 'true');
		}

		updatePosition();
		highlightFirst();
		window.addEventListener('resize', updatePosition);
		document.addEventListener('scroll', updatePosition, true);

		return () => {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
		};
	}, [open, position, setPosition]);

	useEffect(() => {
		if (!open) {
			return;
		}

		function handlePointerDown(event: PointerEvent) {
			const target = event.target as Node | null;
			if (!target) {
				return;
			}
			const content = contentRef.current;
			if (content && content.contains(target)) {
				return;
			}
			closeAll();
		}

		function handleKeyDown(event: KeyboardEvent) {
			if (event.key === 'Escape') {
				closeAll();
			}
		}

		document.addEventListener('pointerdown', handlePointerDown);
		document.addEventListener('keydown', handleKeyDown);
		return () => {
			document.removeEventListener('pointerdown', handlePointerDown);
			document.removeEventListener('keydown', handleKeyDown);
		};
	}, [open, closeAll]);

	function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
		const items = itemsRef.current.filter((item) => item.getAttribute('data-disabled') !== 'true');
		if (items.length === 0) {
			return;
		}

		const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');

		const highlight = (next: number) => {
			items.forEach((item) => item.removeAttribute('data-highlighted'));
			items[next].setAttribute('data-highlighted', 'true');
			items[next].focus();
		};

		switch (event.key) {
			case 'ArrowDown':
				event.preventDefault();
				highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
				break;
			case 'ArrowUp':
				event.preventDefault();
				highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
				break;
			case 'Home':
				event.preventDefault();
				highlight(0);
				break;
			case 'End':
				event.preventDefault();
				highlight(items.length - 1);
				break;
			case 'Enter':
			case ' ':
				event.preventDefault();
				(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
				break;
		}
	}

	const state = getContextMenuState(open);
	const classes = [styles[contextMenuStyleKeys.content], className].filter(Boolean).join(' ');

	const content = (
		<ContextMenuContentContext.Provider value={{ itemsRef, close: closeAll }}>
			<div
				ref={setRef}
				role="menu"
				tabIndex={-1}
				data-state={state}
				className={classes}
				style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
				onKeyDown={handleKeyDown}
				{...props}>
				{children}
			</div>
		</ContextMenuContentContext.Provider>
	);

	if (!open || typeof document === 'undefined') {
		return null;
	}

	return createPortal(content, document.body);
});
ContextMenuContent.displayName = 'ContextMenuContent';

export interface ContextMenuGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const ContextMenuGroup = React.forwardRef<HTMLDivElement, ContextMenuGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} role="group" className={`${styles[contextMenuStyleKeys.group]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ContextMenuGroup.displayName = 'ContextMenuGroup';

export interface ContextMenuLabelProps extends React.HTMLAttributes<HTMLDivElement>, ContextMenuLabelBaseProps {}

const ContextMenuLabel = React.forwardRef<HTMLDivElement, ContextMenuLabelProps>(({ className = '', inset = false, children, ...props }, ref) => {
	const classes = [styles[contextMenuStyleKeys.label], className].filter(Boolean).join(' ');
	return (
		<div ref={ref} data-inset={inset} className={classes} {...props}>
			{children}
		</div>
	);
});
ContextMenuLabel.displayName = 'ContextMenuLabel';

export interface ContextMenuSeparatorProps extends React.HTMLAttributes<HTMLDivElement> {}

const ContextMenuSeparator = React.forwardRef<HTMLDivElement, ContextMenuSeparatorProps>(({ className = '', ...props }, ref) => {
	const classes = [styles[contextMenuStyleKeys.separator], className].filter(Boolean).join(' ');
	return <div ref={ref} role="separator" className={classes} {...props} />;
});
ContextMenuSeparator.displayName = 'ContextMenuSeparator';

export interface ContextMenuShortcutProps extends React.HTMLAttributes<HTMLSpanElement> {}

const ContextMenuShortcut = React.forwardRef<HTMLSpanElement, ContextMenuShortcutProps>(({ className = '', children, ...props }, ref) => {
	const classes = [styles[contextMenuStyleKeys.shortcut], className].filter(Boolean).join(' ');
	return (
		<span ref={ref} className={classes} {...props}>
			{children}
		</span>
	);
});
ContextMenuShortcut.displayName = 'ContextMenuShortcut';

export interface ContextMenuItemProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onSelect'>, ContextMenuItemBaseProps {}

const ContextMenuItem = React.forwardRef<HTMLDivElement, ContextMenuItemProps>(
	({ className = '', inset = false, variant = 'default', disabled = false, onSelect, children, ...props }, ref) => {
		const { itemsRef, close } = useContextMenuContentContext();
		const itemRef = useRef<HTMLDivElement | null>(null);

		useEffect(() => {
			const element = itemRef.current;
			if (!element) {
				return;
			}
			itemsRef.current.push(element);
			return () => {
				itemsRef.current = itemsRef.current.filter((item) => item !== element);
			};
		}, [itemsRef]);

		function setRef(element: HTMLDivElement | null) {
			itemRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		function handleClick(event: React.MouseEvent<HTMLDivElement>) {
			if (disabled) {
				return;
			}
			onSelect?.(event.nativeEvent);
			close();
		}

		const classes = [styles[contextMenuStyleKeys.item], className].filter(Boolean).join(' ');
		return (
			<div ref={setRef} role="menuitem" tabIndex={-1} data-inset={inset} data-variant={variant} data-disabled={disabled} className={classes} onClick={handleClick} {...props}>
				{children}
			</div>
		);
	},
);
ContextMenuItem.displayName = 'ContextMenuItem';

export interface ContextMenuCheckboxItemProps extends React.HTMLAttributes<HTMLDivElement>, ContextMenuCheckboxItemBaseProps {}

const ContextMenuCheckboxItem = React.forwardRef<HTMLDivElement, ContextMenuCheckboxItemProps>(
	({ className = '', checked, defaultChecked = false, onCheckedChange, disabled = false, children, ...props }, ref) => {
		const { itemsRef } = useContextMenuContentContext();
		const itemRef = useRef<HTMLDivElement | null>(null);
		const [internalChecked, setInternalChecked] = useState(defaultChecked);
		const isChecked = checked !== undefined ? checked : internalChecked;

		useEffect(() => {
			const element = itemRef.current;
			if (!element) {
				return;
			}
			itemsRef.current.push(element);
			return () => {
				itemsRef.current = itemsRef.current.filter((item) => item !== element);
			};
		}, [itemsRef]);

		function setRef(element: HTMLDivElement | null) {
			itemRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		function handleClick() {
			if (disabled) {
				return;
			}
			const next = !isChecked;
			if (checked === undefined) {
				setInternalChecked(next);
			}
			onCheckedChange?.(next);
		}

		const classes = [styles[contextMenuStyleKeys.checkboxItem], className].filter(Boolean).join(' ');
		return (
			<div
				ref={setRef}
				role="menuitemcheckbox"
				tabIndex={-1}
				aria-checked={isChecked}
				data-checked={getContextMenuCheckState(isChecked)}
				data-disabled={disabled}
				className={classes}
				onClick={handleClick}
				{...props}>
				<span className={styles[contextMenuStyleKeys.indicator]}>{isChecked && <ContextMenuCheckIcon />}</span>
				{children}
			</div>
		);
	},
);
ContextMenuCheckboxItem.displayName = 'ContextMenuCheckboxItem';

export interface ContextMenuRadioGroupProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'defaultValue'>, ContextMenuRadioGroupBaseProps {}

const ContextMenuRadioGroup = React.forwardRef<HTMLDivElement, ContextMenuRadioGroupProps>(({ className = '', value, defaultValue, onValueChange, children, ...props }, ref) => {
	const [internalValue, setInternalValue] = useState(defaultValue);
	const resolvedValue = value !== undefined ? value : internalValue;

	const setValue = useCallback(
		(next: string) => {
			if (value === undefined) {
				setInternalValue(next);
			}
			onValueChange?.(next);
		},
		[value, onValueChange],
	);

	const classes = [styles[contextMenuStyleKeys.radioGroup], className].filter(Boolean).join(' ');
	return (
		<ContextMenuRadioGroupContext.Provider value={{ value: resolvedValue, setValue }}>
			<div ref={ref} role="group" className={classes} {...props}>
				{children}
			</div>
		</ContextMenuRadioGroupContext.Provider>
	);
});
ContextMenuRadioGroup.displayName = 'ContextMenuRadioGroup';

export interface ContextMenuRadioItemProps extends React.HTMLAttributes<HTMLDivElement>, ContextMenuRadioItemBaseProps {}

const ContextMenuRadioItem = React.forwardRef<HTMLDivElement, ContextMenuRadioItemProps>(({ className = '', value, disabled = false, children, ...props }, ref) => {
	const { itemsRef } = useContextMenuContentContext();
	const { value: groupValue, setValue } = useContextMenuRadioGroupContext();
	const itemRef = useRef<HTMLDivElement | null>(null);
	const isChecked = groupValue === value;

	useEffect(() => {
		const element = itemRef.current;
		if (!element) {
			return;
		}
		itemsRef.current.push(element);
		return () => {
			itemsRef.current = itemsRef.current.filter((item) => item !== element);
		};
	}, [itemsRef]);

	function setRef(element: HTMLDivElement | null) {
		itemRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleClick() {
		if (disabled) {
			return;
		}
		setValue(value);
	}

	const classes = [styles[contextMenuStyleKeys.radioItem], className].filter(Boolean).join(' ');
	return (
		<div
			ref={setRef}
			role="menuitemradio"
			tabIndex={-1}
			aria-checked={isChecked}
			data-checked={getContextMenuCheckState(isChecked)}
			data-disabled={disabled}
			className={classes}
			onClick={handleClick}
			{...props}>
			<span className={styles[contextMenuStyleKeys.indicator]}>{isChecked && <ContextMenuRadioIcon />}</span>
			{children}
		</div>
	);
});
ContextMenuRadioItem.displayName = 'ContextMenuRadioItem';

export interface ContextMenuSubProps extends ContextMenuSubBaseProps {
	children?: React.ReactNode;
}

const ContextMenuSub = ({ open, defaultOpen = false, onOpenChange, children }: ContextMenuSubProps) => {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const isOpen = open !== undefined ? open : internalOpen;
	const triggerRef = useRef<HTMLElement | null>(null);

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}
			onOpenChange?.(next);
		},
		[open, onOpenChange],
	);

	return <ContextMenuSubContext.Provider value={{ open: isOpen, setOpen, triggerRef }}>{children}</ContextMenuSubContext.Provider>;
};
ContextMenuSub.displayName = 'ContextMenuSub';

export interface ContextMenuSubTriggerProps extends React.HTMLAttributes<HTMLDivElement>, ContextMenuSubTriggerBaseProps {}

const ContextMenuSubTrigger = React.forwardRef<HTMLDivElement, ContextMenuSubTriggerProps>(({ className = '', inset = false, disabled = false, children, ...props }, ref) => {
	const { itemsRef } = useContextMenuContentContext();
	const { open, setOpen, triggerRef } = useContextMenuSubContext();
	const itemRef = useRef<HTMLDivElement | null>(null);

	useEffect(() => {
		const element = itemRef.current;
		if (!element) {
			return;
		}
		itemsRef.current.push(element);
		return () => {
			itemsRef.current = itemsRef.current.filter((item) => item !== element);
		};
	}, [itemsRef]);

	function setRef(element: HTMLDivElement | null) {
		itemRef.current = element;
		triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleMouseEnter() {
		if (disabled) {
			return;
		}
		setOpen(true);
	}

	function handleClick() {
		if (disabled) {
			return;
		}
		setOpen(!open);
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
		if (disabled) {
			return;
		}
		if (event.key === 'ArrowRight' || event.key === 'Enter' || event.key === ' ') {
			event.preventDefault();
			setOpen(true);
		}
	}

	const state = getContextMenuState(open);
	const classes = [styles[contextMenuStyleKeys.subTrigger], className].filter(Boolean).join(' ');
	return (
		<div
			ref={setRef}
			role="menuitem"
			tabIndex={-1}
			aria-haspopup="menu"
			aria-expanded={open}
			data-state={state}
			data-inset={inset}
			data-disabled={disabled}
			className={classes}
			onMouseEnter={handleMouseEnter}
			onClick={handleClick}
			onKeyDown={handleKeyDown}
			{...props}>
			{children}
			<ContextMenuChevronIcon />
		</div>
	);
});
ContextMenuSubTrigger.displayName = 'ContextMenuSubTrigger';

export interface ContextMenuSubContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const ContextMenuSubContent = React.forwardRef<HTMLDivElement, ContextMenuSubContentProps>(({ className = '', children, ...props }, ref) => {
	const { open, setOpen, triggerRef } = useContextMenuSubContext();
	const [position, setPosition] = useState<ContextMenuPosition | null>(null);
	const contentRef = useRef<HTMLDivElement | null>(null);
	const itemsRef = useRef<HTMLElement[]>([]);

	function setRef(element: HTMLDivElement | null) {
		contentRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	useLayoutEffect(() => {
		if (!open) {
			return;
		}

		function updatePosition() {
			const trigger = triggerRef.current;
			const content = contentRef.current;
			if (!trigger || !content) {
				return;
			}
			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			setPosition(getContextMenuPosition({ x: triggerRect.right, y: triggerRect.top, contentSize, viewport }));
		}

		updatePosition();
		window.addEventListener('resize', updatePosition);
		document.addEventListener('scroll', updatePosition, true);

		return () => {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
		};
	}, [open, triggerRef]);

	useEffect(() => {
		if (!open) {
			return;
		}

		function handlePointerDown(event: PointerEvent) {
			const target = event.target as Node | null;
			if (!target) {
				return;
			}
			const content = contentRef.current;
			const trigger = triggerRef.current;
			if (content && content.contains(target)) {
				return;
			}
			if (trigger && trigger.contains(target)) {
				return;
			}
			setOpen(false);
		}

		document.addEventListener('pointerdown', handlePointerDown);
		return () => document.removeEventListener('pointerdown', handlePointerDown);
	}, [open, triggerRef, setOpen]);

	function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
		const items = itemsRef.current.filter((item) => item.getAttribute('data-disabled') !== 'true');

		if (event.key === 'Escape' || event.key === 'ArrowLeft') {
			event.preventDefault();
			setOpen(false);
			triggerRef.current?.focus();
			return;
		}

		if (items.length === 0) {
			return;
		}

		const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');
		const highlight = (next: number) => {
			items.forEach((item) => item.removeAttribute('data-highlighted'));
			items[next].setAttribute('data-highlighted', 'true');
			items[next].focus();
		};

		switch (event.key) {
			case 'ArrowDown':
				event.preventDefault();
				highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
				break;
			case 'ArrowUp':
				event.preventDefault();
				highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
				break;
			case 'Enter':
			case ' ':
				event.preventDefault();
				(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
				break;
		}
	}

	const state = getContextMenuState(open);
	const classes = [styles[contextMenuStyleKeys.subContent], className].filter(Boolean).join(' ');

	const content = (
		<ContextMenuContentContext.Provider value={{ itemsRef, close: () => setOpen(false) }}>
			<div
				ref={setRef}
				role="menu"
				tabIndex={-1}
				data-state={state}
				className={classes}
				style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
				onKeyDown={handleKeyDown}
				{...props}>
				{children}
			</div>
		</ContextMenuContentContext.Provider>
	);

	if (!open || typeof document === 'undefined') {
		return null;
	}

	return createPortal(content, document.body);
});
ContextMenuSubContent.displayName = 'ContextMenuSubContent';

export {
	ContextMenu,
	ContextMenuPortal,
	ContextMenuTrigger,
	ContextMenuContent,
	ContextMenuGroup,
	ContextMenuLabel,
	ContextMenuItem,
	ContextMenuCheckboxItem,
	ContextMenuRadioGroup,
	ContextMenuRadioItem,
	ContextMenuSeparator,
	ContextMenuShortcut,
	ContextMenuSub,
	ContextMenuSubTrigger,
	ContextMenuSubContent,
};
export default ContextMenu;

// packages/vue/src/components/context-menu/context-menu.tsx
import {
	computed,
	defineComponent,
	h,
	inject,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	useId,
	watch,
	Teleport,
	type ComputedRef,
	type InjectionKey,
	type PropType,
	type Ref,
} from 'vue';
import { contextMenuStyleKeys, getContextMenuCheckState, getContextMenuPosition, getContextMenuState } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/context-menu.module.scss';

interface ContextMenuContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	triggerRef: Ref<HTMLElement | null>;
	contentId: string;
	position: { top: number; left: number } | null;
	setPosition: (position: { top: number; left: number }) => void;
	closeAll: () => void;
}

type ContextMenuContext = ComputedRef<ContextMenuContextValue>;

const ContextMenuContextKey: InjectionKey<ContextMenuContext> = Symbol('tile-context-menu');

interface ContextMenuContentContextValue {
	itemsRef: Ref<HTMLElement[]>;
	close: () => void;
}

type ContextMenuContentContext = ComputedRef<ContextMenuContentContextValue>;

const ContextMenuContentContextKey: InjectionKey<ContextMenuContentContext> = Symbol('tile-context-menu-content');

interface ContextMenuSubContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	triggerRef: Ref<HTMLElement | null>;
}

type ContextMenuSubContext = ComputedRef<ContextMenuSubContextValue>;

const ContextMenuSubContextKey: InjectionKey<ContextMenuSubContext> = Symbol('tile-context-menu-sub');

interface ContextMenuRadioGroupContextValue {
	value: string | undefined;
	setValue: (value: string) => void;
}

type ContextMenuRadioGroupContext = ComputedRef<ContextMenuRadioGroupContextValue>;

const ContextMenuRadioGroupContextKey: InjectionKey<ContextMenuRadioGroupContext> = Symbol('tile-context-menu-radio-group');

function contextMenuCheckIcon() {
	return h(
		'svg',
		{
			class: styles[contextMenuStyleKeys.checkIcon],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'M20 6 9 17l-5-5' })],
	);
}

function contextMenuRadioIcon() {
	return h(
		'svg',
		{
			class: styles[contextMenuStyleKeys.radioIcon],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'currentColor',
			'aria-hidden': 'true',
		},
		[h('circle', { cx: '12', cy: '12', r: '6' })],
	);
}

function contextMenuChevronIcon() {
	return h(
		'svg',
		{
			class: styles[contextMenuStyleKeys.chevron],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'm9 18 6-6-6-6' })],
	);
}

function useContextMenuContext(): ContextMenuContext {
	const context = inject(ContextMenuContextKey);
	if (!context) {
		throw new Error('ContextMenu 子组件必须位于 <ContextMenu> 内部。');
	}
	return context;
}

function useContextMenuContentContext(): ContextMenuContentContext {
	const context = inject(ContextMenuContentContextKey);
	if (!context) {
		throw new Error('ContextMenu 菜单项必须位于 <ContextMenuContent> 或 <ContextMenuSubContent> 内部。');
	}
	return context;
}

function useContextMenuSubContext(): ContextMenuSubContext {
	const context = inject(ContextMenuSubContextKey);
	if (!context) {
		throw new Error('ContextMenu 子菜单组件必须位于 <ContextMenuSub> 内部。');
	}
	return context;
}

function useContextMenuRadioGroupContext(): ContextMenuRadioGroupContext {
	const context = inject(ContextMenuRadioGroupContextKey);
	if (!context) {
		throw new Error('ContextMenuRadioItem 必须位于 <ContextMenuRadioGroup> 内部。');
	}
	return context;
}

export const ContextMenu = defineComponent({
	name: 'ContextMenu',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots, attrs }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const triggerRef = ref<HTMLElement | null>(null);
		const contentId = `tile-context-menu-${useId()}`;
		const position = ref<{ top: number; left: number } | null>(null);

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		function closeAll() {
			setOpen(false);
		}

		function setPosition(next: { top: number; left: number }) {
			position.value = next;
		}

		const context = computed<ContextMenuContextValue>(() => ({
			open: isOpen.value,
			setOpen,
			triggerRef,
			contentId,
			position: position.value,
			setPosition,
			closeAll,
		}));

		provide(ContextMenuContextKey, context);

		return () => h('div', { ...attrs, class: [styles[contextMenuStyleKeys.root], attrs.class] }, slots.default?.());
	},
});

export const ContextMenuPortal = defineComponent({
	name: 'ContextMenuPortal',
	setup(_props, { slots }) {
		return () => slots.default?.();
	},
});

export const ContextMenuTrigger = defineComponent({
	name: 'ContextMenuTrigger',
	inheritAttrs: false,
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useContextMenuContext();

		function handleContextMenu(event: MouseEvent) {
			if (event.defaultPrevented) {
				return;
			}
			event.preventDefault();
			context.value.setPosition({ top: event.clientY, left: event.clientX });
			context.value.setOpen(true);
		}

		const triggerProps = {
			ref: context.value.triggerRef,
			'data-state': getContextMenuState(context.value.open),
			onContextmenu: handleContextMenu,
		};

		return () => {
			const child = slots.default?.()[0];

			if (props.asChild && child) {
				const childProps = (child.props ?? {}) as Record<string, unknown>;
				return h(child, { ...childProps, ...triggerProps });
			}

			return h('div', { ...attrs, ...triggerProps, class: [styles[contextMenuStyleKeys.trigger], attrs.class] }, slots.default?.());
		};
	},
});

export const ContextMenuContent = defineComponent({
	name: 'ContextMenuContent',
	inheritAttrs: false,
	setup(_props, { slots, attrs }) {
		const context = useContextMenuContext();
		const contentRef = ref<HTMLElement | null>(null);
		const itemsRef = ref<HTMLElement[]>([]);

		const contentContext = computed<ContextMenuContentContextValue>(() => ({
			itemsRef,
			close: () => context.value.closeAll(),
		}));

		provide(ContextMenuContentContextKey, contentContext);

		let disposeDocListeners: (() => void) | null = null;

		function updatePosition() {
			const content = contentRef.value;
			if (!content) {
				return;
			}
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			const base = context.value.position ?? { top: 0, left: 0 };
			context.value.setPosition(getContextMenuPosition({ x: base.left, y: base.top, contentSize, viewport }));
		}

		function highlightFirst() {
			const items = itemsRef.value;
			if (items.length === 0) {
				return;
			}
			items.forEach((item) => item.removeAttribute('data-highlighted'));
			items[0].setAttribute('data-highlighted', 'true');
			items[0].focus();
		}

		function handleOpen() {
			updatePosition();
			highlightFirst();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				const content = contentRef.value;
				if (!target) {
					return;
				}
				if (content && content.contains(target)) {
					return;
				}
				context.value.closeAll();
			}

			function handleKeyDown(event: KeyboardEvent) {
				if (event.key === 'Escape') {
					context.value.closeAll();
				}
			}

			document.addEventListener('pointerdown', handlePointerDown);
			document.addEventListener('keydown', handleKeyDown);
			disposeDocListeners = () => {
				document.removeEventListener('pointerdown', handlePointerDown);
				document.removeEventListener('keydown', handleKeyDown);
			};
		}

		function handleClose() {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
			disposeDocListeners?.();
			disposeDocListeners = null;
		}

		onMounted(() => {
			if (context.value.open) {
				handleOpen();
			}
		});

		watch(
			() => context.value.open,
			(open) => {
				if (open) {
					handleOpen();
				} else {
					handleClose();
				}
			},
		);

		onBeforeUnmount(handleClose);

		function handleKeyDown(event: KeyboardEvent) {
			const items = itemsRef.value.filter((item) => item.getAttribute('data-disabled') !== 'true');
			if (items.length === 0) {
				return;
			}

			const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');

			const highlight = (next: number) => {
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[next].setAttribute('data-highlighted', 'true');
				items[next].focus();
			};

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
					break;
				case 'ArrowUp':
					event.preventDefault();
					highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
					break;
				case 'Home':
					event.preventDefault();
					highlight(0);
					break;
				case 'End':
					event.preventDefault();
					highlight(items.length - 1);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
					break;
			}
		}

		return () => {
			const open = context.value.open;
			const userClass = attrs.class;
			const userStyle = attrs.style;
			const restAttrs = { ...attrs };
			delete restAttrs.class;
			delete restAttrs.style;

			return h(Teleport, { to: 'body' }, [
				h(
					'div',
					{
						...restAttrs,
						ref: contentRef,
						id: context.value.contentId,
						role: 'menu',
						tabindex: -1,
						'data-state': getContextMenuState(open),
						class: [styles[contextMenuStyleKeys.content], userClass],
						style: context.value.position ? [userStyle, { top: `${context.value.position.top}px`, left: `${context.value.position.left}px` }] : userStyle,
						onKeydown: handleKeyDown,
					},
					slots.default?.(),
				),
			]);
		};
	},
});

export const ContextMenuGroup = defineComponent({
	name: 'ContextMenuGroup',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, role: 'group', class: [styles[contextMenuStyleKeys.group], attrs.class] }, slots.default?.());
	},
});

export const ContextMenuLabel = defineComponent({
	name: 'ContextMenuLabel',
	inheritAttrs: false,
	props: {
		inset: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-inset': props.inset, class: [styles[contextMenuStyleKeys.label], attrs.class] }, slots.default?.());
	},
});

export const ContextMenuSeparator = defineComponent({
	name: 'ContextMenuSeparator',
	setup(_props, { attrs }) {
		return () => h('div', { ...attrs, role: 'separator', class: [styles[contextMenuStyleKeys.separator], attrs.class] });
	},
});

export const ContextMenuShortcut = defineComponent({
	name: 'ContextMenuShortcut',
	setup(_props, { slots, attrs }) {
		return () => h('span', { ...attrs, class: [styles[contextMenuStyleKeys.shortcut], attrs.class] }, slots.default?.());
	},
});

export const ContextMenuItem = defineComponent({
	name: 'ContextMenuItem',
	inheritAttrs: false,
	props: {
		inset: { type: Boolean, default: false },
		variant: { type: String as PropType<'default' | 'destructive'>, default: 'default' },
		disabled: { type: Boolean, default: false },
	},
	emits: ['select'],
	setup(props, { emit, slots, attrs }) {
		const context = useContextMenuContentContext();
		const itemRef = ref<HTMLElement | null>(null);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick(event: MouseEvent) {
			if (props.disabled) {
				return;
			}
			emit('select', event);
			context.value.close();
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'menuitem',
					tabindex: -1,
					'data-inset': props.inset,
					'data-variant': props.variant,
					'data-disabled': props.disabled,
					class: [styles[contextMenuStyleKeys.item], attrs.class],
					onClick: handleClick,
				},
				slots.default?.(),
			);
	},
});

export const ContextMenuCheckboxItem = defineComponent({
	name: 'ContextMenuCheckboxItem',
	inheritAttrs: false,
	props: {
		checked: { type: Boolean, default: undefined },
		defaultChecked: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:checked'],
	setup(props, { emit, slots, attrs }) {
		const context = useContextMenuContentContext();
		const itemRef = ref<HTMLElement | null>(null);
		const internalChecked = ref(props.defaultChecked);
		const isChecked = computed(() => (props.checked !== undefined ? props.checked : internalChecked.value));

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick() {
			if (props.disabled) {
				return;
			}
			const next = !isChecked.value;
			if (props.checked === undefined) {
				internalChecked.value = next;
			}
			emit('update:checked', next);
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'menuitemcheckbox',
					tabindex: -1,
					'aria-checked': isChecked.value,
					'data-checked': getContextMenuCheckState(isChecked.value),
					'data-disabled': props.disabled,
					class: [styles[contextMenuStyleKeys.checkboxItem], attrs.class],
					onClick: handleClick,
				},
				[h('span', { class: styles[contextMenuStyleKeys.indicator] }, [isChecked.value ? contextMenuCheckIcon() : null]), ...(slots.default?.() ?? [])],
			);
	},
});

export const ContextMenuRadioGroup = defineComponent({
	name: 'ContextMenuRadioGroup',
	inheritAttrs: false,
	props: {
		value: { type: String, default: undefined },
		defaultValue: { type: String, default: undefined },
	},
	emits: ['update:value'],
	setup(props, { emit, slots, attrs }) {
		const internalValue = ref(props.defaultValue);
		const resolvedValue = computed(() => (props.value !== undefined ? props.value : internalValue.value));

		function setValue(next: string) {
			if (props.value === undefined) {
				internalValue.value = next;
			}
			emit('update:value', next);
		}

		const context = computed<ContextMenuRadioGroupContextValue>(() => ({ value: resolvedValue.value, setValue }));

		provide(ContextMenuRadioGroupContextKey, context);

		return () => h('div', { ...attrs, role: 'group', class: [styles[contextMenuStyleKeys.radioGroup], attrs.class] }, slots.default?.());
	},
});

export const ContextMenuRadioItem = defineComponent({
	name: 'ContextMenuRadioItem',
	inheritAttrs: false,
	props: {
		value: { type: String, required: true },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useContextMenuContentContext();
		const group = useContextMenuRadioGroupContext();
		const itemRef = ref<HTMLElement | null>(null);
		const isChecked = computed(() => group.value.value === props.value);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick() {
			if (props.disabled) {
				return;
			}
			group.value.setValue(props.value);
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'menuitemradio',
					tabindex: -1,
					'aria-checked': isChecked.value,
					'data-checked': getContextMenuCheckState(isChecked.value),
					'data-disabled': props.disabled,
					class: [styles[contextMenuStyleKeys.radioItem], attrs.class],
					onClick: handleClick,
				},
				[h('span', { class: styles[contextMenuStyleKeys.indicator] }, [isChecked.value ? contextMenuRadioIcon() : null]), ...(slots.default?.() ?? [])],
			);
	},
});

export const ContextMenuSub = defineComponent({
	name: 'ContextMenuSub',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const triggerRef = ref<HTMLElement | null>(null);

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		const context = computed<ContextMenuSubContextValue>(() => ({ open: isOpen.value, setOpen, triggerRef }));

		provide(ContextMenuSubContextKey, context);

		return () => slots.default?.();
	},
});

export const ContextMenuSubTrigger = defineComponent({
	name: 'ContextMenuSubTrigger',
	inheritAttrs: false,
	props: {
		inset: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useContextMenuContentContext();
		const sub = useContextMenuSubContext();
		const itemRef = ref<HTMLElement | null>(null);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function setRef(el: unknown) {
			itemRef.value = (el as HTMLElement | null) ?? null;
			sub.value.triggerRef.value = itemRef.value;
		}

		function handleMouseEnter() {
			if (props.disabled) {
				return;
			}
			sub.value.setOpen(true);
		}

		function handleClick() {
			if (props.disabled) {
				return;
			}
			sub.value.setOpen(!sub.value.open);
		}

		function handleKeyDown(event: KeyboardEvent) {
			if (props.disabled) {
				return;
			}
			if (event.key === 'ArrowRight' || event.key === 'Enter' || event.key === ' ') {
				event.preventDefault();
				sub.value.setOpen(true);
			}
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: setRef,
					role: 'menuitem',
					tabindex: -1,
					'aria-haspopup': 'menu',
					'aria-expanded': sub.value.open,
					'data-state': getContextMenuState(sub.value.open),
					'data-inset': props.inset,
					'data-disabled': props.disabled,
					class: [styles[contextMenuStyleKeys.subTrigger], attrs.class],
					onMouseenter: handleMouseEnter,
					onClick: handleClick,
					onKeydown: handleKeyDown,
				},
				[...(slots.default?.() ?? []), contextMenuChevronIcon()],
			);
	},
});

export const ContextMenuSubContent = defineComponent({
	name: 'ContextMenuSubContent',
	inheritAttrs: false,
	setup(_props, { slots, attrs }) {
		const sub = useContextMenuSubContext();
		const contentRef = ref<HTMLElement | null>(null);
		const itemsRef = ref<HTMLElement[]>([]);
		const position = ref<{ top: number; left: number } | null>(null);

		const contentContext = computed<ContextMenuContentContextValue>(() => ({
			itemsRef,
			close: () => sub.value.setOpen(false),
		}));

		provide(ContextMenuContentContextKey, contentContext);

		let disposeDocListeners: (() => void) | null = null;

		function updatePosition() {
			const trigger = sub.value.triggerRef.value;
			const content = contentRef.value;
			if (!trigger || !content) {
				return;
			}
			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			position.value = getContextMenuPosition({ x: triggerRect.right, y: triggerRect.top, contentSize, viewport });
		}

		function handleOpen() {
			updatePosition();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				const content = contentRef.value;
				const trigger = sub.value.triggerRef.value;
				if (!target) {
					return;
				}
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				sub.value.setOpen(false);
			}

			document.addEventListener('pointerdown', handlePointerDown);
			disposeDocListeners = () => document.removeEventListener('pointerdown', handlePointerDown);
		}

		function handleClose() {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
			disposeDocListeners?.();
			disposeDocListeners = null;
		}

		onMounted(() => {
			if (sub.value.open) {
				handleOpen();
			}
		});

		watch(
			() => sub.value.open,
			(open) => {
				if (open) {
					handleOpen();
				} else {
					handleClose();
				}
			},
		);

		onBeforeUnmount(handleClose);

		function handleKeyDown(event: KeyboardEvent) {
			const items = itemsRef.value.filter((item) => item.getAttribute('data-disabled') !== 'true');

			if (event.key === 'Escape' || event.key === 'ArrowLeft') {
				event.preventDefault();
				sub.value.setOpen(false);
				sub.value.triggerRef.value?.focus();
				return;
			}

			if (items.length === 0) {
				return;
			}

			const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');
			const highlight = (next: number) => {
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[next].setAttribute('data-highlighted', 'true');
				items[next].focus();
			};

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
					break;
				case 'ArrowUp':
					event.preventDefault();
					highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
					break;
			}
		}

		return () => {
			const userClass = attrs.class;
			const userStyle = attrs.style;
			const restAttrs = { ...attrs };
			delete restAttrs.class;
			delete restAttrs.style;

			return h(Teleport, { to: 'body' }, [
				h(
					'div',
					{
						...restAttrs,
						ref: contentRef,
						role: 'menu',
						tabindex: -1,
						'data-state': getContextMenuState(sub.value.open),
						class: [styles[contextMenuStyleKeys.subContent], userClass],
						style: position.value ? [userStyle, { top: `${position.value.top}px`, left: `${position.value.left}px` }] : userStyle,
						onKeydown: handleKeyDown,
					},
					slots.default?.(),
				),
			]);
		};
	},
});

export default ContextMenu;
