// packages/react/src/components/marker/marker.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { getMarkerVariantKey, markerStyleKeys } from '@tile-ui/core';
import type { MarkerBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/marker.module.scss';

export interface MarkerProps extends React.HTMLAttributes<HTMLDivElement>, MarkerBaseProps {}

const Marker = React.forwardRef<HTMLDivElement, MarkerProps>(({ className = '', variant = 'default', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'div';
	const variantKey = getMarkerVariantKey(variant);
	const classes = [styles[markerStyleKeys.root], styles[variantKey], className].filter(Boolean).join(' ');

	return (
		<Comp ref={ref} data-slot="marker" data-variant={variant} className={classes} {...props}>
			{children}
		</Comp>
	);
});
Marker.displayName = 'Marker';

export interface MarkerIconProps extends React.HTMLAttributes<HTMLSpanElement> {}

function CircleIcon() {
	return (
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
			<circle cx="12" cy="12" r="6" />
		</svg>
	);
}

const MarkerIcon = React.forwardRef<HTMLSpanElement, MarkerIconProps>(({ className = '', children, ...props }, ref) => {
	return (
		<span ref={ref} data-slot="marker-icon" aria-hidden="true" className={`${styles[markerStyleKeys.icon]} ${className}`} {...props}>
			{children ?? <CircleIcon />}
		</span>
	);
});
MarkerIcon.displayName = 'MarkerIcon';

export interface MarkerContentProps extends React.HTMLAttributes<HTMLSpanElement> {}

const MarkerContent = React.forwardRef<HTMLSpanElement, MarkerContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<span ref={ref} data-slot="marker-content" className={`${styles[markerStyleKeys.content]} ${className}`} {...props}>
			{children}
		</span>
	);
});
MarkerContent.displayName = 'MarkerContent';

export { Marker, MarkerIcon, MarkerContent };
export default Marker;

// packages/vue/src/components/marker/marker.tsx
import { cloneVNode, computed, defineComponent, h, type PropType } from 'vue';
import { getMarkerVariantKey, markerStyleKeys } from '@tile-ui/core';
import type { MarkerVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/marker.module.scss';

export const Marker = defineComponent({
	name: 'Marker',
	props: {
		variant: {
			type: String as PropType<MarkerVariant>,
			default: 'default',
		},
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const variantKey = computed(() => getMarkerVariantKey(props.variant));

		return () => {
			const children = slots.default?.();
			const variantKeyValue = variantKey.value;
			const rootClass = [styles[markerStyleKeys.root], styles[variantKeyValue]];

			if (props.asChild) {
				const firstChild = Array.isArray(children) ? children[0] : children;

				if (firstChild) {
					const childProps = (firstChild.props ?? {}) as { class?: unknown };
					return cloneVNode(firstChild, {
						...attrs,
						'data-slot': 'marker',
						'data-variant': props.variant,
						class: [styles[markerStyleKeys.root], styles[variantKeyValue], attrs.class, childProps.class].filter(Boolean),
					});
				}
			}

			return h('div', { ...attrs, 'data-slot': 'marker', 'data-variant': props.variant, class: [...rootClass, attrs.class] }, children);
		};
	},
});

function renderCircleIcon() {
	return h('svg', { xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 24 24', fill: 'currentColor', 'aria-hidden': 'true' }, [h('circle', { cx: '12', cy: '12', r: '6' })]);
}

export const MarkerIcon = defineComponent({
	name: 'MarkerIcon',
	setup(_props, { slots, attrs }) {
		return () =>
			h(
				'span',
				{ ...attrs, 'data-slot': 'marker-icon', 'aria-hidden': 'true', class: [styles[markerStyleKeys.icon], attrs.class] },
				slots.default?.() ?? [renderCircleIcon()],
			);
	},
});

export const MarkerContent = defineComponent({
	name: 'MarkerContent',
	setup(_props, { slots, attrs }) {
		return () => h('span', { ...attrs, 'data-slot': 'marker-content', class: [styles[markerStyleKeys.content], attrs.class] }, slots.default?.());
	},
});

export default Marker;
