// packages/solid/src/components/button/button.tsx
import { Show, splitProps, type JSX } from 'solid-js';
import { getButtonStyleKeys, isButtonDisabled } from '@tile-ui/core';
import type { ButtonBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/button.module.scss';

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement>, Omit<ButtonBaseProps, 'asChild'> {}

/**
 * SolidJS Button：复用 core 的样式 key 与禁用判定，样式来自共享 SCSS。
 */
export function Button(props: ButtonProps) {
	const [local, rest] = splitProps(props, ['variant', 'size', 'loading', 'children', 'disabled', 'class', 'type']);
	const styleKeys = () => getButtonStyleKeys(local.variant, local.size);
	const isDisabled = () => isButtonDisabled(local.disabled, local.loading);

	return (
		<button
			{...rest}
			class={`${styles[styleKeys().base]} ${styles[styleKeys().variant]} ${styles[styleKeys().size]} ${local.class ?? ''}`}
			disabled={isDisabled()}
			type={local.type ?? 'button'}>
			<Show when={local.loading}>
				<svg
					class={styles.spinner}
					xmlns="http://www.w3.org/2000/svg"
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
					aria-hidden="true">
					<circle cx="12" cy="12" r="10" />
				</svg>
			</Show>
			{local.children}
		</button>
	);
}

export default Button;

// packages/vue/src/components/button/button.tsx
import { defineComponent, computed, h, type PropType } from 'vue';
import { getButtonStyleKeys, isButtonDisabled } from '@tile-ui/core';
import type { ButtonVariant, ButtonSize } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/button.module.scss';

export const Button = defineComponent({
	name: 'Button',
	props: {
		variant: {
			type: String as PropType<ButtonVariant>,
			default: 'default',
		},
		size: {
			type: String as PropType<ButtonSize>,
			default: 'default',
		},
		loading: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
		type: {
			type: String as PropType<'button' | 'submit' | 'reset'>,
			default: 'button',
		},
	},
	setup(props, { slots }) {
		const styleKeys = computed(() => getButtonStyleKeys(props.variant, props.size));
		const computedDisabled = computed(() => isButtonDisabled(props.disabled, props.loading));
		const classes = computed(() => [styles[styleKeys.value.base], styles[styleKeys.value.variant], styles[styleKeys.value.size]]);

		return () => {
			const children: any[] = [];
			if (props.loading) {
				children.push(
					h(
						'svg',
						{
							class: styles.spinner,
							xmlns: 'http://www.w3.org/2000/svg',
							width: '16',
							height: '16',
							viewBox: '0 0 24 24',
							fill: 'none',
							stroke: 'currentColor',
							'stroke-width': '2',
							'stroke-linecap': 'round',
							'stroke-linejoin': 'round',
						},
						[h('circle', { cx: '12', cy: '12', r: '10' })],
					),
				);
			}
			if (slots.default) {
				children.push(slots.default());
			}
			return h(
				'button',
				{
					class: classes.value,
					disabled: computedDisabled.value,
					type: props.type,
				},
				children,
			);
		};
	},
});

export default Button;
