// packages/vue/src/components/input/input.tsx
import { defineComponent, computed, h, onMounted, ref, useId } from 'vue';
import { getInputIds, getInputAriaProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/input.module.scss';

export const Input = defineComponent({
	name: 'Input',
	props: {
		label: String,
		error: String,
		helperText: String,
		required: { type: Boolean, default: false },
		id: String,
		type: { type: String, default: 'text' },
		placeholder: String,
		modelValue: String,
		defaultValue: String,
		readOnly: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:modelValue'],
	setup(props, { emit }) {
		const fallbackId = useId();
		const inputId = computed(() => props.id || fallbackId);
		const ids = computed(() => getInputIds(inputId.value));
		const ariaProps = computed(() => getInputAriaProps(ids.value, props.error, props.helperText));
		const inputEl = ref<HTMLInputElement | null>(null);

		onMounted(() => {
			if (!inputEl.value) return;
			if (props.modelValue === undefined && props.defaultValue !== undefined) {
				inputEl.value.value = props.defaultValue;
			}
		});

		function onInput(event: Event) {
			emit('update:modelValue', (event.target as HTMLInputElement).value);
		}

		return () => {
			const children: any[] = [];

			if (props.label) {
				children.push(
					h(
						'label',
						{
							for: inputId.value,
							class: [styles.label, props.required ? styles.required : ''],
						},
						props.label,
					),
				);
			}

			children.push(
				h('input', {
					ref: inputEl,
					id: inputId.value,
					type: props.type,
					class: [styles.input, props.error ? styles.error : ''],
					value: props.modelValue,
					placeholder: props.placeholder,
					readonly: props.readOnly,
					disabled: props.disabled,
					'aria-invalid': ariaProps.value['aria-invalid'],
					'aria-describedby': ariaProps.value['aria-describedby'],
					onInput,
				}),
			);

			if (props.error) {
				children.push(h('span', { id: ids.value.error, class: styles.errorText }, props.error));
			} else if (props.helperText) {
				children.push(h('span', { id: ids.value.helper, class: styles.helperText }, props.helperText));
			}

			return h('div', { class: styles.inputWrapper }, children);
		};
	},
});

export default Input;

// packages/solid/src/components/input/input.tsx
import { Show, createUniqueId, splitProps, type JSX } from 'solid-js';
import { getInputIds, getInputAriaProps } from '@tile-ui/core';
import type { InputBaseProps } from '@tile-ui/core';
import { invokeEventHandler } from '../../utils/events';
import styles from '@tile-ui/styles/scss/components/input.module.scss';

export interface InputProps extends JSX.InputHTMLAttributes<HTMLInputElement>, InputBaseProps {
	/** 非受控初始值；Solid JSX 未声明原生 defaultValue 属性 */
	defaultValue?: string;
	/** 值变化回调；受控状态由原生 value 属性决定 */
	onChangeValue?: (value: string) => void;
}

/**
 * SolidJS Input：复用 core 的 ID/ARIA 推导，遵循原生 value/defaultValue 契约。
 */
export function Input(props: InputProps) {
	const [local, rest] = splitProps(props, [
		'label',
		'error',
		'helperText',
		'required',
		'id',
		'type',
		'placeholder',
		'value',
		'defaultValue',
		'readOnly',
		'disabled',
		'onChangeValue',
		'onInput',
		'class',
	]);

	const fallbackId = `tile-solid-input-${createUniqueId()}`;
	const inputId = () => local.id ?? fallbackId;
	const ids = () => getInputIds(inputId());
	const aria = () => getInputAriaProps(ids(), local.error, local.helperText);
	const initialDefaultValue = local.defaultValue;
	const valueProps =
		local.value === undefined
			? { 'attr:value': initialDefaultValue }
			: {
					get value() {
						return local.value;
					},
				};

	return (
		<div class={styles.inputWrapper}>
			<Show when={local.label}>
				<label for={inputId()} class={`${styles.label} ${local.required ? styles.required : ''}`}>
					{local.label}
				</label>
			</Show>
			<input
				{...rest}
				{...valueProps}
				id={inputId()}
				type={local.type ?? 'text'}
				class={`${styles.input} ${local.error ? styles.error : ''} ${local.class ?? ''}`}
				placeholder={local.placeholder}
				readonly={local.readOnly}
				disabled={local.disabled}
				required={local.required}
				aria-invalid={aria()['aria-invalid']}
				aria-describedby={aria()['aria-describedby']}
				onInput={(event) => {
					const next = event.currentTarget.value;
					invokeEventHandler(local.onInput as Parameters<typeof invokeEventHandler<InputEvent>>[0], event);
					if (local.value !== undefined) event.currentTarget.value = String(local.value);
					if (!event.defaultPrevented) {
						local.onChangeValue?.(next);
					}
				}}
			/>
			<Show when={local.error}>
				<span id={ids().error} class={styles.errorText}>
					{local.error}
				</span>
			</Show>
			<Show when={!local.error && local.helperText}>
				<span id={ids().helper} class={styles.helperText}>
					{local.helperText}
				</span>
			</Show>
		</div>
	);
}

export default Input;
