// packages/react/src/components/message/message.tsx
import React from 'react';
import { getMessageStyleKeys, messageStyleKeys } from '@tile-ui/core';
import type { MessageBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/message.module.scss';

export interface MessageGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageGroup = React.forwardRef<HTMLDivElement, MessageGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-group" className={[styles[messageStyleKeys.group], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageGroup.displayName = 'MessageGroup';

export interface MessageProps extends React.HTMLAttributes<HTMLDivElement>, MessageBaseProps {}

const Message = React.forwardRef<HTMLDivElement, MessageProps>(({ className = '', align = 'start', children, ...props }, ref) => {
	const styleKeys = getMessageStyleKeys(align);

	return (
		<div ref={ref} data-slot="message" data-align={align} className={[styles[styleKeys.base], styles[styleKeys.align], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
Message.displayName = 'Message';

export interface MessageAvatarProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageAvatar = React.forwardRef<HTMLDivElement, MessageAvatarProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-avatar" className={[styles[messageStyleKeys.avatar], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageAvatar.displayName = 'MessageAvatar';

export interface MessageContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageContent = React.forwardRef<HTMLDivElement, MessageContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-content" className={[styles[messageStyleKeys.content], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageContent.displayName = 'MessageContent';

export interface MessageHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageHeader = React.forwardRef<HTMLDivElement, MessageHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-header" className={[styles[messageStyleKeys.header], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageHeader.displayName = 'MessageHeader';

export interface MessageFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const MessageFooter = React.forwardRef<HTMLDivElement, MessageFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="message-footer" className={[styles[messageStyleKeys.footer], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
MessageFooter.displayName = 'MessageFooter';

export { MessageGroup, Message, MessageAvatar, MessageContent, MessageHeader, MessageFooter };
export default Message;

// packages/vue/src/components/message/message.tsx
import { defineComponent, h, type PropType } from 'vue';
import { getMessageStyleKeys, messageStyleKeys } from '@tile-ui/core';
import type { MessageAlign } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/message.module.scss';

export const MessageGroup = defineComponent({
	name: 'MessageGroup',
	setup(_props, { slots }) {
		return () => h('div', { 'data-slot': 'message-group', class: styles[messageStyleKeys.group] }, slots.default?.());
	},
});

export const Message = defineComponent({
	name: 'Message',
	props: {
		align: { type: String as PropType<MessageAlign>, default: 'start' },
	},
	setup(props, { slots }) {
		return () => {
			const styleKeys = getMessageStyleKeys(props.align);
			return h('div', { 'data-slot': 'message', 'data-align': props.align, class: [styles[styleKeys.base], styles[styleKeys.align]] }, slots.default?.());
		};
	},
});

export const MessageAvatar = defineComponent({
	name: 'MessageAvatar',
	setup(_props, { slots }) {
		return () => h('div', { 'data-slot': 'message-avatar', class: styles[messageStyleKeys.avatar] }, slots.default?.());
	},
});

export const MessageContent = defineComponent({
	name: 'MessageContent',
	setup(_props, { slots }) {
		return () => h('div', { 'data-slot': 'message-content', class: styles[messageStyleKeys.content] }, slots.default?.());
	},
});

export const MessageHeader = defineComponent({
	name: 'MessageHeader',
	setup(_props, { slots }) {
		return () => h('div', { 'data-slot': 'message-header', class: styles[messageStyleKeys.header] }, slots.default?.());
	},
});

export const MessageFooter = defineComponent({
	name: 'MessageFooter',
	setup(_props, { slots }) {
		return () => h('div', { 'data-slot': 'message-footer', class: styles[messageStyleKeys.footer] }, slots.default?.());
	},
});

export default Message;
