// packages/vue/src/components/field/field.tsx
import { computed, defineComponent, h, inject, provide, ref, useId, type InjectionKey, type PropType, type Ref } from 'vue';
import { fieldStyleKeys, getFieldIds, getFieldMessageStyleKeys } from '@tile-ui/core';
import type { FieldMessageVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/field.module.scss';

interface FieldContextValue {
	id: Ref<string>;
	labelId: Ref<string>;
	descriptionId: Ref<string>;
	messageId: Ref<string>;
	invalid: Ref<boolean>;
	required: Ref<boolean>;
}

const FieldContextKey: InjectionKey<FieldContextValue> = Symbol('tile-field');

export const Field = defineComponent({
	name: 'Field',
	props: {
		name: String,
		invalid: { type: Boolean, default: false },
		required: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const ids = getFieldIds(props.name ?? `tile-field-${useId()}`);
		const context: FieldContextValue = {
			id: ref(ids.id),
			labelId: ref(ids.labelId),
			descriptionId: ref(ids.descriptionId),
			messageId: ref(ids.messageId),
			invalid: computed(() => props.invalid),
			required: computed(() => props.required),
		};

		provide(FieldContextKey, context);

		return () =>
			h(
				'div',
				{
					...attrs,
					role: 'group',
					'data-slot': 'field',
					'data-invalid': props.invalid,
					'data-required': props.required,
					class: [styles[fieldStyleKeys.root], attrs.class],
				},
				slots.default?.(),
			);
	},
});

export const FieldLabel = defineComponent({
	name: 'FieldLabel',
	props: {
		htmlFor: String,
	},
	setup(props, { slots, attrs }) {
		const context = inject(FieldContextKey);
		if (!context) {
			throw new Error('FieldLabel must be used within <Field>.');
		}

		return () =>
			h(
				'label',
				{
					...attrs,
					id: context.id.value,
					for: props.htmlFor ?? context.id.value,
					'data-slot': 'field-label',
					class: [styles[fieldStyleKeys.label], attrs.class],
				},
				slots.default?.(),
			);
	},
});

export const FieldDescription = defineComponent({
	name: 'FieldDescription',
	setup(_props, { slots, attrs }) {
		const context = inject(FieldContextKey);
		if (!context) {
			throw new Error('FieldDescription must be used within <Field>.');
		}

		return () =>
			h(
				'p',
				{
					...attrs,
					id: context.descriptionId.value,
					'data-slot': 'field-description',
					class: [styles[fieldStyleKeys.description], attrs.class],
				},
				slots.default?.(),
			);
	},
});

export const FieldMessage = defineComponent({
	name: 'FieldMessage',
	props: {
		variant: {
			type: String as PropType<FieldMessageVariant>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const context = inject(FieldContextKey);
		if (!context) {
			throw new Error('FieldMessage must be used within <Field>.');
		}

		const styleKeys = computed(() => getFieldMessageStyleKeys(props.variant));
		const classes = computed(() => [styles[styleKeys.value.base], styles[styleKeys.value.variant]]);

		return () =>
			h(
				'div',
				{
					...attrs,
					id: context.messageId.value,
					role: props.variant === 'error' ? 'alert' : undefined,
					'data-slot': 'field-message',
					'data-variant': props.variant,
					class: [...classes.value, attrs.class],
				},
				slots.default?.(),
			);
	},
});

export default Field;

// packages/react/src/components/field/field.tsx
import React, { createContext, useContext, useId } from 'react';
import { fieldStyleKeys, getFieldIds, getFieldMessageStyleKeys } from '@tile-ui/core';
import type { FieldBaseProps, FieldDescriptionBaseProps, FieldLabelBaseProps, FieldMessageBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/field.module.scss';

interface FieldContextValue {
	id: string;
	labelId: string;
	descriptionId: string;
	messageId: string;
	invalid: boolean;
	required: boolean;
}

const FieldContext = createContext<FieldContextValue | null>(null);

function useFieldContext(): FieldContextValue {
	const context = useContext(FieldContext);
	if (!context) {
		throw new Error('Field sub-components must be used within <Field>.');
	}
	return context;
}

export interface FieldProps extends React.HTMLAttributes<HTMLDivElement>, FieldBaseProps {}

const Field = React.forwardRef<HTMLDivElement, FieldProps>(({ className = '', name, invalid = false, required = false, children, ...props }, ref) => {
	const generatedId = useId();
	const ids = getFieldIds(name ?? generatedId);
	const context: FieldContextValue = { ...ids, invalid, required };

	return (
		<FieldContext.Provider value={context}>
			<div ref={ref} role="group" data-slot="field" data-invalid={invalid} data-required={required} className={`${styles[fieldStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</FieldContext.Provider>
	);
});
Field.displayName = 'Field';

export interface FieldLabelProps extends React.LabelHTMLAttributes<HTMLLabelElement>, FieldLabelBaseProps {}

const FieldLabel = React.forwardRef<HTMLLabelElement, FieldLabelProps>(({ className = '', htmlFor, children, ...props }, ref) => {
	const context = useFieldContext();

	return (
		<label ref={ref} htmlFor={htmlFor ?? context.id} id={context.labelId} data-slot="field-label" className={`${styles[fieldStyleKeys.label]} ${className}`} {...props}>
			{children}
		</label>
	);
});
FieldLabel.displayName = 'FieldLabel';

export interface FieldDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement>, FieldDescriptionBaseProps {}

const FieldDescription = React.forwardRef<HTMLParagraphElement, FieldDescriptionProps>(({ className = '', children, ...props }, ref) => {
	const context = useFieldContext();

	return (
		<p ref={ref} id={context.descriptionId} data-slot="field-description" className={`${styles[fieldStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
FieldDescription.displayName = 'FieldDescription';

export interface FieldMessageProps extends React.HTMLAttributes<HTMLDivElement>, FieldMessageBaseProps {}

const FieldMessage = React.forwardRef<HTMLDivElement, FieldMessageProps>(({ className = '', variant = 'default', children, ...props }, ref) => {
	const context = useFieldContext();
	const styleKeys = getFieldMessageStyleKeys(variant);
	const classes = [styles[styleKeys.base], styles[styleKeys.variant], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} id={context.messageId} role={variant === 'error' ? 'alert' : undefined} data-slot="field-message" data-variant={variant} className={classes} {...props}>
			{children}
		</div>
	);
});
FieldMessage.displayName = 'FieldMessage';

export { Field, FieldLabel, FieldDescription, FieldMessage };
export default Field;
