// packages/react/src/components/accordion/accordion.tsx
import React, { createContext, useContext, useId, useState } from 'react';
import { accordionStyleKeys, getAccordionState, getAccordionNextValues } from '@tile-ui/core';
import type { AccordionBaseProps, AccordionItemBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/accordion.module.scss';

interface AccordionContextValue {
	type: 'single' | 'multiple';
	collapsible: boolean;
	value: string | string[];
	toggleItem: (value: string) => void;
}

const AccordionContext = createContext<AccordionContextValue | null>(null);

function useAccordionContext(): AccordionContextValue {
	const context = useContext(AccordionContext);
	if (!context) {
		throw new Error('Accordion sub-components must be used within <Accordion>.');
	}
	return context;
}

interface AccordionItemContextValue {
	value: string;
	open: boolean;
	disabled: boolean;
	contentId: string;
}

const AccordionItemContext = createContext<AccordionItemContextValue | null>(null);

function useAccordionItemContext(): AccordionItemContextValue {
	const context = useContext(AccordionItemContext);
	if (!context) {
		throw new Error('AccordionItem sub-components must be used within <AccordionItem>.');
	}
	return context;
}

export interface AccordionProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'value' | 'defaultValue'>, AccordionBaseProps {}

const Accordion = React.forwardRef<HTMLDivElement, AccordionProps>(
	({ className = '', type = 'single', collapsible = false, value, defaultValue, onValueChange, children, ...props }, ref) => {
		const [internalValue, setInternalValue] = useState<string | string[]>(() => {
			if (type === 'multiple') {
				return Array.isArray(defaultValue) ? defaultValue : [];
			}
			return typeof defaultValue === 'string' ? defaultValue : '';
		});
		const currentValue = value !== undefined ? value : internalValue;
		const normalized = type === 'multiple' ? (Array.isArray(currentValue) ? currentValue : []) : typeof currentValue === 'string' ? currentValue : '';

		function toggleItem(itemValue: string) {
			let next: string | string[];

			if (type === 'multiple') {
				const list = Array.isArray(normalized) ? normalized : [];
				next = getAccordionNextValues(itemValue, list);
			} else if (normalized === itemValue) {
				next = collapsible ? '' : normalized;
			} else {
				next = itemValue;
			}

			if (value === undefined) {
				setInternalValue(next);
			}

			onValueChange?.(next);
		}

		return (
			<AccordionContext.Provider value={{ type, collapsible, value: normalized, toggleItem }}>
				<div ref={ref} data-slot="accordion" className={`${styles[accordionStyleKeys.root]} ${className}`} {...props}>
					{children}
				</div>
			</AccordionContext.Provider>
		);
	},
);
Accordion.displayName = 'Accordion';

export interface AccordionItemProps extends React.HTMLAttributes<HTMLDivElement>, AccordionItemBaseProps {
	value: string;
}

const AccordionItem = React.forwardRef<HTMLDivElement, AccordionItemProps>(({ className = '', value, disabled = false, children, ...props }, ref) => {
	const accordion = useAccordionContext();
	const open = accordion.type === 'multiple' ? Array.isArray(accordion.value) && accordion.value.includes(value) : accordion.value === value;
	const state = getAccordionState(open);
	const contentId = useId();

	return (
		<AccordionItemContext.Provider value={{ value, open, disabled, contentId }}>
			<div ref={ref} data-state={state} className={`${styles[accordionStyleKeys.item]} ${className}`} {...props}>
				{children}
			</div>
		</AccordionItemContext.Provider>
	);
});
AccordionItem.displayName = 'AccordionItem';

export interface AccordionTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {}

const AccordionTrigger = React.forwardRef<HTMLButtonElement, AccordionTriggerProps>(({ className = '', children, onClick, ...props }, ref) => {
	const accordion = useAccordionContext();
	const item = useAccordionItemContext();
	const state = getAccordionState(item.open);

	function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
		if (item.disabled) {
			return;
		}
		accordion.toggleItem(item.value);
		onClick?.(event);
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) {
		const keys = ['ArrowDown', 'ArrowUp', 'Home', 'End'];
		if (!keys.includes(event.key)) {
			return;
		}

		const root = event.currentTarget.closest('[data-slot="accordion"]');
		if (!root) {
			return;
		}
		const triggers = Array.from(root.querySelectorAll<HTMLButtonElement>('button[aria-expanded]')).filter((button) => !button.disabled);
		if (triggers.length === 0) {
			return;
		}

		const index = triggers.indexOf(event.currentTarget);
		let next = index;
		if (event.key === 'ArrowDown') {
			next = (index + 1) % triggers.length;
		} else if (event.key === 'ArrowUp') {
			next = (index - 1 + triggers.length) % triggers.length;
		} else if (event.key === 'Home') {
			next = 0;
		} else if (event.key === 'End') {
			next = triggers.length - 1;
		}

		event.preventDefault();
		triggers[next]?.focus();
	}

	return (
		<div className={styles[accordionStyleKeys.header]}>
			<button
				ref={ref}
				type="button"
				aria-expanded={item.open}
				aria-controls={item.contentId}
				data-state={state}
				disabled={item.disabled}
				className={`${styles[accordionStyleKeys.trigger]} ${className}`}
				onClick={handleClick}
				onKeyDown={handleKeyDown}
				{...props}>
				{children}
				<svg
					className={styles[accordionStyleKeys.chevron]}
					xmlns="http://www.w3.org/2000/svg"
					width="16"
					height="16"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					strokeWidth="2"
					strokeLinecap="round"
					strokeLinejoin="round">
					<path d="m6 9 6 6 6-6" />
				</svg>
			</button>
		</div>
	);
});
AccordionTrigger.displayName = 'AccordionTrigger';

export interface AccordionContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const AccordionContent = React.forwardRef<HTMLDivElement, AccordionContentProps>(({ className = '', children, ...props }, ref) => {
	const item = useAccordionItemContext();
	const state = getAccordionState(item.open);

	return (
		<div ref={ref} id={item.contentId} data-state={state} className={`${styles[accordionStyleKeys.content]} ${className}`} {...props}>
			<div className={styles[accordionStyleKeys.contentInner]}>{children}</div>
		</div>
	);
});
AccordionContent.displayName = 'AccordionContent';

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };
export default Accordion;

// packages/vue/src/components/accordion/accordion.tsx
import { computed, defineComponent, h, inject, provide, ref, useId, type ComputedRef, type InjectionKey, type PropType } from 'vue';
import { accordionStyleKeys, getAccordionState, getAccordionNextValues } from '@tile-ui/core';
import type { AccordionType } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/accordion.module.scss';

interface AccordionContextValue {
	type: AccordionType;
	collapsible: boolean;
	value: string | string[];
	toggleItem: (value: string) => void;
}

type AccordionContext = ComputedRef<AccordionContextValue>;

const AccordionContextKey: InjectionKey<AccordionContext> = Symbol('tile-accordion');

interface AccordionItemContextValue {
	value: string;
	open: boolean;
	disabled: boolean;
	contentId: string;
}

type AccordionItemContext = ComputedRef<AccordionItemContextValue>;

const AccordionItemContextKey: InjectionKey<AccordionItemContext> = Symbol('tile-accordion-item');

export const Accordion = defineComponent({
	name: 'Accordion',
	props: {
		modelValue: {
			type: [String, Array] as PropType<string | string[]>,
			default: undefined,
		},
		defaultValue: {
			type: [String, Array] as PropType<string | string[]>,
			default: undefined,
		},
		type: {
			type: String as PropType<AccordionType>,
			default: 'single',
		},
		collapsible: { type: Boolean, default: false },
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit, slots }) {
		const internalValue = ref<string | string[]>(
			props.modelValue !== undefined ? props.modelValue : props.defaultValue !== undefined ? props.defaultValue : props.type === 'multiple' ? [] : '',
		);
		const currentValue = computed<string | string[]>(() => (props.modelValue !== undefined ? props.modelValue : internalValue.value));
		const normalized = computed<string | string[]>(() =>
			props.type === 'multiple' ? (Array.isArray(currentValue.value) ? currentValue.value : []) : typeof currentValue.value === 'string' ? currentValue.value : '',
		);

		function toggleItem(itemValue: string) {
			let next: string | string[];

			if (props.type === 'multiple') {
				const list = Array.isArray(normalized.value) ? normalized.value : [];
				next = getAccordionNextValues(itemValue, list);
			} else if (normalized.value === itemValue) {
				next = props.collapsible ? '' : normalized.value;
			} else {
				next = itemValue;
			}

			if (props.modelValue === undefined) {
				internalValue.value = next;
			}

			emit('update:modelValue', next);
			emit('change', next);
		}

		const context = computed<AccordionContextValue>(() => ({
			type: props.type,
			collapsible: props.collapsible,
			value: normalized.value,
			toggleItem,
		}));

		provide(AccordionContextKey, context);

		return () => h('div', { 'data-slot': 'accordion', class: styles[accordionStyleKeys.root] }, slots.default?.());
	},
});

export const AccordionItem = defineComponent({
	name: 'AccordionItem',
	props: {
		value: { type: String, required: true },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots }) {
		const accordion = inject(AccordionContextKey);
		if (!accordion) {
			throw new Error('AccordionItem must be used within <Accordion>.');
		}

		const open = computed(() =>
			accordion.value.type === 'multiple' ? Array.isArray(accordion.value.value) && accordion.value.value.includes(props.value) : accordion.value.value === props.value,
		);

		const contentId = `tile-accordion-${useId()}`;

		const itemContext = computed<AccordionItemContextValue>(() => ({
			value: props.value,
			open: open.value,
			disabled: props.disabled,
			contentId,
		}));

		provide(AccordionItemContextKey, itemContext);

		return () => h('div', { class: styles[accordionStyleKeys.item], 'data-state': getAccordionState(open.value) }, slots.default?.());
	},
});

export const AccordionTrigger = defineComponent({
	name: 'AccordionTrigger',
	setup(_props, { slots }) {
		const accordion = inject(AccordionContextKey);
		if (!accordion) {
			throw new Error('AccordionTrigger must be used within <Accordion>.');
		}

		const item = inject(AccordionItemContextKey);
		if (!item) {
			throw new Error('AccordionTrigger must be used within <AccordionItem>.');
		}

		function handleKeydown(event: KeyboardEvent) {
			const keys = ['ArrowDown', 'ArrowUp', 'Home', 'End'];
			if (!keys.includes(event.key)) {
				return;
			}

			const root = (event.currentTarget as HTMLElement).closest('[data-slot="accordion"]');
			if (!root) {
				return;
			}
			const triggers = Array.from(root.querySelectorAll<HTMLButtonElement>('button[aria-expanded]')).filter((button) => !button.disabled);
			if (triggers.length === 0) {
				return;
			}

			const index = triggers.indexOf(event.currentTarget as HTMLButtonElement);
			let next = index;
			if (event.key === 'ArrowDown') {
				next = (index + 1) % triggers.length;
			} else if (event.key === 'ArrowUp') {
				next = (index - 1 + triggers.length) % triggers.length;
			} else if (event.key === 'Home') {
				next = 0;
			} else if (event.key === 'End') {
				next = triggers.length - 1;
			}

			event.preventDefault();
			triggers[next]?.focus();
		}

		return () =>
			h('div', { class: styles[accordionStyleKeys.header] }, [
				h(
					'button',
					{
						type: 'button',
						'aria-expanded': item.value.open,
						'aria-controls': item.value.contentId,
						'data-state': getAccordionState(item.value.open),
						disabled: item.value.disabled,
						class: styles[accordionStyleKeys.trigger],
						onClick: () => accordion.value.toggleItem(item.value.value),
						onKeydown: handleKeydown,
					},
					[
						slots.default?.(),
						h(
							'svg',
							{
								class: styles[accordionStyleKeys.chevron],
								xmlns: 'http://www.w3.org/2000/svg',
								width: '16',
								height: '16',
								viewBox: '0 0 24 24',
								fill: 'none',
								stroke: 'currentColor',
								'stroke-width': '2',
								'stroke-linecap': 'round',
								'stroke-linejoin': 'round',
							},
							[h('path', { d: 'm6 9 6 6 6-6' })],
						),
					],
				),
			]);
	},
});

export const AccordionContent = defineComponent({
	name: 'AccordionContent',
	setup(_props, { slots }) {
		const item = inject(AccordionItemContextKey);
		if (!item) {
			throw new Error('AccordionContent must be used within <AccordionItem>.');
		}

		return () =>
			h('div', { id: item.value.contentId, 'data-state': getAccordionState(item.value.open), class: styles[accordionStyleKeys.content] }, [
				h('div', { class: styles[accordionStyleKeys.contentInner] }, slots.default?.()),
			]);
	},
});

export default Accordion;
