// packages/react/src/components/alert-dialog/alert-dialog.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import type { ButtonSize, ButtonVariant } from '@tile-ui/core';
import { alertDialogStyleKeys, getAlertDialogState } from '@tile-ui/core';
import type { AlertDialogBaseProps, AlertDialogSize } from '@tile-ui/core';
import { Button } from '../button';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/alert-dialog.module.scss';

interface AlertDialogContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	close: () => void;
	titleId: string;
	descriptionId: string;
}

const AlertDialogContext = createContext<AlertDialogContextValue | null>(null);

function useAlertDialogContext(): AlertDialogContextValue {
	const context = useContext(AlertDialogContext);
	if (!context) {
		throw new Error('AlertDialog sub-components must be used within <AlertDialog>.');
	}
	return context;
}

export interface AlertDialogProps extends AlertDialogBaseProps {
	open?: boolean;
	defaultOpen?: boolean;
	onOpenChange?: (open: boolean) => void;
	children?: React.ReactNode;
}

function AlertDialog({ open, defaultOpen = false, onOpenChange, children }: AlertDialogProps) {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const onOpenChangeRef = useRef(onOpenChange);

	useEffect(() => {
		onOpenChangeRef.current = onOpenChange;
	});

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}

			onOpenChangeRef.current?.(next);
		},
		[open],
	);

	const close = useCallback(() => {
		setOpen(false);
	}, [setOpen]);

	const isOpen = open !== undefined ? open : internalOpen;
	const titleId = useId();
	const descriptionId = useId();

	return <AlertDialogContext.Provider value={{ open: isOpen, setOpen, close, titleId, descriptionId }}>{children}</AlertDialogContext.Provider>;
}

AlertDialog.displayName = 'AlertDialog';

export interface AlertDialogTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	asChild?: boolean;
}

const AlertDialogTrigger = React.forwardRef<HTMLButtonElement, AlertDialogTriggerProps>(({ asChild = false, className = '', children, onClick, ...props }, ref) => {
	const context = useAlertDialogContext();
	const Comp = asChild ? Slot : 'button';

	return (
		<Comp
			ref={ref}
			type={asChild ? undefined : 'button'}
			className={className}
			onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
				onClick?.(event);
				context.setOpen(true);
			}}
			{...props}>
			{children}
		</Comp>
	);
});
AlertDialogTrigger.displayName = 'AlertDialogTrigger';

export interface AlertDialogOverlayProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDialogOverlay = React.forwardRef<HTMLDivElement, AlertDialogOverlayProps>(({ className = '', onClick, ...props }, ref) => {
	const context = useAlertDialogContext();

	if (!context.open) {
		return null;
	}

	return (
		<div
			ref={ref}
			data-state={getAlertDialogState(context.open)}
			className={`${styles[alertDialogStyleKeys.overlay]} ${className}`}
			onClick={(event: React.MouseEvent<HTMLDivElement>) => {
				onClick?.(event);
				context.close();
			}}
			{...props}
		/>
	);
});
AlertDialogOverlay.displayName = 'AlertDialogOverlay';

export interface AlertDialogContentProps extends React.HTMLAttributes<HTMLDivElement> {
	size?: AlertDialogSize;
	container?: PortalContainer;
}

const AlertDialogContent = React.forwardRef<HTMLDivElement, AlertDialogContentProps>(({ className = '', size = 'default', container, children, ...props }, ref) => {
	const { open, close, titleId, descriptionId } = useAlertDialogContext();
	const portalContainer = usePortalContainer(container);
	const contentRef = useRef<HTMLDivElement | null>(null);

	function setContentRef(element: HTMLDivElement | null) {
		contentRef.current = element;

		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	useLayoutEffect(() => {
		if (!open) {
			return;
		}

		const previouslyFocused = document.activeElement as HTMLElement | null;
		const previousOverflow = document.body.style.overflow;
		document.body.style.overflow = 'hidden';

		const handleKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				close();
				return;
			}

			if (event.key === 'Tab') {
				const container = contentRef.current;
				if (!container) {
					return;
				}
				const focusables = Array.from(
					container.querySelectorAll<HTMLElement>(
						'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
					),
				).filter((el) => el.getClientRects().length > 0);
				if (focusables.length === 0) {
					event.preventDefault();
					return;
				}
				const first = focusables[0];
				const last = focusables[focusables.length - 1];
				const active = document.activeElement;

				if (event.shiftKey) {
					if (active === first || active === container || !container.contains(active)) {
						event.preventDefault();
						last.focus();
					}
				} else if (active === last || !container.contains(active)) {
					event.preventDefault();
					first.focus();
				}
			}
		};

		document.addEventListener('keydown', handleKeyDown);

		const contentEl = contentRef.current;
		if (contentEl) {
			contentEl.focus();
		}

		return () => {
			document.body.style.overflow = previousOverflow;
			document.removeEventListener('keydown', handleKeyDown);
			previouslyFocused?.focus();
		};
	}, [close, open]);

	if (!open || !portalContainer) {
		return null;
	}

	return createPortal(
		<>
			<AlertDialogOverlay />
			<div
				ref={setContentRef}
				role="alertdialog"
				aria-modal="true"
				aria-labelledby={titleId}
				aria-describedby={descriptionId}
				tabIndex={-1}
				data-state={getAlertDialogState(open)}
				data-size={size}
				className={`${styles[alertDialogStyleKeys.content]} ${className}`}
				{...props}>
				{children}
			</div>
		</>,
		portalContainer,
	);
});
AlertDialogContent.displayName = 'AlertDialogContent';

export interface AlertDialogHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDialogHeader = React.forwardRef<HTMLDivElement, AlertDialogHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[alertDialogStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AlertDialogHeader.displayName = 'AlertDialogHeader';

export interface AlertDialogFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDialogFooter = React.forwardRef<HTMLDivElement, AlertDialogFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[alertDialogStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AlertDialogFooter.displayName = 'AlertDialogFooter';

export interface AlertDialogTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {}

const AlertDialogTitle = React.forwardRef<HTMLHeadingElement, AlertDialogTitleProps>(({ className = '', children, ...props }, ref) => {
	const context = useAlertDialogContext();

	return (
		<h2 ref={ref} id={context.titleId} className={`${styles[alertDialogStyleKeys.title]} ${className}`} {...props}>
			{children}
		</h2>
	);
});
AlertDialogTitle.displayName = 'AlertDialogTitle';

export interface AlertDialogDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

const AlertDialogDescription = React.forwardRef<HTMLParagraphElement, AlertDialogDescriptionProps>(({ className = '', children, ...props }, ref) => {
	const context = useAlertDialogContext();

	return (
		<p ref={ref} id={context.descriptionId} className={`${styles[alertDialogStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
AlertDialogDescription.displayName = 'AlertDialogDescription';

export interface AlertDialogActionProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	variant?: ButtonVariant;
	size?: ButtonSize;
}

const AlertDialogAction = React.forwardRef<HTMLButtonElement, AlertDialogActionProps>(
	({ className = '', variant = 'default', size = 'default', children, onClick, ...props }, ref) => {
		const context = useAlertDialogContext();

		return (
			<Button
				ref={ref}
				type="button"
				variant={variant}
				size={size}
				className={className}
				onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
					onClick?.(event);
					context.close();
				}}
				{...props}>
				{children}
			</Button>
		);
	},
);
AlertDialogAction.displayName = 'AlertDialogAction';

export interface AlertDialogCancelProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	variant?: ButtonVariant;
	size?: ButtonSize;
}

const AlertDialogCancel = React.forwardRef<HTMLButtonElement, AlertDialogCancelProps>(
	({ className = '', variant = 'outline', size = 'default', children, onClick, ...props }, ref) => {
		const context = useAlertDialogContext();

		return (
			<Button
				ref={ref}
				type="button"
				variant={variant}
				size={size}
				className={className}
				onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
					onClick?.(event);
					context.close();
				}}
				{...props}>
				{children}
			</Button>
		);
	},
);
AlertDialogCancel.displayName = 'AlertDialogCancel';

export {
	AlertDialog,
	AlertDialogTrigger,
	AlertDialogOverlay,
	AlertDialogContent,
	AlertDialogHeader,
	AlertDialogFooter,
	AlertDialogTitle,
	AlertDialogDescription,
	AlertDialogAction,
	AlertDialogCancel,
};
export default AlertDialog;

// packages/vue/src/components/alert-dialog/alert-dialog.tsx
import {
	cloneVNode,
	computed,
	defineComponent,
	h,
	inject,
	nextTick,
	onBeforeUnmount,
	provide,
	ref,
	useId,
	watch,
	Teleport,
	type ComputedRef,
	type InjectionKey,
	type PropType,
} from 'vue';
import type { ButtonSize, ButtonVariant } from '@tile-ui/core';
import { alertDialogStyleKeys, getAlertDialogState } from '@tile-ui/core';
import type { AlertDialogSize } from '@tile-ui/core';
import { Button } from '../button';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/alert-dialog.module.scss';

interface AlertDialogContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	close: () => void;
	titleId: string;
	descriptionId: string;
}

type AlertDialogContext = ComputedRef<AlertDialogContextValue>;

const AlertDialogContextKey: InjectionKey<AlertDialogContext> = Symbol('tile-alert-dialog');

function composeEventHandlers(...handlers: Array<unknown>): (event: Event) => void {
	return (event: Event) => {
		for (const handler of handlers) {
			if (!handler) {
				continue;
			}

			const list = Array.isArray(handler) ? handler : [handler];

			for (const item of list) {
				if (typeof item === 'function') {
					item(event);
				}
			}
		}
	};
}

export const AlertDialog = defineComponent({
	name: 'AlertDialog',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const baseId = useId();
		const titleId = `${baseId}-title`;
		const descriptionId = `${baseId}-description`;

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}

			emit('update:open', next);
		}

		function close() {
			setOpen(false);
		}

		const context = computed<AlertDialogContextValue>(() => ({
			open: isOpen.value,
			setOpen,
			close,
			titleId,
			descriptionId,
		}));

		provide(AlertDialogContextKey, context);

		return () => slots.default?.();
	},
});

export const AlertDialogTrigger = defineComponent({
	name: 'AlertDialogTrigger',
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogTrigger must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;

		function handleOpen() {
			context.value.setOpen(true);
		}

		return () => {
			const children = slots.default?.();
			const attrOnClick = (attrs as Record<string, unknown>).onClick;

			if (props.asChild) {
				const firstChild = Array.isArray(children) ? children[0] : children;

				if (firstChild) {
					const childProps = (firstChild.props ?? {}) as Record<string, unknown>;
					return cloneVNode(firstChild, {
						...attrs,
						onClick: composeEventHandlers(attrOnClick, childProps.onClick, handleOpen),
					});
				}
			}

			return h('button', { type: 'button', ...attrs, onClick: composeEventHandlers(attrOnClick, handleOpen) }, children);
		};
	},
});

export const AlertDialogOverlay = defineComponent({
	name: 'AlertDialogOverlay',
	setup(_props, { slots, attrs }) {
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogOverlay must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;

		return () => {
			if (!context.value.open) {
				return null;
			}

			return h(
				'div',
				{
					...attrs,
					'data-state': getAlertDialogState(context.value.open),
					class: [styles[alertDialogStyleKeys.overlay], attrs.class],
					onClick: composeEventHandlers((attrs as Record<string, unknown>).onClick, () => context.value.close()),
				},
				slots.default?.(),
			);
		};
	},
});

export const AlertDialogContent = defineComponent({
	name: 'AlertDialogContent',
	props: {
		size: {
			type: String as PropType<AlertDialogSize>,
			default: 'default',
		},
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots, attrs }) {
		const portalContainer = usePortalContainer(() => props.container);
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogContent must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;
		const contentRef = ref<HTMLElement | null>(null);
		const previousOverflow = ref('');
		let previouslyFocused: HTMLElement | null = null;

		function handleKeyDown(event: KeyboardEvent) {
			if (event.key === 'Escape') {
				context.value.close();
				return;
			}

			if (event.key === 'Tab') {
				const container = contentRef.value;
				if (!container) {
					return;
				}
				const focusables = Array.from(
					container.querySelectorAll<HTMLElement>(
						'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
					),
				).filter((el) => el.getClientRects().length > 0);
				if (focusables.length === 0) {
					event.preventDefault();
					return;
				}
				const first = focusables[0];
				const last = focusables[focusables.length - 1];
				const active = document.activeElement;

				if (event.shiftKey) {
					if (active === first || active === container || !container.contains(active)) {
						event.preventDefault();
						last.focus();
					}
				} else if (active === last || !container.contains(active)) {
					event.preventDefault();
					first.focus();
				}
			}
		}

		watch(
			() => context.value.open,
			(open) => {
				if (typeof document === 'undefined') {
					return;
				}

				if (open) {
					previouslyFocused = document.activeElement as HTMLElement | null;
					previousOverflow.value = document.body.style.overflow;
					document.body.style.overflow = 'hidden';
					document.addEventListener('keydown', handleKeyDown);
					nextTick(() => {
						contentRef.value?.focus();
					});
				} else {
					document.removeEventListener('keydown', handleKeyDown);
					document.body.style.overflow = previousOverflow.value;
					previouslyFocused?.focus();
				}
			},
			{ immediate: true },
		);

		onBeforeUnmount(() => {
			document.removeEventListener('keydown', handleKeyDown);
			document.body.style.overflow = previousOverflow.value;
			previouslyFocused?.focus();
		});

		return () => {
			if (!context.value.open) {
				return null;
			}

			const userClass = attrs.class;
			const contentAttrs = { ...attrs };
			delete contentAttrs.class;

			return h(Teleport, { to: portalContainer.value }, [
				h('div', {
					'data-state': getAlertDialogState(context.value.open),
					class: styles[alertDialogStyleKeys.overlay],
					onClick: () => context.value.close(),
				}),
				h(
					'div',
					{
						...contentAttrs,
						ref: contentRef,
						role: 'alertdialog',
						'aria-modal': 'true',
						'aria-labelledby': context.value.titleId,
						'aria-describedby': context.value.descriptionId,
						tabindex: -1,
						'data-state': getAlertDialogState(context.value.open),
						'data-size': props.size,
						class: [styles[alertDialogStyleKeys.content], userClass],
					},
					slots.default?.(),
				),
			]);
		};
	},
});

export const AlertDialogHeader = defineComponent({
	name: 'AlertDialogHeader',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, class: [styles[alertDialogStyleKeys.header], attrs.class] }, slots.default?.());
	},
});

export const AlertDialogFooter = defineComponent({
	name: 'AlertDialogFooter',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, class: [styles[alertDialogStyleKeys.footer], attrs.class] }, slots.default?.());
	},
});

export const AlertDialogTitle = defineComponent({
	name: 'AlertDialogTitle',
	setup(_props, { slots, attrs }) {
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogTitle must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;

		return () => h('h2', { ...attrs, id: context.value.titleId, class: [styles[alertDialogStyleKeys.title], attrs.class] }, slots.default?.());
	},
});

export const AlertDialogDescription = defineComponent({
	name: 'AlertDialogDescription',
	setup(_props, { slots, attrs }) {
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogDescription must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;

		return () => h('p', { ...attrs, id: context.value.descriptionId, class: [styles[alertDialogStyleKeys.description], attrs.class] }, slots.default?.());
	},
});

export const AlertDialogAction = defineComponent({
	name: 'AlertDialogAction',
	props: {
		variant: {
			type: String as PropType<ButtonVariant>,
			default: 'default',
		},
		size: {
			type: String as PropType<ButtonSize>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogAction must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;

		function handleAction() {
			context.value.close();
		}

		return () =>
			h(
				Button,
				{
					...attrs,
					type: 'button',
					variant: props.variant,
					size: props.size,
					onClick: composeEventHandlers((attrs as Record<string, unknown>).onClick, handleAction),
				},
				{ default: () => slots.default?.() },
			);
	},
});

export const AlertDialogCancel = defineComponent({
	name: 'AlertDialogCancel',
	props: {
		variant: {
			type: String as PropType<ButtonVariant>,
			default: 'outline',
		},
		size: {
			type: String as PropType<ButtonSize>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(AlertDialogContextKey);
		if (!contextValue) {
			throw new Error('AlertDialogCancel must be used within <AlertDialog>.');
		}
		const context: AlertDialogContext = contextValue;

		function handleCancel() {
			context.value.close();
		}

		return () =>
			h(
				Button,
				{
					...attrs,
					type: 'button',
					variant: props.variant,
					size: props.size,
					onClick: composeEventHandlers((attrs as Record<string, unknown>).onClick, handleCancel),
				},
				{ default: () => slots.default?.() },
			);
	},
});

export default AlertDialog;
