// packages/vue/src/components/alert/alert.tsx
import { computed, defineComponent, h, type PropType } from 'vue';
import { alertStyleKeys, getAlertStyleKeys } from '@tile-ui/core';
import type { AlertVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/alert.module.scss';

export const Alert = defineComponent({
	name: 'Alert',
	props: {
		variant: {
			type: String as PropType<AlertVariant>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const styleKeys = computed(() => getAlertStyleKeys(props.variant));
		const classes = computed(() => [styles[styleKeys.value.base], styles[styleKeys.value.variant], attrs.class]);

		return () => h('div', { ...attrs, role: 'alert', 'data-slot': 'alert', 'data-variant': props.variant, class: classes.value }, slots.default?.());
	},
});

export const AlertTitle = defineComponent({
	name: 'AlertTitle',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'alert-title', class: [styles[alertStyleKeys.title], attrs.class] }, slots.default?.());
	},
});

export const AlertDescription = defineComponent({
	name: 'AlertDescription',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'alert-description', class: [styles[alertStyleKeys.description], attrs.class] }, slots.default?.());
	},
});

export default Alert;

// packages/react/src/components/alert/alert.tsx
import React from 'react';
import { alertStyleKeys, getAlertStyleKeys } from '@tile-ui/core';
import type { AlertBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/alert.module.scss';

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement>, AlertBaseProps {}

const Alert = React.forwardRef<HTMLDivElement, AlertProps>(({ className = '', variant = 'default', children, ...props }, ref) => {
	const styleKeys = getAlertStyleKeys(variant);
	const classes = [styles[styleKeys.base], styles[styleKeys.variant], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} role="alert" data-slot="alert" data-variant={variant} className={classes} {...props}>
			{children}
		</div>
	);
});
Alert.displayName = 'Alert';

export interface AlertTitleProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertTitle = React.forwardRef<HTMLDivElement, AlertTitleProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="alert-title" className={`${styles[alertStyleKeys.title]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AlertTitle.displayName = 'AlertTitle';

export interface AlertDescriptionProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDescription = React.forwardRef<HTMLDivElement, AlertDescriptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="alert-description" className={`${styles[alertStyleKeys.description]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AlertDescription.displayName = 'AlertDescription';

export { Alert, AlertTitle, AlertDescription };
export default Alert;
