// packages/vue/src/components/progress/progress.tsx
import { defineComponent, computed, h } from 'vue';
import { getProgressOffset, progressStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/progress.module.scss';

export const TProgress = defineComponent({
	name: 'TProgress',
	props: {
		value: { type: Number, default: 0 },
		min: { type: Number, default: 0 },
		max: { type: Number, default: 100 },
	},
	setup(props) {
		const offset = computed(() => getProgressOffset(props.value, props.min, props.max));

		return () =>
			h(
				'div',
				{
					role: 'progressbar',
					'aria-valuemin': props.min,
					'aria-valuemax': props.max,
					'aria-valuenow': props.value,
					class: styles[progressStyleKeys.root],
				},
				[h('div', { class: styles[progressStyleKeys.indicator], style: { transform: `translateX(-${100 - offset.value}%)` } })],
			);
	},
});

export default TProgress;

// packages/react/src/components/progress/progress.tsx
import React from 'react';
import { getProgressOffset, progressStyleKeys } from '@tile-ui/core';
import type { ProgressBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/progress.module.scss';

export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement>, ProgressBaseProps {}

const Progress = React.forwardRef<HTMLDivElement, ProgressProps>(({ className = '', value = 0, min = 0, max = 100, ...props }, ref) => {
	const offset = getProgressOffset(value, min, max);

	return (
		<div ref={ref} role="progressbar" aria-valuemin={min} aria-valuemax={max} aria-valuenow={value} className={`${styles[progressStyleKeys.root]} ${className}`} {...props}>
			<div className={styles[progressStyleKeys.indicator]} style={{ transform: `translateX(-${100 - offset}%)` }} />
		</div>
	);
});

Progress.displayName = 'Progress';

export { Progress };
export default Progress;
