// apps/solid/src/components/component-demo.tsx
import { Show } from 'solid-js';
import { solidDemoRegistry } from '../../components/demos';
import { previewCodeMap } from '../generated/preview-code';
import { ComponentPreview } from './component-preview';
import { DemoVariants } from './demo-variants';

export function ComponentDemo(props: { slug: string }) {
	return (
		<Show when={solidDemoRegistry[props.slug]} keyed>
			{(entry) => (
				<Show
					when={entry.variants?.length ? entry.variants : undefined}
					keyed
					fallback={
						<ComponentPreview code={previewCodeMap[props.slug]}>
							<entry.Component />
						</ComponentPreview>
					}>
					{(variants) => <DemoVariants slug={props.slug} title={entry.title} variants={variants} />}
				</Show>
			)}
		</Show>
	);
}

// apps/react/components/component-demo.tsx
'use client';

import { ComponentPreview, PreviewCodeProvider } from '@/components/component-preview';
import { demoRegistry } from '@/components/demos';
import { previewCodeMap } from '@/lib/preview-code';
import { DemoVariants } from './demo-variants';

export function ComponentDemo({ slug }: { slug: string }) {
	const demo = demoRegistry[slug];

	if (!demo) {
		return null;
	}
	if (demo.variants?.length) return <DemoVariants key={slug} slug={slug} title={demo.title} variants={demo.variants} />;

	return (
		<PreviewCodeProvider value={previewCodeMap[slug] ?? null}>
			<ComponentPreview title={demo.title} description={demo.description}>
				<demo.Component />
			</ComponentPreview>
		</PreviewCodeProvider>
	);
}
