// packages/vue/src/components/button-group/button-group.tsx
import { cloneVNode, computed, defineComponent, h, type PropType } from 'vue';
import { buttonGroupStyleKeys, getButtonGroupStyleKeys } from '@tile-ui/core';
import type { ButtonGroupOrientation } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/button-group.module.scss';

export const ButtonGroup = defineComponent({
	name: 'ButtonGroup',
	props: {
		orientation: {
			type: String as PropType<ButtonGroupOrientation>,
			default: 'horizontal',
		},
	},
	setup(props, { slots, attrs }) {
		const styleKeys = computed(() => getButtonGroupStyleKeys(props.orientation));
		const rootClass = computed(() => [styles[styleKeys.value.base], styles[styleKeys.value.orientation]]);

		return () =>
			h('div', { ...attrs, role: 'group', 'data-slot': 'button-group', 'data-orientation': props.orientation, class: [...rootClass.value, attrs.class] }, slots.default?.());
	},
});

export const ButtonGroupText = defineComponent({
	name: 'ButtonGroupText',
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		return () => {
			const children = slots.default?.();

			if (props.asChild) {
				const firstChild = Array.isArray(children) ? children[0] : children;

				if (firstChild) {
					const childProps = (firstChild.props ?? {}) as { class?: unknown };
					return cloneVNode(firstChild, {
						...attrs,
						'data-slot': 'button-group-text',
						class: [styles[buttonGroupStyleKeys.text], attrs.class, childProps.class].filter(Boolean),
					});
				}
			}

			return h('div', { ...attrs, 'data-slot': 'button-group-text', class: [styles[buttonGroupStyleKeys.text], attrs.class] }, children);
		};
	},
});

export const ButtonGroupSeparator = defineComponent({
	name: 'ButtonGroupSeparator',
	props: {
		orientation: {
			type: String as PropType<ButtonGroupOrientation>,
			default: 'vertical',
		},
	},
	setup(props, { attrs }) {
		return () =>
			h('div', {
				...attrs,
				role: 'none',
				'aria-hidden': 'true',
				'data-slot': 'button-group-separator',
				'data-orientation': props.orientation,
				class: [styles[buttonGroupStyleKeys.separator], attrs.class],
			});
	},
});

export default ButtonGroup;

// packages/react/src/components/button-group/button-group.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { buttonGroupStyleKeys, getButtonGroupStyleKeys } from '@tile-ui/core';
import type { ButtonGroupBaseProps, ButtonGroupTextBaseProps, ButtonGroupSeparatorBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/button-group.module.scss';

export interface ButtonGroupProps extends React.HTMLAttributes<HTMLDivElement>, ButtonGroupBaseProps {}

const ButtonGroup = React.forwardRef<HTMLDivElement, ButtonGroupProps>(({ className = '', orientation = 'horizontal', children, ...props }, ref) => {
	const styleKeys = getButtonGroupStyleKeys(orientation);
	const classes = [styles[styleKeys.base], styles[styleKeys.orientation], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} role="group" data-slot="button-group" data-orientation={orientation} className={classes} {...props}>
			{children}
		</div>
	);
});
ButtonGroup.displayName = 'ButtonGroup';

export interface ButtonGroupTextProps extends React.HTMLAttributes<HTMLDivElement>, ButtonGroupTextBaseProps {}

const ButtonGroupText = React.forwardRef<HTMLDivElement, ButtonGroupTextProps>(({ className = '', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'div';

	return (
		<Comp ref={ref} className={`${styles[buttonGroupStyleKeys.text]} ${className}`} {...props}>
			{children}
		</Comp>
	);
});
ButtonGroupText.displayName = 'ButtonGroupText';

export interface ButtonGroupSeparatorProps extends React.HTMLAttributes<HTMLDivElement>, ButtonGroupSeparatorBaseProps {}

const ButtonGroupSeparator = React.forwardRef<HTMLDivElement, ButtonGroupSeparatorProps>(({ className = '', orientation = 'vertical', ...props }, ref) => {
	return (
		<div
			ref={ref}
			role="none"
			aria-hidden="true"
			data-slot="button-group-separator"
			data-orientation={orientation}
			className={`${styles[buttonGroupStyleKeys.separator]} ${className}`}
			{...props}
		/>
	);
});
ButtonGroupSeparator.displayName = 'ButtonGroupSeparator';

export { ButtonGroup, ButtonGroupText, ButtonGroupSeparator };
export default ButtonGroup;
