// packages/react/src/components/alert-dialog/alert-dialog.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import type { ButtonSize, ButtonVariant } from '@tile-ui/core';
import { alertDialogStyleKeys, getAlertDialogState } from '@tile-ui/core';
import type { AlertDialogBaseProps, AlertDialogSize } from '@tile-ui/core';
import { Button } from '../button';
import styles from '@tile-ui/styles/scss/components/alert-dialog.module.scss';

interface AlertDialogContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	close: () => void;
	titleId: string;
	descriptionId: string;
}

const AlertDialogContext = createContext<AlertDialogContextValue | null>(null);

function useAlertDialogContext(): AlertDialogContextValue {
	const context = useContext(AlertDialogContext);
	if (!context) {
		throw new Error('AlertDialog sub-components must be used within <AlertDialog>.');
	}
	return context;
}

export interface AlertDialogProps extends AlertDialogBaseProps {
	open?: boolean;
	defaultOpen?: boolean;
	onOpenChange?: (open: boolean) => void;
	children?: React.ReactNode;
}

function AlertDialog({ open, defaultOpen = false, onOpenChange, children }: AlertDialogProps) {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const onOpenChangeRef = useRef(onOpenChange);

	useEffect(() => {
		onOpenChangeRef.current = onOpenChange;
	});

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}

			onOpenChangeRef.current?.(next);
		},
		[open],
	);

	const close = useCallback(() => {
		setOpen(false);
	}, [setOpen]);

	const isOpen = open !== undefined ? open : internalOpen;
	const titleId = useId();
	const descriptionId = useId();

	return <AlertDialogContext.Provider value={{ open: isOpen, setOpen, close, titleId, descriptionId }}>{children}</AlertDialogContext.Provider>;
}

AlertDialog.displayName = 'AlertDialog';

export interface AlertDialogTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	asChild?: boolean;
}

const AlertDialogTrigger = React.forwardRef<HTMLButtonElement, AlertDialogTriggerProps>(({ asChild = false, className = '', children, onClick, ...props }, ref) => {
	const context = useAlertDialogContext();
	const Comp = asChild ? Slot : 'button';

	return (
		<Comp
			ref={ref}
			type={asChild ? undefined : 'button'}
			className={className}
			onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
				onClick?.(event);
				context.setOpen(true);
			}}
			{...props}>
			{children}
		</Comp>
	);
});
AlertDialogTrigger.displayName = 'AlertDialogTrigger';

export interface AlertDialogOverlayProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDialogOverlay = React.forwardRef<HTMLDivElement, AlertDialogOverlayProps>(({ className = '', onClick, ...props }, ref) => {
	const context = useAlertDialogContext();

	if (!context.open) {
		return null;
	}

	return (
		<div
			ref={ref}
			data-state={getAlertDialogState(context.open)}
			className={`${styles[alertDialogStyleKeys.overlay]} ${className}`}
			onClick={(event: React.MouseEvent<HTMLDivElement>) => {
				onClick?.(event);
				context.close();
			}}
			{...props}
		/>
	);
});
AlertDialogOverlay.displayName = 'AlertDialogOverlay';

export interface AlertDialogContentProps extends React.HTMLAttributes<HTMLDivElement> {
	size?: AlertDialogSize;
}

const AlertDialogContent = React.forwardRef<HTMLDivElement, AlertDialogContentProps>(({ className = '', size = 'default', children, ...props }, ref) => {
	const { open, close, titleId, descriptionId } = useAlertDialogContext();
	const contentRef = useRef<HTMLDivElement | null>(null);

	function setContentRef(element: HTMLDivElement | null) {
		contentRef.current = element;

		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	useLayoutEffect(() => {
		if (!open) {
			return;
		}

		const previouslyFocused = document.activeElement as HTMLElement | null;
		const previousOverflow = document.body.style.overflow;
		document.body.style.overflow = 'hidden';

		const handleKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				close();
			}
		};

		document.addEventListener('keydown', handleKeyDown);

		const contentEl = contentRef.current;
		if (contentEl) {
			contentEl.focus();
		}

		return () => {
			document.body.style.overflow = previousOverflow;
			document.removeEventListener('keydown', handleKeyDown);
			previouslyFocused?.focus();
		};
	}, [close, open]);

	if (!open) {
		return null;
	}

	return createPortal(
		<>
			<AlertDialogOverlay />
			<div
				ref={setContentRef}
				role="alertdialog"
				aria-modal="true"
				aria-labelledby={titleId}
				aria-describedby={descriptionId}
				tabIndex={-1}
				data-state={getAlertDialogState(open)}
				data-size={size}
				className={`${styles[alertDialogStyleKeys.content]} ${className}`}
				{...props}>
				{children}
			</div>
		</>,
		document.body,
	);
});
AlertDialogContent.displayName = 'AlertDialogContent';

export interface AlertDialogHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDialogHeader = React.forwardRef<HTMLDivElement, AlertDialogHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[alertDialogStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AlertDialogHeader.displayName = 'AlertDialogHeader';

export interface AlertDialogFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const AlertDialogFooter = React.forwardRef<HTMLDivElement, AlertDialogFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[alertDialogStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AlertDialogFooter.displayName = 'AlertDialogFooter';

export interface AlertDialogTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {}

const AlertDialogTitle = React.forwardRef<HTMLHeadingElement, AlertDialogTitleProps>(({ className = '', children, ...props }, ref) => {
	const context = useAlertDialogContext();

	return (
		<h2 ref={ref} id={context.titleId} className={`${styles[alertDialogStyleKeys.title]} ${className}`} {...props}>
			{children}
		</h2>
	);
});
AlertDialogTitle.displayName = 'AlertDialogTitle';

export interface AlertDialogDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

const AlertDialogDescription = React.forwardRef<HTMLParagraphElement, AlertDialogDescriptionProps>(({ className = '', children, ...props }, ref) => {
	const context = useAlertDialogContext();

	return (
		<p ref={ref} id={context.descriptionId} className={`${styles[alertDialogStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
AlertDialogDescription.displayName = 'AlertDialogDescription';

export interface AlertDialogActionProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	variant?: ButtonVariant;
	size?: ButtonSize;
}

const AlertDialogAction = React.forwardRef<HTMLButtonElement, AlertDialogActionProps>(
	({ className = '', variant = 'default', size = 'default', children, onClick, ...props }, ref) => {
		const context = useAlertDialogContext();

		return (
			<Button
				ref={ref}
				type="button"
				variant={variant}
				size={size}
				className={className}
				onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
					onClick?.(event);
					context.close();
				}}
				{...props}>
				{children}
			</Button>
		);
	},
);
AlertDialogAction.displayName = 'AlertDialogAction';

export interface AlertDialogCancelProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	variant?: ButtonVariant;
	size?: ButtonSize;
}

const AlertDialogCancel = React.forwardRef<HTMLButtonElement, AlertDialogCancelProps>(
	({ className = '', variant = 'outline', size = 'default', children, onClick, ...props }, ref) => {
		const context = useAlertDialogContext();

		return (
			<Button
				ref={ref}
				type="button"
				variant={variant}
				size={size}
				className={className}
				onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
					onClick?.(event);
					context.close();
				}}
				{...props}>
				{children}
			</Button>
		);
	},
);
AlertDialogCancel.displayName = 'AlertDialogCancel';

export {
	AlertDialog,
	AlertDialogTrigger,
	AlertDialogOverlay,
	AlertDialogContent,
	AlertDialogHeader,
	AlertDialogFooter,
	AlertDialogTitle,
	AlertDialogDescription,
	AlertDialogAction,
	AlertDialogCancel,
};
export default AlertDialog;

// packages/solid/src/components/alert-dialog/alert-dialog.tsx
import { Show, createContext, createEffect, createSignal, createUniqueId, onCleanup, onMount, splitProps, useContext, type Accessor, type JSX, type ParentProps } from 'solid-js';
import { Portal } from 'solid-js/web';
import { alertDialogStyleKeys, getAlertDialogState, type AlertDialogBaseProps, type AlertDialogSize, type ButtonSize, type ButtonVariant } from '@tile-ui/core';
import {
	PortalScopeContext,
	activateModalFocusScope,
	composeRefs,
	createCompositeIdRegistry,
	createPortalScope,
	invokeEventHandler,
	isNodeValue,
	registerDismissableLayer,
	resolvePortalContainer,
	type CallbackRef,
	type DismissableLayerEvent,
	type DismissableLayerOutsideEvent,
} from '../../utils';
import { Button } from '../button';
import styles from '@tile-ui/styles/scss/components/alert-dialog.module.scss';

interface AlertDialogContextValue {
	open: Accessor<boolean>;
	setOpen: (open: boolean) => void;
	contentId: Accessor<string | undefined>;
	titleId: Accessor<string | undefined>;
	descriptionId: Accessor<string | undefined>;
	trigger: Accessor<HTMLButtonElement | undefined>;
	setTrigger: (element: HTMLButtonElement) => void;
	contentMounted: Accessor<boolean>;
	setContentMounted: (mounted: boolean) => void;
	registerContentId: (id?: string) => () => void;
	registerTitleId: (id?: string) => () => void;
	registerDescriptionId: (id?: string) => () => void;
	cancel: Accessor<HTMLButtonElement | undefined>;
	setCancel: (element: HTMLButtonElement) => void;
}

const AlertDialogContext = createContext<AlertDialogContextValue>();

function useAlertDialogContext() {
	const context = useContext(AlertDialogContext);
	if (!context) throw new Error('AlertDialog 子组件必须位于 <AlertDialog> 内部。');
	return context;
}

export interface AlertDialogProps extends AlertDialogBaseProps {
	open?: boolean;
	defaultOpen?: boolean;
	onOpenChange?: (open: boolean) => void;
	children?: JSX.Element;
}

export function AlertDialog(props: AlertDialogProps) {
	const [internalOpen, setInternalOpen] = createSignal(props.defaultOpen ?? false);
	const [trigger, setTrigger] = createSignal<HTMLButtonElement>();
	const [cancel, setCancel] = createSignal<HTMLButtonElement>();
	const [contentMounted, setContentMounted] = createSignal(false);
	const ids = createCompositeIdRegistry(`tile-solid-alert-dialog-${createUniqueId()}`);
	const open = () => props.open ?? internalOpen();
	const setOpen = (next: boolean) => {
		if (next === open()) return;
		if (props.open === undefined) setInternalOpen(next);
		props.onOpenChange?.(next);
	};
	const value: AlertDialogContextValue = {
		open,
		setOpen,
		contentId: ids.id('content'),
		titleId: ids.id('title'),
		descriptionId: ids.id('description'),
		trigger,
		setTrigger,
		contentMounted,
		setContentMounted,
		registerContentId: (id) => ids.register('content', id),
		registerTitleId: (id) => ids.register('title', id),
		registerDescriptionId: (id) => ids.register('description', id),
		cancel,
		setCancel,
	};
	return <AlertDialogContext.Provider value={value}>{props.children}</AlertDialogContext.Provider>;
}

export interface AlertDialogTriggerProps extends Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, 'ref'> {
	ref?: CallbackRef<HTMLButtonElement>;
}

export function AlertDialogTrigger(props: ParentProps<AlertDialogTriggerProps>) {
	const context = useAlertDialogContext();
	const [local, rest] = splitProps(props, ['children', 'onClick', 'type', 'ref']);
	return (
		<button
			{...rest}
			ref={composeRefs(local.ref, context.setTrigger)}
			type={local.type ?? 'button'}
			aria-haspopup="dialog"
			aria-expanded={context.open()}
			aria-controls={context.open() && context.contentMounted() ? context.contentId() : undefined}
			onClick={(event) => {
				invokeEventHandler(local.onClick, event);
				if (!event.defaultPrevented) context.setOpen(true);
			}}>
			{local.children}
		</button>
	);
}

export interface AlertDialogOverlayProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'ref'> {
	ref?: CallbackRef<HTMLDivElement>;
}

export function AlertDialogOverlay(props: AlertDialogOverlayProps) {
	const context = useAlertDialogContext();
	const [local, rest] = splitProps(props, ['class', 'ref']);
	return (
		<Show when={context.open()}>
			<div {...rest} ref={local.ref} data-state={getAlertDialogState(context.open())} class={`${styles[alertDialogStyleKeys.overlay]} ${local.class ?? ''}`} />
		</Show>
	);
}

export interface AlertDialogContentProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'ref'> {
	ref?: CallbackRef<HTMLDivElement>;
	size?: AlertDialogSize;
	container?: Node;
	overlayClass?: string;
	onEscapeKeyDown?: (event: DismissableLayerEvent<KeyboardEvent>) => void;
	onPointerDownOutside?: (event: DismissableLayerEvent<PointerEvent>) => void;
	onFocusOutside?: (event: DismissableLayerEvent<FocusEvent>) => void;
	onInteractOutside?: (event: DismissableLayerEvent<DismissableLayerOutsideEvent>) => void;
}

export function AlertDialogContent(props: ParentProps<AlertDialogContentProps>) {
	const context = useAlertDialogContext();
	const parentScope = useContext(PortalScopeContext);
	const scope = createPortalScope(() => resolvePortalContainer(parentScope, props.container), parentScope);
	const [content, setContent] = createSignal<HTMLDivElement>();
	const [portalReady, setPortalReady] = createSignal(false);
	const [local, rest] = splitProps(props, [
		'children',
		'class',
		'ref',
		'id',
		'size',
		'container',
		'overlayClass',
		'aria-label',
		'aria-labelledby',
		'aria-describedby',
		'onEscapeKeyDown',
		'onPointerDownOutside',
		'onFocusOutside',
		'onInteractOutside',
	]);
	const contentId = () => local.id ?? context.contentId();
	onMount(() => {
		const timeout = window.setTimeout(() => {
			context.setContentMounted(true);
			setPortalReady(true);
		}, 0);
		onCleanup(() => {
			window.clearTimeout(timeout);
			context.setContentMounted(false);
		});
	});
	createEffect(() => onCleanup(context.registerContentId(local.id)));

	createEffect(() => {
		const element = content();
		if (!context.open() || !element) return;
		const removeBranch = scope.addBranch(element);
		const document = element.ownerDocument;
		const blockOutsideClick = (event: MouseEvent) => {
			const target = event.target;
			if (!isNodeValue(target)) return;
			const roots = [element, ...scope.getBranches()];
			if (roots.some((root) => root === target || root.contains(target))) return;
			if (event.cancelable) event.preventDefault();
			event.stopImmediatePropagation();
		};
		document.addEventListener('click', blockOutsideClick, true);
		const dismiss = registerDismissableLayer({
			element: content,
			portalScope: scope,
			modal: true,
			onEscapeKeyDown: local.onEscapeKeyDown,
			onPointerDownOutside: (event) => {
				local.onPointerDownOutside?.(event);
				const originalEvent = event.originalEvent;
				if (originalEvent.cancelable) originalEvent.preventDefault();
				event.preventDefault();
			},
			onFocusOutside: (event) => {
				local.onFocusOutside?.(event);
				if (!event.defaultPrevented) event.preventDefault();
			},
			onInteractOutside: local.onInteractOutside,
			onDismiss: () => context.setOpen(false),
		});
		const focus = activateModalFocusScope({ container: content, portalScope: scope, initialFocus: () => context.cancel(), restoreFocus: context.trigger });
		dismiss.update();
		focus.update();
		onCleanup(() => {
			document.removeEventListener('click', blockOutsideClick, true);
			dismiss.destroy();
			focus.destroy();
			removeBranch();
		});
	});

	return (
		<Show when={context.open() && portalReady()}>
			<Portal mount={scope.container()}>
				<PortalScopeContext.Provider value={scope}>
					<AlertDialogOverlay class={local.overlayClass} />
					<div
						{...rest}
						ref={composeRefs(local.ref, setContent)}
						id={contentId()}
						role="alertdialog"
						aria-modal="true"
						aria-label={local['aria-label']}
						aria-labelledby={local['aria-labelledby'] ?? (local['aria-label'] ? undefined : context.titleId())}
						aria-describedby={local['aria-describedby'] ?? context.descriptionId()}
						tabIndex={-1}
						data-state={getAlertDialogState(context.open())}
						data-size={local.size ?? 'default'}
						class={`${styles[alertDialogStyleKeys.content]} ${local.class ?? ''}`}>
						{local.children}
					</div>
				</PortalScopeContext.Provider>
			</Portal>
		</Show>
	);
}

export interface AlertDialogHeaderProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'ref'> {
	ref?: CallbackRef<HTMLDivElement>;
}

export function AlertDialogHeader(props: ParentProps<AlertDialogHeaderProps>) {
	const [local, rest] = splitProps(props, ['children', 'class', 'ref']);
	return (
		<div {...rest} ref={local.ref} class={`${styles[alertDialogStyleKeys.header]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export interface AlertDialogFooterProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'ref'> {
	ref?: CallbackRef<HTMLDivElement>;
}

export function AlertDialogFooter(props: ParentProps<AlertDialogFooterProps>) {
	const [local, rest] = splitProps(props, ['children', 'class', 'ref']);
	return (
		<div {...rest} ref={local.ref} class={`${styles[alertDialogStyleKeys.footer]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}

export interface AlertDialogTitleProps extends Omit<JSX.HTMLAttributes<HTMLHeadingElement>, 'ref'> {
	ref?: CallbackRef<HTMLHeadingElement>;
}

export function AlertDialogTitle(props: ParentProps<AlertDialogTitleProps>) {
	const context = useAlertDialogContext();
	const [local, rest] = splitProps(props, ['children', 'class', 'ref', 'id']);
	const id = () => local.id ?? `${context.contentId()}-title`;
	createEffect(() => onCleanup(context.registerTitleId(id())));
	return (
		<h2 {...rest} ref={local.ref} id={id()} class={`${styles[alertDialogStyleKeys.title]} ${local.class ?? ''}`}>
			{local.children}
		</h2>
	);
}

export interface AlertDialogDescriptionProps extends Omit<JSX.HTMLAttributes<HTMLParagraphElement>, 'ref'> {
	ref?: CallbackRef<HTMLParagraphElement>;
}

export function AlertDialogDescription(props: ParentProps<AlertDialogDescriptionProps>) {
	const context = useAlertDialogContext();
	const [local, rest] = splitProps(props, ['children', 'class', 'ref', 'id']);
	const id = () => local.id ?? `${context.contentId()}-description`;
	createEffect(() => onCleanup(context.registerDescriptionId(id())));
	return (
		<p {...rest} ref={local.ref} id={id()} class={`${styles[alertDialogStyleKeys.description]} ${local.class ?? ''}`}>
			{local.children}
		</p>
	);
}

export interface AlertDialogActionProps extends Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, 'ref' | 'size'> {
	ref?: CallbackRef<HTMLButtonElement>;
	variant?: ButtonVariant;
	size?: ButtonSize;
}

export function AlertDialogAction(props: ParentProps<AlertDialogActionProps>) {
	const context = useAlertDialogContext();
	const [local, rest] = splitProps(props, ['children', 'ref', 'onClick', 'variant', 'size', 'type']);
	return (
		<Button
			{...rest}
			ref={local.ref}
			type={local.type ?? 'button'}
			variant={local.variant}
			size={local.size}
			onClick={(event) => {
				invokeEventHandler(local.onClick, event);
				if (!event.defaultPrevented) context.setOpen(false);
			}}>
			{local.children}
		</Button>
	);
}

export interface AlertDialogCancelProps extends AlertDialogActionProps {}

export function AlertDialogCancel(props: ParentProps<AlertDialogCancelProps>) {
	const context = useAlertDialogContext();
	const [local, rest] = splitProps(props, ['children', 'ref', 'onClick', 'variant', 'size', 'type']);
	return (
		<Button
			{...rest}
			ref={composeRefs(local.ref, context.setCancel)}
			type={local.type ?? 'button'}
			variant={local.variant ?? 'outline'}
			size={local.size}
			onClick={(event) => {
				invokeEventHandler(local.onClick, event);
				if (!event.defaultPrevented) context.setOpen(false);
			}}>
			{local.children}
		</Button>
	);
}

export default AlertDialog;
