// packages/react/src/components/slider/slider.tsx
import React, { createContext, useContext, useState } from 'react';
import { clampSliderValue, getSliderOffsetStyle, getSliderPercent, sliderStyleKeys } from '@tile-ui/core';
import type { SliderBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/slider.module.scss';

interface SliderContextValue {
	value: number;
	min: number;
	max: number;
	step: number;
	orientation: 'horizontal' | 'vertical';
	disabled: boolean;
	setValue: (value: number) => void;
}

const SliderContext = createContext<SliderContextValue | null>(null);

function useSliderContext(): SliderContextValue {
	const context = useContext(SliderContext);
	if (!context) {
		throw new Error('Slider sub-components must be used within <Slider>.');
	}
	return context;
}

export interface SliderProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'value' | 'defaultValue'>, SliderBaseProps {}

const Slider = React.forwardRef<HTMLDivElement, SliderProps>(
	({ className = '', value, defaultValue = 0, min = 0, max = 100, step = 1, orientation = 'horizontal', disabled = false, onValueChange, children, ...props }, ref) => {
		const [internalValue, setInternalValue] = useState(defaultValue);
		const currentValue = value !== undefined ? value : internalValue;
		const clampedValue = clampSliderValue(currentValue, min, max);

		function setValue(next: number) {
			if (disabled) {
				return;
			}
			const clamped = clampSliderValue(next, min, max);
			const stepped = clampSliderValue(min + Math.round((clamped - min) / step) * step, min, max);
			if (value === undefined) {
				setInternalValue(stepped);
			}
			onValueChange?.(stepped);
		}

		function updateFromEvent(event: React.PointerEvent<HTMLDivElement>, element: HTMLElement) {
			const rect = element.getBoundingClientRect();
			let next: number;
			if (orientation === 'vertical') {
				next = min + ((event.clientY - rect.top) / rect.height) * (max - min);
			} else {
				next = min + ((event.clientX - rect.left) / rect.width) * (max - min);
			}
			setValue(next);
		}

		function handlePointerDown(event: React.PointerEvent<HTMLDivElement>) {
			if (disabled) {
				return;
			}
			event.currentTarget.setPointerCapture(event.pointerId);
			updateFromEvent(event, event.currentTarget);
		}

		function handlePointerMove(event: React.PointerEvent<HTMLDivElement>) {
			if (disabled || !event.currentTarget.hasPointerCapture(event.pointerId)) {
				return;
			}
			updateFromEvent(event, event.currentTarget);
		}

		return (
			<SliderContext.Provider value={{ value: clampedValue, min, max, step, orientation, disabled, setValue }}>
				<div
					{...props}
					ref={ref}
					data-orientation={orientation}
					data-disabled={disabled}
					className={`${styles[sliderStyleKeys.root]} ${className}`}
					onPointerDown={handlePointerDown}
					onPointerMove={handlePointerMove}>
					{children}
				</div>
			</SliderContext.Provider>
		);
	},
);
Slider.displayName = 'Slider';

export interface SliderTrackProps extends React.HTMLAttributes<HTMLDivElement> {}

const SliderTrack = React.forwardRef<HTMLDivElement, SliderTrackProps>(({ className = '', ...props }, ref) => {
	const context = useSliderContext();

	return <div ref={ref} data-orientation={context.orientation} className={`${styles[sliderStyleKeys.track]} ${className}`} {...props} />;
});
SliderTrack.displayName = 'SliderTrack';

export interface SliderRangeProps extends React.HTMLAttributes<HTMLDivElement> {}

const SliderRange = React.forwardRef<HTMLDivElement, SliderRangeProps>(({ className = '', ...props }, ref) => {
	const context = useSliderContext();
	const percent = getSliderPercent(context.value, context.min, context.max);
	const style = context.orientation === 'vertical' ? { height: `${percent}%` } : { width: `${percent}%` };

	return <div ref={ref} data-orientation={context.orientation} className={`${styles[sliderStyleKeys.range]} ${className}`} style={style} {...props} />;
});
SliderRange.displayName = 'SliderRange';

export interface SliderThumbProps extends React.HTMLAttributes<HTMLSpanElement> {}

const SliderThumb = React.forwardRef<HTMLSpanElement, SliderThumbProps>(({ className = '', onKeyDown, ...props }, ref) => {
	const context = useSliderContext();
	const offsetStyle = getSliderOffsetStyle(context.value, context.min, context.max, context.orientation);

	function handleKeyDown(event: React.KeyboardEvent<HTMLSpanElement>) {
		onKeyDown?.(event);

		if (event.key === 'Home') {
			context.setValue(context.min);
			event.preventDefault();
			return;
		}

		if (event.key === 'End') {
			context.setValue(context.max);
			event.preventDefault();
			return;
		}

		const delta =
			context.orientation === 'horizontal'
				? event.key === 'ArrowRight'
					? 1
					: event.key === 'ArrowLeft'
						? -1
						: 0
				: event.key === 'ArrowDown'
					? 1
					: event.key === 'ArrowUp'
						? -1
						: 0;

		if (delta !== 0) {
			context.setValue(context.value + delta * context.step);
			event.preventDefault();
		}
	}

	return (
		<span
			{...props}
			ref={ref}
			role="slider"
			tabIndex={context.disabled ? -1 : 0}
			aria-disabled={context.disabled}
			aria-valuemin={context.min}
			aria-valuemax={context.max}
			aria-valuenow={context.value}
			aria-orientation={context.orientation}
			data-orientation={context.orientation}
			className={`${styles[sliderStyleKeys.thumb]} ${className}`}
			style={offsetStyle}
			onKeyDown={handleKeyDown}
		/>
	);
});
SliderThumb.displayName = 'SliderThumb';

export { Slider, SliderTrack, SliderRange, SliderThumb };
export default Slider;

// packages/vue/src/components/slider/slider.tsx
import { computed, defineComponent, h, inject, provide, ref, type ComputedRef, type InjectionKey, type PropType } from 'vue';
import { clampSliderValue, getSliderOffsetStyle, getSliderPercent, sliderStyleKeys } from '@tile-ui/core';
import type { SliderOrientation } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/slider.module.scss';

interface SliderContextValue {
	value: number;
	min: number;
	max: number;
	step: number;
	orientation: SliderOrientation;
	disabled: boolean;
	setValue: (value: number) => void;
}

type SliderContext = ComputedRef<SliderContextValue>;

const SliderContextKey: InjectionKey<SliderContext> = Symbol('tile-slider');

export const Slider = defineComponent({
	name: 'Slider',
	props: {
		modelValue: { type: Number, default: undefined },
		defaultValue: { type: Number, default: 0 },
		min: { type: Number, default: 0 },
		max: { type: Number, default: 100 },
		step: { type: Number, default: 1 },
		orientation: {
			type: String as PropType<SliderOrientation>,
			default: 'horizontal',
		},
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit, slots }) {
		const internalValue = ref(props.defaultValue);
		const currentValue = computed(() => (props.modelValue !== undefined ? props.modelValue : internalValue.value));
		const clampedValue = computed(() => clampSliderValue(currentValue.value, props.min, props.max));

		function setValue(next: number) {
			if (props.disabled) {
				return;
			}
			const clamped = clampSliderValue(next, props.min, props.max);
			const stepped = clampSliderValue(props.min + Math.round((clamped - props.min) / props.step) * props.step, props.min, props.max);
			if (props.modelValue === undefined) {
				internalValue.value = stepped;
			}
			emit('update:modelValue', stepped);
			emit('change', stepped);
		}

		function updateFromEvent(event: PointerEvent, element: HTMLElement) {
			const rect = element.getBoundingClientRect();
			let next: number;
			if (props.orientation === 'vertical') {
				next = props.min + ((event.clientY - rect.top) / rect.height) * (props.max - props.min);
			} else {
				next = props.min + ((event.clientX - rect.left) / rect.width) * (props.max - props.min);
			}
			setValue(next);
		}

		function handlePointerdown(event: PointerEvent) {
			if (props.disabled) {
				return;
			}
			const current = event.currentTarget as HTMLElement;
			current.setPointerCapture(event.pointerId);
			updateFromEvent(event, current);
		}

		function handlePointermove(event: PointerEvent) {
			if (props.disabled) {
				return;
			}
			const current = event.currentTarget as HTMLElement;
			if (!current.hasPointerCapture(event.pointerId)) {
				return;
			}
			updateFromEvent(event, current);
		}

		const context = computed<SliderContextValue>(() => ({
			value: clampedValue.value,
			min: props.min,
			max: props.max,
			step: props.step,
			orientation: props.orientation,
			disabled: props.disabled,
			setValue,
		}));

		provide(SliderContextKey, context);

		return () =>
			h(
				'div',
				{
					class: styles[sliderStyleKeys.root],
					'data-orientation': props.orientation,
					'data-disabled': props.disabled,
					onPointerdown: handlePointerdown,
					onPointermove: handlePointermove,
				},
				slots.default?.(),
			);
	},
});

export const SliderTrack = defineComponent({
	name: 'SliderTrack',
	setup(_props, { slots }) {
		const context = inject(SliderContextKey);
		if (!context) {
			throw new Error('SliderTrack must be used within <Slider>.');
		}

		return () => h('div', { class: styles[sliderStyleKeys.track], 'data-orientation': context.value.orientation }, slots.default?.());
	},
});

export const SliderRange = defineComponent({
	name: 'SliderRange',
	setup(_props) {
		const context = inject(SliderContextKey);
		if (!context) {
			throw new Error('SliderRange must be used within <Slider>.');
		}

		return () => {
			const percent = getSliderPercent(context.value.value, context.value.min, context.value.max);
			const style = context.value.orientation === 'vertical' ? { height: `${percent}%` } : { width: `${percent}%` };
			return h('div', { class: styles[sliderStyleKeys.range], 'data-orientation': context.value.orientation, style });
		};
	},
});

export const SliderThumb = defineComponent({
	name: 'SliderThumb',
	setup(_props) {
		const contextValue = inject(SliderContextKey);
		if (!contextValue) {
			throw new Error('SliderThumb must be used within <Slider>.');
		}
		const context: SliderContext = contextValue;

		function handleKeydown(event: KeyboardEvent) {
			const { value, min, max, step, orientation } = context.value;

			if (event.key === 'Home') {
				context.value.setValue(min);
				event.preventDefault();
				return;
			}

			if (event.key === 'End') {
				context.value.setValue(max);
				event.preventDefault();
				return;
			}

			let delta = 0;
			if (orientation === 'horizontal') {
				if (event.key === 'ArrowRight') {
					delta = 1;
				} else if (event.key === 'ArrowLeft') {
					delta = -1;
				}
			} else if (event.key === 'ArrowDown') {
				delta = 1;
			} else if (event.key === 'ArrowUp') {
				delta = -1;
			}

			if (delta !== 0) {
				context.value.setValue(value + delta * step);
				event.preventDefault();
			}
		}

		return () =>
			h('span', {
				role: 'slider',
				tabindex: context.value.disabled ? -1 : 0,
				'aria-disabled': context.value.disabled,
				'aria-valuemin': context.value.min,
				'aria-valuemax': context.value.max,
				'aria-valuenow': context.value.value,
				'aria-orientation': context.value.orientation,
				'data-orientation': context.value.orientation,
				class: styles[sliderStyleKeys.thumb],
				style: getSliderOffsetStyle(context.value.value, context.value.min, context.value.max, context.value.orientation),
				onKeydown: handleKeydown,
			});
	},
});

export default Slider;
