// packages/react/src/components/drawer/drawer.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import { drawerStyleKeys, getDrawerState, getDrawerTranslateStyle } from '@tile-ui/core';
import type { DrawerBaseProps, DrawerDirection } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/drawer.module.scss';

interface DrawerContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	close: () => void;
	direction: DrawerDirection;
	modal: boolean;
	titleId: string;
	descriptionId: string;
}

const DrawerContext = createContext<DrawerContextValue | null>(null);

function useDrawerContext(): DrawerContextValue {
	const context = useContext(DrawerContext);
	if (!context) {
		throw new Error('Drawer sub-components must be used within <Drawer>.');
	}
	return context;
}

export interface DrawerProps extends DrawerBaseProps {
	open?: boolean;
	defaultOpen?: boolean;
	onOpenChange?: (open: boolean) => void;
	children?: React.ReactNode;
}

function Drawer({ direction = 'right', modal = true, open, defaultOpen = false, onOpenChange, children }: DrawerProps) {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const onOpenChangeRef = useRef(onOpenChange);

	useEffect(() => {
		onOpenChangeRef.current = onOpenChange;
	});

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}

			onOpenChangeRef.current?.(next);
		},
		[open],
	);

	const close = useCallback(() => {
		setOpen(false);
	}, [setOpen]);

	const isOpen = open !== undefined ? open : internalOpen;
	const titleId = useId();
	const descriptionId = useId();

	return <DrawerContext.Provider value={{ open: isOpen, setOpen, close, direction, modal, titleId, descriptionId }}>{children}</DrawerContext.Provider>;
}

Drawer.displayName = 'Drawer';

export interface DrawerTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	asChild?: boolean;
}

const DrawerTrigger = React.forwardRef<HTMLButtonElement, DrawerTriggerProps>(({ asChild = false, className = '', children, onClick, ...props }, ref) => {
	const context = useDrawerContext();
	const Comp = asChild ? Slot : 'button';

	return (
		<Comp
			ref={ref}
			type={asChild ? undefined : 'button'}
			className={className}
			onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
				onClick?.(event);
				context.setOpen(true);
			}}
			{...props}>
			{children}
		</Comp>
	);
});
DrawerTrigger.displayName = 'DrawerTrigger';

export interface DrawerCloseProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
	asChild?: boolean;
}

const DrawerClose = React.forwardRef<HTMLButtonElement, DrawerCloseProps>(({ asChild = false, className = '', children, onClick, ...props }, ref) => {
	const context = useDrawerContext();
	const Comp = asChild ? Slot : 'button';

	return (
		<Comp
			ref={ref}
			type={asChild ? undefined : 'button'}
			className={className}
			onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
				onClick?.(event);
				context.close();
			}}
			{...props}>
			{children}
		</Comp>
	);
});
DrawerClose.displayName = 'DrawerClose';

export interface DrawerOverlayProps extends React.HTMLAttributes<HTMLDivElement> {}

const DrawerOverlay = React.forwardRef<HTMLDivElement, DrawerOverlayProps>(({ className = '', onClick, ...props }, ref) => {
	const context = useDrawerContext();

	if (!context.open || !context.modal) {
		return null;
	}

	return (
		<div
			ref={ref}
			data-state={getDrawerState(context.open)}
			className={`${styles[drawerStyleKeys.overlay]} ${className}`}
			onClick={(event: React.MouseEvent<HTMLDivElement>) => {
				onClick?.(event);
				context.close();
			}}
			{...props}
		/>
	);
});
DrawerOverlay.displayName = 'DrawerOverlay';

export interface DrawerContentProps extends React.HTMLAttributes<HTMLDivElement> {
	showCloseButton?: boolean;
	container?: PortalContainer;
}

const DrawerContent = React.forwardRef<HTMLDivElement, DrawerContentProps>(({ className = '', showCloseButton = true, container, style, children, ...props }, ref) => {
	const { open, close, direction, modal, titleId, descriptionId } = useDrawerContext();
	const portalContainer = usePortalContainer(container);
	const contentRef = useRef<HTMLDivElement | null>(null);
	const [isVisible, setIsVisible] = useState(false);

	function setContentRef(element: HTMLDivElement | null) {
		contentRef.current = element;

		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	useLayoutEffect(() => {
		if (!open) {
			return;
		}

		const previouslyFocused = document.activeElement as HTMLElement | null;
		const previousOverflow = document.body.style.overflow;
		if (modal) {
			document.body.style.overflow = 'hidden';
		}

		const handleKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape' && modal) {
				close();
				return;
			}

			if (event.key === 'Tab' && modal) {
				const container = contentRef.current;
				if (!container) {
					return;
				}
				const focusables = Array.from(
					container.querySelectorAll<HTMLElement>(
						'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
					),
				).filter((el) => el.getClientRects().length > 0);
				if (focusables.length === 0) {
					event.preventDefault();
					return;
				}
				const first = focusables[0];
				const last = focusables[focusables.length - 1];
				const active = document.activeElement;

				if (event.shiftKey) {
					if (active === first || active === container || !container.contains(active)) {
						event.preventDefault();
						last.focus();
					}
				} else if (active === last || !container.contains(active)) {
					event.preventDefault();
					first.focus();
				}
			}
		};

		document.addEventListener('keydown', handleKeyDown);

		const contentEl = contentRef.current;
		if (contentEl) {
			contentEl.focus();
		}

		return () => {
			document.body.style.overflow = previousOverflow;
			document.removeEventListener('keydown', handleKeyDown);
			previouslyFocused?.focus();
		};
	}, [close, open, modal]);

	useEffect(() => {
		if (!open) {
			return;
		}

		const frame = requestAnimationFrame(() => {
			setIsVisible(true);
		});

		return () => cancelAnimationFrame(frame);
	}, [open]);

	if (!open || !portalContainer) {
		return null;
	}

	return createPortal(
		<>
			{modal && <DrawerOverlay />}
			<div
				ref={setContentRef}
				role="dialog"
				aria-modal={modal ? 'true' : 'false'}
				aria-labelledby={titleId}
				aria-describedby={descriptionId}
				tabIndex={-1}
				data-state={getDrawerState(open)}
				data-direction={direction}
				style={{ transform: isVisible ? '' : getDrawerTranslateStyle(direction), opacity: isVisible ? '' : 0, ...style }}
				className={`${styles[drawerStyleKeys.content]} ${className}`}
				{...props}>
				<div className={styles[drawerStyleKeys.handle]} />
				{children}
				{showCloseButton && (
					<button type="button" aria-label="关闭" className={styles[drawerStyleKeys.close]} onClick={() => close()}>
						<svg
							className={styles[drawerStyleKeys.xIcon]}
							xmlns="http://www.w3.org/2000/svg"
							width="16"
							height="16"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth="2"
							strokeLinecap="round"
							strokeLinejoin="round"
							aria-hidden="true">
							<path d="M18 6 6 18" />
							<path d="m6 6 12 12" />
						</svg>
					</button>
				)}
			</div>
		</>,
		portalContainer,
	);
});
DrawerContent.displayName = 'DrawerContent';

export interface DrawerHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const DrawerHeader = React.forwardRef<HTMLDivElement, DrawerHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[drawerStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
DrawerHeader.displayName = 'DrawerHeader';

export interface DrawerFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const DrawerFooter = React.forwardRef<HTMLDivElement, DrawerFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[drawerStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</div>
	);
});
DrawerFooter.displayName = 'DrawerFooter';

export interface DrawerTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {}

const DrawerTitle = React.forwardRef<HTMLHeadingElement, DrawerTitleProps>(({ className = '', children, ...props }, ref) => {
	const context = useDrawerContext();

	return (
		<h2 ref={ref} id={context.titleId} className={`${styles[drawerStyleKeys.title]} ${className}`} {...props}>
			{children}
		</h2>
	);
});
DrawerTitle.displayName = 'DrawerTitle';

export interface DrawerDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

const DrawerDescription = React.forwardRef<HTMLParagraphElement, DrawerDescriptionProps>(({ className = '', children, ...props }, ref) => {
	const context = useDrawerContext();

	return (
		<p ref={ref} id={context.descriptionId} className={`${styles[drawerStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
DrawerDescription.displayName = 'DrawerDescription';

export { Drawer, DrawerTrigger, DrawerClose, DrawerOverlay, DrawerContent, DrawerHeader, DrawerFooter, DrawerTitle, DrawerDescription };
export default Drawer;

// packages/vue/src/components/drawer/drawer.tsx
import {
	cloneVNode,
	computed,
	defineComponent,
	h,
	inject,
	nextTick,
	onBeforeUnmount,
	provide,
	ref,
	useId,
	watch,
	Teleport,
	type ComputedRef,
	type InjectionKey,
	type PropType,
} from 'vue';
import { drawerStyleKeys, getDrawerState, getDrawerTranslateStyle } from '@tile-ui/core';
import type { DrawerDirection } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/drawer.module.scss';

interface DrawerContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	close: () => void;
	direction: DrawerDirection;
	modal: boolean;
	titleId: string;
	descriptionId: string;
}

type DrawerContext = ComputedRef<DrawerContextValue>;

const DrawerContextKey: InjectionKey<DrawerContext> = Symbol('tile-drawer');

function composeEventHandlers(...handlers: Array<unknown>): (event: Event) => void {
	return (event: Event) => {
		for (const handler of handlers) {
			if (!handler) {
				continue;
			}

			const list = Array.isArray(handler) ? handler : [handler];

			for (const item of list) {
				if (typeof item === 'function') {
					item(event);
				}
			}
		}
	};
}

export const Drawer = defineComponent({
	name: 'Drawer',
	props: {
		direction: { type: String as PropType<DrawerDirection>, default: 'right' },
		modal: { type: Boolean, default: true },
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const baseId = useId();
		const titleId = `${baseId}-title`;
		const descriptionId = `${baseId}-description`;

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}

			emit('update:open', next);
		}

		function close() {
			setOpen(false);
		}

		const context = computed<DrawerContextValue>(() => ({
			open: isOpen.value,
			setOpen,
			close,
			direction: props.direction,
			modal: props.modal,
			titleId,
			descriptionId,
		}));

		provide(DrawerContextKey, context);

		return () => slots.default?.();
	},
});

export const DrawerTrigger = defineComponent({
	name: 'DrawerTrigger',
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(DrawerContextKey);
		if (!contextValue) {
			throw new Error('DrawerTrigger must be used within <Drawer>.');
		}
		const context: DrawerContext = contextValue;

		function handleOpen() {
			context.value.setOpen(true);
		}

		return () => {
			const children = slots.default?.();
			const attrOnClick = (attrs as Record<string, unknown>).onClick;

			if (props.asChild) {
				const firstChild = Array.isArray(children) ? children[0] : children;

				if (firstChild) {
					const childProps = (firstChild.props ?? {}) as Record<string, unknown>;
					return cloneVNode(firstChild, {
						...attrs,
						onClick: composeEventHandlers(attrOnClick, childProps.onClick, handleOpen),
					});
				}
			}

			return h('button', { type: 'button', ...attrs, onClick: composeEventHandlers(attrOnClick, handleOpen) }, children);
		};
	},
});

export const DrawerClose = defineComponent({
	name: 'DrawerClose',
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(DrawerContextKey);
		if (!contextValue) {
			throw new Error('DrawerClose must be used within <Drawer>.');
		}
		const context: DrawerContext = contextValue;

		function handleClose() {
			context.value.close();
		}

		return () => {
			const children = slots.default?.();
			const attrOnClick = (attrs as Record<string, unknown>).onClick;

			if (props.asChild) {
				const firstChild = Array.isArray(children) ? children[0] : children;

				if (firstChild) {
					const childProps = (firstChild.props ?? {}) as Record<string, unknown>;
					return cloneVNode(firstChild, {
						...attrs,
						onClick: composeEventHandlers(attrOnClick, childProps.onClick, handleClose),
					});
				}
			}

			return h('button', { type: 'button', ...attrs, onClick: composeEventHandlers(attrOnClick, handleClose) }, children);
		};
	},
});

export const DrawerOverlay = defineComponent({
	name: 'DrawerOverlay',
	setup(_props, { slots, attrs }) {
		const contextValue = inject(DrawerContextKey);
		if (!contextValue) {
			throw new Error('DrawerOverlay must be used within <Drawer>.');
		}
		const context: DrawerContext = contextValue;

		return () => {
			if (!context.value.open || !context.value.modal) {
				return null;
			}

			return h(
				'div',
				{
					...attrs,
					'data-state': getDrawerState(context.value.open),
					class: [styles[drawerStyleKeys.overlay], attrs.class],
					onClick: composeEventHandlers((attrs as Record<string, unknown>).onClick, () => context.value.close()),
				},
				slots.default?.(),
			);
		};
	},
});

export const DrawerContent = defineComponent({
	name: 'DrawerContent',
	props: {
		showCloseButton: { type: Boolean, default: true },
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots, attrs }) {
		const portalContainer = usePortalContainer(() => props.container);
		const contextValue = inject(DrawerContextKey);
		if (!contextValue) {
			throw new Error('DrawerContent must be used within <Drawer>.');
		}
		const context: DrawerContext = contextValue;
		const contentRef = ref<HTMLElement | null>(null);
		const previousOverflow = ref('');
		const isVisible = ref(false);
		let animationFrame = 0;
		let previouslyFocused: HTMLElement | null = null;

		function handleKeyDown(event: KeyboardEvent) {
			if (event.key === 'Escape' && context.value.modal) {
				context.value.close();
				return;
			}

			if (event.key === 'Tab' && context.value.modal) {
				const container = contentRef.value;
				if (!container) {
					return;
				}
				const focusables = Array.from(
					container.querySelectorAll<HTMLElement>(
						'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
					),
				).filter((el) => el.getClientRects().length > 0);
				if (focusables.length === 0) {
					event.preventDefault();
					return;
				}
				const first = focusables[0];
				const last = focusables[focusables.length - 1];
				const active = document.activeElement;

				if (event.shiftKey) {
					if (active === first || active === container || !container.contains(active)) {
						event.preventDefault();
						last.focus();
					}
				} else if (active === last || !container.contains(active)) {
					event.preventDefault();
					first.focus();
				}
			}
		}

		watch(
			() => context.value.open,
			(open) => {
				if (typeof document === 'undefined') {
					return;
				}

				if (open) {
					isVisible.value = false;
					previouslyFocused = document.activeElement as HTMLElement | null;
					previousOverflow.value = document.body.style.overflow;
					if (context.value.modal) {
						document.body.style.overflow = 'hidden';
					}
					document.addEventListener('keydown', handleKeyDown);
					animationFrame = requestAnimationFrame(() => {
						isVisible.value = true;
					});
					nextTick(() => {
						contentRef.value?.focus();
					});
				} else {
					cancelAnimationFrame(animationFrame);
					document.removeEventListener('keydown', handleKeyDown);
					document.body.style.overflow = previousOverflow.value;
					previouslyFocused?.focus();
				}
			},
			{ immediate: true },
		);

		onBeforeUnmount(() => {
			cancelAnimationFrame(animationFrame);
			document.removeEventListener('keydown', handleKeyDown);
			document.body.style.overflow = previousOverflow.value;
			previouslyFocused?.focus();
		});

		return () => {
			if (!context.value.open) {
				return null;
			}

			const contentChildren: any[] = [h('div', { class: styles[drawerStyleKeys.handle] })];
			const slotChildren = slots.default?.() ?? [];
			for (const child of slotChildren) {
				contentChildren.push(child);
			}

			if (props.showCloseButton) {
				contentChildren.push(
					h(
						'button',
						{
							type: 'button',
							'aria-label': '关闭',
							class: styles[drawerStyleKeys.close],
							onClick: () => context.value.close(),
						},
						[
							h(
								'svg',
								{
									class: styles[drawerStyleKeys.xIcon],
									xmlns: 'http://www.w3.org/2000/svg',
									width: '16',
									height: '16',
									viewBox: '0 0 24 24',
									fill: 'none',
									stroke: 'currentColor',
									'stroke-width': '2',
									'stroke-linecap': 'round',
									'stroke-linejoin': 'round',
									'aria-hidden': 'true',
								},
								[h('path', { d: 'M18 6 6 18' }), h('path', { d: 'm6 6 12 12' })],
							),
						],
					),
				);
			}

			const userClass = attrs.class;
			const contentAttrs = { ...attrs };
			delete contentAttrs.class;

			return h(Teleport, { to: portalContainer.value }, [
				context.value.modal
					? h('div', {
							'data-state': getDrawerState(context.value.open),
							class: styles[drawerStyleKeys.overlay],
							onClick: () => context.value.close(),
						})
					: null,
				h(
					'div',
					{
						...contentAttrs,
						ref: contentRef,
						role: 'dialog',
						'aria-modal': context.value.modal ? 'true' : 'false',
						'aria-labelledby': context.value.titleId,
						'aria-describedby': context.value.descriptionId,
						tabindex: -1,
						'data-state': getDrawerState(context.value.open),
						'data-direction': context.value.direction,
						style: {
							transform: isVisible.value ? undefined : getDrawerTranslateStyle(context.value.direction),
							opacity: isVisible.value ? undefined : 0,
						},
						class: [styles[drawerStyleKeys.content], userClass],
					},
					contentChildren,
				),
			]);
		};
	},
});

export const DrawerHeader = defineComponent({
	name: 'DrawerHeader',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, class: [styles[drawerStyleKeys.header], attrs.class] }, slots.default?.());
	},
});

export const DrawerFooter = defineComponent({
	name: 'DrawerFooter',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, class: [styles[drawerStyleKeys.footer], attrs.class] }, slots.default?.());
	},
});

export const DrawerTitle = defineComponent({
	name: 'DrawerTitle',
	setup(_props, { slots, attrs }) {
		const contextValue = inject(DrawerContextKey);
		if (!contextValue) {
			throw new Error('DrawerTitle must be used within <Drawer>.');
		}
		const context: DrawerContext = contextValue;

		return () => h('h2', { ...attrs, id: context.value.titleId, class: [styles[drawerStyleKeys.title], attrs.class] }, slots.default?.());
	},
});

export const DrawerDescription = defineComponent({
	name: 'DrawerDescription',
	setup(_props, { slots, attrs }) {
		const contextValue = inject(DrawerContextKey);
		if (!contextValue) {
			throw new Error('DrawerDescription must be used within <Drawer>.');
		}
		const context: DrawerContext = contextValue;

		return () => h('p', { ...attrs, id: context.value.descriptionId, class: [styles[drawerStyleKeys.description], attrs.class] }, slots.default?.());
	},
});

export default Drawer;
