// packages/react/src/components/bubble/bubble.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { bubbleStyleKeys, getBubbleStyleKeys } from '@tile-ui/core';
import type { BubbleBaseProps, BubbleContentBaseProps, BubbleReactionsBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/bubble.module.scss';

export interface BubbleGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const BubbleGroup = React.forwardRef<HTMLDivElement, BubbleGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="bubble-group" className={[styles[bubbleStyleKeys.group], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</div>
	);
});
BubbleGroup.displayName = 'BubbleGroup';

export interface BubbleProps extends React.HTMLAttributes<HTMLDivElement>, BubbleBaseProps {}

const Bubble = React.forwardRef<HTMLDivElement, BubbleProps>(({ className = '', variant = 'default', align = 'start', children, ...props }, ref) => {
	const styleKeys = getBubbleStyleKeys(variant);

	return (
		<div
			ref={ref}
			data-slot="bubble"
			data-variant={variant}
			data-align={align}
			className={[styles[styleKeys.base], styles[styleKeys.variant], className].filter(Boolean).join(' ')}
			{...props}>
			{children}
		</div>
	);
});
Bubble.displayName = 'Bubble';

export interface BubbleContentProps extends React.HTMLAttributes<HTMLDivElement>, BubbleContentBaseProps {}

const BubbleContent = React.forwardRef<HTMLDivElement, BubbleContentProps>(({ className = '', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'div';

	return (
		<Comp ref={ref} data-slot="bubble-content" className={[styles[bubbleStyleKeys.content], className].filter(Boolean).join(' ')} {...props}>
			{children}
		</Comp>
	);
});
BubbleContent.displayName = 'BubbleContent';

export interface BubbleReactionsProps extends React.HTMLAttributes<HTMLDivElement>, BubbleReactionsBaseProps {}

const BubbleReactions = React.forwardRef<HTMLDivElement, BubbleReactionsProps>(({ className = '', side = 'bottom', align = 'end', children, ...props }, ref) => {
	return (
		<div
			ref={ref}
			data-slot="bubble-reactions"
			data-side={side}
			data-align={align}
			className={[styles[bubbleStyleKeys.reactions], className].filter(Boolean).join(' ')}
			{...props}>
			{children}
		</div>
	);
});
BubbleReactions.displayName = 'BubbleReactions';

export { BubbleGroup, Bubble, BubbleContent, BubbleReactions };
export default Bubble;

// packages/vue/src/components/bubble/bubble.tsx
import { cloneVNode, defineComponent, h, type PropType } from 'vue';
import { bubbleStyleKeys, getBubbleStyleKeys } from '@tile-ui/core';
import type { BubbleAlign, BubbleReactionsSide, BubbleVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/bubble.module.scss';

export const BubbleGroup = defineComponent({
	name: 'BubbleGroup',
	setup(_props, { slots }) {
		return () => h('div', { 'data-slot': 'bubble-group', class: styles[bubbleStyleKeys.group] }, slots.default?.());
	},
});

export const Bubble = defineComponent({
	name: 'Bubble',
	props: {
		variant: { type: String as PropType<BubbleVariant>, default: 'default' },
		align: { type: String as PropType<BubbleAlign>, default: 'start' },
	},
	setup(props, { slots }) {
		return () => {
			const styleKeys = getBubbleStyleKeys(props.variant);
			return h(
				'div',
				{
					'data-slot': 'bubble',
					'data-variant': props.variant,
					'data-align': props.align,
					class: [styles[styleKeys.base], styles[styleKeys.variant]],
				},
				slots.default?.(),
			);
		};
	},
});

export const BubbleContent = defineComponent({
	name: 'BubbleContent',
	inheritAttrs: false,
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		return () => {
			const userClass = attrs.class;
			const restAttrs = { ...attrs };
			delete restAttrs.class;

			const slotChildren = slots.default?.();
			const firstChild = Array.isArray(slotChildren) ? slotChildren[0] : slotChildren;

			if (props.asChild && firstChild) {
				return cloneVNode(firstChild, {
					...restAttrs,
					'data-slot': 'bubble-content',
					class: [styles[bubbleStyleKeys.content], userClass, (firstChild.props as Record<string, unknown> | null)?.class],
				});
			}

			return h('div', { ...restAttrs, 'data-slot': 'bubble-content', class: [styles[bubbleStyleKeys.content], userClass] }, slotChildren);
		};
	},
});

export const BubbleReactions = defineComponent({
	name: 'BubbleReactions',
	props: {
		side: { type: String as PropType<BubbleReactionsSide>, default: 'bottom' },
		align: { type: String as PropType<BubbleAlign>, default: 'end' },
	},
	setup(props, { slots }) {
		return () =>
			h(
				'div',
				{
					'data-slot': 'bubble-reactions',
					'data-side': props.side,
					'data-align': props.align,
					class: styles[bubbleStyleKeys.reactions],
				},
				slots.default?.(),
			);
	},
});

export default Bubble;
