// packages/react/src/components/skeleton/skeleton.tsx
import React from 'react';
import { skeletonStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/skeleton.module.scss';

export interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {}

const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(({ className = '', ...props }, ref) => {
	return <div ref={ref} className={`${styles[skeletonStyleKeys.base]} ${className}`} {...props} />;
});

Skeleton.displayName = 'Skeleton';

export { Skeleton };
export default Skeleton;

// packages/solid/src/components/skeleton/skeleton.tsx
import { splitProps, type JSX } from 'solid-js';
import { skeletonStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/skeleton.module.scss';
export interface SkeletonProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export function Skeleton(props: SkeletonProps) {
	const [local, rest] = splitProps(props, ['class']);
	return <div {...rest} aria-hidden={rest['aria-hidden'] ?? 'true'} class={`${styles[skeletonStyleKeys.base]} ${local.class ?? ''}`} />;
}
export default Skeleton;
