// apps/react/components/demos/checkbox.tsx
import { useState } from 'react';
import { Checkbox } from '@tile-ui/react';

export default function CheckboxDemo() {
	const [checked, setChecked] = useState(true);

	return (
		<div className="button-group">
			<Checkbox checked={checked} onCheckedChange={(next) => setChecked(next === true)} aria-label="Accept terms" />
			<Checkbox checked="indeterminate" aria-label="Indeterminate checkbox" />
			<Checkbox disabled aria-label="Disabled checkbox" />
		</div>
	);
}

// apps/vue/components/demos/checkbox.tsx
import { defineComponent, ref } from 'vue';
import { Checkbox } from '@tile-ui/vue';

export default defineComponent({
	name: 'CheckboxDemo',
	setup() {
		const checked = ref(true);
		return () => (
			<div class="button-group">
				<Checkbox
					modelValue={checked.value}
					onUpdate:modelValue={(next) => {
						checked.value = next === true;
					}}
					aria-label="Accept terms"
				/>
				<Checkbox defaultChecked="indeterminate" aria-label="Indeterminate checkbox" />
				<Checkbox disabled aria-label="Disabled checkbox" />
			</div>
		);
	},
});
