// apps/react/components/demos/direction.tsx
import { useState } from 'react';
import { DirectionProvider, Button } from '@tile-ui/react';

export default function DirectionDemo() {
	const [rtl, setRtl] = useState(false);

	return (
		<div className="component-preview__stack">
			<DirectionProvider dir={rtl ? 'rtl' : 'ltr'}>
				<div style={{ display: 'flex', gap: 8 }}>
					<span className="component-preview__text">One</span>
					<span className="component-preview__text">Two</span>
					<span className="component-preview__text">Three</span>
				</div>
			</DirectionProvider>
			<div className="button-group">
				<Button variant="outline" onClick={() => setRtl((v) => !v)}>
					{rtl ? 'RTL' : 'LTR'}
				</Button>
			</div>
		</div>
	);
}

// apps/vue/components/demos/direction.tsx
import { ref } from 'vue';
import { DirectionProvider } from '@tile-ui/vue';

export default defineComponent({
	name: 'DirectionDemo',
	setup() {
		const rtl = ref(false);
		return () => (
			<div class="component-preview__stack">
				<DirectionProvider dir={rtl.value ? 'rtl' : 'ltr'}>
					<div style={{ display: 'flex', gap: '8px' }}>
						<span class="component-preview__text">One</span>
						<span class="component-preview__text">Two</span>
						<span class="component-preview__text">Three</span>
					</div>
				</DirectionProvider>
				<div class="button-group">
					<button
						type="button"
						class="component-preview__action"
						onClick={() => {
							rtl.value = !rtl.value;
						}}>
						{rtl.value ? 'RTL' : 'LTR'}
					</button>
				</div>
			</div>
		);
	},
});
