// apps/react/components/demos/switch.tsx
import { useState } from 'react';
import { Switch } from '@tile-ui/react';

export default function SwitchDemo() {
	const [checked, setChecked] = useState(true);

	return (
		<div className="button-group">
			<Switch checked={checked} onCheckedChange={setChecked} aria-label="Enable notifications" />
			<Switch size="sm" aria-label="Compact mode" />
		</div>
	);
}

// apps/vue/components/demos/switch.tsx
import { defineComponent, ref } from 'vue';
import { Switch } from '@tile-ui/vue';

export default defineComponent({
	name: 'SwitchDemo',
	setup() {
		const checked = ref(true);
		return () => (
			<div class="button-group">
				<Switch
					modelValue={checked.value}
					onUpdate:modelValue={(next: boolean) => {
						checked.value = next;
					}}
					aria-label="Enable notifications"
				/>
				<Switch size="sm" aria-label="Compact mode" />
			</div>
		);
	},
});
