// apps/react/components/demos/textarea.tsx
import { useState } from 'react';
import { Textarea } from '@tile-ui/react';

export default function TextareaDemo() {
	const [value, setValue] = useState('');

	return (
		<div className="component-preview__stack">
			<Textarea
				label="Summary"
				helperText="Keep it short and specific for reviewers."
				value={value}
				onChange={(event) => setValue(event.target.value)}
				placeholder="Describe the release in one paragraph"
			/>
			<Textarea label="Validation example" error="Please provide at least 20 characters before submitting." defaultValue="Too short" />
		</div>
	);
}

// apps/vue/components/demos/textarea.tsx
import { defineComponent, ref } from 'vue';
import { Textarea } from '@tile-ui/vue';

export default defineComponent({
	name: 'TextareaDemo',
	setup() {
		const value = ref('');
		return () => (
			<div class="component-preview__stack">
				<Textarea
					label="Summary"
					helperText="Keep it short and specific for reviewers."
					modelValue={value.value}
					onUpdate:modelValue={(nextValue: string) => {
						value.value = nextValue;
					}}
					placeholder="Describe the release in one paragraph"
				/>
				<Textarea label="Validation example" error="Please provide at least 20 characters before submitting." defaultValue="Too short" />
			</div>
		);
	},
});
