// packages/react/src/components/tabs/tabs.tsx
import React, { createContext, useContext, useId, useState } from 'react';
import { getTabsListVariantKey, getTabsState, tabsStyleKeys } from '@tile-ui/core';
import type { TabsBaseProps, TabsListBaseProps, TabsTriggerBaseProps, TabsContentBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/tabs.module.scss';

interface TabsContextValue {
	value: string;
	orientation: 'horizontal' | 'vertical';
	baseId: string;
	select: (value: string) => void;
}

const TabsContext = createContext<TabsContextValue | null>(null);

function useTabsContext(): TabsContextValue {
	const context = useContext(TabsContext);
	if (!context) {
		throw new Error('Tabs sub-components must be used within <Tabs>.');
	}
	return context;
}

export interface TabsProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'value' | 'defaultValue'>, TabsBaseProps {}

const Tabs = React.forwardRef<HTMLDivElement, TabsProps>(({ className = '', value, defaultValue = '', orientation = 'horizontal', onValueChange, children, ...props }, ref) => {
	const [internalValue, setInternalValue] = useState(defaultValue);
	const currentValue = value !== undefined ? value : internalValue;
	const baseId = useId();

	function select(next: string) {
		if (value === undefined) {
			setInternalValue(next);
		}
		onValueChange?.(next);
	}

	return (
		<TabsContext.Provider value={{ value: currentValue, orientation, baseId, select }}>
			<div ref={ref} data-orientation={orientation} className={`${styles[tabsStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</TabsContext.Provider>
	);
});
Tabs.displayName = 'Tabs';

export interface TabsListProps extends React.HTMLAttributes<HTMLDivElement>, TabsListBaseProps {}

const TabsList = React.forwardRef<HTMLDivElement, TabsListProps>(({ className = '', variant = 'default', children, onKeyDown, ...props }, ref) => {
	const context = useTabsContext();
	const variantKey = getTabsListVariantKey(variant);
	const isVertical = context.orientation === 'vertical';

	function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
		onKeyDown?.(event);

		const nextKey = isVertical ? 'ArrowDown' : 'ArrowRight';
		const prevKey = isVertical ? 'ArrowUp' : 'ArrowLeft';
		const isNext = event.key === nextKey;
		const isPrev = event.key === prevKey;
		const isHome = event.key === 'Home';
		const isEnd = event.key === 'End';

		if (!isNext && !isPrev && !isHome && !isEnd) {
			return;
		}

		const triggers = Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('button[role="tab"]')).filter((trigger) => !trigger.disabled);

		if (triggers.length === 0) {
			return;
		}

		const currentIndex = triggers.indexOf(document.activeElement as HTMLButtonElement);
		let nextIndex: number;
		if (isHome) {
			nextIndex = 0;
		} else if (isEnd) {
			nextIndex = triggers.length - 1;
		} else {
			const direction = isNext ? 1 : -1;
			nextIndex = (currentIndex + direction + triggers.length) % triggers.length;
		}

		const nextTrigger = triggers[nextIndex];
		nextTrigger?.focus();

		// 自动激活：方向键移动焦点时同步选中对应标签页。
		const nextValue = nextTrigger?.getAttribute('data-value');
		if (nextValue !== null && nextValue !== undefined) {
			context.select(nextValue);
		}

		event.preventDefault();
	}

	return (
		<div
			ref={ref}
			role="tablist"
			data-orientation={context.orientation}
			data-variant={variant}
			onKeyDown={handleKeyDown}
			className={`${styles[tabsStyleKeys.list]} ${styles[variantKey]} ${className}`}
			{...props}>
			{children}
		</div>
	);
});
TabsList.displayName = 'TabsList';

export interface TabsTriggerProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'value'>, TabsTriggerBaseProps {
	value: string;
}

const TabsTrigger = React.forwardRef<HTMLButtonElement, TabsTriggerProps>(({ className = '', value, disabled = false, children, onClick, ...props }, ref) => {
	const context = useTabsContext();
	const active = context.value === value;
	const state = getTabsState(active);
	const triggerId = `${context.baseId}-trigger-${value}`;
	const contentId = `${context.baseId}-content-${value}`;

	function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
		context.select(value);
		onClick?.(event);
	}

	return (
		<button
			ref={ref}
			type="button"
			id={triggerId}
			role="tab"
			aria-selected={active}
			aria-controls={contentId}
			data-value={value}
			tabIndex={active ? 0 : -1}
			disabled={disabled}
			data-state={state}
			data-orientation={context.orientation}
			className={`${styles[tabsStyleKeys.trigger]} ${className}`}
			onClick={handleClick}
			{...props}>
			{children}
		</button>
	);
});
TabsTrigger.displayName = 'TabsTrigger';

export interface TabsContentProps extends React.HTMLAttributes<HTMLDivElement>, TabsContentBaseProps {
	value: string;
}

const TabsContent = React.forwardRef<HTMLDivElement, TabsContentProps>(({ className = '', value, children, ...props }, ref) => {
	const context = useTabsContext();
	const active = context.value === value;
	const state = getTabsState(active);
	const triggerId = `${context.baseId}-trigger-${value}`;
	const contentId = `${context.baseId}-content-${value}`;

	return (
		<div
			{...props}
			ref={ref}
			id={contentId}
			role="tabpanel"
			aria-labelledby={triggerId}
			data-state={state}
			data-orientation={context.orientation}
			hidden={!active}
			className={`${styles[tabsStyleKeys.content]} ${className}`}>
			{children}
		</div>
	);
});
TabsContent.displayName = 'TabsContent';

export { Tabs, TabsList, TabsTrigger, TabsContent };
export default Tabs;

// packages/vue/src/components/tabs/tabs.tsx
import { computed, defineComponent, h, inject, provide, ref, useId, type ComputedRef, type InjectionKey, type PropType } from 'vue';
import { getTabsListVariantKey, getTabsState, tabsStyleKeys } from '@tile-ui/core';
import type { TabsListVariant, TabsOrientation } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/tabs.module.scss';

interface TabsContextValue {
	value: string;
	orientation: TabsOrientation;
	baseId: string;
	select: (value: string) => void;
}

type TabsContext = ComputedRef<TabsContextValue>;

const TabsContextKey: InjectionKey<TabsContext> = Symbol('tile-tabs');

export const Tabs = defineComponent({
	name: 'Tabs',
	props: {
		modelValue: { type: String, default: undefined },
		defaultValue: { type: String, default: '' },
		orientation: {
			type: String as PropType<TabsOrientation>,
			default: 'horizontal',
		},
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit, slots }) {
		const internalValue = ref(props.defaultValue);
		const currentValue = computed(() => (props.modelValue !== undefined ? props.modelValue : internalValue.value));
		const baseId = useId();

		const context = computed<TabsContextValue>(() => ({
			value: currentValue.value,
			orientation: props.orientation,
			baseId,
			select: (next: string) => {
				if (props.modelValue === undefined) {
					internalValue.value = next;
				}
				emit('update:modelValue', next);
				emit('change', next);
			},
		}));

		provide(TabsContextKey, context);

		return () => h('div', { class: styles[tabsStyleKeys.root], 'data-orientation': props.orientation }, slots.default?.());
	},
});

export const TabsList = defineComponent({
	name: 'TabsList',
	props: {
		variant: {
			type: String as PropType<TabsListVariant>,
			default: 'default',
		},
	},
	setup(props, { slots }) {
		const context = inject(TabsContextKey);
		if (!context) {
			throw new Error('TabsList must be used within <Tabs>.');
		}

		const variantKey = computed(() => getTabsListVariantKey(props.variant));
		const isVertical = computed(() => context!.value.orientation === 'vertical');

		function handleKeydown(event: KeyboardEvent) {
			const nextKey = isVertical.value ? 'ArrowDown' : 'ArrowRight';
			const prevKey = isVertical.value ? 'ArrowUp' : 'ArrowLeft';
			const isNext = event.key === nextKey;
			const isPrev = event.key === prevKey;
			const isHome = event.key === 'Home';
			const isEnd = event.key === 'End';

			if (!isNext && !isPrev && !isHome && !isEnd) {
				return;
			}

			const triggers = Array.from((event.currentTarget as HTMLElement).querySelectorAll<HTMLButtonElement>('button[role="tab"]')).filter((trigger) => !trigger.disabled);

			if (triggers.length === 0) {
				return;
			}

			const currentIndex = triggers.indexOf(document.activeElement as HTMLButtonElement);
			let nextIndex: number;
			if (isHome) {
				nextIndex = 0;
			} else if (isEnd) {
				nextIndex = triggers.length - 1;
			} else {
				const direction = isNext ? 1 : -1;
				nextIndex = (currentIndex + direction + triggers.length) % triggers.length;
			}

			const nextTrigger = triggers[nextIndex];
			nextTrigger?.focus();

			const nextValue = nextTrigger?.getAttribute('data-value');
			if (nextValue !== null && nextValue !== undefined) {
				context!.value.select(nextValue);
			}

			event.preventDefault();
		}

		return () =>
			h(
				'div',
				{
					class: [styles[tabsStyleKeys.list], styles[variantKey.value]],
					role: 'tablist',
					'data-orientation': context.value.orientation,
					'data-variant': props.variant,
					onKeydown: handleKeydown,
				},
				slots.default?.(),
			);
	},
});

export const TabsTrigger = defineComponent({
	name: 'TabsTrigger',
	props: {
		value: { type: String, required: true },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots }) {
		const context = inject(TabsContextKey);
		if (!context) {
			throw new Error('TabsTrigger must be used within <Tabs>.');
		}

		const active = computed(() => context.value.value === props.value);
		const state = computed(() => getTabsState(active.value));
		const triggerId = computed(() => `${context.value.baseId}-trigger-${props.value}`);
		const contentId = computed(() => `${context.value.baseId}-content-${props.value}`);

		return () =>
			h(
				'button',
				{
					type: 'button',
					id: triggerId.value,
					role: 'tab',
					'aria-selected': active.value,
					'aria-controls': contentId.value,
					'data-value': props.value,
					tabindex: active.value ? 0 : -1,
					disabled: props.disabled,
					'data-state': state.value,
					'data-orientation': context.value.orientation,
					class: styles[tabsStyleKeys.trigger],
					onClick: () => context.value.select(props.value),
				},
				slots.default?.(),
			);
	},
});

export const TabsContent = defineComponent({
	name: 'TabsContent',
	props: {
		value: { type: String, required: true },
	},
	setup(props, { slots }) {
		const context = inject(TabsContextKey);
		if (!context) {
			throw new Error('TabsContent must be used within <Tabs>.');
		}

		const active = computed(() => context.value.value === props.value);
		const state = computed(() => getTabsState(active.value));
		const contentId = computed(() => `${context.value.baseId}-content-${props.value}`);
		const triggerId = computed(() => `${context.value.baseId}-trigger-${props.value}`);

		return () =>
			h(
				'div',
				{
					id: contentId.value,
					role: 'tabpanel',
					'aria-labelledby': triggerId.value,
					'data-state': state.value,
					'data-orientation': context.value.orientation,
					hidden: !active.value,
					class: styles[tabsStyleKeys.content],
				},
				slots.default?.(),
			);
	},
});

export default Tabs;
