// packages/vue/src/components/collapsible/collapsible.tsx
import { computed, defineComponent, h, inject, provide, ref, useId, type ComputedRef, type InjectionKey } from 'vue';
import { collapsibleStyleKeys, getCollapsibleState } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/collapsible.module.scss';

interface CollapsibleContextValue {
	open: boolean;
	disabled: boolean;
	contentId: string;
	toggle: () => void;
}

type CollapsibleContext = ComputedRef<CollapsibleContextValue>;

const CollapsibleContextKey: InjectionKey<CollapsibleContext> = Symbol('tile-collapsible');

export const Collapsible = defineComponent({
	name: 'Collapsible',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const contentId = `tile-collapsible-${useId()}`;

		function toggle() {
			if (props.disabled) {
				return;
			}

			const next = !isOpen.value;

			if (props.open === undefined) {
				internalOpen.value = next;
			}

			emit('update:open', next);
		}

		const context = computed<CollapsibleContextValue>(() => ({
			open: isOpen.value,
			disabled: props.disabled,
			contentId,
			toggle,
		}));

		provide(CollapsibleContextKey, context);

		return () => h('div', { class: styles[collapsibleStyleKeys.root] }, slots.default?.());
	},
});

export const CollapsibleTrigger = defineComponent({
	name: 'CollapsibleTrigger',
	setup(_props, { slots }) {
		const context = inject(CollapsibleContextKey);
		if (!context) {
			throw new Error('CollapsibleTrigger must be used within <Collapsible>.');
		}

		return () =>
			h(
				'button',
				{
					type: 'button',
					'aria-expanded': context.value.open,
					'aria-controls': context.value.contentId,
					'data-state': getCollapsibleState(context.value.open),
					disabled: context.value.disabled,
					class: styles[collapsibleStyleKeys.trigger],
					onClick: context.value.toggle,
				},
				slots.default?.(),
			);
	},
});

export const CollapsibleContent = defineComponent({
	name: 'CollapsibleContent',
	setup(_props, { slots }) {
		const context = inject(CollapsibleContextKey);
		if (!context) {
			throw new Error('CollapsibleContent must be used within <Collapsible>.');
		}

		return () =>
			h('div', { id: context.value.contentId, 'data-state': getCollapsibleState(context.value.open), class: styles[collapsibleStyleKeys.content] }, [
				h('div', { class: styles[collapsibleStyleKeys.contentInner] }, slots.default?.()),
			]);
	},
});

export default Collapsible;

// packages/react/src/components/collapsible/collapsible.tsx
import React, { createContext, useCallback, useContext, useId, useState } from 'react';
import { collapsibleStyleKeys, getCollapsibleState } from '@tile-ui/core';
import type { CollapsibleBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/collapsible.module.scss';

interface CollapsibleContextValue {
	open: boolean;
	disabled: boolean;
	contentId: string;
	toggle: () => void;
}

const CollapsibleContext = createContext<CollapsibleContextValue | null>(null);

function useCollapsibleContext(): CollapsibleContextValue {
	const context = useContext(CollapsibleContext);
	if (!context) {
		throw new Error('Collapsible sub-components must be used within <Collapsible>.');
	}
	return context;
}

export interface CollapsibleProps extends React.HTMLAttributes<HTMLDivElement>, CollapsibleBaseProps {
	onOpenChange?: (open: boolean) => void;
}

const Collapsible = React.forwardRef<HTMLDivElement, CollapsibleProps>(({ className = '', open, defaultOpen = false, disabled = false, onOpenChange, children, ...props }, ref) => {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const isOpen = open !== undefined ? open : internalOpen;
	const contentId = useId();

	const toggle = useCallback(() => {
		if (disabled) {
			return;
		}

		const next = !isOpen;

		if (open === undefined) {
			setInternalOpen(next);
		}

		onOpenChange?.(next);
	}, [disabled, isOpen, open, onOpenChange]);

	return (
		<CollapsibleContext.Provider value={{ open: isOpen, disabled, contentId, toggle }}>
			<div ref={ref} className={`${styles[collapsibleStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</CollapsibleContext.Provider>
	);
});
Collapsible.displayName = 'Collapsible';

export interface CollapsibleTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {}

const CollapsibleTrigger = React.forwardRef<HTMLButtonElement, CollapsibleTriggerProps>(({ className = '', children, ...props }, ref) => {
	const context = useCollapsibleContext();
	const state = getCollapsibleState(context.open);

	return (
		<button
			ref={ref}
			type="button"
			aria-expanded={context.open}
			aria-controls={context.contentId}
			data-state={state}
			disabled={context.disabled}
			className={`${styles[collapsibleStyleKeys.trigger]} ${className}`}
			onClick={context.toggle}
			{...props}>
			{children}
		</button>
	);
});
CollapsibleTrigger.displayName = 'CollapsibleTrigger';

export interface CollapsibleContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const CollapsibleContent = React.forwardRef<HTMLDivElement, CollapsibleContentProps>(({ className = '', children, ...props }, ref) => {
	const context = useCollapsibleContext();
	const state = getCollapsibleState(context.open);

	return (
		<div ref={ref} id={context.contentId} data-state={state} className={`${styles[collapsibleStyleKeys.content]} ${className}`} {...props}>
			<div className={styles[collapsibleStyleKeys.contentInner]}>{children}</div>
		</div>
	);
});
CollapsibleContent.displayName = 'CollapsibleContent';

export { Collapsible, CollapsibleTrigger, CollapsibleContent };
export default Collapsible;
