// packages/vue/src/components/kbd/kbd.tsx
import { defineComponent, h } from 'vue';
import { kbdStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/kbd.module.scss';

export const Kbd = defineComponent({
	name: 'Kbd',
	setup(_props, { slots }) {
		return () => h('kbd', { class: styles[kbdStyleKeys.base] }, slots.default?.());
	},
});

export const KbdGroup = defineComponent({
	name: 'KbdGroup',
	setup(_props, { slots }) {
		return () => h('kbd', { class: styles[kbdStyleKeys.group] }, slots.default?.());
	},
});

export default Kbd;

// packages/react/src/components/kbd/kbd.tsx
import React from 'react';
import { kbdStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/kbd.module.scss';

export interface KbdProps extends React.HTMLAttributes<HTMLElement> {}

const Kbd = React.forwardRef<HTMLElement, KbdProps>(({ className = '', children, ...props }, ref) => {
	return (
		<kbd ref={ref} className={`${styles[kbdStyleKeys.base]} ${className}`} {...props}>
			{children}
		</kbd>
	);
});
Kbd.displayName = 'Kbd';

export interface KbdGroupProps extends React.HTMLAttributes<HTMLElement> {}

const KbdGroup = React.forwardRef<HTMLElement, KbdGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<kbd ref={ref} className={`${styles[kbdStyleKeys.group]} ${className}`} {...props}>
			{children}
		</kbd>
	);
});
KbdGroup.displayName = 'KbdGroup';

export { Kbd, KbdGroup };
export default Kbd;
