// packages/solid/src/components/kbd/kbd.tsx
import { splitProps, type JSX, type ParentProps } from 'solid-js';
import { kbdStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/kbd.module.scss';
export interface KbdProps extends JSX.HTMLAttributes<HTMLElement> {}
export function Kbd(props: ParentProps<KbdProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<kbd {...rest} class={`${styles[kbdStyleKeys.base]} ${local.class ?? ''}`}>
			{local.children}
		</kbd>
	);
}
export interface KbdGroupProps extends JSX.HTMLAttributes<HTMLElement> {}
export function KbdGroup(props: ParentProps<KbdGroupProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<kbd {...rest} class={`${styles[kbdStyleKeys.group]} ${local.class ?? ''}`}>
			{local.children}
		</kbd>
	);
}
export default Kbd;

// packages/react/src/components/kbd/kbd.tsx
import React from 'react';
import { kbdStyleKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/kbd.module.scss';

export interface KbdProps extends React.HTMLAttributes<HTMLElement> {}

const Kbd = React.forwardRef<HTMLElement, KbdProps>(({ className = '', children, ...props }, ref) => {
	return (
		<kbd ref={ref} className={`${styles[kbdStyleKeys.base]} ${className}`} {...props}>
			{children}
		</kbd>
	);
});
Kbd.displayName = 'Kbd';

export interface KbdGroupProps extends React.HTMLAttributes<HTMLElement> {}

const KbdGroup = React.forwardRef<HTMLElement, KbdGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<kbd ref={ref} className={`${styles[kbdStyleKeys.group]} ${className}`} {...props}>
			{children}
		</kbd>
	);
});
KbdGroup.displayName = 'KbdGroup';

export { Kbd, KbdGroup };
export default Kbd;
