// packages/react/src/components/combobox/combobox.tsx
import React, { useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { comboboxStyleKeys, filterComboboxItems, getSelectState, moveComboboxIndex } from '@tile-ui/core';
import type { ComboboxBaseProps, ComboboxItem } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/combobox.module.scss';

function ComboboxCheckIcon() {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="M20 6 9 17l-5-5" />
		</svg>
	);
}

function ComboboxChevronIcon() {
	return (
		<svg
			className={styles[comboboxStyleKeys.triggerIcon]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="m6 9 6 6 6-6" />
		</svg>
	);
}

export interface ComboboxProps extends React.HTMLAttributes<HTMLDivElement>, ComboboxBaseProps {
	container?: PortalContainer;
}

const Combobox = React.forwardRef<HTMLDivElement, ComboboxProps>(
	(
		{
			className = '',
			items,
			value,
			defaultValue,
			onValueChange,
			placeholder = 'Select...',
			searchPlaceholder = 'Search...',
			emptyText = 'No items.',
			notFoundText = 'No results found.',
			maxItems,
			disabled = false,
			filter,
			container,
			...props
		},
		ref,
	) => {
		const portalContainer = usePortalContainer(container);
		const [open, setOpen] = useState(false);
		const [query, setQuery] = useState('');
		const [activeValue, setActiveValue] = useState<string | null>(null);
		const [internalValue, setInternalValue] = useState(defaultValue);
		const triggerRef = useRef<HTMLButtonElement | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);
		const contentId = useId();

		const currentValue = value !== undefined ? value : internalValue;

		const filteredItems = useMemo(() => filterComboboxItems(items, query, maxItems, filter), [items, query, maxItems, filter]);

		const selectedItem = useMemo(() => items.find((item) => item.value === currentValue), [items, currentValue]);

		function setOpenState(next: boolean) {
			setOpen(next);
			if (!next) {
				setQuery('');
				setActiveValue(null);
			}
		}

		const handleTriggerClick = useCallback(() => {
			if (disabled) {
				return;
			}
			setOpenState(!open);
		}, [disabled, open]);

		const handleSelect = useCallback(
			(item: ComboboxItem) => {
				if (item.disabled) {
					return;
				}
				if (value === undefined) {
					setInternalValue(item.value);
				}
				onValueChange?.(item.value);
				setOpenState(false);
			},
			[value, onValueChange],
		);

		function handleTriggerKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) {
			if (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown' || event.key === 'ArrowUp') {
				event.preventDefault();
				if (disabled) {
					return;
				}
				setOpenState(true);
			}
		}

		function handleContentKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
			const enabledItems = filteredItems.filter((item) => !item.disabled);
			if (enabledItems.length === 0) {
				if (event.key === 'Escape') {
					event.preventDefault();
					setOpenState(false);
				}
				return;
			}

			const currentIndex = enabledItems.findIndex((item) => item.value === activeValue);

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					setActiveValue(enabledItems[moveComboboxIndex(currentIndex, 1, enabledItems.length)].value);
					break;
				case 'ArrowUp':
					event.preventDefault();
					setActiveValue(enabledItems[moveComboboxIndex(currentIndex, -1, enabledItems.length)].value);
					break;
				case 'Home':
					event.preventDefault();
					setActiveValue(enabledItems[0].value);
					break;
				case 'End':
					event.preventDefault();
					setActiveValue(enabledItems[enabledItems.length - 1].value);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					handleSelect(enabledItems[currentIndex >= 0 ? currentIndex : 0]);
					break;
				case 'Escape':
					event.preventDefault();
					setOpenState(false);
					triggerRef.current?.focus();
					break;
			}
		}

		useLayoutEffect(() => {
			if (!open) {
				return;
			}

			function updatePosition() {
				const trigger = triggerRef.current;
				const content = contentRef.current;
				if (!trigger || !content) {
					return;
				}
				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				const margin = 8;
				const left = Math.min(Math.max(triggerRect.left, margin), Math.max(margin, viewport.width - contentSize.width - margin));
				const top = Math.min(Math.max(triggerRect.bottom + 4, margin), Math.max(margin, viewport.height - contentSize.height - margin));
				content.style.top = `${top}px`;
				content.style.left = `${left}px`;
			}

			updatePosition();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			return () => {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
			};
		}, [open]);

		useEffect(() => {
			if (!open) {
				return;
			}

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				if (!target) {
					return;
				}
				const content = contentRef.current;
				const trigger = triggerRef.current;
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				setOpenState(false);
			}

			document.addEventListener('pointerdown', handlePointerDown);
			return () => document.removeEventListener('pointerdown', handlePointerDown);
		}, [open]);

		const state = getSelectState(open);
		const showEmpty = filteredItems.length === 0;
		const emptyMessage = query ? notFoundText : emptyText;

		const content = open ? (
			<div ref={contentRef} id={contentId} role="listbox" tabIndex={-1} data-state={state} className={styles[comboboxStyleKeys.content]} onKeyDown={handleContentKeyDown}>
				<div className={styles[comboboxStyleKeys.search]}>
					<input
						role="combobox"
						aria-expanded={open}
						aria-controls={contentId}
						aria-autocomplete="list"
						className={styles[comboboxStyleKeys.searchInput]}
						value={query}
						placeholder={searchPlaceholder}
						autoFocus
						onChange={(event) => {
							setQuery(event.target.value);
							setActiveValue(null);
						}}
					/>
				</div>
				<div className={styles[comboboxStyleKeys.list]}>
					{showEmpty ? (
						<div className={styles[comboboxStyleKeys.empty]}>{emptyMessage}</div>
					) : (
						filteredItems.map((item) => {
							const isActive = activeValue === item.value;
							const isSelected = item.value === currentValue;
							return (
								<div
									key={item.value}
									role="option"
									tabIndex={-1}
									aria-selected={isSelected}
									data-highlighted={isActive}
									data-disabled={item.disabled}
									className={styles[comboboxStyleKeys.item]}
									onMouseEnter={() => {
										if (!item.disabled) {
											setActiveValue(item.value);
										}
									}}
									onClick={() => handleSelect(item)}>
									<span className={styles[comboboxStyleKeys.itemIndicator]}>{isSelected && <ComboboxCheckIcon />}</span>
									{item.label}
								</div>
							);
						})
					)}
				</div>
			</div>
		) : null;

		return (
			<div ref={ref} className={`${styles[comboboxStyleKeys.root]} ${className}`} {...props}>
				<button
					ref={triggerRef}
					type="button"
					aria-haspopup="listbox"
					aria-expanded={open}
					aria-controls={contentId}
					data-disabled={disabled}
					className={styles[comboboxStyleKeys.trigger]}
					onClick={handleTriggerClick}
					onKeyDown={handleTriggerKeyDown}>
					<span data-placeholder={!selectedItem} className={styles[comboboxStyleKeys.triggerValue]}>
						{selectedItem?.label ?? placeholder}
					</span>
					<ComboboxChevronIcon />
				</button>
				{open && portalContainer ? createPortal(content, portalContainer) : null}
			</div>
		);
	},
);
Combobox.displayName = 'Combobox';

export { Combobox };
export default Combobox;

// packages/solid/src/components/combobox/combobox.tsx
import { For, Show, createEffect, createSignal, createUniqueId, onCleanup, splitProps, type JSX } from 'solid-js';
import { Portal, isServer } from 'solid-js/web';
import { comboboxStyleKeys, filterComboboxItems, getSelectPosition, getSelectState, moveComboboxIndex } from '@tile-ui/core';
import type { ComboboxBaseProps, ComboboxItem } from '@tile-ui/core';
import {
	createAnchoredPosition,
	createControllableSignal,
	createPortalScope,
	isNodeValue,
	PortalScopeContext,
	registerDismissableLayer,
	resolvePortalContainer,
	usePortalScope,
	type CallbackRef,
} from '../../utils';
import { getLogicalTabTarget } from '../select/logical-tab';
import styles from '@tile-ui/styles/scss/components/combobox.module.scss';

function ComboboxCheckIcon() {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
			aria-hidden="true">
			<path d="M20 6 9 17l-5-5" />
		</svg>
	);
}

function ComboboxChevronIcon() {
	return (
		<svg
			class={styles[comboboxStyleKeys.triggerIcon]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
			aria-hidden="true">
			<path d="m6 9 6 6 6-6" />
		</svg>
	);
}

export interface ComboboxProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'onChange' | 'ref'>, Omit<ComboboxBaseProps, 'value'> {
	value?: string;
	defaultValue?: string;
	onValueChange?: (value: string) => void;
	container?: Node;
	triggerId?: string;
	contentId?: string;
	inputId?: string;
	ref?: CallbackRef<HTMLDivElement>;
}

/** SolidJS Combobox：数据驱动单选搜索，打开与搜索保持内部状态。 */
export function Combobox(props: ComboboxProps) {
	const [local, rest] = splitProps(props, [
		'items',
		'value',
		'defaultValue',
		'onValueChange',
		'placeholder',
		'searchPlaceholder',
		'emptyText',
		'notFoundText',
		'maxItems',
		'disabled',
		'filter',
		'container',
		'triggerId',
		'contentId',
		'inputId',
		'class',
		'ref',
	]);
	const [value, setValue] = createControllableSignal<string | undefined>({
		value: () => local.value,
		defaultValue: () => local.defaultValue,
		onChange: (next) => next !== undefined && local.onValueChange?.(next),
	});
	const [open, setOpen] = createSignal(false);
	const [openIntent, setOpenIntent] = createSignal<'first' | 'selected-or-first' | 'selected-or-last'>('selected-or-first');
	const [search, setSearch] = createSignal('');
	const [active, setActive] = createSignal<string>();
	const baseId = `tile-solid-combobox-${createUniqueId()}`;
	const triggerId = () => local.triggerId ?? `${baseId}-trigger`;
	const contentId = () => local.contentId ?? `${baseId}-content`;
	const popupId = () => `${contentId()}-popup`;
	const inputId = () => local.inputId ?? `${baseId}-input`;
	const emptyId = () => `${contentId()}-empty`;
	const optionId = (item: ComboboxItem) => `${contentId()}-option-${encodeURIComponent(item.value)}`;
	const activeOptionId = () => {
		const item = enabled().find((candidate) => candidate.value === active());
		return item ? optionId(item) : undefined;
	};
	const filtered = () => filterComboboxItems(local.items, search(), local.maxItems, local.filter);
	const enabled = () => filtered().filter((item) => !item.disabled);
	const empty = () => filtered().length === 0;
	const selected = () => local.items.find((item) => item.value === value());
	let trigger: HTMLButtonElement | undefined;
	let content: HTMLDivElement | undefined;
	let input: HTMLInputElement | undefined;
	const parentScope = usePortalScope();
	const mount = () => resolvePortalContainer(parentScope, local.container);
	const scope = createPortalScope(mount, parentScope);
	const close = (restore = false) => {
		setOpen(false);
		setSearch('');
		setActive(undefined);
		if (restore) trigger?.focus();
	};
	const choose = (item: ComboboxItem) => {
		if (item.disabled) return;
		setValue(item.value);
		close(true);
	};
	const positioner = createAnchoredPosition({
		anchor: () => trigger,
		content: () => content,
		container: () => {
			const container = mount();
			const ElementConstructor = isNodeValue(container) ? container.ownerDocument?.defaultView?.Element : undefined;
			return ElementConstructor && container instanceof ElementConstructor ? container : undefined;
		},
		open,
		onPosition: ({ anchorRect, contentRect, containerRect, direction }) => {
			if (!content) return;
			const next = getSelectPosition({ triggerRect: anchorRect, contentSize: contentRect, viewport: containerRect, sideOffset: 4, align: 'start', rtl: direction === 'rtl' });
			content.style.left = `${next.left + containerRect.left}px`;
			content.style.top = `${next.top + containerRect.top}px`;
		},
	});
	createEffect(() => {
		if (!open()) return;
		queueMicrotask(() => {
			positioner.recompute();
			const items = enabled();
			const selectedItem = items.find((item) => item.value === value());
			setActive(openIntent() === 'first' ? items[0]?.value : (selectedItem?.value ?? (openIntent() === 'selected-or-last' ? items.at(-1)?.value : items[0]?.value)));
			input?.focus();
		});
	});
	createEffect(() => {
		if (!open() || !content) return;
		const removeBranch = scope.addBranch(content);
		let restore = true;
		const layer = registerDismissableLayer({
			element: () => content,
			branches: () => (trigger ? [trigger] : []),
			portalScope: scope,
			onFocusOutside: () => {
				restore = false;
			},
			onDismiss: () => close(restore),
		});
		queueMicrotask(layer.update);
		onCleanup(() => {
			layer.destroy();
			removeBranch();
		});
	});
	onCleanup(() => positioner.destroy());

	function move(key: string) {
		const items = enabled();
		if (items.length === 0) return;
		const current = items.findIndex((item) => item.value === active());
		if (key === 'Home') setActive(items[0].value);
		else if (key === 'End') setActive(items.at(-1)!.value);
		else setActive(items[moveComboboxIndex(current, key === 'ArrowDown' ? 1 : -1, items.length)].value);
	}

	const popup = (
		<PortalScopeContext.Provider value={scope}>
			<div
				ref={(element) => (content = element)}
				id={popupId()}
				hidden={!open()}
				data-slot="combobox-content"
				data-state={getSelectState(open())}
				class={styles[comboboxStyleKeys.content]}>
				<div class={styles[comboboxStyleKeys.search]}>
					<input
						ref={(element) => (input = element)}
						id={inputId()}
						role="combobox"
						aria-autocomplete="list"
						aria-expanded={open()}
						aria-controls={contentId()}
						aria-activedescendant={activeOptionId()}
						aria-describedby={empty() ? emptyId() : undefined}
						value={search()}
						placeholder={local.searchPlaceholder ?? 'Search...'}
						class={styles[comboboxStyleKeys.searchInput]}
						onInput={(event) => {
							setSearch(event.currentTarget.value);
							queueMicrotask(() => setActive(enabled()[0]?.value));
						}}
						onPaste={() => queueMicrotask(() => setActive(enabled()[0]?.value))}
						onKeyDown={(event) => {
							if (event.key === 'Tab') {
								if (event.ctrlKey || event.metaKey || event.altKey) return;
								event.preventDefault();
								close();
								getLogicalTabTarget(trigger, content, event.shiftKey)?.focus();
							} else if (['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key)) {
								event.preventDefault();
								move(event.key);
							} else if (event.key === 'Enter') {
								const item = enabled().find((candidate) => candidate.value === active());
								if (item) {
									event.preventDefault();
									choose(item);
								}
							} else if (event.key === 'Escape') {
								event.preventDefault();
								close(true);
							}
						}}
					/>
				</div>
				<div id={contentId()} role="listbox" data-slot="combobox-list" class={styles[comboboxStyleKeys.list]}>
					<For each={filtered()}>
						{(item) => (
							<div
								id={optionId(item)}
								role="option"
								aria-selected={value() === item.value}
								aria-disabled={item.disabled || undefined}
								data-highlighted={active() === item.value || undefined}
								data-disabled={item.disabled || undefined}
								data-slot="combobox-item"
								class={styles[comboboxStyleKeys.item]}
								onPointerMove={() => !item.disabled && setActive(item.value)}
								onClick={() => choose(item)}>
								<span class={styles[comboboxStyleKeys.itemIndicator]}>
									<Show when={value() === item.value}>
										<ComboboxCheckIcon />
									</Show>
								</span>
								{item.label}
							</div>
						)}
					</For>
				</div>
				<Show when={empty()}>
					<div id={emptyId()} role="status" data-slot="combobox-empty" class={styles[comboboxStyleKeys.empty]}>
						{search() ? (local.notFoundText ?? 'No results found.') : (local.emptyText ?? 'No items.')}
					</div>
				</Show>
			</div>
		</PortalScopeContext.Provider>
	);

	return (
		<div
			{...rest}
			ref={local.ref}
			data-slot="combobox"
			data-state={getSelectState(open())}
			data-disabled={local.disabled || undefined}
			class={`${styles[comboboxStyleKeys.root]} ${local.class ?? ''}`}>
			<button
				ref={(element) => (trigger = element)}
				id={triggerId()}
				type="button"
				role={open() ? undefined : 'combobox'}
				aria-label={selected()?.label ?? local.placeholder ?? 'Select...'}
				aria-haspopup="listbox"
				aria-expanded={open()}
				aria-controls={contentId()}
				disabled={local.disabled}
				class={styles[comboboxStyleKeys.trigger]}
				onClick={() => {
					if (local.disabled) return;
					setOpenIntent('selected-or-first');
					setOpen((current) => !current);
				}}
				onKeyDown={(event) => {
					if (!local.disabled && ['Enter', ' ', 'ArrowDown', 'ArrowUp'].includes(event.key)) {
						event.preventDefault();
						setOpenIntent(event.key === 'ArrowDown' ? 'first' : event.key === 'ArrowUp' ? 'selected-or-last' : 'selected-or-first');
						setOpen(true);
					}
				}}>
				<span data-placeholder={!selected() || undefined} class={styles[comboboxStyleKeys.triggerValue]}>
					{selected()?.label ?? local.placeholder ?? 'Select...'}
				</span>
				<ComboboxChevronIcon />
			</button>
			{isServer ? <Show when={open()}>{popup}</Show> : <Portal mount={mount()}>{popup}</Portal>}
		</div>
	);
}

export default Combobox;
