// packages/vue/src/components/menubar/menubar.tsx
import {
	computed,
	defineComponent,
	h,
	inject,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	useId,
	watch,
	Teleport,
	type ComputedRef,
	type InjectionKey,
	type PropType,
	type Ref,
} from 'vue';
import { getMenubarCheckState, getMenubarPosition, getMenubarState, menubarStyleKeys } from '@tile-ui/core';
import type { MenubarAlign, MenubarSide } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/menubar.module.scss';

interface MenubarContextValue {
	activeValue: string | undefined;
	setActiveValue: (value: string | undefined) => void;
}

type MenubarContext = ComputedRef<MenubarContextValue>;

const MenubarContextKey: InjectionKey<MenubarContext> = Symbol('tile-menubar');

interface MenubarMenuContextValue {
	value: string;
	open: boolean;
	triggerRef: Ref<HTMLElement | null>;
	contentId: string;
	setOpen: (open: boolean) => void;
}

type MenubarMenuContext = ComputedRef<MenubarMenuContextValue>;

const MenubarMenuContextKey: InjectionKey<MenubarMenuContext> = Symbol('tile-menubar-menu');

interface MenubarContentContextValue {
	itemsRef: Ref<HTMLElement[]>;
	close: () => void;
}

type MenubarContentContext = ComputedRef<MenubarContentContextValue>;

const MenubarContentContextKey: InjectionKey<MenubarContentContext> = Symbol('tile-menubar-content');

interface MenubarSubContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	triggerRef: Ref<HTMLElement | null>;
}

type MenubarSubContext = ComputedRef<MenubarSubContextValue>;

const MenubarSubContextKey: InjectionKey<MenubarSubContext> = Symbol('tile-menubar-sub');

interface MenubarRadioGroupContextValue {
	value: string | undefined;
	setValue: (value: string) => void;
}

type MenubarRadioGroupContext = ComputedRef<MenubarRadioGroupContextValue>;

const MenubarRadioGroupContextKey: InjectionKey<MenubarRadioGroupContext> = Symbol('tile-menubar-radio-group');

function menubarCheckIcon() {
	return h(
		'svg',
		{
			class: styles[menubarStyleKeys.checkIcon],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'M20 6 9 17l-5-5' })],
	);
}

function menubarRadioIcon() {
	return h(
		'svg',
		{
			class: styles[menubarStyleKeys.radioIcon],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'currentColor',
			'aria-hidden': 'true',
		},
		[h('circle', { cx: '12', cy: '12', r: '6' })],
	);
}

function menubarChevronIcon() {
	return h(
		'svg',
		{
			class: styles[menubarStyleKeys.chevron],
			xmlns: 'http://www.w3.org/2000/svg',
			width: '16',
			height: '16',
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			'stroke-width': '2',
			'stroke-linecap': 'round',
			'stroke-linejoin': 'round',
			'aria-hidden': 'true',
		},
		[h('path', { d: 'm9 18 6-6-6-6' })],
	);
}

function useMenubarContext(): MenubarContext {
	const context = inject(MenubarContextKey);
	if (!context) {
		throw new Error('Menubar 子组件必须位于 <Menubar> 内部。');
	}
	return context;
}

function useMenubarMenuContext(): MenubarMenuContext {
	const context = inject(MenubarMenuContextKey);
	if (!context) {
		throw new Error('Menubar 菜单子组件必须位于 <MenubarMenu> 内部。');
	}
	return context;
}

function useMenubarContentContext(): MenubarContentContext {
	const context = inject(MenubarContentContextKey);
	if (!context) {
		throw new Error('Menubar 菜单项必须位于 <MenubarContent> 或 <MenubarSubContent> 内部。');
	}
	return context;
}

function useMenubarSubContext(): MenubarSubContext {
	const context = inject(MenubarSubContextKey);
	if (!context) {
		throw new Error('Menubar 子菜单组件必须位于 <MenubarSub> 内部。');
	}
	return context;
}

function useMenubarRadioGroupContext(): MenubarRadioGroupContext {
	const context = inject(MenubarRadioGroupContextKey);
	if (!context) {
		throw new Error('MenubarRadioItem 必须位于 <MenubarRadioGroup> 内部。');
	}
	return context;
}

export const Menubar = defineComponent({
	name: 'Menubar',
	props: {
		value: { type: String, default: undefined },
		defaultValue: { type: String, default: undefined },
	},
	emits: ['update:value'],
	setup(props, { emit, slots, attrs }) {
		const internalValue = ref(props.defaultValue);
		const activeValue = computed(() => (props.value !== undefined ? props.value : internalValue.value));

		function setActiveValue(next: string | undefined) {
			if (props.value === undefined) {
				internalValue.value = next;
			}
			emit('update:value', next);
		}

		const context = computed<MenubarContextValue>(() => ({ activeValue: activeValue.value, setActiveValue }));

		provide(MenubarContextKey, context);

		return () => h('div', { ...attrs, class: [styles[menubarStyleKeys.root], attrs.class] }, slots.default?.());
	},
});

export const MenubarPortal = defineComponent({
	name: 'MenubarPortal',
	setup(_props, { slots }) {
		return () => slots.default?.();
	},
});

export const MenubarMenu = defineComponent({
	name: 'MenubarMenu',
	props: {
		value: { type: String, required: true },
	},
	setup(props, { slots }) {
		const context = useMenubarContext();
		const triggerRef = ref<HTMLElement | null>(null);
		const contentId = `tile-menubar-${useId()}`;
		const open = computed(() => context.value.activeValue === props.value);

		function setOpen(next: boolean) {
			context.value.setActiveValue(next ? props.value : undefined);
		}

		const menuContext = computed<MenubarMenuContextValue>(() => ({
			value: props.value,
			open: open.value,
			triggerRef,
			contentId,
			setOpen,
		}));

		provide(MenubarMenuContextKey, menuContext);

		return () => h('div', { class: styles[menubarStyleKeys.menu] }, slots.default?.());
	},
});

export const MenubarTrigger = defineComponent({
	name: 'MenubarTrigger',
	inheritAttrs: false,
	props: {
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useMenubarMenuContext();

		function handleClick() {
			if (props.disabled) {
				return;
			}
			context.value.setOpen(!context.value.open);
		}

		function handleKeyDown(event: KeyboardEvent) {
			if (event.defaultPrevented || props.disabled) {
				return;
			}
			if (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown' || event.key === 'ArrowUp') {
				event.preventDefault();
				context.value.setOpen(true);
			}
		}

		return () =>
			h(
				'button',
				{
					...attrs,
					ref: context.value.triggerRef,
					type: 'button',
					'aria-haspopup': 'menu',
					'aria-expanded': context.value.open,
					'aria-controls': context.value.contentId,
					'data-state': getMenubarState(context.value.open),
					'data-disabled': props.disabled,
					class: [styles[menubarStyleKeys.trigger], attrs.class],
					onClick: handleClick,
					onKeydown: handleKeyDown,
				},
				slots.default?.(),
			);
	},
});

function createMenubarContentBase({ isSub = false }: { isSub?: boolean } = {}) {
	interface ContentContext {
		open: boolean;
		setOpen: (open: boolean) => void;
		triggerRef: Ref<HTMLElement | null>;
		contentId?: string;
	}

	return defineComponent({
		name: isSub ? 'MenubarSubContent' : 'MenubarContent',
		inheritAttrs: false,
		props: {
			side: { type: String as PropType<MenubarSide>, default: 'bottom' },
			align: { type: String as PropType<MenubarAlign>, default: 'start' },
			sideOffset: { type: Number, default: 8 },
			alignOffset: { type: Number, default: -4 },
		},
		setup(props, { slots, attrs }) {
			const context = (isSub ? useMenubarSubContext() : useMenubarMenuContext()) as ComputedRef<ContentContext>;
			const contentRef = ref<HTMLElement | null>(null);
			const itemsRef = ref<HTMLElement[]>([]);
			const position = ref<{ top: number; left: number } | null>(null);

			const contentContext = computed<MenubarContentContextValue>(() => ({
				itemsRef,
				close: () => context.value.setOpen(false),
			}));

			provide(MenubarContentContextKey, contentContext);

			let disposeDocListeners: (() => void) | null = null;

			function updatePosition() {
				const trigger = context.value.triggerRef.value;
				const content = contentRef.value;
				if (!trigger || !content) {
					return;
				}
				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				position.value = getMenubarPosition({
					triggerRect,
					contentSize,
					side: props.side,
					align: props.align,
					sideOffset: props.sideOffset,
					alignOffset: props.alignOffset,
					viewport,
				});
			}

			function highlightFirst() {
				const items = itemsRef.value;
				if (items.length === 0) {
					return;
				}
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[0].setAttribute('data-highlighted', 'true');
				items[0].focus();
			}

			function handleOpen() {
				updatePosition();
				highlightFirst();
				window.addEventListener('resize', updatePosition);
				document.addEventListener('scroll', updatePosition, true);

				function handlePointerDown(event: PointerEvent) {
					const target = event.target as Node | null;
					const content = contentRef.value;
					const trigger = context.value.triggerRef.value;
					if (!target) {
						return;
					}
					if (content && content.contains(target)) {
						return;
					}
					if (trigger && trigger.contains(target)) {
						return;
					}
					context.value.setOpen(false);
				}

				document.addEventListener('pointerdown', handlePointerDown);
				disposeDocListeners = () => document.removeEventListener('pointerdown', handlePointerDown);
			}

			function handleClose() {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
				disposeDocListeners?.();
				disposeDocListeners = null;
			}

			onMounted(() => {
				if (context.value.open) {
					handleOpen();
				}
			});

			watch(
				() => context.value.open,
				(open) => {
					if (open) {
						handleOpen();
					} else {
						handleClose();
					}
				},
			);

			watch(
				() => [props.side, props.align, props.sideOffset, props.alignOffset],
				() => {
					if (context.value.open) {
						updatePosition();
					}
				},
			);

			onBeforeUnmount(handleClose);

			function handleKeyDown(event: KeyboardEvent) {
				const items = itemsRef.value.filter((item) => item.getAttribute('data-disabled') !== 'true');

				if (event.key === 'Escape' || (isSub && event.key === 'ArrowLeft')) {
					event.preventDefault();
					context.value.setOpen(false);
					context.value.triggerRef.value?.focus();
					return;
				}

				if (items.length === 0) {
					return;
				}

				const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');

				const highlight = (next: number) => {
					items.forEach((item) => item.removeAttribute('data-highlighted'));
					items[next].setAttribute('data-highlighted', 'true');
					items[next].focus();
				};

				switch (event.key) {
					case 'ArrowDown':
						event.preventDefault();
						highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
						break;
					case 'ArrowUp':
						event.preventDefault();
						highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
						break;
					case 'Home':
						event.preventDefault();
						highlight(0);
						break;
					case 'End':
						event.preventDefault();
						highlight(items.length - 1);
						break;
					case 'Enter':
					case ' ':
						event.preventDefault();
						(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
						break;
				}
			}

			return () => {
				const open = context.value.open;
				const userClass = attrs.class;
				const userStyle = attrs.style;
				const restAttrs = { ...attrs };
				delete restAttrs.class;
				delete restAttrs.style;

				return h(Teleport, { to: 'body' }, [
					h(
						'div',
						{
							...restAttrs,
							ref: contentRef,
							id: isSub ? undefined : context.value.contentId,
							role: 'menu',
							tabindex: -1,
							'data-state': getMenubarState(open),
							'data-side': props.side,
							'data-align': props.align,
							class: [styles[isSub ? menubarStyleKeys.subContent : menubarStyleKeys.content], userClass],
							style: position.value ? [userStyle, { top: `${position.value.top}px`, left: `${position.value.left}px` }] : userStyle,
							onKeydown: handleKeyDown,
						},
						slots.default?.(),
					),
				]);
			};
		},
	});
}

export const MenubarContent = createMenubarContentBase({ isSub: false });
export const MenubarSubContent = createMenubarContentBase({ isSub: true });

export const MenubarGroup = defineComponent({
	name: 'MenubarGroup',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, role: 'group', class: [styles[menubarStyleKeys.group], attrs.class] }, slots.default?.());
	},
});

export const MenubarLabel = defineComponent({
	name: 'MenubarLabel',
	inheritAttrs: false,
	props: {
		inset: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-inset': props.inset, class: [styles[menubarStyleKeys.label], attrs.class] }, slots.default?.());
	},
});

export const MenubarSeparator = defineComponent({
	name: 'MenubarSeparator',
	setup(_props, { attrs }) {
		return () => h('div', { ...attrs, role: 'separator', class: [styles[menubarStyleKeys.separator], attrs.class] });
	},
});

export const MenubarShortcut = defineComponent({
	name: 'MenubarShortcut',
	setup(_props, { slots, attrs }) {
		return () => h('span', { ...attrs, class: [styles[menubarStyleKeys.shortcut], attrs.class] }, slots.default?.());
	},
});

export const MenubarItem = defineComponent({
	name: 'MenubarItem',
	inheritAttrs: false,
	props: {
		inset: { type: Boolean, default: false },
		variant: { type: String as PropType<'default' | 'destructive'>, default: 'default' },
		disabled: { type: Boolean, default: false },
	},
	emits: ['select'],
	setup(props, { emit, slots, attrs }) {
		const context = useMenubarContentContext();
		const itemRef = ref<HTMLElement | null>(null);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick(event: MouseEvent) {
			if (props.disabled) {
				return;
			}
			emit('select', event);
			context.value.close();
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'menuitem',
					tabindex: -1,
					'data-inset': props.inset,
					'data-variant': props.variant,
					'data-disabled': props.disabled,
					class: [styles[menubarStyleKeys.item], attrs.class],
					onClick: handleClick,
				},
				slots.default?.(),
			);
	},
});

export const MenubarCheckboxItem = defineComponent({
	name: 'MenubarCheckboxItem',
	inheritAttrs: false,
	props: {
		checked: { type: Boolean, default: undefined },
		defaultChecked: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:checked'],
	setup(props, { emit, slots, attrs }) {
		const context = useMenubarContentContext();
		const itemRef = ref<HTMLElement | null>(null);
		const internalChecked = ref(props.defaultChecked);
		const isChecked = computed(() => (props.checked !== undefined ? props.checked : internalChecked.value));

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick() {
			if (props.disabled) {
				return;
			}
			const next = !isChecked.value;
			if (props.checked === undefined) {
				internalChecked.value = next;
			}
			emit('update:checked', next);
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'menuitemcheckbox',
					tabindex: -1,
					'aria-checked': isChecked.value,
					'data-checked': getMenubarCheckState(isChecked.value),
					'data-disabled': props.disabled,
					class: [styles[menubarStyleKeys.checkboxItem], attrs.class],
					onClick: handleClick,
				},
				[h('span', { class: styles[menubarStyleKeys.indicator] }, [isChecked.value ? menubarCheckIcon() : null]), ...(slots.default?.() ?? [])],
			);
	},
});

export const MenubarRadioGroup = defineComponent({
	name: 'MenubarRadioGroup',
	inheritAttrs: false,
	props: {
		value: { type: String, default: undefined },
		defaultValue: { type: String, default: undefined },
	},
	emits: ['update:value'],
	setup(props, { emit, slots, attrs }) {
		const internalValue = ref(props.defaultValue);
		const resolvedValue = computed(() => (props.value !== undefined ? props.value : internalValue.value));

		function setValue(next: string) {
			if (props.value === undefined) {
				internalValue.value = next;
			}
			emit('update:value', next);
		}

		const context = computed<MenubarRadioGroupContextValue>(() => ({ value: resolvedValue.value, setValue }));

		provide(MenubarRadioGroupContextKey, context);

		return () => h('div', { ...attrs, role: 'group', class: [styles[menubarStyleKeys.radioGroup], attrs.class] }, slots.default?.());
	},
});

export const MenubarRadioItem = defineComponent({
	name: 'MenubarRadioItem',
	inheritAttrs: false,
	props: {
		value: { type: String, required: true },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useMenubarContentContext();
		const group = useMenubarRadioGroupContext();
		const itemRef = ref<HTMLElement | null>(null);
		const isChecked = computed(() => group.value.value === props.value);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function handleClick() {
			if (props.disabled) {
				return;
			}
			group.value.setValue(props.value);
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: itemRef,
					role: 'menuitemradio',
					tabindex: -1,
					'aria-checked': isChecked.value,
					'data-checked': getMenubarCheckState(isChecked.value),
					'data-disabled': props.disabled,
					class: [styles[menubarStyleKeys.radioItem], attrs.class],
					onClick: handleClick,
				},
				[h('span', { class: styles[menubarStyleKeys.indicator] }, [isChecked.value ? menubarRadioIcon() : null]), ...(slots.default?.() ?? [])],
			);
	},
});

export const MenubarSub = defineComponent({
	name: 'MenubarSub',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const triggerRef = ref<HTMLElement | null>(null);

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		const context = computed<MenubarSubContextValue>(() => ({ open: isOpen.value, setOpen, triggerRef }));

		provide(MenubarSubContextKey, context);

		return () => slots.default?.();
	},
});

export const MenubarSubTrigger = defineComponent({
	name: 'MenubarSubTrigger',
	inheritAttrs: false,
	props: {
		inset: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const context = useMenubarContentContext();
		const sub = useMenubarSubContext();
		const itemRef = ref<HTMLElement | null>(null);

		onMounted(() => {
			if (itemRef.value) {
				context.value.itemsRef.value.push(itemRef.value);
			}
		});

		onBeforeUnmount(() => {
			context.value.itemsRef.value = context.value.itemsRef.value.filter((item) => item !== itemRef.value);
		});

		function setRef(el: unknown) {
			itemRef.value = (el as HTMLElement | null) ?? null;
			sub.value.triggerRef.value = itemRef.value;
		}

		function handleMouseEnter() {
			if (props.disabled) {
				return;
			}
			sub.value.setOpen(true);
		}

		function handleClick() {
			if (props.disabled) {
				return;
			}
			sub.value.setOpen(!sub.value.open);
		}

		function handleKeyDown(event: KeyboardEvent) {
			if (props.disabled) {
				return;
			}
			if (event.key === 'ArrowRight' || event.key === 'Enter' || event.key === ' ') {
				event.preventDefault();
				sub.value.setOpen(true);
			}
		}

		return () =>
			h(
				'div',
				{
					...attrs,
					ref: setRef,
					role: 'menuitem',
					tabindex: -1,
					'aria-haspopup': 'menu',
					'aria-expanded': sub.value.open,
					'data-state': getMenubarState(sub.value.open),
					'data-inset': props.inset,
					'data-disabled': props.disabled,
					class: [styles[menubarStyleKeys.subTrigger], attrs.class],
					onMouseenter: handleMouseEnter,
					onClick: handleClick,
					onKeydown: handleKeyDown,
				},
				[...(slots.default?.() ?? []), menubarChevronIcon()],
			);
	},
});

export default Menubar;

// packages/react/src/components/menubar/menubar.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { getMenubarCheckState, getMenubarPosition, getMenubarState, menubarStyleKeys } from '@tile-ui/core';
import type {
	MenubarBaseProps,
	MenubarCheckboxItemBaseProps,
	MenubarContentBaseProps,
	MenubarItemBaseProps,
	MenubarLabelBaseProps,
	MenubarMenuBaseProps,
	MenubarPosition,
	MenubarRadioGroupBaseProps,
	MenubarRadioItemBaseProps,
	MenubarSubBaseProps,
	MenubarSubTriggerBaseProps,
	MenubarTriggerBaseProps,
} from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/menubar.module.scss';

interface MenubarContextValue {
	activeValue: string | undefined;
	setActiveValue: (value: string | undefined) => void;
}

const MenubarContext = createContext<MenubarContextValue | null>(null);

function useMenubarContext(): MenubarContextValue {
	const context = useContext(MenubarContext);
	if (!context) {
		throw new Error('Menubar 子组件必须位于 <Menubar> 内部。');
	}
	return context;
}

interface MenubarMenuContextValue {
	value: string;
	open: boolean;
	triggerRef: React.RefObject<HTMLElement | null>;
	contentId: string;
	setOpen: (open: boolean) => void;
}

const MenubarMenuContext = createContext<MenubarMenuContextValue | null>(null);

function useMenubarMenuContext(): MenubarMenuContextValue {
	const context = useContext(MenubarMenuContext);
	if (!context) {
		throw new Error('Menubar 菜单子组件必须位于 <MenubarMenu> 内部。');
	}
	return context;
}

interface MenubarContentContextValue {
	itemsRef: React.RefObject<HTMLElement[]>;
	close: () => void;
}

const MenubarContentContext = createContext<MenubarContentContextValue | null>(null);

function useMenubarContentContext(): MenubarContentContextValue {
	const context = useContext(MenubarContentContext);
	if (!context) {
		throw new Error('Menubar 菜单项必须位于 <MenubarContent> 或 <MenubarSubContent> 内部。');
	}
	return context;
}

interface MenubarSubContextValue {
	open: boolean;
	setOpen: (open: boolean) => void;
	triggerRef: React.RefObject<HTMLElement | null>;
}

const MenubarSubContext = createContext<MenubarSubContextValue | null>(null);

function useMenubarSubContext(): MenubarSubContextValue {
	const context = useContext(MenubarSubContext);
	if (!context) {
		throw new Error('Menubar 子菜单组件必须位于 <MenubarSub> 内部。');
	}
	return context;
}

interface MenubarRadioGroupContextValue {
	value: string | undefined;
	setValue: (value: string) => void;
}

const MenubarRadioGroupContext = createContext<MenubarRadioGroupContextValue | null>(null);

function useMenubarRadioGroupContext(): MenubarRadioGroupContextValue {
	const context = useContext(MenubarRadioGroupContext);
	if (!context) {
		throw new Error('MenubarRadioItem 必须位于 <MenubarRadioGroup> 内部。');
	}
	return context;
}

function MenubarCheckIcon() {
	return (
		<svg
			className={styles[menubarStyleKeys.checkIcon]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="M20 6 9 17l-5-5" />
		</svg>
	);
}

function MenubarRadioIcon() {
	return (
		<svg className={styles[menubarStyleKeys.radioIcon]} xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
			<circle cx="12" cy="12" r="6" />
		</svg>
	);
}

function MenubarChevronIcon() {
	return (
		<svg
			className={styles[menubarStyleKeys.chevron]}
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true">
			<path d="m9 18 6-6-6-6" />
		</svg>
	);
}

export interface MenubarProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'defaultValue'>, MenubarBaseProps {}

const Menubar = React.forwardRef<HTMLDivElement, MenubarProps>(({ className = '', value, defaultValue, onValueChange, children, ...props }, ref) => {
	const [internalValue, setInternalValue] = useState(defaultValue);
	const activeValue = value !== undefined ? value : internalValue;

	const setActiveValue = useCallback(
		(next: string | undefined) => {
			if (value === undefined) {
				setInternalValue(next);
			}
			onValueChange?.(next);
		},
		[value, onValueChange],
	);

	return (
		<MenubarContext.Provider value={{ activeValue, setActiveValue }}>
			<div ref={ref} className={`${styles[menubarStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</MenubarContext.Provider>
	);
});
Menubar.displayName = 'Menubar';

export interface MenubarPortalProps {
	children?: React.ReactNode;
}

const MenubarPortal = ({ children }: MenubarPortalProps) => {
	return <>{children}</>;
};
MenubarPortal.displayName = 'MenubarPortal';

export interface MenubarMenuProps extends MenubarMenuBaseProps {
	children?: React.ReactNode;
}

const MenubarMenu = ({ value, children }: MenubarMenuProps) => {
	const { activeValue, setActiveValue } = useMenubarContext();
	const open = activeValue === value;
	const triggerRef = useRef<HTMLElement | null>(null);
	const contentId = useId();

	const setOpen = useCallback(
		(next: boolean) => {
			setActiveValue(next ? value : undefined);
		},
		[value, setActiveValue],
	);

	return (
		<MenubarMenuContext.Provider value={{ value, open, triggerRef, contentId, setOpen }}>
			<div className={styles[menubarStyleKeys.menu]}>{children}</div>
		</MenubarMenuContext.Provider>
	);
};
MenubarMenu.displayName = 'MenubarMenu';

export interface MenubarTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, MenubarTriggerBaseProps {}

const MenubarTrigger = React.forwardRef<HTMLButtonElement, MenubarTriggerProps>(({ className = '', disabled = false, children, onClick, onKeyDown, ...props }, ref) => {
	const context = useMenubarMenuContext();

	function setRef(element: HTMLButtonElement | null) {
		context.triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
		onClick?.(event);
		if (disabled) {
			return;
		}
		context.setOpen(!context.open);
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) {
		onKeyDown?.(event);
		if (event.defaultPrevented || disabled) {
			return;
		}
		if (event.key === 'Enter' || event.key === ' ' || event.key === 'ArrowDown' || event.key === 'ArrowUp') {
			event.preventDefault();
			context.setOpen(true);
		}
	}

	const state = getMenubarState(context.open);

	return (
		<button
			ref={setRef}
			type="button"
			aria-haspopup="menu"
			aria-expanded={context.open}
			aria-controls={context.contentId}
			data-state={state}
			data-disabled={disabled}
			className={`${styles[menubarStyleKeys.trigger]} ${className}`}
			onClick={handleClick}
			onKeyDown={handleKeyDown}
			{...props}>
			{children}
		</button>
	);
});
MenubarTrigger.displayName = 'MenubarTrigger';

export interface MenubarContentProps extends React.HTMLAttributes<HTMLDivElement>, MenubarContentBaseProps {}

const MenubarContent = React.forwardRef<HTMLDivElement, MenubarContentProps>(
	({ className = '', side = 'bottom', align = 'start', sideOffset = 8, alignOffset = -4, children, ...props }, ref) => {
		const { open, triggerRef, contentId, setOpen } = useMenubarMenuContext();
		const [position, setPosition] = useState<MenubarPosition | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);
		const itemsRef = useRef<HTMLElement[]>([]);

		function setRef(element: HTMLDivElement | null) {
			contentRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		useLayoutEffect(() => {
			if (!open) {
				return;
			}

			function updatePosition() {
				const trigger = triggerRef.current;
				const content = contentRef.current;
				if (!trigger || !content) {
					return;
				}

				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				setPosition(getMenubarPosition({ triggerRect, contentSize, side, align, sideOffset, alignOffset, viewport }));
			}

			function highlightFirst() {
				const items = itemsRef.current;
				if (items.length === 0) {
					return;
				}
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[0].setAttribute('data-highlighted', 'true');
			}

			updatePosition();
			highlightFirst();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			return () => {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
			};
		}, [open, side, align, sideOffset, alignOffset, triggerRef]);

		useEffect(() => {
			if (!open) {
				return;
			}

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				if (!target) {
					return;
				}
				const content = contentRef.current;
				const trigger = triggerRef.current;
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				setOpen(false);
			}

			document.addEventListener('pointerdown', handlePointerDown);
			return () => document.removeEventListener('pointerdown', handlePointerDown);
		}, [open, triggerRef, setOpen]);

		function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
			const items = itemsRef.current.filter((item) => item.getAttribute('data-disabled') !== 'true');
			if (items.length === 0) {
				if (event.key === 'Escape') {
					event.preventDefault();
					setOpen(false);
				}
				return;
			}

			const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');

			const highlight = (next: number) => {
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[next].setAttribute('data-highlighted', 'true');
				items[next].focus();
			};

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
					break;
				case 'ArrowUp':
					event.preventDefault();
					highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
					break;
				case 'Home':
					event.preventDefault();
					highlight(0);
					break;
				case 'End':
					event.preventDefault();
					highlight(items.length - 1);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
					break;
				case 'Escape':
					event.preventDefault();
					setOpen(false);
					triggerRef.current?.focus();
					break;
			}
		}

		const state = getMenubarState(open);
		const classes = [styles[menubarStyleKeys.content], className].filter(Boolean).join(' ');

		const content = (
			<MenubarContentContext.Provider value={{ itemsRef, close: () => setOpen(false) }}>
				<div
					ref={setRef}
					id={contentId}
					role="menu"
					tabIndex={-1}
					data-state={state}
					data-side={side}
					data-align={align}
					className={classes}
					style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
					onKeyDown={handleKeyDown}
					{...props}>
					{children}
				</div>
			</MenubarContentContext.Provider>
		);

		if (typeof document === 'undefined') {
			return null;
		}

		return createPortal(content, document.body);
	},
);
MenubarContent.displayName = 'MenubarContent';

export interface MenubarGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const MenubarGroup = React.forwardRef<HTMLDivElement, MenubarGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} role="group" className={`${styles[menubarStyleKeys.group]} ${className}`} {...props}>
			{children}
		</div>
	);
});
MenubarGroup.displayName = 'MenubarGroup';

export interface MenubarLabelProps extends React.HTMLAttributes<HTMLDivElement>, MenubarLabelBaseProps {}

const MenubarLabel = React.forwardRef<HTMLDivElement, MenubarLabelProps>(({ className = '', inset = false, children, ...props }, ref) => {
	const classes = [styles[menubarStyleKeys.label], className].filter(Boolean).join(' ');
	return (
		<div ref={ref} data-inset={inset} className={classes} {...props}>
			{children}
		</div>
	);
});
MenubarLabel.displayName = 'MenubarLabel';

export interface MenubarSeparatorProps extends React.HTMLAttributes<HTMLDivElement> {}

const MenubarSeparator = React.forwardRef<HTMLDivElement, MenubarSeparatorProps>(({ className = '', ...props }, ref) => {
	const classes = [styles[menubarStyleKeys.separator], className].filter(Boolean).join(' ');
	return <div ref={ref} role="separator" className={classes} {...props} />;
});
MenubarSeparator.displayName = 'MenubarSeparator';

export interface MenubarShortcutProps extends React.HTMLAttributes<HTMLSpanElement> {}

const MenubarShortcut = React.forwardRef<HTMLSpanElement, MenubarShortcutProps>(({ className = '', children, ...props }, ref) => {
	const classes = [styles[menubarStyleKeys.shortcut], className].filter(Boolean).join(' ');
	return (
		<span ref={ref} className={classes} {...props}>
			{children}
		</span>
	);
});
MenubarShortcut.displayName = 'MenubarShortcut';

export interface MenubarItemProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onSelect'>, MenubarItemBaseProps {}

const MenubarItem = React.forwardRef<HTMLDivElement, MenubarItemProps>(
	({ className = '', inset = false, variant = 'default', disabled = false, onSelect, children, ...props }, ref) => {
		const { itemsRef, close } = useMenubarContentContext();
		const itemRef = useRef<HTMLDivElement | null>(null);

		useEffect(() => {
			const element = itemRef.current;
			if (!element) {
				return;
			}
			itemsRef.current.push(element);
			return () => {
				itemsRef.current = itemsRef.current.filter((item) => item !== element);
			};
		}, [itemsRef]);

		function setRef(element: HTMLDivElement | null) {
			itemRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		function handleClick(event: React.MouseEvent<HTMLDivElement>) {
			if (disabled) {
				return;
			}
			onSelect?.(event.nativeEvent);
			close();
		}

		const classes = [styles[menubarStyleKeys.item], className].filter(Boolean).join(' ');
		return (
			<div ref={setRef} role="menuitem" tabIndex={-1} data-inset={inset} data-variant={variant} data-disabled={disabled} className={classes} onClick={handleClick} {...props}>
				{children}
			</div>
		);
	},
);
MenubarItem.displayName = 'MenubarItem';

export interface MenubarCheckboxItemProps extends React.HTMLAttributes<HTMLDivElement>, MenubarCheckboxItemBaseProps {}

const MenubarCheckboxItem = React.forwardRef<HTMLDivElement, MenubarCheckboxItemProps>(
	({ className = '', checked, defaultChecked = false, onCheckedChange, disabled = false, children, ...props }, ref) => {
		const { itemsRef } = useMenubarContentContext();
		const itemRef = useRef<HTMLDivElement | null>(null);
		const [internalChecked, setInternalChecked] = useState(defaultChecked);
		const isChecked = checked !== undefined ? checked : internalChecked;

		useEffect(() => {
			const element = itemRef.current;
			if (!element) {
				return;
			}
			itemsRef.current.push(element);
			return () => {
				itemsRef.current = itemsRef.current.filter((item) => item !== element);
			};
		}, [itemsRef]);

		function setRef(element: HTMLDivElement | null) {
			itemRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		function handleClick() {
			if (disabled) {
				return;
			}
			const next = !isChecked;
			if (checked === undefined) {
				setInternalChecked(next);
			}
			onCheckedChange?.(next);
		}

		const classes = [styles[menubarStyleKeys.checkboxItem], className].filter(Boolean).join(' ');
		return (
			<div
				ref={setRef}
				role="menuitemcheckbox"
				tabIndex={-1}
				aria-checked={isChecked}
				data-checked={getMenubarCheckState(isChecked)}
				data-disabled={disabled}
				className={classes}
				onClick={handleClick}
				{...props}>
				<span className={styles[menubarStyleKeys.indicator]}>{isChecked && <MenubarCheckIcon />}</span>
				{children}
			</div>
		);
	},
);
MenubarCheckboxItem.displayName = 'MenubarCheckboxItem';

export interface MenubarRadioGroupProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'defaultValue'>, MenubarRadioGroupBaseProps {}

const MenubarRadioGroup = React.forwardRef<HTMLDivElement, MenubarRadioGroupProps>(({ className = '', value, defaultValue, onValueChange, children, ...props }, ref) => {
	const [internalValue, setInternalValue] = useState(defaultValue);
	const resolvedValue = value !== undefined ? value : internalValue;

	const setValue = useCallback(
		(next: string) => {
			if (value === undefined) {
				setInternalValue(next);
			}
			onValueChange?.(next);
		},
		[value, onValueChange],
	);

	const classes = [styles[menubarStyleKeys.radioGroup], className].filter(Boolean).join(' ');
	return (
		<MenubarRadioGroupContext.Provider value={{ value: resolvedValue, setValue }}>
			<div ref={ref} role="group" className={classes} {...props}>
				{children}
			</div>
		</MenubarRadioGroupContext.Provider>
	);
});
MenubarRadioGroup.displayName = 'MenubarRadioGroup';

export interface MenubarRadioItemProps extends React.HTMLAttributes<HTMLDivElement>, MenubarRadioItemBaseProps {}

const MenubarRadioItem = React.forwardRef<HTMLDivElement, MenubarRadioItemProps>(({ className = '', value, disabled = false, children, ...props }, ref) => {
	const { itemsRef } = useMenubarContentContext();
	const { value: groupValue, setValue } = useMenubarRadioGroupContext();
	const itemRef = useRef<HTMLDivElement | null>(null);
	const isChecked = groupValue === value;

	useEffect(() => {
		const element = itemRef.current;
		if (!element) {
			return;
		}
		itemsRef.current.push(element);
		return () => {
			itemsRef.current = itemsRef.current.filter((item) => item !== element);
		};
	}, [itemsRef]);

	function setRef(element: HTMLDivElement | null) {
		itemRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleClick() {
		if (disabled) {
			return;
		}
		setValue(value);
	}

	const classes = [styles[menubarStyleKeys.radioItem], className].filter(Boolean).join(' ');
	return (
		<div
			ref={setRef}
			role="menuitemradio"
			tabIndex={-1}
			aria-checked={isChecked}
			data-checked={getMenubarCheckState(isChecked)}
			data-disabled={disabled}
			className={classes}
			onClick={handleClick}
			{...props}>
			<span className={styles[menubarStyleKeys.indicator]}>{isChecked && <MenubarRadioIcon />}</span>
			{children}
		</div>
	);
});
MenubarRadioItem.displayName = 'MenubarRadioItem';

export interface MenubarSubProps extends MenubarSubBaseProps {
	children?: React.ReactNode;
}

const MenubarSub = ({ open, defaultOpen = false, onOpenChange, children }: MenubarSubProps) => {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const isOpen = open !== undefined ? open : internalOpen;
	const triggerRef = useRef<HTMLElement | null>(null);

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}
			onOpenChange?.(next);
		},
		[open, onOpenChange],
	);

	return <MenubarSubContext.Provider value={{ open: isOpen, setOpen, triggerRef }}>{children}</MenubarSubContext.Provider>;
};
MenubarSub.displayName = 'MenubarSub';

export interface MenubarSubTriggerProps extends React.HTMLAttributes<HTMLDivElement>, MenubarSubTriggerBaseProps {}

const MenubarSubTrigger = React.forwardRef<HTMLDivElement, MenubarSubTriggerProps>(({ className = '', inset = false, disabled = false, children, ...props }, ref) => {
	const { itemsRef } = useMenubarContentContext();
	const { open, setOpen, triggerRef } = useMenubarSubContext();
	const itemRef = useRef<HTMLDivElement | null>(null);

	useEffect(() => {
		const element = itemRef.current;
		if (!element) {
			return;
		}
		itemsRef.current.push(element);
		return () => {
			itemsRef.current = itemsRef.current.filter((item) => item !== element);
		};
	}, [itemsRef]);

	function setRef(element: HTMLDivElement | null) {
		itemRef.current = element;
		triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleMouseEnter() {
		if (disabled) {
			return;
		}
		setOpen(true);
	}

	function handleClick() {
		if (disabled) {
			return;
		}
		setOpen(!open);
	}

	function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
		if (disabled) {
			return;
		}
		if (event.key === 'ArrowRight' || event.key === 'Enter' || event.key === ' ') {
			event.preventDefault();
			setOpen(true);
		}
	}

	const state = getMenubarState(open);
	const classes = [styles[menubarStyleKeys.subTrigger], className].filter(Boolean).join(' ');
	return (
		<div
			ref={setRef}
			role="menuitem"
			tabIndex={-1}
			aria-haspopup="menu"
			aria-expanded={open}
			data-state={state}
			data-inset={inset}
			data-disabled={disabled}
			className={classes}
			onMouseEnter={handleMouseEnter}
			onClick={handleClick}
			onKeyDown={handleKeyDown}
			{...props}>
			{children}
			<MenubarChevronIcon />
		</div>
	);
});
MenubarSubTrigger.displayName = 'MenubarSubTrigger';

export interface MenubarSubContentProps extends React.HTMLAttributes<HTMLDivElement>, MenubarContentBaseProps {}

const MenubarSubContent = React.forwardRef<HTMLDivElement, MenubarSubContentProps>(
	({ className = '', side = 'right', align = 'start', sideOffset = 0, alignOffset = 0, children, ...props }, ref) => {
		const { open, setOpen, triggerRef } = useMenubarSubContext();
		const [position, setPosition] = useState<MenubarPosition | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);
		const itemsRef = useRef<HTMLElement[]>([]);

		function setRef(element: HTMLDivElement | null) {
			contentRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		useLayoutEffect(() => {
			if (!open) {
				return;
			}

			function updatePosition() {
				const trigger = triggerRef.current;
				const content = contentRef.current;
				if (!trigger || !content) {
					return;
				}

				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				setPosition(getMenubarPosition({ triggerRect, contentSize, side, align, sideOffset, alignOffset, viewport }));
			}

			updatePosition();
			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			return () => {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
			};
		}, [open, side, align, sideOffset, alignOffset, triggerRef]);

		useEffect(() => {
			if (!open) {
				return;
			}

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				if (!target) {
					return;
				}
				const content = contentRef.current;
				const trigger = triggerRef.current;
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				setOpen(false);
			}

			document.addEventListener('pointerdown', handlePointerDown);
			return () => document.removeEventListener('pointerdown', handlePointerDown);
		}, [open, triggerRef, setOpen]);

		function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
			const items = itemsRef.current.filter((item) => item.getAttribute('data-disabled') !== 'true');

			if (event.key === 'Escape' || event.key === 'ArrowLeft') {
				event.preventDefault();
				setOpen(false);
				triggerRef.current?.focus();
				return;
			}

			if (items.length === 0) {
				return;
			}

			const currentIndex = items.findIndex((item) => item.getAttribute('data-highlighted') === 'true');
			const highlight = (next: number) => {
				items.forEach((item) => item.removeAttribute('data-highlighted'));
				items[next].setAttribute('data-highlighted', 'true');
				items[next].focus();
			};

			switch (event.key) {
				case 'ArrowDown':
					event.preventDefault();
					highlight(currentIndex < 0 ? 0 : (currentIndex + 1) % items.length);
					break;
				case 'ArrowUp':
					event.preventDefault();
					highlight(currentIndex < 0 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length);
					break;
				case 'Enter':
				case ' ':
					event.preventDefault();
					(currentIndex >= 0 ? items[currentIndex] : items[0]).click();
					break;
			}
		}

		const state = getMenubarState(open);
		const classes = [styles[menubarStyleKeys.subContent], className].filter(Boolean).join(' ');

		const content = (
			<MenubarContentContext.Provider value={{ itemsRef, close: () => setOpen(false) }}>
				<div
					ref={setRef}
					role="menu"
					tabIndex={-1}
					data-state={state}
					data-side={side}
					data-align={align}
					className={classes}
					style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
					onKeyDown={handleKeyDown}
					{...props}>
					{children}
				</div>
			</MenubarContentContext.Provider>
		);

		if (typeof document === 'undefined') {
			return null;
		}

		return createPortal(content, document.body);
	},
);
MenubarSubContent.displayName = 'MenubarSubContent';

export {
	Menubar,
	MenubarPortal,
	MenubarMenu,
	MenubarTrigger,
	MenubarContent,
	MenubarGroup,
	MenubarLabel,
	MenubarItem,
	MenubarCheckboxItem,
	MenubarRadioGroup,
	MenubarRadioItem,
	MenubarSeparator,
	MenubarShortcut,
	MenubarSub,
	MenubarSubTrigger,
	MenubarSubContent,
};
export default Menubar;
