// packages/vue/src/components/aspect-ratio/aspect-ratio.tsx
import { computed, defineComponent, h } from 'vue';
import { aspectRatioStyleKeys, getAspectRatioPadding } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/aspect-ratio.module.scss';

export const AspectRatio = defineComponent({
	name: 'AspectRatio',
	props: {
		ratio: { type: Number, default: 1 },
	},
	setup(props, { slots, attrs }) {
		const paddingTop = computed(() => `${getAspectRatioPadding(props.ratio)}%`);

		return () =>
			h(
				'div',
				{
					...attrs,
					'data-slot': 'aspect-ratio',
					class: [styles[aspectRatioStyleKeys.root], attrs.class],
					style: [attrs.style, { paddingTop: paddingTop.value }],
				},
				[h('div', { class: styles[aspectRatioStyleKeys.content] }, slots.default?.())],
			);
	},
});

export default AspectRatio;

// packages/react/src/components/aspect-ratio/aspect-ratio.tsx
import React from 'react';
import { aspectRatioStyleKeys, getAspectRatioPadding } from '@tile-ui/core';
import type { AspectRatioBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/aspect-ratio.module.scss';

export interface AspectRatioProps extends React.HTMLAttributes<HTMLDivElement>, AspectRatioBaseProps {}

const AspectRatio = React.forwardRef<HTMLDivElement, AspectRatioProps>(({ className = '', ratio = 1, children, style, ...props }, ref) => {
	const paddingTop = `${getAspectRatioPadding(ratio)}%`;

	return (
		<div ref={ref} data-slot="aspect-ratio" className={`${styles[aspectRatioStyleKeys.root]} ${className}`} style={{ ...style, paddingTop }} {...props}>
			<div className={styles[aspectRatioStyleKeys.content]}>{children}</div>
		</div>
	);
});
AspectRatio.displayName = 'AspectRatio';

export { AspectRatio };
export default AspectRatio;
