// packages/vue/src/components/native-select/native-select.tsx
import { computed, defineComponent, h, ref, type PropType } from 'vue';
import { getNativeSelectState, nativeSelectStyleKeys } from '@tile-ui/core';
import type { NativeSelectSize } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/native-select.module.scss';

export const NativeSelect = defineComponent({
	name: 'NativeSelect',
	props: {
		modelValue: { type: String, default: undefined },
		defaultValue: { type: String, default: '' },
		size: {
			type: String as PropType<NativeSelectSize>,
			default: 'default',
		},
		disabled: { type: Boolean, default: false },
	},
	emits: ['update:modelValue', 'change'],
	setup(props, { emit, attrs, slots }) {
		const internalValue = ref(props.defaultValue);
		const currentValue = computed(() => (props.modelValue !== undefined ? props.modelValue : internalValue.value));
		const state = computed(() => getNativeSelectState(currentValue.value));

		function handleChange(event: Event) {
			const next = (event.target as HTMLSelectElement).value;
			if (props.modelValue === undefined) {
				internalValue.value = next;
			}
			emit('update:modelValue', next);
			emit('change', next);
		}

		return () =>
			h('div', { class: styles[nativeSelectStyleKeys.wrapper] }, [
				h(
					'select',
					{
						...attrs,
						'data-slot': 'native-select',
						'data-size': props.size,
						'data-state': state.value,
						value: currentValue.value,
						disabled: props.disabled,
						class: [styles[nativeSelectStyleKeys.select], attrs.class],
						onChange: handleChange,
					},
					slots.default?.(),
				),
				h(
					'svg',
					{
						class: styles[nativeSelectStyleKeys.icon],
						xmlns: 'http://www.w3.org/2000/svg',
						viewBox: '0 0 24 24',
						fill: 'none',
						stroke: 'currentColor',
						'stroke-width': '2',
						'stroke-linecap': 'round',
						'stroke-linejoin': 'round',
						'aria-hidden': 'true',
						'data-slot': 'native-select-icon',
					},
					[h('path', { d: 'm6 9 6 6 6-6' })],
				),
			]);
	},
});

export const NativeSelectOption = defineComponent({
	name: 'NativeSelectOption',
	props: {
		value: { type: String, default: undefined },
		label: String,
		disabled: { type: Boolean, default: false },
	},
	setup(props, { attrs, slots }) {
		return () =>
			h(
				'option',
				{
					...attrs,
					'data-slot': 'native-select-option',
					value: props.value,
					label: props.label,
					disabled: props.disabled,
					class: [styles[nativeSelectStyleKeys.option], attrs.class],
				},
				slots.default?.(),
			);
	},
});

export const NativeSelectOptGroup = defineComponent({
	name: 'NativeSelectOptGroup',
	props: {
		label: String,
		disabled: { type: Boolean, default: false },
	},
	setup(props, { attrs, slots }) {
		return () =>
			h(
				'optgroup',
				{
					...attrs,
					'data-slot': 'native-select-optgroup',
					label: props.label,
					disabled: props.disabled,
					class: [styles[nativeSelectStyleKeys.optGroup], attrs.class],
				},
				slots.default?.(),
			);
	},
});

export default NativeSelect;

// packages/react/src/components/native-select/native-select.tsx
import React, { useState } from 'react';
import { getNativeSelectState, nativeSelectStyleKeys } from '@tile-ui/core';
import type { NativeSelectBaseProps, NativeSelectOptionBaseProps, NativeSelectOptGroupBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/native-select.module.scss';

export interface NativeSelectProps extends Omit<React.SelectHTMLAttributes<HTMLSelectElement>, 'size' | 'value' | 'defaultValue'>, NativeSelectBaseProps {
	value?: string;
	defaultValue?: string;
	onValueChange?: (value: string) => void;
}

const NativeSelect = React.forwardRef<HTMLSelectElement, NativeSelectProps>(
	({ className = '', size = 'default', value, defaultValue = '', onValueChange, onChange, children, ...props }, ref) => {
		const [internalValue, setInternalValue] = useState(defaultValue);
		const currentValue = value !== undefined ? value : internalValue;
		const state = getNativeSelectState(currentValue);

		function handleChange(event: React.ChangeEvent<HTMLSelectElement>) {
			const next = event.target.value;

			if (value === undefined) {
				setInternalValue(next);
			}

			onValueChange?.(next);
			onChange?.(event);
		}

		return (
			<div className={styles[nativeSelectStyleKeys.wrapper]}>
				<select
					ref={ref}
					data-slot="native-select"
					data-size={size}
					data-state={state}
					value={currentValue}
					onChange={handleChange}
					className={`${styles[nativeSelectStyleKeys.select]} ${className}`}
					{...props}>
					{children}
				</select>
				<svg
					className={styles[nativeSelectStyleKeys.icon]}
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					strokeWidth="2"
					strokeLinecap="round"
					strokeLinejoin="round"
					aria-hidden="true"
					data-slot="native-select-icon">
					<path d="m6 9 6 6 6-6" />
				</svg>
			</div>
		);
	},
);
NativeSelect.displayName = 'NativeSelect';

export interface NativeSelectOptionProps extends React.OptionHTMLAttributes<HTMLOptionElement>, NativeSelectOptionBaseProps {}

const NativeSelectOption = React.forwardRef<HTMLOptionElement, NativeSelectOptionProps>(({ className = '', ...props }, ref) => {
	return <option ref={ref} data-slot="native-select-option" className={`${styles[nativeSelectStyleKeys.option]} ${className}`} {...props} />;
});
NativeSelectOption.displayName = 'NativeSelectOption';

export interface NativeSelectOptGroupProps extends React.OptgroupHTMLAttributes<HTMLOptGroupElement>, NativeSelectOptGroupBaseProps {}

const NativeSelectOptGroup = React.forwardRef<HTMLOptGroupElement, NativeSelectOptGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<optgroup ref={ref} data-slot="native-select-optgroup" className={`${styles[nativeSelectStyleKeys.optGroup]} ${className}`} {...props}>
			{children}
		</optgroup>
	);
});
NativeSelectOptGroup.displayName = 'NativeSelectOptGroup';

export { NativeSelect, NativeSelectOption, NativeSelectOptGroup };
export default NativeSelect;
