// packages/react/src/components/popover/popover.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Slot } from '@radix-ui/react-slot';
import { getPopoverPosition, getPopoverState, popoverStyleKeys } from '@tile-ui/core';
import type { PopoverBaseProps, PopoverContentBaseProps, PopoverPosition, PopoverTriggerBaseProps } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/popover.module.scss';

interface PopoverContextValue {
	open: boolean;
	triggerRef: React.RefObject<HTMLElement | null>;
	contentId: string;
	setOpen: (open: boolean) => void;
}

const PopoverContext = createContext<PopoverContextValue | null>(null);

function usePopoverContext(): PopoverContextValue {
	const context = useContext(PopoverContext);
	if (!context) {
		throw new Error('Popover sub-components must be used within <Popover>.');
	}
	return context;
}

export interface PopoverProps extends React.HTMLAttributes<HTMLDivElement>, PopoverBaseProps {}

const Popover = React.forwardRef<HTMLDivElement, PopoverProps>(({ className = '', open, defaultOpen = false, onOpenChange, children, ...props }, ref) => {
	const [internalOpen, setInternalOpen] = useState(defaultOpen);
	const isOpen = open !== undefined ? open : internalOpen;
	const triggerRef = useRef<HTMLElement | null>(null);
	const contentId = useId();

	const setOpen = useCallback(
		(next: boolean) => {
			if (open === undefined) {
				setInternalOpen(next);
			}
			onOpenChange?.(next);
		},
		[open, onOpenChange],
	);

	return (
		<PopoverContext.Provider value={{ open: isOpen, triggerRef, contentId, setOpen }}>
			<div ref={ref} className={`${styles[popoverStyleKeys.root]} ${className}`} {...props}>
				{children}
			</div>
		</PopoverContext.Provider>
	);
});
Popover.displayName = 'Popover';

export interface PopoverTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, PopoverTriggerBaseProps {}

const PopoverTrigger = React.forwardRef<HTMLButtonElement, PopoverTriggerProps>(({ className = '', asChild = false, children, onClick, ...props }, ref) => {
	const context = usePopoverContext();

	function setRef(element: HTMLElement | null) {
		context.triggerRef.current = element;
		if (typeof ref === 'function') {
			ref(element as HTMLButtonElement | null);
		} else if (ref) {
			ref.current = element as HTMLButtonElement | null;
		}
	}

	function handleClick(event: React.MouseEvent<HTMLButtonElement>) {
		context.setOpen(!context.open);
		onClick?.(event);
	}

	const Comp = asChild ? Slot : 'button';
	const state = getPopoverState(context.open);

	return (
		<Comp
			ref={setRef}
			aria-haspopup="dialog"
			aria-expanded={context.open}
			aria-controls={context.contentId}
			data-state={state}
			className={asChild ? undefined : `${styles[popoverStyleKeys.trigger]} ${className}`}
			onClick={handleClick}
			{...props}>
			{children}
		</Comp>
	);
});
PopoverTrigger.displayName = 'PopoverTrigger';

export interface PopoverContentProps extends React.HTMLAttributes<HTMLDivElement>, PopoverContentBaseProps {
	container?: PortalContainer;
}

const PopoverContent = React.forwardRef<HTMLDivElement, PopoverContentProps>(
	({ className = '', side = 'bottom', align = 'center', sideOffset = 4, container, children, ...props }, ref) => {
		const { open, triggerRef, contentId, setOpen } = usePopoverContext();
		const portalContainer = usePortalContainer(container);
		const [position, setPosition] = useState<PopoverPosition | null>(null);
		const contentRef = useRef<HTMLDivElement | null>(null);

		function setRef(element: HTMLDivElement | null) {
			contentRef.current = element;
			if (typeof ref === 'function') {
				ref(element);
			} else if (ref) {
				ref.current = element;
			}
		}

		useLayoutEffect(() => {
			if (!open) {
				return;
			}

			function updatePosition() {
				const trigger = triggerRef.current;
				const content = contentRef.current;
				if (!trigger || !content) {
					return;
				}

				const triggerRect = trigger.getBoundingClientRect();
				const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
				const viewport = { width: window.innerWidth, height: window.innerHeight };
				setPosition(getPopoverPosition({ triggerRect, contentSize, side, align, sideOffset, viewport }));
			}

			updatePosition();

			const content = contentRef.current;
			if (content && !content.contains(document.activeElement)) {
				content.focus();
			}

			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);

			return () => {
				window.removeEventListener('resize', updatePosition);
				document.removeEventListener('scroll', updatePosition, true);
			};
		}, [open, side, align, sideOffset, triggerRef]);

		useEffect(() => {
			if (!open) {
				return;
			}

			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				const content = contentRef.current;
				const trigger = triggerRef.current;
				if (!target) {
					return;
				}
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				setOpen(false);
			}

			function handleKeyDown(event: KeyboardEvent) {
				if (event.key === 'Escape') {
					setOpen(false);
					triggerRef.current?.focus();
				}
			}

			document.addEventListener('pointerdown', handlePointerDown);
			document.addEventListener('keydown', handleKeyDown);

			return () => {
				document.removeEventListener('pointerdown', handlePointerDown);
				document.removeEventListener('keydown', handleKeyDown);
			};
		}, [open, triggerRef, setOpen]);

		const state = getPopoverState(open);
		const classes = [styles[popoverStyleKeys.content], className].filter(Boolean).join(' ');

		const content = (
			<div
				ref={setRef}
				id={contentId}
				role="dialog"
				aria-modal="false"
				tabIndex={-1}
				data-state={state}
				data-side={side}
				data-align={align}
				className={classes}
				style={position ? { top: `${position.top}px`, left: `${position.left}px` } : undefined}
				{...props}>
				{children}
			</div>
		);

		if (!open || !portalContainer) {
			return null;
		}

		return createPortal(content, portalContainer);
	},
);
PopoverContent.displayName = 'PopoverContent';

export { Popover, PopoverTrigger, PopoverContent };
export default Popover;

// packages/vue/src/components/popover/popover.tsx
import {
	cloneVNode,
	computed,
	defineComponent,
	h,
	inject,
	mergeProps,
	onBeforeUnmount,
	onMounted,
	provide,
	ref,
	useId,
	watch,
	type InjectionKey,
	type PropType,
	type Ref,
	Teleport,
} from 'vue';
import { getPopoverPosition, getPopoverState, popoverStyleKeys } from '@tile-ui/core';
import type { PopoverAlign, PopoverSide } from '@tile-ui/core';
import { usePortalContainer, type PortalContainer } from '../portal';
import styles from '@tile-ui/styles/scss/components/popover.module.scss';

interface PopoverContextValue {
	open: Ref<boolean>;
	triggerRef: Ref<HTMLElement | null>;
	contentId: string;
	setOpen: (open: boolean) => void;
}

const PopoverContextKey: InjectionKey<PopoverContextValue> = Symbol('tile-popover');

export const Popover = defineComponent({
	name: 'Popover',
	props: {
		open: { type: Boolean, default: undefined },
		defaultOpen: { type: Boolean, default: false },
	},
	emits: ['update:open'],
	setup(props, { emit, slots }) {
		const internalOpen = ref(props.defaultOpen);
		const isOpen = computed(() => (props.open !== undefined ? props.open : internalOpen.value));
		const triggerRef = ref<HTMLElement | null>(null);
		const contentId = `tile-popover-${useId()}`;

		function setOpen(next: boolean) {
			if (props.open === undefined) {
				internalOpen.value = next;
			}
			emit('update:open', next);
		}

		provide(PopoverContextKey, { open: isOpen, triggerRef, contentId, setOpen });

		return () => h('div', { class: styles[popoverStyleKeys.root] }, slots.default?.());
	},
});

export const PopoverTrigger = defineComponent({
	name: 'PopoverTrigger',
	inheritAttrs: false,
	props: {
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const contextValue = inject(PopoverContextKey);
		if (!contextValue) {
			throw new Error('PopoverTrigger must be used within <Popover>.');
		}
		const context: PopoverContextValue = contextValue;

		function handleClick() {
			context.setOpen(!context.open.value);
		}

		function setRef(el: unknown) {
			context.triggerRef.value = (el as HTMLElement | null) ?? null;
		}

		const triggerProps = computed(() => ({
			ref: setRef,
			'aria-haspopup': 'dialog',
			'aria-expanded': context.open.value ? 'true' : 'false',
			'aria-controls': context.contentId,
			'data-state': getPopoverState(context.open.value),
			onClick: handleClick,
		}));

		return () => {
			const child = slots.default?.()[0];

			if (props.asChild && child) {
				return cloneVNode(child, mergeProps(child.props ?? {}, triggerProps.value));
			}

			return h('button', { ...attrs, ...triggerProps.value, type: 'button', class: [styles[popoverStyleKeys.trigger], attrs.class] }, slots.default?.());
		};
	},
});

export const PopoverContent = defineComponent({
	name: 'PopoverContent',
	inheritAttrs: false,
	props: {
		side: { type: String as PropType<PopoverSide>, default: 'bottom' },
		align: { type: String as PropType<PopoverAlign>, default: 'center' },
		sideOffset: { type: Number, default: 4 },
		container: { type: Object as PropType<PortalContainer>, default: null },
	},
	setup(props, { slots, attrs }) {
		const portalContainer = usePortalContainer(() => props.container);
		const contextValue = inject(PopoverContextKey);
		if (!contextValue) {
			throw new Error('PopoverContent must be used within <Popover>.');
		}
		const context: PopoverContextValue = contextValue;

		const contentRef = ref<HTMLElement | null>(null);
		const position = ref<{ top: number; left: number } | null>(null);

		let disposeDocListeners: (() => void) | null = null;

		function updatePosition() {
			const trigger = context.triggerRef.value;
			const content = contentRef.value;
			if (!trigger || !content) {
				return;
			}

			const triggerRect = trigger.getBoundingClientRect();
			const contentSize = { width: content.offsetWidth, height: content.offsetHeight };
			const viewport = { width: window.innerWidth, height: window.innerHeight };
			position.value = getPopoverPosition({ triggerRect, contentSize, side: props.side, align: props.align, sideOffset: props.sideOffset, viewport });
		}

		function handleOpen() {
			updatePosition();

			const content = contentRef.value;
			if (content && !content.contains(document.activeElement)) {
				content.focus();
			}

			window.addEventListener('resize', updatePosition);
			document.addEventListener('scroll', updatePosition, true);
		}

		function handleClose() {
			window.removeEventListener('resize', updatePosition);
			document.removeEventListener('scroll', updatePosition, true);
		}

		function addDocListeners(): () => void {
			function handlePointerDown(event: PointerEvent) {
				const target = event.target as Node | null;
				const content = contentRef.value;
				const trigger = context.triggerRef.value;
				if (!target) {
					return;
				}
				if (content && content.contains(target)) {
					return;
				}
				if (trigger && trigger.contains(target)) {
					return;
				}
				context.setOpen(false);
			}

			function handleKeyDown(event: KeyboardEvent) {
				if (event.key === 'Escape') {
					context.setOpen(false);
					context.triggerRef.value?.focus();
				}
			}

			document.addEventListener('pointerdown', handlePointerDown);
			document.addEventListener('keydown', handleKeyDown);

			return () => {
				document.removeEventListener('pointerdown', handlePointerDown);
				document.removeEventListener('keydown', handleKeyDown);
			};
		}

		onMounted(() => {
			if (context.open.value) {
				handleOpen();
				disposeDocListeners = addDocListeners();
			}
		});

		watch(
			() => context.open.value,
			(open) => {
				if (open) {
					handleOpen();
					disposeDocListeners = addDocListeners();
				} else {
					handleClose();
					disposeDocListeners?.();
					disposeDocListeners = null;
				}
			},
		);

		watch(
			() => [props.side, props.align, props.sideOffset],
			() => {
				if (context.open.value) {
					updatePosition();
				}
			},
		);

		onBeforeUnmount(() => {
			disposeDocListeners?.();
			handleClose();
		});

		return () => {
			const open = context.open.value;
			const userClass = attrs.class;
			const userStyle = attrs.style;
			const restAttrs = { ...attrs };
			delete restAttrs.class;
			delete restAttrs.style;

			return h(Teleport, { to: portalContainer.value }, [
				h(
					'div',
					{
						...restAttrs,
						ref: contentRef,
						id: context.contentId,
						role: 'dialog',
						'aria-modal': 'false',
						tabindex: -1,
						'data-state': getPopoverState(open),
						'data-side': props.side,
						'data-align': props.align,
						class: [styles[popoverStyleKeys.content], userClass],
						style: position.value ? [userStyle, { top: `${position.value.top}px`, left: `${position.value.left}px` }] : userStyle,
					},
					slots.default?.(),
				),
			]);
		};
	},
});

export default Popover;
