// packages/react/src/components/form/form.tsx
import React, { createContext, useCallback, useContext, useEffect, useId, useLayoutEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Slot } from '@radix-ui/react-slot';
import { createFormStore, formStyleKeys, getFormFieldIds, normalizeFormValue, FormStore } from '@tile-ui/core';
import type { FormBaseProps, FormControllerField, FormFieldError, FormRegisterOptions, FormSnapshot } from '@tile-ui/core';
import { Label } from '../label';
import styles from '@tile-ui/styles/scss/components/form.module.scss';

const FormStoreContext = createContext<FormStore | null>(null);

function useFormStore(): FormStore {
	const store = useContext(FormStoreContext);
	if (!store) {
		throw new Error('Form sub-components must be used within <Form>.');
	}
	return store;
}

/**
 * 订阅表单存储快照，触发组件重渲染
 */
function useFormSnapshot(store: FormStore): FormSnapshot {
	return useSyncExternalStore(
		(listener) => store.subscribe(listener),
		() => store.getSnapshot(),
		() => store.getSnapshot(),
	);
}

/**
 * 返回当前表单实例 (FormStore)，可调用 handleSubmit / trigger / getValues 等
 */
export function useForm(): FormStore {
	return useFormStore();
}

const FormFieldContext = createContext<{ name: string }>({ name: '' });

interface FormItemContextValue {
	id: string;
	declaredDescriptionId: string | undefined;
	declaredMessageId: string | undefined;
	descriptionIds: () => string[];
	messageIds: () => string[];
	registerDescription: (id: string) => () => void;
	registerMessage: (id: string) => () => void;
}

const FormItemContext = createContext<FormItemContextValue>({
	id: '',
	declaredDescriptionId: undefined,
	declaredMessageId: undefined,
	descriptionIds: () => [],
	messageIds: () => [],
	registerDescription: () => () => {},
	registerMessage: () => () => {},
});

/**
 * 注册一个已挂载节点的 ID；返回值用于在卸载时注销。
 */
function registerPresence(registry: Set<string>, bump: () => void, registeredId: string) {
	registry.add(registeredId);
	bump();
	let active = true;
	return () => {
		if (!active) return;
		active = false;
		registry.delete(registeredId);
		bump();
	};
}

const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;

export interface FormFieldResult {
	id: string;
	name: string;
	formItemId: string;
	formDescriptionId: string;
	formMessageId: string;
	error?: FormFieldError;
	isTouched: boolean;
	isDirty: boolean;
}

/**
 * 读取当前字段上下文 (name + 表单项 id + 错误信息)
 */
export function useFormField(): FormFieldResult {
	const fieldContext = useContext(FormFieldContext);
	const itemContext = useContext(FormItemContext);
	const store = useFormStore();
	useFormSnapshot(store);

	if (!fieldContext.name) {
		throw new Error('useFormField should be used within <FormField>');
	}

	const ids = getFormFieldIds(itemContext.id);
	const fieldState = store.getFieldState(fieldContext.name);

	return {
		id: ids.id,
		name: fieldContext.name,
		formItemId: ids.formItemId,
		formDescriptionId: ids.formDescriptionId,
		formMessageId: ids.formMessageId,
		error: fieldState.error,
		isTouched: fieldState.isTouched,
		isDirty: fieldState.isDirty,
	};
}

export interface FormProps extends FormBaseProps {
	children?: React.ReactNode;
}

/**
 * 表单容器：创建并提供 FormStore 上下文
 */
function Form({ defaultValues = {}, resolver, form, children }: FormProps) {
	const [store] = useState<FormStore>(() => (form ? (form as FormStore) : createFormStore(defaultValues, resolver)));

	return <FormStoreContext.Provider value={store}>{children}</FormStoreContext.Provider>;
}

Form.displayName = 'Form';

export interface FormFieldProps {
	name: string;
	options?: FormRegisterOptions;
	render?: (props: { field: FormControllerField }) => React.ReactNode;
	children?: React.ReactNode;
}

/** 共享的空注册选项，避免默认值在每次渲染时产生新引用导致重复注册。 */
const EMPTY_REGISTER_OPTIONS: FormRegisterOptions = {};

/**
 * 表单字段：注册字段并提供字段渲染上下文
 */
function FormField({ name, options = EMPTY_REGISTER_OPTIONS, render, children }: FormFieldProps) {
	const store = useFormStore();
	useFormSnapshot(store);

	useEffect(() => {
		const registration = store.registerField(name, options);
		return registration.unregister;
	}, [store, name, options]);

	const field: FormControllerField = {
		name,
		value: store.getValue(name),
		onChange: (value: unknown) => store.setValue(name, normalizeFormValue(value, options.valueAsNumber)),
		onBlur: () => store.blurField(name),
		ref: name,
	};

	return <FormFieldContext.Provider value={{ name }}>{render ? render({ field }) : children}</FormFieldContext.Provider>;
}

FormField.displayName = 'FormField';

export interface FormItemProps extends React.HTMLAttributes<HTMLDivElement> {
	/** SSR 时预声明已渲染的描述节点 ID；同时作为 FormDescription 的默认 ID。 */
	descriptionId?: string;
	/** SSR 时预声明错误消息节点 ID；同时作为 FormMessage 的默认 ID。 */
	messageId?: string;
}

function FormItem({ className = '', descriptionId, messageId, ...props }: FormItemProps) {
	const id = useId();
	const descriptionIdsRef = useRef(new Set<string>(descriptionId === undefined ? [] : [descriptionId]));
	const messageIdsRef = useRef(new Set<string>(messageId === undefined ? [] : [messageId]));
	const [presence, setPresence] = useState(0);
	const bump = useCallback(() => setPresence((version) => version + 1), []);

	useIsomorphicLayoutEffect(() => {
		if (descriptionId === undefined) return;
		return registerPresence(descriptionIdsRef.current, bump, descriptionId);
	}, [descriptionId, bump]);

	useIsomorphicLayoutEffect(() => {
		if (messageId === undefined) return;
		return registerPresence(messageIdsRef.current, bump, messageId);
	}, [messageId, bump]);

	const registerDescription = useCallback((registeredId: string) => registerPresence(descriptionIdsRef.current, bump, registeredId), [bump]);
	const registerMessage = useCallback((registeredId: string) => registerPresence(messageIdsRef.current, bump, registeredId), [bump]);

	const context: FormItemContextValue = {
		id,
		declaredDescriptionId: descriptionId,
		declaredMessageId: messageId,
		descriptionIds: () => {
			void presence;
			return [...descriptionIdsRef.current];
		},
		messageIds: () => {
			void presence;
			return [...messageIdsRef.current];
		},
		registerDescription,
		registerMessage,
	};

	return (
		<FormItemContext.Provider value={context}>
			<div data-slot="form-item" className={`${styles[formStyleKeys.item]} ${className}`} {...props} />
		</FormItemContext.Provider>
	);
}

FormItem.displayName = 'FormItem';

export interface FormLabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {}

function FormLabel({ className = '', ...props }: FormLabelProps) {
	const { error, formItemId } = useFormField();

	return <Label data-slot="form-label" data-error={!!error} className={`${styles[formStyleKeys.label]} ${className}`} htmlFor={formItemId} {...props} />;
}

FormLabel.displayName = 'FormLabel';

export interface FormControlProps extends React.ComponentProps<typeof Slot> {}

function FormControl({ ...props }: FormControlProps) {
	const { error, formItemId } = useFormField();
	const item = useContext(FormItemContext);

	const describedByIds = [...item.descriptionIds()];
	if (error) describedByIds.push(...item.messageIds());

	return <Slot data-slot="form-control" id={formItemId} aria-describedby={describedByIds.length > 0 ? describedByIds.join(' ') : undefined} aria-invalid={!!error} {...props} />;
}

FormControl.displayName = 'FormControl';

export interface FormDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

function FormDescription({ className = '', ...props }: FormDescriptionProps) {
	const { formDescriptionId } = useFormField();
	const item = useContext(FormItemContext);
	const effectiveId = props.id ?? item.declaredDescriptionId ?? formDescriptionId;
	const { registerDescription } = item;

	useIsomorphicLayoutEffect(() => registerDescription(effectiveId), [registerDescription, effectiveId]);

	return <p data-slot="form-description" id={effectiveId} className={`${styles[formStyleKeys.description]} ${className}`} {...props} />;
}

FormDescription.displayName = 'FormDescription';

export interface FormMessageProps extends React.HTMLAttributes<HTMLParagraphElement> {}

function FormMessage({ className = '', children, ...props }: FormMessageProps) {
	const { error, formMessageId } = useFormField();
	const item = useContext(FormItemContext);
	const effectiveId = props.id ?? item.declaredMessageId ?? formMessageId;
	const { registerMessage } = item;
	const hasBody = error ? !!String(error.message ?? '') : !!children;

	useIsomorphicLayoutEffect(() => {
		if (!hasBody) return;
		return registerMessage(effectiveId);
	}, [registerMessage, effectiveId, hasBody]);

	if (!hasBody) {
		return null;
	}

	const body = error ? String(error.message ?? '') : children;

	return (
		<p data-slot="form-message" id={effectiveId} className={`${styles[formStyleKeys.message]} ${className}`} {...props}>
			{body}
		</p>
	);
}

FormMessage.displayName = 'FormMessage';

export { Form, FormItem, FormLabel, FormControl, FormDescription, FormMessage, FormField };
export default Form;

// packages/vue/src/components/form/form.tsx
import {
	Comment,
	cloneVNode,
	computed,
	defineComponent,
	h,
	inject,
	onBeforeUnmount,
	provide,
	ref,
	useId,
	watch,
	type ComputedRef,
	type InjectionKey,
	type PropType,
	type Ref,
	type VNode,
} from 'vue';
import { createFormStore, formStyleKeys, getFormFieldIds, FormStore } from '@tile-ui/core';
import type { FormControllerField, FormErrors, FormRegisterOptions, FormValues } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/form.module.scss';

interface FormContextValue {
	store: FormStore;
	version: Ref<number>;
}

const FormContextKey: InjectionKey<FormContextValue> = Symbol('tile-form');

const FormFieldContextKey: InjectionKey<ComputedRef<string>> = Symbol('tile-form-field');

interface FormItemContextValue {
	id: ComputedRef<string>;
	declaredDescriptionId: ComputedRef<string | undefined>;
	declaredMessageId: ComputedRef<string | undefined>;
	descriptionIds: ComputedRef<string[]>;
	messageIds: ComputedRef<string[]>;
	registerDescription: (id: string) => () => void;
	registerMessage: (id: string) => () => void;
}

const FormItemContextKey: InjectionKey<FormItemContextValue> = Symbol('tile-form-item');

function useFormContext(): FormContextValue {
	const context = inject(FormContextKey);
	if (!context) {
		throw new Error('表单子组件必须在 <Form> 内使用');
	}
	return context;
}

/** 判断插槽产物是否包含可见内容（空字符串/纯注释视为无内容）。 */
function hasSlotContent(nodes: VNode[] | undefined): boolean {
	if (!nodes || nodes.length === 0) return false;
	return nodes.some((node) => {
		if (node.type === Comment) return false;
		if (typeof node.children === 'string') return node.children.trim().length > 0;
		return true;
	});
}

function useFormField() {
	const { store, version } = useFormContext();
	const fieldName = inject(FormFieldContextKey);
	const itemContext = inject(FormItemContextKey);

	if (!fieldName) {
		throw new Error('useFormField 必须在 <FormField> 内使用');
	}

	return computed(() => {
		void version.value;
		const name = fieldName.value;
		const ids = getFormFieldIds(itemContext?.id.value ?? 'tile-form-field');
		const fieldState = store.getFieldState(name);

		return {
			id: ids.id,
			name,
			formItemId: ids.formItemId,
			formDescriptionId: ids.formDescriptionId,
			formMessageId: ids.formMessageId,
			error: fieldState.error,
			isTouched: fieldState.isTouched,
			isDirty: fieldState.isDirty,
		};
	});
}

export const Form = defineComponent({
	name: 'Form',
	props: {
		defaultValues: { type: Object as PropType<FormValues>, default: () => ({}) },
		resolver: { type: Function as PropType<(values: FormValues) => FormErrors | Promise<FormErrors>>, default: undefined },
		form: { type: Object as PropType<FormStore>, default: undefined },
	},
	setup(props, { slots }) {
		const store = props.form ?? createFormStore(props.defaultValues, props.resolver);
		const version = ref(0);
		const unsubscribe = store.subscribe(() => {
			version.value += 1;
		});
		onBeforeUnmount(unsubscribe);

		provide(FormContextKey, { store, version });

		return () => slots.default?.();
	},
});

export const FormField = defineComponent({
	name: 'FormField',
	props: {
		name: { type: String, required: true },
		options: { type: Object as PropType<FormRegisterOptions>, default: () => ({}) },
	},
	setup(props, { slots }) {
		const { store, version } = useFormContext();
		let registration: ReturnType<FormStore['registerField']> | undefined;

		const stop = watch(
			() => [props.name, props.options] as const,
			([name, options]) => {
				registration?.unregister();
				registration = store.registerField(name, options);
			},
			{ immediate: true, deep: true },
		);

		onBeforeUnmount(() => {
			stop();
			registration?.unregister();
		});

		provide(
			FormFieldContextKey,
			computed(() => props.name),
		);

		return () => {
			void version.value;
			const field: FormControllerField = {
				name: props.name,
				value: store.getValue(props.name),
				onChange: (value: unknown) => registration?.onChange(value),
				onBlur: () => store.blurField(props.name),
				ref: props.name,
			};

			return slots.default ? slots.default({ field }) : null;
		};
	},
});

export const FormItem = defineComponent({
	name: 'FormItem',
	props: {
		descriptionId: { type: String, default: undefined },
		messageId: { type: String, default: undefined },
	},
	setup(props, { slots, attrs }) {
		const id = `tile-form-item-${useId()}`;
		const version = ref(0);
		const descriptions = new Set<string>();
		const messages = new Set<string>();
		if (props.descriptionId) descriptions.add(props.descriptionId);
		if (props.messageId) messages.add(props.messageId);
		const bump = () => {
			version.value += 1;
		};
		const register = (registry: Set<string>) => (registeredId: string) => {
			registry.add(registeredId);
			bump();
			let active = true;
			return () => {
				if (!active) return;
				active = false;
				registry.delete(registeredId);
				bump();
			};
		};

		provide(FormItemContextKey, {
			id: computed(() => id),
			declaredDescriptionId: computed(() => props.descriptionId),
			declaredMessageId: computed(() => props.messageId),
			descriptionIds: computed(() => {
				void version.value;
				return [...descriptions];
			}),
			messageIds: computed(() => {
				void version.value;
				return [...messages];
			}),
			registerDescription: register(descriptions),
			registerMessage: register(messages),
		});

		return () => h('div', { ...attrs, 'data-slot': 'form-item', class: [styles[formStyleKeys.item], attrs.class] }, slots.default?.());
	},
});

export const FormLabel = defineComponent({
	name: 'FormLabel',
	setup(_props, { slots, attrs }) {
		const field = useFormField();

		return () =>
			h(
				'label',
				{
					...attrs,
					'data-slot': 'form-label',
					'data-error': field.value.error ? 'true' : 'false',
					for: field.value.formItemId,
					class: [styles[formStyleKeys.label], attrs.class],
				},
				slots.default?.(),
			);
	},
});

export const FormControl = defineComponent({
	name: 'FormControl',
	setup(_props, { slots }) {
		const field = useFormField();
		const itemContext = inject(FormItemContextKey);

		return () => {
			const f = field.value;
			const describedByIds = [...(itemContext?.descriptionIds.value ?? [])];
			if (f.error) describedByIds.push(...(itemContext?.messageIds.value ?? []));
			const controlProps = {
				id: f.formItemId,
				'aria-describedby': describedByIds.length > 0 ? describedByIds.join(' ') : undefined,
				'aria-invalid': f.error ? 'true' : 'false',
			};

			const child = slots.default?.()[0];
			if (child) {
				return cloneVNode(child, { ...controlProps, 'data-slot': 'form-control' });
			}

			return h('div', { ...controlProps, 'data-slot': 'form-control' });
		};
	},
});

export const FormDescription = defineComponent({
	name: 'FormDescription',
	props: {
		id: { type: String, default: undefined },
	},
	setup(props, { slots, attrs }) {
		const field = useFormField();
		const itemContext = inject(FormItemContextKey);
		const effectiveId = computed(() => props.id ?? itemContext?.declaredDescriptionId.value ?? field.value.formDescriptionId);

		let unregister: (() => void) | undefined;
		const stop = watch(
			effectiveId,
			(id) => {
				unregister?.();
				unregister = itemContext?.registerDescription(id);
			},
			{ immediate: true },
		);
		onBeforeUnmount(() => {
			stop();
			unregister?.();
		});

		return () => h('p', { ...attrs, 'data-slot': 'form-description', id: effectiveId.value, class: [styles[formStyleKeys.description], attrs.class] }, slots.default?.());
	},
});

export const FormMessage = defineComponent({
	name: 'FormMessage',
	props: {
		id: { type: String, default: undefined },
	},
	setup(props, { slots, attrs }) {
		const field = useFormField();
		const itemContext = inject(FormItemContextKey);
		const effectiveId = computed(() => props.id ?? itemContext?.declaredMessageId.value ?? field.value.formMessageId);
		let registeredId: string | undefined;
		let unregister: (() => void) | undefined;
		onBeforeUnmount(() => {
			unregister?.();
		});

		return () => {
			const error = field.value.error;
			const slotContent = slots.default?.();
			const body = error ? String(error.message ?? '') : slotContent;
			const present = error ? !!body : hasSlotContent(slotContent);

			const id = effectiveId.value;
			if (present && registeredId !== id) {
				unregister?.();
				unregister = itemContext?.registerMessage(id);
				registeredId = id;
			} else if (!present && registeredId !== undefined) {
				unregister?.();
				unregister = undefined;
				registeredId = undefined;
			}

			if (!present) {
				return null;
			}

			return h('p', { ...attrs, 'data-slot': 'form-message', id, class: [styles[formStyleKeys.message], attrs.class] }, body);
		};
	},
});

export default Form;
