// packages/vue/src/components/item/item.tsx
import { cloneVNode, computed, defineComponent, h, type PropType } from 'vue';
import { getItemMediaVariantKey, getItemSizeKey, getItemVariantKey, itemStyleKeys } from '@tile-ui/core';
import type { ItemMediaVariant, ItemSize, ItemVariant } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/item.module.scss';

export const ItemGroup = defineComponent({
	name: 'ItemGroup',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, role: 'list', 'data-slot': 'item-group', class: [styles[itemStyleKeys.group], attrs.class] }, slots.default?.());
	},
});

export const ItemSeparator = defineComponent({
	name: 'ItemSeparator',
	setup(_props, { attrs }) {
		return () =>
			h('div', { ...attrs, role: 'separator', 'aria-orientation': 'horizontal', 'data-slot': 'item-separator', class: [styles[itemStyleKeys.separator], attrs.class] });
	},
});

export const Item = defineComponent({
	name: 'Item',
	props: {
		variant: {
			type: String as PropType<ItemVariant>,
			default: 'default',
		},
		size: {
			type: String as PropType<ItemSize>,
			default: 'default',
		},
		asChild: { type: Boolean, default: false },
	},
	setup(props, { slots, attrs }) {
		const variantKey = computed(() => getItemVariantKey(props.variant));
		const sizeKey = computed(() => getItemSizeKey(props.size));

		return () => {
			const children = slots.default?.();
			const rootClass = [styles[itemStyleKeys.item], styles[variantKey.value], styles[sizeKey.value]];

			if (props.asChild) {
				const firstChild = Array.isArray(children) ? children[0] : children;

				if (firstChild) {
					const childProps = (firstChild.props ?? {}) as { class?: unknown };
					return cloneVNode(firstChild, {
						...attrs,
						'data-slot': 'item',
						'data-variant': props.variant,
						'data-size': props.size,
						class: [styles[itemStyleKeys.item], styles[variantKey.value], styles[sizeKey.value], attrs.class, childProps.class].filter(Boolean),
					});
				}
			}

			return h('div', { ...attrs, 'data-slot': 'item', 'data-variant': props.variant, 'data-size': props.size, class: [...rootClass, attrs.class] }, children);
		};
	},
});

export const ItemMedia = defineComponent({
	name: 'ItemMedia',
	props: {
		variant: {
			type: String as PropType<ItemMediaVariant>,
			default: 'default',
		},
	},
	setup(props, { slots, attrs }) {
		const variantKey = computed(() => getItemMediaVariantKey(props.variant));
		return () =>
			h(
				'div',
				{ ...attrs, 'data-slot': 'item-media', 'data-variant': props.variant, class: [styles[itemStyleKeys.media], styles[variantKey.value], attrs.class] },
				slots.default?.(),
			);
	},
});

export const ItemContent = defineComponent({
	name: 'ItemContent',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'item-content', class: [styles[itemStyleKeys.content], attrs.class] }, slots.default?.());
	},
});

export const ItemTitle = defineComponent({
	name: 'ItemTitle',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'item-title', class: [styles[itemStyleKeys.title], attrs.class] }, slots.default?.());
	},
});

export const ItemDescription = defineComponent({
	name: 'ItemDescription',
	setup(_props, { slots, attrs }) {
		return () => h('p', { ...attrs, 'data-slot': 'item-description', class: [styles[itemStyleKeys.description], attrs.class] }, slots.default?.());
	},
});

export const ItemActions = defineComponent({
	name: 'ItemActions',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'item-actions', class: [styles[itemStyleKeys.actions], attrs.class] }, slots.default?.());
	},
});

export const ItemHeader = defineComponent({
	name: 'ItemHeader',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'item-header', class: [styles[itemStyleKeys.header], attrs.class] }, slots.default?.());
	},
});

export const ItemFooter = defineComponent({
	name: 'ItemFooter',
	setup(_props, { slots, attrs }) {
		return () => h('div', { ...attrs, 'data-slot': 'item-footer', class: [styles[itemStyleKeys.footer], attrs.class] }, slots.default?.());
	},
});

export default Item;

// packages/react/src/components/item/item.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { getItemMediaVariantKey, getItemSizeKey, getItemVariantKey, itemStyleKeys } from '@tile-ui/core';
import type { ItemBaseProps, ItemMediaBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/item.module.scss';

export interface ItemGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemGroup = React.forwardRef<HTMLDivElement, ItemGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} role="list" data-slot="item-group" className={`${styles[itemStyleKeys.group]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemGroup.displayName = 'ItemGroup';

export interface ItemSeparatorProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemSeparator = React.forwardRef<HTMLDivElement, ItemSeparatorProps>(({ className = '', ...props }, ref) => {
	return <div ref={ref} role="separator" aria-orientation="horizontal" data-slot="item-separator" className={`${styles[itemStyleKeys.separator]} ${className}`} {...props} />;
});
ItemSeparator.displayName = 'ItemSeparator';

export interface ItemProps extends React.HTMLAttributes<HTMLDivElement>, ItemBaseProps {}

const Item = React.forwardRef<HTMLDivElement, ItemProps>(({ className = '', variant = 'default', size = 'default', asChild = false, children, ...props }, ref) => {
	const Comp = asChild ? Slot : 'div';
	const variantKey = getItemVariantKey(variant);
	const sizeKey = getItemSizeKey(size);
	const classes = [styles[itemStyleKeys.item], styles[variantKey], styles[sizeKey], className].filter(Boolean).join(' ');

	return (
		<Comp ref={ref} data-slot="item" data-variant={variant} data-size={size} className={classes} {...props}>
			{children}
		</Comp>
	);
});
Item.displayName = 'Item';

export interface ItemMediaProps extends React.HTMLAttributes<HTMLDivElement>, ItemMediaBaseProps {}

const ItemMedia = React.forwardRef<HTMLDivElement, ItemMediaProps>(({ className = '', variant = 'default', children, ...props }, ref) => {
	const variantKey = getItemMediaVariantKey(variant);
	const classes = [styles[itemStyleKeys.media], styles[variantKey], className].filter(Boolean).join(' ');

	return (
		<div ref={ref} data-slot="item-media" data-variant={variant} className={classes} {...props}>
			{children}
		</div>
	);
});
ItemMedia.displayName = 'ItemMedia';

export interface ItemContentProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemContent = React.forwardRef<HTMLDivElement, ItemContentProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-content" className={`${styles[itemStyleKeys.content]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemContent.displayName = 'ItemContent';

export interface ItemTitleProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemTitle = React.forwardRef<HTMLDivElement, ItemTitleProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-title" className={`${styles[itemStyleKeys.title]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemTitle.displayName = 'ItemTitle';

export interface ItemDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

const ItemDescription = React.forwardRef<HTMLParagraphElement, ItemDescriptionProps>(({ className = '', children, ...props }, ref) => {
	return (
		<p ref={ref} data-slot="item-description" className={`${styles[itemStyleKeys.description]} ${className}`} {...props}>
			{children}
		</p>
	);
});
ItemDescription.displayName = 'ItemDescription';

export interface ItemActionsProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemActions = React.forwardRef<HTMLDivElement, ItemActionsProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-actions" className={`${styles[itemStyleKeys.actions]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemActions.displayName = 'ItemActions';

export interface ItemHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemHeader = React.forwardRef<HTMLDivElement, ItemHeaderProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-header" className={`${styles[itemStyleKeys.header]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemHeader.displayName = 'ItemHeader';

export interface ItemFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

const ItemFooter = React.forwardRef<HTMLDivElement, ItemFooterProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} data-slot="item-footer" className={`${styles[itemStyleKeys.footer]} ${className}`} {...props}>
			{children}
		</div>
	);
});
ItemFooter.displayName = 'ItemFooter';

export { Item, ItemMedia, ItemContent, ItemActions, ItemGroup, ItemSeparator, ItemTitle, ItemDescription, ItemHeader, ItemFooter };
export default Item;
