// packages/react/src/components/avatar/avatar.tsx
import React, { createContext, useContext, useEffect, useRef, useState } from 'react';
import { avatarStyleKeys, shouldShowAvatarFallback } from '@tile-ui/core';
import type { AvatarImageStatus } from '@tile-ui/core';
import type { AvatarBaseProps, AvatarImageBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/avatar.module.scss';

interface AvatarContextValue {
	status: AvatarImageStatus;
	setStatus: (status: AvatarImageStatus) => void;
	hasImage: boolean;
	setHasImage: (has: boolean) => void;
}

const AvatarContext = createContext<AvatarContextValue | null>(null);

function useAvatarContext(): AvatarContextValue {
	const context = useContext(AvatarContext);
	if (!context) {
		throw new Error('Avatar sub-components must be used within <Avatar>.');
	}
	return context;
}

export interface AvatarProps extends React.HTMLAttributes<HTMLSpanElement>, AvatarBaseProps {}

const Avatar = React.forwardRef<HTMLSpanElement, AvatarProps>(({ className = '', size = 'default', children, ...props }, ref) => {
	const [status, setStatus] = useState<AvatarImageStatus>('loading');
	const [hasImage, setHasImage] = useState(false);

	return (
		<AvatarContext.Provider value={{ status, setStatus, hasImage, setHasImage }}>
			<span ref={ref} data-size={size} className={`${styles[avatarStyleKeys.root]} ${className}`} {...props}>
				{children}
			</span>
		</AvatarContext.Provider>
	);
});
Avatar.displayName = 'Avatar';

export interface AvatarImageProps extends React.ImgHTMLAttributes<HTMLImageElement>, AvatarImageBaseProps {}

const AvatarImage = React.forwardRef<HTMLImageElement, AvatarImageProps>(({ className = '', onLoad, onError, ...props }, ref) => {
	const context = useAvatarContext();
	const imgRef = useRef<HTMLImageElement | null>(null);

	useEffect(() => {
		context.setHasImage(true);

		const img = imgRef.current;
		if (img && img.complete) {
			context.setStatus(img.naturalWidth > 0 ? 'loaded' : 'error');
		}
	}, [context]);

	function setRef(element: HTMLImageElement | null) {
		imgRef.current = element;

		if (typeof ref === 'function') {
			ref(element);
		} else if (ref) {
			ref.current = element;
		}
	}

	function handleLoad(event: React.SyntheticEvent<HTMLImageElement>) {
		context.setStatus('loaded');
		onLoad?.(event);
	}

	function handleError(event: React.SyntheticEvent<HTMLImageElement>) {
		context.setStatus('error');
		onError?.(event);
	}

	return <img ref={setRef} className={`${styles[avatarStyleKeys.image]} ${className}`} onLoad={handleLoad} onError={handleError} {...props} />;
});
AvatarImage.displayName = 'AvatarImage';

export interface AvatarFallbackProps extends React.HTMLAttributes<HTMLSpanElement> {}

const AvatarFallback = React.forwardRef<HTMLSpanElement, AvatarFallbackProps>(({ className = '', children, ...props }, ref) => {
	const context = useAvatarContext();

	if (!shouldShowAvatarFallback(context.status, context.hasImage)) {
		return null;
	}

	return (
		<span ref={ref} className={`${styles[avatarStyleKeys.fallback]} ${className}`} {...props}>
			{children}
		</span>
	);
});
AvatarFallback.displayName = 'AvatarFallback';

export interface AvatarBadgeProps extends React.HTMLAttributes<HTMLSpanElement> {}

const AvatarBadge = React.forwardRef<HTMLSpanElement, AvatarBadgeProps>(({ className = '', children, ...props }, ref) => {
	return (
		<span ref={ref} className={`${styles[avatarStyleKeys.badge]} ${className}`} {...props}>
			{children}
		</span>
	);
});
AvatarBadge.displayName = 'AvatarBadge';

export interface AvatarGroupProps extends React.HTMLAttributes<HTMLDivElement> {}

const AvatarGroup = React.forwardRef<HTMLDivElement, AvatarGroupProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[avatarStyleKeys.group]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AvatarGroup.displayName = 'AvatarGroup';

export interface AvatarGroupCountProps extends React.HTMLAttributes<HTMLDivElement> {}

const AvatarGroupCount = React.forwardRef<HTMLDivElement, AvatarGroupCountProps>(({ className = '', children, ...props }, ref) => {
	return (
		<div ref={ref} className={`${styles[avatarStyleKeys.groupCount]} ${className}`} {...props}>
			{children}
		</div>
	);
});
AvatarGroupCount.displayName = 'AvatarGroupCount';

export { Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup, AvatarGroupCount };
export default Avatar;

// packages/solid/src/components/avatar/avatar.tsx
import {
	Show,
	createContext,
	createRenderEffect,
	createSignal,
	onCleanup,
	onMount,
	splitProps,
	useContext,
	type Accessor,
	type JSX,
	type ParentProps,
	type Setter,
} from 'solid-js';
import { avatarStyleKeys, shouldShowAvatarFallback } from '@tile-ui/core';
import type { AvatarBaseProps, AvatarImageBaseProps, AvatarImageStatus } from '@tile-ui/core';
import { invokeEventHandler } from '../../utils/events';
import styles from '@tile-ui/styles/scss/components/avatar.module.scss';

interface AvatarContextValue {
	status: Accessor<AvatarImageStatus>;
	setStatus: Setter<AvatarImageStatus>;
	hasImage: Accessor<boolean>;
	setHasImage: Setter<boolean>;
	root: Accessor<HTMLSpanElement | undefined>;
}
const AvatarContext = createContext<AvatarContextValue>();
function useAvatar() {
	const value = useContext(AvatarContext);
	if (!value) throw new Error('Avatar 子组件必须位于 <Avatar> 内部。');
	return value;
}

export interface AvatarProps extends JSX.HTMLAttributes<HTMLSpanElement>, AvatarBaseProps {}
export function Avatar(props: ParentProps<AvatarProps>) {
	const [local, rest] = splitProps(props, ['class', 'children', 'size']);
	const [status, setStatus] = createSignal<AvatarImageStatus>('loading');
	const [hasImage, setHasImage] = createSignal(false);
	let root: HTMLSpanElement | undefined = undefined;
	return (
		<AvatarContext.Provider value={{ status, setStatus, hasImage, setHasImage, root: () => root }}>
			<span
				{...rest}
				ref={root!}
				data-slot="avatar"
				data-size={local.size ?? 'default'}
				data-image-status={status()}
				class={`${styles[avatarStyleKeys.root]} ${local.class ?? ''}`}>
				{local.children}
			</span>
		</AvatarContext.Provider>
	);
}

export interface AvatarImageProps extends JSX.ImgHTMLAttributes<HTMLImageElement>, AvatarImageBaseProps {}
export function AvatarImage(props: AvatarImageProps) {
	const context = useAvatar();
	const [local, rest] = splitProps(props, ['class', 'onLoad', 'onError', 'ref', 'src']);
	let sourceGeneration = 0;
	let activeImage: HTMLImageElement | undefined;

	function renderImage(source: string | undefined) {
		const generation = ++sourceGeneration;
		let image: HTMLImageElement | undefined = undefined;
		let consumerRefAssigned = false;
		context.setHasImage(true);
		context.setStatus('loading');

		const isCurrent = (element: HTMLImageElement) => generation === sourceGeneration && activeImage === element && local.src === source;
		const reconcile = () => {
			const currentImage = image as HTMLImageElement | undefined;
			if (currentImage && isCurrent(currentImage) && currentImage.complete) context.setStatus(currentImage.naturalWidth > 0 ? 'loaded' : 'error');
		};
		const assignImage = (element: HTMLImageElement) => {
			image = element;
			activeImage = element;
			context.setHasImage(true);
			reconcile();
			if (typeof local.ref === 'function') {
				consumerRefAssigned = true;
				local.ref(element);
			}
		};

		createRenderEffect(reconcile);
		onMount(() => {
			if (!image) image = context.root()?.querySelector('img') ?? undefined;
			if (!image) return;
			activeImage = image;
			context.setHasImage(true);
			reconcile();
			if (!consumerRefAssigned && typeof local.ref === 'function') local.ref(image);
		});
		onCleanup(() => {
			if (generation === sourceGeneration) {
				activeImage = undefined;
				context.setHasImage(false);
			}
		});

		return (
			<img
				{...rest}
				src={source}
				ref={assignImage}
				class={`${styles[avatarStyleKeys.image]} ${local.class ?? ''}`}
				onLoad={(event) => {
					if (isCurrent(event.currentTarget) && event.currentTarget === image) context.setStatus('loaded');
					invokeEventHandler(local.onLoad, event);
				}}
				onError={(event) => {
					if (isCurrent(event.currentTarget) && event.currentTarget === image) context.setStatus('error');
					invokeEventHandler(local.onError, event);
				}}
			/>
		);
	}

	return (
		<Show when={local.src} keyed>
			{(source) => renderImage(source)}
		</Show>
	);
}

export interface AvatarFallbackProps extends JSX.HTMLAttributes<HTMLSpanElement> {}
export function AvatarFallback(props: ParentProps<AvatarFallbackProps>) {
	const context = useAvatar();
	const [local, rest] = splitProps(props, ['class', 'children', 'hidden']);
	const internallyHidden = () => !shouldShowAvatarFallback(context.status(), context.hasImage());
	return (
		<span {...rest} hidden={internallyHidden() || local.hidden === true} class={`${styles[avatarStyleKeys.fallback]} ${local.class ?? ''}`}>
			{local.children}
		</span>
	);
}
export interface AvatarBadgeProps extends JSX.HTMLAttributes<HTMLSpanElement> {}
export function AvatarBadge(props: ParentProps<AvatarBadgeProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<span {...rest} class={`${styles[avatarStyleKeys.badge]} ${local.class ?? ''}`}>
			{local.children}
		</span>
	);
}
export interface AvatarGroupProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export function AvatarGroup(props: ParentProps<AvatarGroupProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} class={`${styles[avatarStyleKeys.group]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}
export interface AvatarGroupCountProps extends JSX.HTMLAttributes<HTMLDivElement> {}
export function AvatarGroupCount(props: ParentProps<AvatarGroupCountProps>) {
	const [local, rest] = splitProps(props, ['class', 'children']);
	return (
		<div {...rest} class={`${styles[avatarStyleKeys.groupCount]} ${local.class ?? ''}`}>
			{local.children}
		</div>
	);
}
export default Avatar;
