// apps/react/components/demos/field.tsx
import { Field, FieldLabel, FieldDescription, FieldMessage } from '@tile-ui/react';

export default function FieldDemo() {
	return (
		<Field name="email" required invalid>
			<FieldLabel htmlFor="demo-email">Email</FieldLabel>
			<input id="demo-email" className="component-preview__native-field" placeholder="you@example.com" />
			<FieldDescription>We never share your email.</FieldDescription>
			<FieldMessage variant="error">An email address is required.</FieldMessage>
		</Field>
	);
}

// apps/solid/components/demos/field.tsx
import { createSignal } from 'solid-js';
import { Field, FieldDescription, FieldLabel, FieldMessage, useFieldContext } from '@tile-ui/solid';

function FieldControl(props: { onInput: (value: string) => void }) {
	const field = useFieldContext();
	return (
		<input
			id={field.id}
			class="component-preview__native-field"
			required={field.required()}
			aria-invalid={field.invalid()}
			aria-describedby={`${field.descriptionId} ${field.messageId}`}
			onInput={(event) => props.onInput(event.currentTarget.value)}
		/>
	);
}

export default function FieldDemo() {
	const [value, setValue] = createSignal('');
	const invalid = () => value().length > 0 && value().length < 4;
	return (
		<Field name="workspace" required invalid={invalid()}>
			<FieldLabel>Workspace</FieldLabel>
			<FieldControl onInput={setValue} />
			<FieldDescription>Use at least four characters.</FieldDescription>
			<FieldMessage variant={invalid() ? 'error' : 'default'}>{invalid() ? 'Workspace is too short.' : 'Field IDs and ARIA stay connected.'}</FieldMessage>
		</Field>
	);
}
