// apps/react/components/demos/select.tsx
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@tile-ui/react';

export default function SelectDemo() {
	return (
		<Select defaultValue="apple">
			<SelectTrigger aria-label="Fruit" style={{ width: 220 }}>
				<SelectValue placeholder="Choose a fruit" />
			</SelectTrigger>
			<SelectContent>
				<SelectItem value="apple">Apple</SelectItem>
				<SelectItem value="banana">Banana</SelectItem>
				<SelectItem value="cherry">Cherry</SelectItem>
			</SelectContent>
		</Select>
	);
}

// apps/solid/components/demos/select.tsx
import { createSignal } from 'solid-js';
import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue } from '@tile-ui/solid';

export default function SelectDemo() {
	const [value, setValue] = createSignal('solid');
	return (
		<div class="component-preview__stack" data-demo-select>
			<Select value={value()} onValueChange={setValue} selectedText={value() === 'solid' ? 'Solid <SSR>' : 'Vue & React'}>
				<SelectTrigger aria-label="Framework lane">
					<SelectValue placeholder="Choose a lane" />
				</SelectTrigger>
				<SelectContent>
					<SelectGroup>
						<SelectLabel>Framework lanes</SelectLabel>
						<SelectItem value="solid">Solid &lt;SSR&gt;</SelectItem>
						<SelectItem value="shared">Vue &amp; React</SelectItem>
					</SelectGroup>
					<SelectSeparator />
					<SelectItem value="disabled" disabled>
						Disabled lane
					</SelectItem>
				</SelectContent>
			</Select>
			<button type="button" data-after-select>
				Logical Tab target
			</button>
			<p data-demo-state>Selected: {value()}.</p>
		</div>
	);
}
