// apps/react/components/demos/slider.tsx
import { useState } from 'react';
import { Slider, SliderTrack, SliderRange, SliderThumb } from '@tile-ui/react';

export default function SliderDemo() {
	const [value, setValue] = useState(40);

	return (
		<div className="component-preview__stack">
			<Slider value={value} onValueChange={setValue} max={100} step={1}>
				<SliderTrack>
					<SliderRange />
					<SliderThumb aria-label="Volume" />
				</SliderTrack>
			</Slider>
			<p className="component-preview__text">
				Value: <strong>{value}</strong>
			</p>
		</div>
	);
}

// apps/solid/components/demos/slider.tsx
import { createSignal } from 'solid-js';
import { Slider, SliderRange, SliderThumb, SliderTrack } from '@tile-ui/solid';

function DemoSlider(props: { orientation: 'horizontal' | 'vertical'; value: number; onValueChange: (value: number) => void }) {
	return (
		<Slider
			orientation={props.orientation}
			value={props.value}
			onValueChange={props.onValueChange}
			min={0}
			max={100}
			step={5}
			style={props.orientation === 'vertical' ? { height: '8rem' } : undefined}>
			<SliderTrack>
				<SliderRange />
			</SliderTrack>
			<SliderThumb aria-label={`${props.orientation} volume`} />
		</Slider>
	);
}

export default function SliderDemo() {
	const [horizontal, setHorizontal] = createSignal(40);
	const [vertical, setVertical] = createSignal(65);
	return (
		<div class="component-preview__stack">
			<DemoSlider orientation="horizontal" value={horizontal()} onValueChange={setHorizontal} />
			<DemoSlider orientation="vertical" value={vertical()} onValueChange={setVertical} />
			<p class="component-preview__text">
				Values: {horizontal()} horizontal, {vertical()} vertical. Use pointer or arrow keys.
			</p>
		</div>
	);
}
